;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: wasm-opt %s --autobatch -S -o - | filecheck %s

;; The output will replace non-returning imports with wrappers that serialize
;; commands.
;;
;; Value-returning imports will flush in their wrappers, then do the call.
;;
;; $caller does not change at all, as calls to the imports now call wrappers
;; with the same names.

(module
  ;; This serializes as [i32 id, i32 param, f64 param], which is a total of 16
  ;; bytes. The f64 is aligned properly just by how the offsets work out.
  (import "outside" "foo1" (func $noresult1 (param i32) (param f64)))

  ;; This serializes as [i32 id, i64 param, f32 param], which is a total of 16
  ;; bytes again, but now the 64-bit param must have a 4-byte buffer before it,
  ;; so it is aligned.
  (import "outside" "foo2" (func $noresult2 (param i64) (param f32)))

  ;; A function with a result. We purposefully put this before "foo3" to test
  ;; for mixups in the indexing (we do not index "bar", as calls to functions
  ;; returning a value are not serialized).
  (import "outside" "bar" (func $result (result f64)))

  ;; This serializes as [i32 id, i32 param, f32 param], which is a total of 12
  ;; bytes. We bump $cmdbufpos by 16, to keep the thing after us aligned.
  (import "outside" "foo3" (func $noresult3 (param i32) (param f32)))

  ;; CHECK:      (type $0 (func (result f64)))

  ;; CHECK:      (type $1 (func (param i32 f64)))

  ;; CHECK:      (type $2 (func (param i64 f32)))

  ;; CHECK:      (type $3 (func (param i32 f32)))

  ;; CHECK:      (type $4 (func (param i32 i32)))

  ;; CHECK:      (import "autobatch" "flush" (func $flush (param i32 i32)))

  ;; CHECK:      (import "outside" "foo1" (func $noresult1_6 (param i32 f64)))

  ;; CHECK:      (import "outside" "foo2" (func $noresult2_7 (param i64 f32)))

  ;; CHECK:      (import "outside" "bar" (func $result_8 (result f64)))

  ;; CHECK:      (import "outside" "foo3" (func $noresult3_9 (param i32 f32)))

  ;; CHECK:      (global $cmdbufbase (mut i32) (i32.const 0))

  ;; CHECK:      (global $cmdbufpos (mut i32) (i32.const 0))

  ;; CHECK:      (memory $mem 10 20)
  (memory $mem 10 20)

  ;; CHECK:      (func $noresult1 (param $0 i32) (param $1 f64)
  ;; CHECK-NEXT:  (local $2 i32)
  ;; CHECK-NEXT:  (local.set $2
  ;; CHECK-NEXT:   (global.get $cmdbufpos)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (i32.store
  ;; CHECK-NEXT:   (local.get $2)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (i32.store offset=4
  ;; CHECK-NEXT:   (local.get $2)
  ;; CHECK-NEXT:   (local.get $0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (f64.store offset=8
  ;; CHECK-NEXT:   (local.get $2)
  ;; CHECK-NEXT:   (local.get $1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $cmdbufpos
  ;; CHECK-NEXT:   (i32.add
  ;; CHECK-NEXT:    (local.get $2)
  ;; CHECK-NEXT:    (i32.const 16)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )

  ;; CHECK:      (func $noresult2 (param $0 i64) (param $1 f32)
  ;; CHECK-NEXT:  (local $2 i32)
  ;; CHECK-NEXT:  (local.set $2
  ;; CHECK-NEXT:   (global.get $cmdbufpos)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (i32.store
  ;; CHECK-NEXT:   (local.get $2)
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (i64.store offset=8
  ;; CHECK-NEXT:   (local.get $2)
  ;; CHECK-NEXT:   (local.get $0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (f32.store offset=16
  ;; CHECK-NEXT:   (local.get $2)
  ;; CHECK-NEXT:   (local.get $1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $cmdbufpos
  ;; CHECK-NEXT:   (i32.add
  ;; CHECK-NEXT:    (local.get $2)
  ;; CHECK-NEXT:    (i32.const 24)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )

  ;; CHECK:      (func $result (result f64)
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (global.get $cmdbufpos)
  ;; CHECK-NEXT:   (then
  ;; CHECK-NEXT:    (call $flush
  ;; CHECK-NEXT:     (global.get $cmdbufbase)
  ;; CHECK-NEXT:     (global.get $cmdbufpos)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (global.set $cmdbufpos
  ;; CHECK-NEXT:     (global.get $cmdbufbase)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $result_8)
  ;; CHECK-NEXT: )

  ;; CHECK:      (func $noresult3 (param $0 i32) (param $1 f32)
  ;; CHECK-NEXT:  (local $2 i32)
  ;; CHECK-NEXT:  (local.set $2
  ;; CHECK-NEXT:   (global.get $cmdbufpos)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (i32.store
  ;; CHECK-NEXT:   (local.get $2)
  ;; CHECK-NEXT:   (i32.const 2)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (i32.store offset=4
  ;; CHECK-NEXT:   (local.get $2)
  ;; CHECK-NEXT:   (local.get $0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (f32.store offset=8
  ;; CHECK-NEXT:   (local.get $2)
  ;; CHECK-NEXT:   (local.get $1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.set $cmdbufpos
  ;; CHECK-NEXT:   (i32.add
  ;; CHECK-NEXT:    (local.get $2)
  ;; CHECK-NEXT:    (i32.const 16)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )

  ;; CHECK:      (func $caller (result f64)
  ;; CHECK-NEXT:  (call $noresult1
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:   (f64.const 3.14159)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $noresult2
  ;; CHECK-NEXT:   (i64.const 1234)
  ;; CHECK-NEXT:   (f32.const 2.718280076980591)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (call $result)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $noresult3
  ;; CHECK-NEXT:   (i32.const -1)
  ;; CHECK-NEXT:   (f32.const -2.299999952316284)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $noresult1
  ;; CHECK-NEXT:   (i32.const 942)
  ;; CHECK-NEXT:   (f64.const 93.14159)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $noresult2
  ;; CHECK-NEXT:   (i64.const 91234)
  ;; CHECK-NEXT:   (f32.const 92.71827697753906)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $result)
  ;; CHECK-NEXT: )
  (func $caller (result f64)
    ;; A bunch of calls to them all.
    (call $noresult1
      (i32.const 42)
      (f64.const 3.14159)
    )
    (call $noresult2
      (i64.const 1234)
      (f32.const 2.71828)
    )
    (drop (call $result))

    (call $noresult3
      (i32.const -1)
      (f32.const -2.3)
    )

    (call $noresult1
      (i32.const 942)
      (f64.const 93.14159)
    )
    (call $noresult2
      (i64.const 91234)
      (f32.const 92.71828)
    )
    (call $result)
  )
)

