;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.

;; Run in both TNH and non-TNH mode. This pass should do nothing atm in non-TNH.

;; foreach %s %t wasm-opt --cast-refining --traps-never-happen -all -S -o - | filecheck %s --check-prefix=YESTNH
;; foreach %s %t wasm-opt --cast-refining                      -all -S -o - | filecheck %s --check-prefix=NO_TNH

;; $A :> $B :> $C :> $D1,
;;                   $D2
;;
;; $A and $C have no struct.news, so we can optimize casts of them in theory.
;; But for $C the two children prevent that.
(module
  (type $A (struct))

  (type $B (struct_subtype $A))

  (type $C (struct_subtype $B))

  (type $D1 (struct_subtype $C))

  (type $D2 (struct_subtype $C))

  (global $global anyref (struct.new $B))

  (func $func
    (drop
      (struct.new $D1
    )
    (drop
      (struct.new $D2
    )
  )
)
