;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: wasm-opt --new-wat-parser -all %s -S -o - | filecheck %s

(module

 ;; CHECK:      (type $0 (func))

 ;; CHECK:      (func $debug-location-propagation (type $0)
 ;; CHECK-NEXT:  ;;@ src.cpp:20:1
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.add
 ;; CHECK-NEXT:    ;;@ src.cpp:10:1
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:    ;;@ src.cpp:10:1
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  ;;@ src.cpp:20:1
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 2)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  ;;@ src.cpp:30:1
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.add
 ;; CHECK-NEXT:    (i32.const 100)
 ;; CHECK-NEXT:    (i32.const 200)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $debug-location-propagation
  ;;@ src.cpp:10:1
  i32.const 0
  i32.const 1
  i32.add
  ;;@ src.cpp:20:1
  drop
  i32.const 2
  drop
  i32.const 100
  i32.const 200
  i32.add
  ;;@ src.cpp:30:1
  drop
 )
)
