;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --duplicate-import-elimination -S -o - | filecheck %s

(module
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (type $1 (func (param i32)))

  ;; CHECK:      (import "env" "waka" (func $foo))
  (import "env" "waka" (func $foo))
  (import "env" "waka" (func $bar))
  ;; CHECK:      (import "env" "waka" (func $wrong (param i32)))
  (import "env" "waka" (func $wrong (param i32)))
  (table 2 2 funcref)
  (elem (i32.const 0) $foo $bar)
  (start $bar)
  ;; CHECK:      (table $0 2 2 funcref)

  ;; CHECK:      (elem $0 (i32.const 0) $foo $foo)

  ;; CHECK:      (export "baz" (func $baz))

  ;; CHECK:      (start $foo)

  ;; CHECK:      (func $baz
  ;; CHECK-NEXT:  (call $foo)
  ;; CHECK-NEXT:  (call $foo)
  ;; CHECK-NEXT:  (call $wrong
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $baz (export "baz")
    (call $foo)
    (call $bar)
    (call $wrong (i32.const 1))
  )
)
