;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --flatten --all-features -S -o - | filecheck %s

(module
  ;; CHECK:      (type $s (sub (struct)))
  (type $s (sub (struct)))
  ;; CHECK:      (type $t (sub $s (struct)))
  (type $t (sub $s (struct)))

  ;; CHECK:      (type $2 (func (param (ref $s)) (result (ref $t))))

  ;; CHECK:      (func $br_on_cast (type $2) (param $x (ref $s)) (result (ref $t))
  ;; CHECK-NEXT:  (local $1 (ref $s))
  ;; CHECK-NEXT:  (local $2 (ref $s))
  ;; CHECK-NEXT:  (local $3 i32)
  ;; CHECK-NEXT:  (local $4 (ref null $t))
  ;; CHECK-NEXT:  (local $5 (ref $s))
  ;; CHECK-NEXT:  (local $6 (ref $s))
  ;; CHECK-NEXT:  (local $7 (ref (exact $t)))
  ;; CHECK-NEXT:  (local $8 (ref $t))
  ;; CHECK-NEXT:  (block $label0
  ;; CHECK-NEXT:   (local.set $1
  ;; CHECK-NEXT:    (local.get $x)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (local.set $2
  ;; CHECK-NEXT:    (local.get $1)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (local.set $3
  ;; CHECK-NEXT:    (ref.test (ref $t)
  ;; CHECK-NEXT:     (local.get $2)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (if
  ;; CHECK-NEXT:    (local.get $3)
  ;; CHECK-NEXT:    (then
  ;; CHECK-NEXT:     (local.set $4
  ;; CHECK-NEXT:      (ref.cast (ref $t)
  ;; CHECK-NEXT:       (local.get $2)
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (br $label0)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (local.set $5
  ;; CHECK-NEXT:    (local.get $2)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (local.set $6
  ;; CHECK-NEXT:    (local.get $5)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (local.get $6)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (local.set $7
  ;; CHECK-NEXT:    (struct.new_default $t)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (local.set $4
  ;; CHECK-NEXT:    (local.get $7)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (local.set $8
  ;; CHECK-NEXT:   (ref.as_non_null
  ;; CHECK-NEXT:    (local.get $4)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (return
  ;; CHECK-NEXT:   (local.get $8)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (unreachable)
  ;; CHECK-NEXT: )
  (func $br_on_cast (param $x (ref $s)) (result (ref $t))
    (return
      (block $label0 (result (ref $t))
        (drop
          (br_on_cast $label0 (ref $s) (ref $t)
            (local.get $x)
          )
        )
      (struct.new $t))
    )
  )
)

