;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; RUN: foreach %s %t wasm-opt --gc-lowering --remove-unused-module-elements -all -S -o - | filecheck %s
;; (--remove-unused-module-elements is useful to avoid clutter in the output
;; here)

(module
 (type $any-any (func (param anyref) (result anyref)))

 (type $empty (struct))
 (type $struct-i32 (struct (mut i32)))
 (type $struct-i64 (struct (mut i64)))
 (type $struct-f32 (struct (field (mut f32))))
 (type $struct-f64 (struct (field (mut f64))))
 (type $struct-ref (struct (field (mut (ref null $empty)))))
 (type $struct-rtt (struct (field (mut (rtt $empty)))))
 (type $struct-nn (struct (field (ref func))))

 (type $struct-i32-f64 (struct (field (mut i32)) (field (mut i64))))

 (type $many-fields (struct (field (mut i32)) (field (mut f64)) (field (mut f32))))

 (type $bytes (array (mut i8)))
 (type $doubles (array (mut f64)))

 ;; CHECK:      (type $i32_=>_i32 (func (param i32) (result i32)))

 ;; CHECK:      (type $type$0 (func))

 ;; CHECK:      (type $i32_i32_=>_i32 (func (param i32 i32) (result i32)))

 ;; CHECK:      (type $i32_=>_none (func (param i32)))

 ;; CHECK:      (type $i32_i32_=>_none (func (param i32 i32)))

 ;; CHECK:      (type $i32_i32_i32_i32_i32_i32_=>_none (func (param i32 i32 i32 i32 i32 i32)))

 ;; CHECK:      (type $type$7 (func (param i64)))

 ;; CHECK:      (type $i32_f64_=>_none (func (param i32 f64)))

 ;; CHECK:      (type $i32_f32_=>_none (func (param i32 f32)))

 ;; CHECK:      (type $i32_i32_i32_=>_i32 (func (param i32 i32 i32) (result i32)))

 ;; CHECK:      (type $i32_i64_=>_none (func (param i32 i64)))

 ;; CHECK:      (type $i32_i32_=>_i64 (func (param i32 i32) (result i64)))

 ;; CHECK:      (type $i32_i32_=>_f32 (func (param i32 i32) (result f32)))

 ;; CHECK:      (type $i32_i32_=>_f64 (func (param i32 i32) (result f64)))

 ;; CHECK:      (type $i32_i32_f64_=>_none (func (param i32 i32 f64)))

 ;; CHECK:      (type $i32_i32_i32_=>_f64 (func (param i32 i32 i32) (result f64)))

 ;; CHECK:      (type $i32_i32_i32_=>_none (func (param i32 i32 i32)))

 ;; CHECK:      (type $i64_i32_=>_none (func (param i64 i32)))

 ;; CHECK:      (import "module" "func" (func $send-any (param i32)))
 (import "module" "func" (func $send-any (param anyref)))

 ;; CHECK:      (global $global0 i32 (i32.const 8))

 ;; CHECK:      (global $global1 (mut i32) (i32.const 0))

 ;; CHECK:      (global $global2 (mut i32) (i32.const 0))

 ;; CHECK:      (global $global3 (mut i32) (i32.const 0))

 ;; CHECK:      (global $lowergc-next-malloc (mut i32) (i32.const 316))

 ;; CHECK:      (memory $0 16384 16384)

 ;; CHECK:      (table $original-table 0 funcref)
 (table $original-table 0 funcref)

 (global $global0 (rtt 0 $empty) (rtt.canon $empty))
 (global $global1 (rtt 1 $struct-i32) (rtt.sub $struct-i32
  (global.get $global0)
 ))
 (global $global2 (rtt 2 $struct-i32-f64) (rtt.sub $struct-i32-f64
  (global.get $global1)
 ))
 (global $global3 (rtt 3 $struct-i32-f64) (rtt.sub $struct-i32-f64
  (global.get $global2)
 ))

 ;; CHECK:      (table $lowergc-table 4 4 funcref)

 ;; CHECK:      (elem (table $lowergc-table) (i32.const 0) func $call_ref $call_ref_i64 $ref.func $ref.is)

 ;; CHECK:      (export "struct-gets" (func $struct-gets))

 ;; CHECK:      (export "struct-sets" (func $struct-sets))

 ;; CHECK:      (export "many-fields" (func $many-fields))

 ;; CHECK:      (export "new-struct" (func $new-struct))

 ;; CHECK:      (export "new-struct-default" (func $new-struct-default))

 ;; CHECK:      (export "array-gets" (func $array-gets))

 ;; CHECK:      (export "array-sets" (func $array-sets))

 ;; CHECK:      (export "new-array" (func $new-array))

 ;; CHECK:      (export "new-array-default" (func $new-array-default))

 ;; CHECK:      (export "array-len" (func $array-len))

 ;; CHECK:      (export "rtt.sub" (func $rtt.sub))

 ;; CHECK:      (export "ref.as" (func $ref.as))

 ;; CHECK:      (export "ref.is" (func $ref.is))

 ;; CHECK:      (export "ref.func" (func $ref.func))

 ;; CHECK:      (export "ref.cast" (func $ref.cast))

 ;; CHECK:      (export "ref.test" (func $ref.test))

 ;; CHECK:      (export "call_indirect" (func $call_indirect))

 ;; CHECK:      (export "call_ref" (func $call_ref))

 ;; CHECK:      (export "call_ref_i64" (func $call_ref_i64))

 ;; CHECK:      (export "br_on_X" (func $br_on_X))

 ;; CHECK:      (export "ref-eq" (func $ref-eq))

 ;; CHECK:      (export "struct-nn" (func $struct-nn))

 ;; CHECK:      (export "send-any" (func $send-anything))

 ;; CHECK:      (start $lowergc-start)

 ;; CHECK:      (func $struct-gets (param $ref-i32 i32) (param $ref-i64 i32) (param $ref-f32 i32) (param $ref-f64 i32) (param $ref-ref i32) (param $ref-rtt i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $StructGet$struct-i32$0
 ;; CHECK-NEXT:    (local.get $ref-i32)
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $StructGet$struct-i64$0
 ;; CHECK-NEXT:    (local.get $ref-i64)
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $StructGet$struct-f32$0
 ;; CHECK-NEXT:    (local.get $ref-f32)
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $StructGet$struct-f64$0
 ;; CHECK-NEXT:    (local.get $ref-f64)
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $StructGet$struct-ref$0
 ;; CHECK-NEXT:    (local.get $ref-ref)
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $StructGet$struct-rtt$0
 ;; CHECK-NEXT:    (local.get $ref-rtt)
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $struct-gets (export "struct-gets")
  (param $ref-i32 (ref $struct-i32))
  (param $ref-i64 (ref $struct-i64))
  (param $ref-f32 (ref $struct-f32))
  (param $ref-f64 (ref $struct-f64))
  (param $ref-ref (ref $struct-ref))
  (param $ref-rtt (ref $struct-rtt))
  (drop
   (struct.get $struct-i32 0 (local.get $ref-i32))
  )
  (drop
   (struct.get $struct-i64 0 (local.get $ref-i64))
  )
  (drop
   (struct.get $struct-f32 0 (local.get $ref-f32))
  )
  (drop
   (struct.get $struct-f64 0 (local.get $ref-f64))
  )
  (drop
   (struct.get $struct-ref 0 (local.get $ref-ref))
  )
  (drop
   (struct.get $struct-rtt 0 (local.get $ref-rtt))
  )
 )

 ;; CHECK:      (func $struct-sets (param $ref-i32 i32) (param $ref-i64 i32) (param $ref-f32 i32) (param $ref-f64 i32) (param $ref-ref i32) (param $ref-rtt i32)
 ;; CHECK-NEXT:  (call $StructSet$struct-i32$0
 ;; CHECK-NEXT:   (local.get $ref-i32)
 ;; CHECK-NEXT:   (i32.const 0)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (call $StructSet$struct-i64$0
 ;; CHECK-NEXT:   (local.get $ref-i64)
 ;; CHECK-NEXT:   (i64.const 0)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (call $StructSet$struct-f32$0
 ;; CHECK-NEXT:   (local.get $ref-f32)
 ;; CHECK-NEXT:   (f32.const 0)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (call $StructSet$struct-f64$0
 ;; CHECK-NEXT:   (local.get $ref-f64)
 ;; CHECK-NEXT:   (f64.const 0)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (call $StructSet$struct-ref$0
 ;; CHECK-NEXT:   (local.get $ref-ref)
 ;; CHECK-NEXT:   (i32.const 0)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (call $StructSet$struct-rtt$0
 ;; CHECK-NEXT:   (local.get $ref-rtt)
 ;; CHECK-NEXT:   (i32.const 8)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $struct-sets (export "struct-sets")
  (param $ref-i32 (ref $struct-i32))
  (param $ref-i64 (ref $struct-i64))
  (param $ref-f32 (ref $struct-f32))
  (param $ref-f64 (ref $struct-f64))
  (param $ref-ref (ref $struct-ref))
  (param $ref-rtt (ref $struct-rtt))
  (struct.set $struct-i32 0 (local.get $ref-i32) (i32.const 0))
  (struct.set $struct-i64 0 (local.get $ref-i64) (i64.const 0))
  (struct.set $struct-f32 0 (local.get $ref-f32) (f32.const 0))
  (struct.set $struct-f64 0 (local.get $ref-f64) (f64.const 0))
  (struct.set $struct-ref 0 (local.get $ref-ref) (ref.null $empty))
  (struct.set $struct-rtt 0 (local.get $ref-rtt) (rtt.canon $empty))
 )

 ;; CHECK:      (func $many-fields (param $ref i32)
 ;; CHECK-NEXT:  (call $StructSet$many-fields$0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (call $StructSet$many-fields$1
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (f64.const 3.14159)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (call $StructSet$many-fields$2
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (f32.const 2.718280076980591)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $many-fields (export "many-fields")
  (param $ref (ref $many-fields))
  (struct.set $many-fields 0 (local.get $ref) (i32.const 1))
  (struct.set $many-fields 1 (local.get $ref) (f64.const 3.14159))
  (struct.set $many-fields 2 (local.get $ref) (f32.const 2.71828))
 )

 ;; CHECK:      (func $new-struct
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $StructNew$struct-i32
 ;; CHECK-NEXT:    (i32.const 42)
 ;; CHECK-NEXT:    (i32.const 32)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $new-struct (export "new-struct")
  (drop
   (struct.new_with_rtt $struct-i32
    (i32.const 42)
    (rtt.canon $struct-i32)
   )
  )
 )

 ;; CHECK:      (func $new-struct-default
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $StructNewWithDefault$many-fields
 ;; CHECK-NEXT:    (i32.const 56)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $new-struct-default (export "new-struct-default")
  (drop
   (struct.new_default_with_rtt $many-fields
    (rtt.canon $many-fields)
   )
  )
 )

 ;; CHECK:      (func $array-gets (param $ref-bytes i32) (param $ref-doubles i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $ArrayGet$bytes
 ;; CHECK-NEXT:    (local.get $ref-bytes)
 ;; CHECK-NEXT:    (i32.const 7)
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $ArrayGet$doubles
 ;; CHECK-NEXT:    (local.get $ref-doubles)
 ;; CHECK-NEXT:    (i32.const 7)
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $array-gets (export "array-gets")
  (param $ref-bytes (ref $bytes))
  (param $ref-doubles (ref $doubles))
  (drop
   (array.get $bytes (local.get $ref-bytes) (i32.const 7))
  )
  (drop
   (array.get $doubles (local.get $ref-doubles) (i32.const 7))
  )
 )

 ;; CHECK:      (func $array-sets (param $ref-bytes i32) (param $ref-doubles i32)
 ;; CHECK-NEXT:  (call $ArraySet$bytes
 ;; CHECK-NEXT:   (local.get $ref-bytes)
 ;; CHECK-NEXT:   (i32.const 7)
 ;; CHECK-NEXT:   (i32.const 42)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (call $ArraySet$doubles
 ;; CHECK-NEXT:   (local.get $ref-doubles)
 ;; CHECK-NEXT:   (i32.const 7)
 ;; CHECK-NEXT:   (f64.const 3.14159)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $array-sets (export "array-sets")
  (param $ref-bytes (ref $bytes))
  (param $ref-doubles (ref $doubles))
  (array.set $bytes (local.get $ref-bytes) (i32.const 7) (i32.const 42))
  (array.set $doubles (local.get $ref-doubles) (i32.const 7) (f64.const 3.14159))
 )

 ;; CHECK:      (func $new-array
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $ArrayNew$bytes
 ;; CHECK-NEXT:    (i32.const 42)
 ;; CHECK-NEXT:    (i32.const 11)
 ;; CHECK-NEXT:    (i32.const 176)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $new-array (export "new-array")
  (drop
   (array.new_with_rtt $bytes
    (i32.const 42)
    (i32.const 11)
    (rtt.canon $bytes)
   )
  )
 )

 ;; CHECK:      (func $new-array-default
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $ArrayNewWithDefault$doubles
 ;; CHECK-NEXT:    (i32.const 11)
 ;; CHECK-NEXT:    (i32.const 128)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $new-array-default (export "new-array-default")
  (drop
   (array.new_default_with_rtt $doubles
    (i32.const 11)
    (rtt.canon $doubles)
   )
  )
 )

 ;; CHECK:      (func $array-len (param $x i32) (result i32)
 ;; CHECK-NEXT:  (call $ArrayLen
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $array-len (export "array-len") (param $x (ref $doubles)) (result i32)
  (array.len $doubles
   (local.get $x)
  )
 )

 ;; CHECK:      (func $rtt.sub
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $RttSub
 ;; CHECK-NEXT:    (i32.const 32)
 ;; CHECK-NEXT:    (i32.const 8)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $rtt.sub (export "rtt.sub")
  (drop
   (rtt.sub $struct-i32
    (rtt.canon $empty)
   )
  )
 )

 ;; CHECK:      (func $ref.as (param $x i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $RefAsNonNull
 ;; CHECK-NEXT:    (local.get $x)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $RefAsFunc
 ;; CHECK-NEXT:    (local.get $x)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $ref.as (export "ref.as") (param $x anyref)
  (drop
   (ref.as_non_null (local.get $x))
  )
  (drop
   (ref.as_func (local.get $x))
  )
 )

 ;; CHECK:      (func $ref.is (param $x i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $RefAsNonNull
 ;; CHECK-NEXT:    (local.get $x)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $RefAsData
 ;; CHECK-NEXT:    (local.get $x)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $ref.is (export "ref.is") (param $x anyref)
  (drop
   (ref.as_non_null (local.get $x))
  )
  (drop
   (ref.as_data (local.get $x))
  )
 )

 ;; CHECK:      (func $ref.func
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 300)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 300)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 308)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $ref.func (export "ref.func")
  (drop
   (ref.func $ref.func)
  )
  ;; the same ref.func should be the same.
  (drop
   (ref.func $ref.func)
  )
  ;; a different one should be different.
  (drop
   (ref.func $ref.is)
  )
 )

 ;; CHECK:      (func $ref.cast (param $x i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $RefCast
 ;; CHECK-NEXT:    (local.get $x)
 ;; CHECK-NEXT:    (i32.const 8)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $ref.cast (export "ref.cast") (param $x anyref)
  (drop
   (ref.cast (local.get $x) (rtt.canon $empty))
  )
 )

 ;; CHECK:      (func $ref.test (param $x i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $RefTest
 ;; CHECK-NEXT:    (local.get $x)
 ;; CHECK-NEXT:    (i32.const 8)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $ref.test (export "ref.test") (param $x anyref)
  (drop
   (ref.test (local.get $x) (rtt.canon $empty))
  )
 )

 ;; CHECK:      (func $call_indirect (param $x i32) (result i32)
 ;; CHECK-NEXT:  (call_indirect $original-table (type $i32_=>_i32)
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:   (i32.const 10)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $call_indirect (export "call_indirect") (param $x (ref $empty)) (result anyref)
  (call_indirect $original-table (type $any-any)
   (local.get $x)
   (i32.const 10)
  )
 )

 ;; CHECK:      (func $call_ref
 ;; CHECK-NEXT:  (call $CallRef$type$0
 ;; CHECK-NEXT:   (i32.const 284)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $call_ref (export "call_ref")
  (call_ref
   (ref.func $call_ref)
  )
 )

 ;; CHECK:      (func $call_ref_i64 (param $x i64)
 ;; CHECK-NEXT:  (call $CallRef$type$7
 ;; CHECK-NEXT:   (i64.const 100)
 ;; CHECK-NEXT:   (i32.const 292)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $call_ref_i64 (export "call_ref_i64") (param $x i64)
  (call_ref
   (i64.const 100)
   (ref.func $call_ref_i64)
  )
 )

 ;; CHECK:      (func $br_on_X (param $x i32)
 ;; CHECK-NEXT:  (local $y i32)
 ;; CHECK-NEXT:  (local $z i32)
 ;; CHECK-NEXT:  (local $temp-func i32)
 ;; CHECK-NEXT:  (local $temp-data i32)
 ;; CHECK-NEXT:  (local $temp-i31 i32)
 ;; CHECK-NEXT:  (local $6 i32)
 ;; CHECK-NEXT:  (local $7 i32)
 ;; CHECK-NEXT:  (local $8 i32)
 ;; CHECK-NEXT:  (local $9 i32)
 ;; CHECK-NEXT:  (local $10 i32)
 ;; CHECK-NEXT:  (local $11 i32)
 ;; CHECK-NEXT:  (local $12 i32)
 ;; CHECK-NEXT:  (local $13 i32)
 ;; CHECK-NEXT:  (block $null
 ;; CHECK-NEXT:   (local.set $z
 ;; CHECK-NEXT:    (block (result i32)
 ;; CHECK-NEXT:     (local.set $6
 ;; CHECK-NEXT:      (local.get $x)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (br_if $null
 ;; CHECK-NEXT:      (call $RefIsNull
 ;; CHECK-NEXT:       (local.get $6)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (local.get $6)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (block $func (result i32)
 ;; CHECK-NEXT:    (local.set $y
 ;; CHECK-NEXT:     (block (result i32)
 ;; CHECK-NEXT:      (local.set $7
 ;; CHECK-NEXT:       (local.get $x)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:      (br_if $func
 ;; CHECK-NEXT:       (local.get $7)
 ;; CHECK-NEXT:       (call $RefIsFunc
 ;; CHECK-NEXT:        (local.get $7)
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (block $data (result i32)
 ;; CHECK-NEXT:    (local.set $y
 ;; CHECK-NEXT:     (block (result i32)
 ;; CHECK-NEXT:      (local.set $8
 ;; CHECK-NEXT:       (local.get $x)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:      (br_if $data
 ;; CHECK-NEXT:       (local.get $8)
 ;; CHECK-NEXT:       (call $RefIsData
 ;; CHECK-NEXT:        (local.get $8)
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (block $i31 (result i32)
 ;; CHECK-NEXT:    (local.set $y
 ;; CHECK-NEXT:     (block (result i32)
 ;; CHECK-NEXT:      (local.set $9
 ;; CHECK-NEXT:       (local.get $x)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:      (br_if $i31
 ;; CHECK-NEXT:       (local.get $9)
 ;; CHECK-NEXT:       (call $RefIsI31
 ;; CHECK-NEXT:        (local.get $9)
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (block $non-null (result i32)
 ;; CHECK-NEXT:    (block
 ;; CHECK-NEXT:     (local.set $10
 ;; CHECK-NEXT:      (local.get $x)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (drop
 ;; CHECK-NEXT:      (br_if $non-null
 ;; CHECK-NEXT:       (local.get $10)
 ;; CHECK-NEXT:       (i32.eqz
 ;; CHECK-NEXT:        (call $RefIsNull
 ;; CHECK-NEXT:         (local.get $10)
 ;; CHECK-NEXT:        )
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (unreachable)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (block $non-func (result i32)
 ;; CHECK-NEXT:    (local.set $temp-func
 ;; CHECK-NEXT:     (block (result i32)
 ;; CHECK-NEXT:      (local.set $11
 ;; CHECK-NEXT:       (local.get $x)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:      (br_if $non-func
 ;; CHECK-NEXT:       (local.get $11)
 ;; CHECK-NEXT:       (i32.eqz
 ;; CHECK-NEXT:        (call $RefIsFunc
 ;; CHECK-NEXT:         (local.get $11)
 ;; CHECK-NEXT:        )
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (block $non-data (result i32)
 ;; CHECK-NEXT:    (local.set $temp-data
 ;; CHECK-NEXT:     (block (result i32)
 ;; CHECK-NEXT:      (local.set $12
 ;; CHECK-NEXT:       (local.get $x)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:      (br_if $non-data
 ;; CHECK-NEXT:       (local.get $12)
 ;; CHECK-NEXT:       (i32.eqz
 ;; CHECK-NEXT:        (call $RefIsData
 ;; CHECK-NEXT:         (local.get $12)
 ;; CHECK-NEXT:        )
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (block $non-i31 (result i32)
 ;; CHECK-NEXT:    (local.set $temp-i31
 ;; CHECK-NEXT:     (block (result i32)
 ;; CHECK-NEXT:      (local.set $13
 ;; CHECK-NEXT:       (local.get $x)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:      (br_if $non-i31
 ;; CHECK-NEXT:       (local.get $13)
 ;; CHECK-NEXT:       (i32.eqz
 ;; CHECK-NEXT:        (call $RefIsI31
 ;; CHECK-NEXT:         (local.get $13)
 ;; CHECK-NEXT:        )
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $br_on_X (export "br_on_X") (param $x anyref)
  (local $y anyref)
  (local $z (ref null any))
  (local $temp-func (ref null func))
  (local $temp-data (ref null data))
  (local $temp-i31 (ref null i31))
  (block $null
   (local.set $z
    (br_on_null $null (local.get $x))
   )
  )
  (drop
   (block $func (result funcref)
    (local.set $y
     (br_on_func $func (local.get $x))
    )
    (ref.null func)
   )
  )
  (drop
   (block $data (result (ref null data))
    (local.set $y
     (br_on_data $data (local.get $x))
    )
    (ref.null data)
   )
  )
  (drop
   (block $i31 (result (ref null i31))
    (local.set $y
     (br_on_i31 $i31 (local.get $x))
    )
    (ref.null i31)
   )
  )
  (drop
   (block $non-null (result (ref any))
    (br_on_non_null $non-null (local.get $x))
    (unreachable)
   )
  )
  (drop
   (block $non-func (result anyref)
    (local.set $temp-func
     (br_on_non_func $non-func (local.get $x))
    )
    (ref.null any)
   )
  )
  (drop
   (block $non-data (result anyref)
    (local.set $temp-data
     (br_on_non_data $non-data (local.get $x))
    )
    (ref.null any)
   )
  )
  (drop
   (block $non-i31 (result anyref)
    (local.set $temp-i31
     (br_on_non_i31 $non-i31 (local.get $x))
    )
    (ref.null any)
   )
  )
 )
 ;; CHECK:      (func $ref-eq (param $x i32) (param $y i32) (result i32)
 ;; CHECK-NEXT:  (i32.eq
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $ref-eq (export "ref-eq") (param $x eqref) (param $y eqref) (result i32)
  (ref.eq (local.get $x) (local.get $y))
 )
 ;; CHECK:      (func $struct-nn (param $x i32) (result i32)
 ;; CHECK-NEXT:  (local.get $x)
 ;; CHECK-NEXT: )
 (func $struct-nn (export "struct-nn") (param $x (ref $struct-nn)) (result (ref $struct-nn))
  ;; Use this type, so that we emit the support code for it, which tests our
  ;; handling of a struct with a non-nullable field.
  (local.get $x)
 )
 ;; CHECK:      (func $send-anything
 ;; CHECK-NEXT:  (call $send-any
 ;; CHECK-NEXT:   (i32.const 0)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $send-anything (export "send-any")
  (call $send-any
   (ref.null $empty)
  )
 )
)
;; CHECK:      (func $lowergc-start
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 8)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 12)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 16)
;; CHECK-NEXT:   (i32.const 8)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 20)
;; CHECK-NEXT:   (i32.const 0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 24)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 28)
;; CHECK-NEXT:   (i32.const 20)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 32)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 36)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 40)
;; CHECK-NEXT:   (i32.const 32)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 44)
;; CHECK-NEXT:   (i32.const 0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 48)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 52)
;; CHECK-NEXT:   (i32.const 44)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 56)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 60)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 64)
;; CHECK-NEXT:   (i32.const 56)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 68)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 72)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 76)
;; CHECK-NEXT:   (i32.const 68)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 80)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 84)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 88)
;; CHECK-NEXT:   (i32.const 80)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 92)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 96)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 100)
;; CHECK-NEXT:   (i32.const 92)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 104)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 108)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 112)
;; CHECK-NEXT:   (i32.const 104)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 116)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 120)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 124)
;; CHECK-NEXT:   (i32.const 116)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 128)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 132)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 136)
;; CHECK-NEXT:   (i32.const 128)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 140)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 144)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 148)
;; CHECK-NEXT:   (i32.const 140)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 152)
;; CHECK-NEXT:   (i32.const 0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 156)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 160)
;; CHECK-NEXT:   (i32.const 152)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 164)
;; CHECK-NEXT:   (i32.const 0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 168)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 172)
;; CHECK-NEXT:   (i32.const 164)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 176)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 180)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 184)
;; CHECK-NEXT:   (i32.const 176)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 188)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 192)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 196)
;; CHECK-NEXT:   (i32.const 188)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 200)
;; CHECK-NEXT:   (i32.const 0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 204)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 208)
;; CHECK-NEXT:   (i32.const 200)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 212)
;; CHECK-NEXT:   (i32.const 0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 216)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 220)
;; CHECK-NEXT:   (i32.const 212)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 224)
;; CHECK-NEXT:   (i32.const 0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 228)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 232)
;; CHECK-NEXT:   (i32.const 224)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 236)
;; CHECK-NEXT:   (i32.const 0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 240)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 244)
;; CHECK-NEXT:   (i32.const 236)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 248)
;; CHECK-NEXT:   (i32.const 0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 252)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 256)
;; CHECK-NEXT:   (i32.const 248)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 260)
;; CHECK-NEXT:   (i32.const 0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 264)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 268)
;; CHECK-NEXT:   (i32.const 260)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 272)
;; CHECK-NEXT:   (i32.const 0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 276)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 280)
;; CHECK-NEXT:   (i32.const 272)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 284)
;; CHECK-NEXT:   (i32.const 20)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 288)
;; CHECK-NEXT:   (i32.const 0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 292)
;; CHECK-NEXT:   (i32.const 248)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 296)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 300)
;; CHECK-NEXT:   (i32.const 20)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 304)
;; CHECK-NEXT:   (i32.const 2)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 308)
;; CHECK-NEXT:   (i32.const 44)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 312)
;; CHECK-NEXT:   (i32.const 3)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (global.set $global1
;; CHECK-NEXT:   (call $RttSub
;; CHECK-NEXT:    (i32.const 32)
;; CHECK-NEXT:    (global.get $global0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (global.set $global2
;; CHECK-NEXT:   (call $RttSub
;; CHECK-NEXT:    (i32.const 140)
;; CHECK-NEXT:    (global.get $global1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (global.set $global3
;; CHECK-NEXT:   (call $RttSub
;; CHECK-NEXT:    (i32.const 140)
;; CHECK-NEXT:    (global.get $global2)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $CallRef$type$0 (param $0 i32)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (call_indirect $lowergc-table (type $type$0)
;; CHECK-NEXT:    (i32.load offset=4
;; CHECK-NEXT:     (local.get $0)
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $StructNew$struct-i32 (param $0 i32) (param $1 i32) (result i32)
;; CHECK-NEXT:  (local $2 i32)
;; CHECK-NEXT:  (local.set $2
;; CHECK-NEXT:   (call $malloc
;; CHECK-NEXT:    (i32.const 8)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (local.get $2)
;; CHECK-NEXT:   (local.get $1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (call $StructSet$struct-i32$0
;; CHECK-NEXT:   (local.get $2)
;; CHECK-NEXT:   (local.get $0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (local.get $2)
;; CHECK-NEXT: )

;; CHECK:      (func $StructSet$struct-i32$0 (param $0 i32) (param $1 i32)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (i32.store offset=4
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:    (local.get $1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $StructGet$struct-i32$0 (param $0 i32) (param $1 i32) (result i32)
;; CHECK-NEXT:  (if (result i32)
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (i32.load offset=4
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $StructNewWithDefault$many-fields (param $0 i32) (result i32)
;; CHECK-NEXT:  (local $1 i32)
;; CHECK-NEXT:  (local.set $1
;; CHECK-NEXT:   (call $malloc
;; CHECK-NEXT:    (i32.const 20)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (local.get $1)
;; CHECK-NEXT:   (local.get $0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (call $StructSet$many-fields$0
;; CHECK-NEXT:   (local.get $1)
;; CHECK-NEXT:   (i32.const 0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (call $StructSet$many-fields$1
;; CHECK-NEXT:   (local.get $1)
;; CHECK-NEXT:   (f64.const 0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (call $StructSet$many-fields$2
;; CHECK-NEXT:   (local.get $1)
;; CHECK-NEXT:   (f32.const 0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (local.get $1)
;; CHECK-NEXT: )

;; CHECK:      (func $StructSet$many-fields$0 (param $0 i32) (param $1 i32)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (i32.store offset=4
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:    (local.get $1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $StructSet$many-fields$1 (param $0 i32) (param $1 f64)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (f64.store offset=8
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:    (local.get $1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $StructSet$many-fields$2 (param $0 i32) (param $1 f32)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (f32.store offset=16
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:    (local.get $1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $StructSet$struct-i64$0 (param $0 i32) (param $1 i64)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (i64.store offset=4
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:    (local.get $1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $StructGet$struct-i64$0 (param $0 i32) (param $1 i32) (result i64)
;; CHECK-NEXT:  (if (result i64)
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (i64.load offset=4
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $StructSet$struct-f32$0 (param $0 i32) (param $1 f32)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (f32.store offset=4
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:    (local.get $1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $StructGet$struct-f32$0 (param $0 i32) (param $1 i32) (result f32)
;; CHECK-NEXT:  (if (result f32)
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (f32.load offset=4
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $StructSet$struct-f64$0 (param $0 i32) (param $1 f64)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (f64.store offset=4
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:    (local.get $1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $StructGet$struct-f64$0 (param $0 i32) (param $1 i32) (result f64)
;; CHECK-NEXT:  (if (result f64)
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (f64.load offset=4
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $StructSet$struct-ref$0 (param $0 i32) (param $1 i32)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (i32.store offset=4
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:    (local.get $1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $StructGet$struct-ref$0 (param $0 i32) (param $1 i32) (result i32)
;; CHECK-NEXT:  (if (result i32)
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (i32.load offset=4
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $StructSet$struct-rtt$0 (param $0 i32) (param $1 i32)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (i32.store offset=4
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:    (local.get $1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $StructGet$struct-rtt$0 (param $0 i32) (param $1 i32) (result i32)
;; CHECK-NEXT:  (if (result i32)
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (i32.load offset=4
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $ArrayNewWithDefault$doubles (param $0 i32) (param $1 i32) (result i32)
;; CHECK-NEXT:  (local $2 i32)
;; CHECK-NEXT:  (local.set $2
;; CHECK-NEXT:   (call $malloc
;; CHECK-NEXT:    (i32.add
;; CHECK-NEXT:     (i32.const 8)
;; CHECK-NEXT:     (i32.mul
;; CHECK-NEXT:      (i32.const 8)
;; CHECK-NEXT:      (local.get $0)
;; CHECK-NEXT:     )
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store offset=4
;; CHECK-NEXT:   (local.get $2)
;; CHECK-NEXT:   (local.get $0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (local.get $2)
;; CHECK-NEXT:   (local.get $1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (loop $loop
;; CHECK-NEXT:   (block $block
;; CHECK-NEXT:    (br_if $block
;; CHECK-NEXT:     (i32.eqz
;; CHECK-NEXT:      (local.get $0)
;; CHECK-NEXT:     )
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (call $ArraySet$doubles
;; CHECK-NEXT:     (local.get $2)
;; CHECK-NEXT:     (i32.sub
;; CHECK-NEXT:      (local.get $0)
;; CHECK-NEXT:      (i32.const 1)
;; CHECK-NEXT:     )
;; CHECK-NEXT:     (f64.const 0)
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (local.set $0
;; CHECK-NEXT:     (i32.sub
;; CHECK-NEXT:      (local.get $0)
;; CHECK-NEXT:      (i32.const 1)
;; CHECK-NEXT:     )
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (br $loop)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (local.get $2)
;; CHECK-NEXT: )

;; CHECK:      (func $ArraySet$doubles (param $0 i32) (param $1 i32) (param $2 f64)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (f64.store
;; CHECK-NEXT:    (i32.add
;; CHECK-NEXT:     (i32.add
;; CHECK-NEXT:      (local.get $0)
;; CHECK-NEXT:      (i32.const 8)
;; CHECK-NEXT:     )
;; CHECK-NEXT:     (i32.mul
;; CHECK-NEXT:      (i32.const 8)
;; CHECK-NEXT:      (local.get $1)
;; CHECK-NEXT:     )
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (local.get $2)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $ArrayGet$doubles (param $0 i32) (param $1 i32) (param $2 i32) (result f64)
;; CHECK-NEXT:  (if (result f64)
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (f64.load
;; CHECK-NEXT:    (i32.add
;; CHECK-NEXT:     (i32.add
;; CHECK-NEXT:      (local.get $0)
;; CHECK-NEXT:      (i32.const 8)
;; CHECK-NEXT:     )
;; CHECK-NEXT:     (i32.mul
;; CHECK-NEXT:      (i32.const 8)
;; CHECK-NEXT:      (local.get $1)
;; CHECK-NEXT:     )
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $ArrayNew$bytes (param $0 i32) (param $1 i32) (param $2 i32) (result i32)
;; CHECK-NEXT:  (local $3 i32)
;; CHECK-NEXT:  (local.set $3
;; CHECK-NEXT:   (call $malloc
;; CHECK-NEXT:    (i32.add
;; CHECK-NEXT:     (i32.const 8)
;; CHECK-NEXT:     (i32.mul
;; CHECK-NEXT:      (i32.const 1)
;; CHECK-NEXT:      (local.get $1)
;; CHECK-NEXT:     )
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store offset=4
;; CHECK-NEXT:   (local.get $3)
;; CHECK-NEXT:   (local.get $1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (local.get $3)
;; CHECK-NEXT:   (local.get $2)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (loop $loop
;; CHECK-NEXT:   (block $block
;; CHECK-NEXT:    (br_if $block
;; CHECK-NEXT:     (i32.eqz
;; CHECK-NEXT:      (local.get $1)
;; CHECK-NEXT:     )
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (call $ArraySet$bytes
;; CHECK-NEXT:     (local.get $3)
;; CHECK-NEXT:     (i32.sub
;; CHECK-NEXT:      (local.get $1)
;; CHECK-NEXT:      (i32.const 1)
;; CHECK-NEXT:     )
;; CHECK-NEXT:     (local.get $0)
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (local.set $1
;; CHECK-NEXT:     (i32.sub
;; CHECK-NEXT:      (local.get $1)
;; CHECK-NEXT:      (i32.const 1)
;; CHECK-NEXT:     )
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (br $loop)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (local.get $3)
;; CHECK-NEXT: )

;; CHECK:      (func $ArraySet$bytes (param $0 i32) (param $1 i32) (param $2 i32)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (i32.store8
;; CHECK-NEXT:    (i32.add
;; CHECK-NEXT:     (i32.add
;; CHECK-NEXT:      (local.get $0)
;; CHECK-NEXT:      (i32.const 8)
;; CHECK-NEXT:     )
;; CHECK-NEXT:     (i32.mul
;; CHECK-NEXT:      (i32.const 1)
;; CHECK-NEXT:      (local.get $1)
;; CHECK-NEXT:     )
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (local.get $2)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $ArrayGet$bytes (param $0 i32) (param $1 i32) (param $2 i32) (result i32)
;; CHECK-NEXT:  (if (result i32)
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (if (result i32)
;; CHECK-NEXT:    (i32.eqz
;; CHECK-NEXT:     (local.get $2)
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (i32.load8_u
;; CHECK-NEXT:     (i32.add
;; CHECK-NEXT:      (i32.add
;; CHECK-NEXT:       (local.get $0)
;; CHECK-NEXT:       (i32.const 8)
;; CHECK-NEXT:      )
;; CHECK-NEXT:      (i32.mul
;; CHECK-NEXT:       (i32.const 1)
;; CHECK-NEXT:       (local.get $1)
;; CHECK-NEXT:      )
;; CHECK-NEXT:     )
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (i32.load8_s
;; CHECK-NEXT:     (i32.add
;; CHECK-NEXT:      (i32.add
;; CHECK-NEXT:       (local.get $0)
;; CHECK-NEXT:       (i32.const 8)
;; CHECK-NEXT:      )
;; CHECK-NEXT:      (i32.mul
;; CHECK-NEXT:       (i32.const 1)
;; CHECK-NEXT:       (local.get $1)
;; CHECK-NEXT:      )
;; CHECK-NEXT:     )
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $CallRef$type$7 (param $0 i64) (param $1 i32)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (call_indirect $lowergc-table (type $type$7)
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:    (i32.load offset=4
;; CHECK-NEXT:     (local.get $1)
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $RefAsNonNull (param $0 i32) (result i32)
;; CHECK-NEXT:  (if (result i32)
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (local.get $0)
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $RefAsFunc (param $0 i32) (result i32)
;; CHECK-NEXT:  (if (result i32)
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (block (result i32)
;; CHECK-NEXT:    (if
;; CHECK-NEXT:     (i32.ne
;; CHECK-NEXT:      (i32.load
;; CHECK-NEXT:       (i32.load
;; CHECK-NEXT:        (local.get $0)
;; CHECK-NEXT:       )
;; CHECK-NEXT:      )
;; CHECK-NEXT:      (i32.const 0)
;; CHECK-NEXT:     )
;; CHECK-NEXT:     (unreachable)
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $RefAsData (param $0 i32) (result i32)
;; CHECK-NEXT:  (if (result i32)
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (block (result i32)
;; CHECK-NEXT:    (if
;; CHECK-NEXT:     (i32.ne
;; CHECK-NEXT:      (i32.load
;; CHECK-NEXT:       (i32.load
;; CHECK-NEXT:        (local.get $0)
;; CHECK-NEXT:       )
;; CHECK-NEXT:      )
;; CHECK-NEXT:      (i32.const 1)
;; CHECK-NEXT:     )
;; CHECK-NEXT:     (unreachable)
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $RefIsNull (param $0 i32) (result i32)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (return
;; CHECK-NEXT:    (i32.const 1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.const 0)
;; CHECK-NEXT: )

;; CHECK:      (func $RefIsFunc (param $0 i32) (result i32)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (return
;; CHECK-NEXT:    (i32.const 0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.ne
;; CHECK-NEXT:    (i32.load
;; CHECK-NEXT:     (i32.load
;; CHECK-NEXT:      (local.get $0)
;; CHECK-NEXT:     )
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (i32.const 0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (return
;; CHECK-NEXT:    (i32.const 0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.const 1)
;; CHECK-NEXT: )

;; CHECK:      (func $RefIsData (param $0 i32) (result i32)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (return
;; CHECK-NEXT:    (i32.const 0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.ne
;; CHECK-NEXT:    (i32.load
;; CHECK-NEXT:     (i32.load
;; CHECK-NEXT:      (local.get $0)
;; CHECK-NEXT:     )
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (i32.const 1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (return
;; CHECK-NEXT:    (i32.const 0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.const 1)
;; CHECK-NEXT: )

;; CHECK:      (func $RefIsI31 (param $0 i32) (result i32)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (return
;; CHECK-NEXT:    (i32.const 0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.ne
;; CHECK-NEXT:    (i32.load
;; CHECK-NEXT:     (i32.load
;; CHECK-NEXT:      (local.get $0)
;; CHECK-NEXT:     )
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (i32.const 2)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (return
;; CHECK-NEXT:    (i32.const 0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.const 1)
;; CHECK-NEXT: )

;; CHECK:      (func $RefTest (param $0 i32) (param $1 i32) (result i32)
;; CHECK-NEXT:  (local $2 i32)
;; CHECK-NEXT:  (local $3 i32)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (return
;; CHECK-NEXT:    (i32.const 0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (local.set $2
;; CHECK-NEXT:   (i32.load
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.ne
;; CHECK-NEXT:    (i32.load
;; CHECK-NEXT:     (local.get $1)
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (i32.load
;; CHECK-NEXT:     (local.get $2)
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (return
;; CHECK-NEXT:    (i32.const 0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.gt_u
;; CHECK-NEXT:    (i32.load offset=4
;; CHECK-NEXT:     (local.get $1)
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (i32.load offset=4
;; CHECK-NEXT:     (local.get $2)
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (return
;; CHECK-NEXT:    (i32.const 0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (local.set $3
;; CHECK-NEXT:   (i32.load offset=4
;; CHECK-NEXT:    (local.get $1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (loop $loop
;; CHECK-NEXT:   (if
;; CHECK-NEXT:    (i32.ne
;; CHECK-NEXT:     (i32.load offset=8
;; CHECK-NEXT:      (local.get $1)
;; CHECK-NEXT:     )
;; CHECK-NEXT:     (i32.load offset=8
;; CHECK-NEXT:      (local.get $2)
;; CHECK-NEXT:     )
;; CHECK-NEXT:    )
;; CHECK-NEXT:    (return
;; CHECK-NEXT:     (i32.const 0)
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (local.set $1
;; CHECK-NEXT:    (i32.add
;; CHECK-NEXT:     (local.get $1)
;; CHECK-NEXT:     (i32.const 4)
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (local.set $2
;; CHECK-NEXT:    (i32.add
;; CHECK-NEXT:     (local.get $2)
;; CHECK-NEXT:     (i32.const 4)
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (local.set $3
;; CHECK-NEXT:    (i32.sub
;; CHECK-NEXT:     (local.get $3)
;; CHECK-NEXT:     (i32.const 1)
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (br_if $loop
;; CHECK-NEXT:    (local.get $3)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (return
;; CHECK-NEXT:    (i32.const 1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $RefCast (param $0 i32) (param $1 i32) (result i32)
;; CHECK-NEXT:  (local $2 i32)
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (return
;; CHECK-NEXT:    (i32.const 0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (call $RefTest
;; CHECK-NEXT:     (local.get $0)
;; CHECK-NEXT:     (local.get $1)
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (return
;; CHECK-NEXT:   (local.get $0)
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $RttSub (param $0 i32) (param $1 i32) (result i32)
;; CHECK-NEXT:  (local $2 i32)
;; CHECK-NEXT:  (local $3 i32)
;; CHECK-NEXT:  (local $4 i32)
;; CHECK-NEXT:  (local.set $3
;; CHECK-NEXT:   (i32.load offset=4
;; CHECK-NEXT:    (local.get $1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (local.set $2
;; CHECK-NEXT:   (call $malloc
;; CHECK-NEXT:    (i32.add
;; CHECK-NEXT:     (i32.mul
;; CHECK-NEXT:      (local.get $3)
;; CHECK-NEXT:      (i32.const 4)
;; CHECK-NEXT:     )
;; CHECK-NEXT:     (i32.const 12)
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (local.get $2)
;; CHECK-NEXT:   (i32.load
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store offset=4
;; CHECK-NEXT:   (local.get $2)
;; CHECK-NEXT:   (i32.add
;; CHECK-NEXT:    (local.get $3)
;; CHECK-NEXT:    (i32.const 1)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (local.set $4
;; CHECK-NEXT:   (local.get $2)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (loop $loop
;; CHECK-NEXT:   (i32.store offset=8
;; CHECK-NEXT:    (local.get $4)
;; CHECK-NEXT:    (i32.load offset=8
;; CHECK-NEXT:     (local.get $1)
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (local.set $4
;; CHECK-NEXT:    (i32.add
;; CHECK-NEXT:     (local.get $4)
;; CHECK-NEXT:     (i32.const 4)
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (local.set $1
;; CHECK-NEXT:    (i32.add
;; CHECK-NEXT:     (local.get $1)
;; CHECK-NEXT:     (i32.const 4)
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (local.set $3
;; CHECK-NEXT:    (i32.sub
;; CHECK-NEXT:     (local.get $3)
;; CHECK-NEXT:     (i32.const 1)
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (br_if $loop
;; CHECK-NEXT:    (local.get $3)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store offset=8
;; CHECK-NEXT:   (local.get $4)
;; CHECK-NEXT:   (local.get $0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (local.get $2)
;; CHECK-NEXT: )

;; CHECK:      (func $ArrayLen (param $0 i32) (result i32)
;; CHECK-NEXT:  (if (result i32)
;; CHECK-NEXT:   (i32.eqz
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:   (i32.load offset=4
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $malloc (param $0 i32) (result i32)
;; CHECK-NEXT:  (global.set $lowergc-next-malloc
;; CHECK-NEXT:   (i32.add
;; CHECK-NEXT:    (global.get $lowergc-next-malloc)
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.ge_u
;; CHECK-NEXT:    (global.get $lowergc-next-malloc)
;; CHECK-NEXT:    (i32.mul
;; CHECK-NEXT:     (memory.size)
;; CHECK-NEXT:     (i32.const 65536)
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.sub
;; CHECK-NEXT:   (global.get $lowergc-next-malloc)
;; CHECK-NEXT:   (local.get $0)
;; CHECK-NEXT:  )
;; CHECK-NEXT: )
(module ;; If a memory already exists, we should append to it. The total memory
        ;; size should increase, and malloc should start from the new part.
 ;; CHECK:      (type $type$0 (func))

 ;; CHECK:      (type $i32_=>_i32 (func (param i32) (result i32)))

 ;; CHECK:      (global $lowergc-next-malloc (mut i32) (i32.const 65560))

 ;; CHECK:      (memory $0 16385 16385)
 (memory $0 1 1)
 (type $empty (struct))

 ;; CHECK:      (export "new-struct" (func $new-struct))

 ;; CHECK:      (start $lowergc-start)

 ;; CHECK:      (func $new-struct
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (call $StructNewWithDefault$empty
 ;; CHECK-NEXT:    (i32.const 65548)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $new-struct (export "new-struct")
  (drop
   (struct.new_with_rtt $empty
    (rtt.canon $empty)
   )
  )
 )
)
;; CHECK:      (func $lowergc-start
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 65536)
;; CHECK-NEXT:   (i32.const 0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 65540)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 65544)
;; CHECK-NEXT:   (i32.const 65536)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 65548)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 65552)
;; CHECK-NEXT:   (i32.const 1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (i32.const 65556)
;; CHECK-NEXT:   (i32.const 65548)
;; CHECK-NEXT:  )
;; CHECK-NEXT: )

;; CHECK:      (func $StructNewWithDefault$empty (param $0 i32) (result i32)
;; CHECK-NEXT:  (local $1 i32)
;; CHECK-NEXT:  (local.set $1
;; CHECK-NEXT:   (call $malloc
;; CHECK-NEXT:    (i32.const 4)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.store
;; CHECK-NEXT:   (local.get $1)
;; CHECK-NEXT:   (local.get $0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (local.get $1)
;; CHECK-NEXT: )

;; CHECK:      (func $malloc (param $0 i32) (result i32)
;; CHECK-NEXT:  (global.set $lowergc-next-malloc
;; CHECK-NEXT:   (i32.add
;; CHECK-NEXT:    (global.get $lowergc-next-malloc)
;; CHECK-NEXT:    (local.get $0)
;; CHECK-NEXT:   )
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (if
;; CHECK-NEXT:   (i32.ge_u
;; CHECK-NEXT:    (global.get $lowergc-next-malloc)
;; CHECK-NEXT:    (i32.mul
;; CHECK-NEXT:     (memory.size)
;; CHECK-NEXT:     (i32.const 65536)
;; CHECK-NEXT:    )
;; CHECK-NEXT:   )
;; CHECK-NEXT:   (unreachable)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (i32.sub
;; CHECK-NEXT:   (global.get $lowergc-next-malloc)
;; CHECK-NEXT:   (local.get $0)
;; CHECK-NEXT:  )
;; CHECK-NEXT: )
(module) ;; We should not crash on an empty module.
;; CHECK:      (type $none_=>_none (func))

;; CHECK:      (start $lowergc-start)

;; CHECK:      (func $lowergc-start
;; CHECK-NEXT: )
