;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: foreach %s %t wasm-opt -all --closed-world --traps-never-happen --generate-global-effects --vacuum -S -o - | filecheck %s

;; Tests for aggregating effects from indirect calls in GlobalEffects when
;; --closed-world is true. Continued from global-effects-closed-world.wast, but
;; adding traps-never-happen.

(module
  ;; CHECK:      (type $nopType (func (param i32)))
  (type $nopType (func (param i32)))

  (table 1 1 funcref)

  ;; CHECK:      (func $nop (type $nopType) (param $0 i32)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $nop (export "nop") (type $nopType)
    (nop)
  )

  ;; CHECK:      (func $calls-nop-via-nullable-ref (type $1) (param $ref (ref null $nopType))
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $calls-nop-via-nullable-ref (param $ref (ref null $nopType))
    ;; We would trap if $ref is null, but otherwise this has no effects.
    (call_ref $nopType (i32.const 1) (local.get $ref))
  )

  ;; CHECK:      (func $calls-nop-via-ref (type $2)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $calls-nop-via-ref
    ;; We may trap due to index out of bounds or the function type not matching
    ;; the table, but otherwise this has no possible effects.
    (call_indirect (type $nopType) (i32.const 1) (i32.const 0))
  )
)

(module
  ;; CHECK:      (type $super (sub (func)))
  (type $super (sub (func)))
  ;; CHECK:      (type $sub (sub $super (func)))
  (type $sub (sub $super (func)))

  ;; CHECK:      (import "" "" (func $import (type $super)))
  (import "" "" (func $import (type $super)))

  (func
    (drop (ref.func $import))
  )

  ;; CHECK:      (func $downcast-import (type $3) (param $ref (ref $super))
  ;; CHECK-NEXT:  (call_ref $sub
  ;; CHECK-NEXT:   (ref.cast (ref $sub)
  ;; CHECK-NEXT:    (local.get $ref)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call_ref $sub
  ;; CHECK-NEXT:   (ref.cast (ref (exact $sub))
  ;; CHECK-NEXT:    (local.get $ref)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $downcast-import (param $ref (ref $super))
    ;; $import's exact type could be $sub although we imported it as $super.
    ;; Since we don't know, we need to propagate $import's effects to $sub and
    ;; (exact $sub) as well.
    (call_ref $sub (ref.cast (ref $sub) (local.get $ref)))
    (call_ref $sub (ref.cast (ref (exact $sub)) (local.get $ref)))
  )
)

(module
  ;; CHECK:      (type $super (sub (func)))
  (type $super (sub (func)))
  ;; CHECK:      (type $sub (sub $super (func)))
  (type $sub (sub $super (func)))

  ;; CHECK:      (import "" "" (func $import (exact (type $super))))
  (import "" "" (func $import (exact (type $super))))

  ;; CHECK:      (func $nop (type $sub)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $nop (type $sub)
    (nop)
  )

  (func
    (drop (ref.func $nop))
    (drop (ref.func $import))
  )

  ;; CHECK:      (func $downcast (type $3) (param $ref (ref $super))
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $downcast (param $ref (ref $super))
    ;; $ref could be $import, in which case the downcast will trap.
    ;; Or it could be $nop in which case this call_ref is a nop.
    ;; We're free to optimize this to nop.
    (call_ref $sub (ref.cast (ref $sub) (local.get $ref)))
  )
)

(module
  ;; CHECK:      (type $super (sub (func)))
  (type $super (sub (func)))
  ;; CHECK:      (type $sub (sub $super (func)))
  (type $sub (sub $super (func)))

  ;; CHECK:      (import "" "" (func $import (type $super)))
  (import "" "" (func $import (type $super)))

  ;; CHECK:      (func $nop (type $sub)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $nop (type $sub)
    (nop)
  )

  (func
    (drop (ref.func $nop))
  )

  ;; CHECK:      (func $downcast (type $3) (param $ref (ref $super))
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $downcast (param $ref (ref $super))
    ;; Similar to above exact that $import is never referenced, so the only
    ;; possible callee here is $nop.
    (call_ref $sub (ref.cast (ref $sub) (local.get $ref)))
  )
)
