;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: foreach %s %t wasm-opt -all --closed-world --ignore-implicit-traps --generate-global-effects --vacuum -S -o - | filecheck %s

;; Tests for aggregating effects from indirect calls in GlobalEffects when
;; --closed-world is true. Continued from global-effects-closed-world.wast but
;; adding --ignore-implicit-traps.

(module
  (rec
    ;; CHECK:      (rec
    ;; CHECK-NEXT:  (type $nopType (func (param i32)))
    (type $nopType (func (param i32)))
    ;; CHECK:       (type $otherNopType (func (param i32)))
    (type $otherNopType (func (param i32)))
  )

  (table 1 1 (ref null $nopType))

  ;; CHECK:      (func $nop (type $nopType) (param $0 i32)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $nop (export "nop") (type $nopType)
    (nop)
  )

  ;; CHECK:      (func $indirect-call-correct-type (type $0)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $indirect-call-correct-type
    ;; Only implicit traps are possible here since the type is correct.
    ;; A trap will happen if the index is out of bounds or contains null.
    (call_indirect (type $nopType) (i32.const 1) (i32.const 0))
  )

  ;; CHECK:      (func $indirect-call-wrong-type (type $0)
  ;; CHECK-NEXT:  (call_indirect $0 (type $otherNopType)
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $indirect-call-wrong-type
    ;; This is guaranteed to trap because the type does not match the table.
    (call_indirect (type $otherNopType) (i32.const 1) (i32.const 0))
  )
)

(module
  (table 1 1 funcref)

  ;; CHECK:      (type $maybe-has-effects (func (param i32)))
  (type $maybe-has-effects (func (param i32)))

  ;; CHECK:      (func $unreachable (type $maybe-has-effects) (param $0 i32)
  ;; CHECK-NEXT:  (unreachable)
  ;; CHECK-NEXT: )
  (func $unreachable (export "unreachable") (type $maybe-has-effects) (param i32)
    (unreachable)
  )

  ;; CHECK:      (func $nop (type $maybe-has-effects) (param $0 i32)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $nop (export "nop") (type $maybe-has-effects) (param i32)
    (nop)
  )

  ;; CHECK:      (func $call-indirect-effectful-function (type $1)
  ;; CHECK-NEXT:  (call_indirect $0 (type $maybe-has-effects)
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $call-indirect-effectful-function
    ;; This may be a nop or it may trap depending on the ref.
    ;; We don't know so we don't optimize it out.
    ;; Similar to the test in global-effects-closed-world.wast, but in this case
    ;; we don't optimize the call out solely because we don't know what effects
    ;; the target function will have and not because of potential implicit
    ;; traps.
    (call_indirect (type $maybe-has-effects) (i32.const 1) (i32.const 1))
  )
)
