;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; RUN: foreach %s %t wasm-opt --nominal --global-refining -all -S -o - | filecheck %s

(module
  (global $func-1 (mut funcref) (ref.null func))
  (global $func-2 (mut funcref) (ref.func $foo))
  (func $foo
   (global.set $func-1 (ref.null func))
   (global.set $func-2 (ref.func $foo))
  )
)
