;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; RUN: foreach %s %t wasm-opt -all --closed-world --generate-global-effects --simplify-locals -S -o - | filecheck %s

;; Tests for aggregating effects from indirect calls in GlobalEffects when
;; --closed-world is true. Continued from global-effects-closed-world.wast.

(module
  ;; CHECK:      (type $indirect-type-super (sub (func (param i32))))
  (type $indirect-type-super (sub (func (param i32))))

  ;; CHECK:      (type $indirect-type-sub (sub $indirect-type-super (func (param i32))))
  (type $indirect-type-sub (sub $indirect-type-super (func (param i32))))

  ;; CHECK:      (type $2 (func (param (ref $indirect-type-super))))

  ;; CHECK:      (global $g1 (mut i32) (i32.const 0))
  (global $g1 (mut i32) (i32.const 0))
  ;; CHECK:      (global $g2 (mut i32) (i32.const 0))
  (global $g2 (mut i32) (i32.const 0))
  ;; CHECK:      (global $g3 (mut i32) (i32.const 0))
  (global $g3 (mut i32) (i32.const 0))

  ;; CHECK:      (export "impl1" (func $impl1))

  ;; CHECK:      (export "impl2" (func $impl2))

  ;; CHECK:      (func $impl1 (type $indirect-type-super) (param $i32 i32)
  ;; CHECK-NEXT:  (global.set $g1
  ;; CHECK-NEXT:   (local.get $i32)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $impl1 (export "impl1") (type $indirect-type-super) (param $i32 i32)
    (global.set $g1 (local.get $i32))
  )

  ;; CHECK:      (func $impl2 (type $indirect-type-sub) (param $i32 i32)
  ;; CHECK-NEXT:  (global.set $g2
  ;; CHECK-NEXT:   (local.get $i32)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $impl2 (export "impl2") (type $indirect-type-sub) (param $i32 i32)
    (global.set $g2 (local.get $i32))
  )

  ;; CHECK:      (func $merges-multiple-effects (type $2) (param $ref (ref $indirect-type-super))
  ;; CHECK-NEXT:  (local $x i32)
  ;; CHECK-NEXT:  (local $y i32)
  ;; CHECK-NEXT:  (local $z i32)
  ;; CHECK-NEXT:  (local.set $x
  ;; CHECK-NEXT:   (global.get $g1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (local.set $y
  ;; CHECK-NEXT:   (global.get $g2)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (call_ref $indirect-type-super
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:   (local.get $ref)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (local.get $x)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (local.get $y)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (global.get $g3)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $merges-multiple-effects (param $ref (ref $indirect-type-super))
    (local $x i32)
    (local $y i32)
    (local $z i32)

    (local.set $x (global.get $g1))
    (local.set $y (global.get $g2))
    (local.set $z (global.get $g3))

    ;; This acts as a barrier for $x and $y, but not $z because
    ;; $ref may write to $g1 (via $impl1) or $g2 (via $impl2) but not $g3.
    ;; $z is optimized out and $x and $y are left alone.
    (call_ref $indirect-type-super (i32.const 1) (local.get $ref))

    (drop (local.get $x))
    (drop (local.get $y))
    (drop (local.get $z))
  )
)
