;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; RUN: foreach %s %t wasm-opt --gto --closed-world -all -S -o - | filecheck %s

;; Test that StructRMW and StructCmpxchg field indices are updated when GTO
;; removes or reorders fields.

(module
  ;; A shared struct with three fields. Field 0 is only written, never read,
  ;; so it will be removed. Fields 1 and 2 have both reads and writes (via
  ;; atomic operations) so they stay, but their indices shift from 1->0, 2->1.

  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $s (shared (struct (field (mut i32)) (field (mut i32)))))
  (type $s (shared (struct (field (mut i32)) (field (mut i32)) (field (mut i32)))))

  ;; CHECK:       (type $1 (func (param (ref $s))))

  ;; CHECK:       (type $2 (func (param (ref $s)) (result i32)))

  ;; CHECK:      (func $rmw-reindex (type $2) (param $0 (ref $s)) (result i32)
  ;; CHECK-NEXT:  (struct.atomic.rmw.add $s 0
  ;; CHECK-NEXT:   (local.get $0)
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $rmw-reindex (param (ref $s)) (result i32)
    ;; This RMW is on field 1, which should become field 0 after removal.
    (struct.atomic.rmw.add $s 1
      (local.get 0)
      (i32.const 1)
    )
  )

  ;; CHECK:      (func $cmpxchg-reindex (type $2) (param $0 (ref $s)) (result i32)
  ;; CHECK-NEXT:  (struct.atomic.rmw.cmpxchg $s 1
  ;; CHECK-NEXT:   (local.get $0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $cmpxchg-reindex (param (ref $s)) (result i32)
    ;; This cmpxchg is on field 2, which should become field 1 after removal.
    (struct.atomic.rmw.cmpxchg $s 2
      (local.get 0)
      (i32.const 0)
      (i32.const 1)
    )
  )

  ;; CHECK:      (func $write-only (type $1) (param $0 (ref $s))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.as_non_null
  ;; CHECK-NEXT:    (block (result (ref $s))
  ;; CHECK-NEXT:     (drop
  ;; CHECK-NEXT:      (i32.const 99)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (local.get $0)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $write-only (param (ref $s))
    ;; Write-only access to field 0, which causes it to be removable.
    (struct.set $s 0
      (local.get 0)
      (i32.const 99)
    )
  )
)
