;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt -all --heap2local -S -o - %s | filecheck %s

(module
  ;; CHECK:      (type $inner (struct (field i32)))
  (type $inner (struct (field i32)))
  ;; CHECK:      (type $outer (struct (field (mut (ref null $inner)))))
  (type $outer (struct (field (mut (ref null $inner)))))

  ;; CHECK:      (func $test (type $1) (result (ref null $inner))
  ;; CHECK-NEXT:  (local $x (ref null $outer))
  ;; CHECK-NEXT:  (local $1 (ref null $inner))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block (result nullref)
  ;; CHECK-NEXT:    (local.set $1
  ;; CHECK-NEXT:     (ref.null none)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (ref.null none)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (ref.null none)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (local.set $1
  ;; CHECK-NEXT:    (struct.new $inner
  ;; CHECK-NEXT:     (i32.const 42)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block (result (ref null $inner))
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (ref.null none)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (local.get $1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $test (result (ref null $inner))
    (local $x (ref null $outer))
    (local.set $x (struct.new_default $outer))
    (struct.set $outer 0 (local.get $x) (struct.new $inner (i32.const 42)))
    (struct.get $outer 0 (local.get $x))
  )
)
