;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --inlining --all-features -S -o - | filecheck %s

(module
 ;; CHECK:      (type $0 (func))

 ;; CHECK:      (start $2)
 (start $2)

 (func $0
  ;;@ foo.cpp:1:2
  (nop)
 )

 (func $1
  ;;@ bar.cpp:3:4:MyFunction
  (nop)
 )

 ;; CHECK:      (func $2 (type $0)
 ;; CHECK-NEXT:  (block $__inlined_func$0
 ;; CHECK-NEXT:   ;;@ foo.cpp:1:2
 ;; CHECK-NEXT:   (nop)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  ;;@
 ;; CHECK-NEXT:  (block $__inlined_func$1$1
 ;; CHECK-NEXT:   ;;@ bar.cpp:3:4:MyFunction
 ;; CHECK-NEXT:   (nop)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $2
  (call $0)
  (call $1)
 )
)
