;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --inlining -all --optimize-level=3 -S -o - | filecheck %s

;; Test the maySkipHeavyWork functionality in inlining: if a function has heavy
;; work, but we might actually avoid doing that work, then, it is still
;; potentially worth inlining.

(module
  ;; CHECK:      (type $i32_=>_none (func (param i32)))

  ;; CHECK:      (type $none_=>_none (func))

  ;; CHECK:      (type $none_=>_i32 (func (result i32)))

  ;; CHECK:      (import "outside" "work1" (func $outside-work))
  (import "outside" "work1" (func $outside-work))

  ;; CHECK:      (import "outside" "work2" (func $outside-work-result (result i32)))
  (import "outside" "work2" (func $outside-work-result (result i32)))

  (memory 1 1)

  ;; CHECK:      (memory $0 1 1)

  ;; CHECK:      (tag $exception (param i32))
  (tag $exception (param i32))

  (func $if-call (param $x i32)
    ;; An avoidable call. This should be inlined.
    (if
      (local.get $x)
      (call $outside-work)
    )
  )

  ;; CHECK:      (func $if-call-caller (param $x i32)
  ;; CHECK-NEXT:  (local $1 i32)
  ;; CHECK-NEXT:  (local $2 i32)
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (block $__inlined_func$if-call
  ;; CHECK-NEXT:    (local.set $1
  ;; CHECK-NEXT:     (local.get $x)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (if
  ;; CHECK-NEXT:     (local.get $1)
  ;; CHECK-NEXT:     (call $outside-work)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (block $__inlined_func$if-call0
  ;; CHECK-NEXT:    (local.set $2
  ;; CHECK-NEXT:     (local.get $x)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (if
  ;; CHECK-NEXT:     (local.get $2)
  ;; CHECK-NEXT:     (call $outside-work)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $if-call-caller (param $x i32)
    ;; Call more than once, to avoid us deciding to inline just because the
    ;; target has a single use.
    (call $if-call (local.get $x))
    (call $if-call (local.get $x))
  )

  (func $if-fence (param $x i32)
    ;; An avoidable atomic fence, which is very costly.
    (if
      (local.get $x)
      (atomic.fence)
    )
  )

  ;; CHECK:      (func $if-fence-caller (param $x i32)
  ;; CHECK-NEXT:  (local $1 i32)
  ;; CHECK-NEXT:  (local $2 i32)
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (block $__inlined_func$if-fence
  ;; CHECK-NEXT:    (local.set $1
  ;; CHECK-NEXT:     (local.get $x)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (if
  ;; CHECK-NEXT:     (local.get $1)
  ;; CHECK-NEXT:     (atomic.fence)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (block $__inlined_func$if-fence0
  ;; CHECK-NEXT:    (local.set $2
  ;; CHECK-NEXT:     (local.get $x)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (if
  ;; CHECK-NEXT:     (local.get $2)
  ;; CHECK-NEXT:     (atomic.fence)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $if-fence-caller (param $x i32)
    (call $if-fence (local.get $x))
    (call $if-fence (local.get $x))
  )

  (func $if-throw (param $x i32)
    ;; An avoidable throw, which is very costly.
    (if
      (local.get $x)
      (throw $exception (i32.const 0))
    )
  )

  ;; CHECK:      (func $if-throw-caller (param $x i32)
  ;; CHECK-NEXT:  (local $1 i32)
  ;; CHECK-NEXT:  (local $2 i32)
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (block $__inlined_func$if-throw
  ;; CHECK-NEXT:    (local.set $1
  ;; CHECK-NEXT:     (local.get $x)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (if
  ;; CHECK-NEXT:     (local.get $1)
  ;; CHECK-NEXT:     (throw $exception
  ;; CHECK-NEXT:      (i32.const 0)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (block $__inlined_func$if-throw0
  ;; CHECK-NEXT:    (local.set $2
  ;; CHECK-NEXT:     (local.get $x)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (if
  ;; CHECK-NEXT:     (local.get $2)
  ;; CHECK-NEXT:     (throw $exception
  ;; CHECK-NEXT:      (i32.const 0)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $if-throw-caller (param $x i32)
    (call $if-throw (local.get $x))
    (call $if-throw (local.get $x))
  )

  (func $if-else (param $x i32)
    ;; As above, but in if-else form.
    (if
      (local.get $x)
      (nop)
      (call $outside-work)
    )
  )

  ;; CHECK:      (func $if-else-caller (param $x i32)
  ;; CHECK-NEXT:  (local $1 i32)
  ;; CHECK-NEXT:  (local $2 i32)
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (block $__inlined_func$if-else
  ;; CHECK-NEXT:    (local.set $1
  ;; CHECK-NEXT:     (local.get $x)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (if
  ;; CHECK-NEXT:     (local.get $1)
  ;; CHECK-NEXT:     (nop)
  ;; CHECK-NEXT:     (call $outside-work)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (block $__inlined_func$if-else0
  ;; CHECK-NEXT:    (local.set $2
  ;; CHECK-NEXT:     (local.get $x)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (if
  ;; CHECK-NEXT:     (local.get $2)
  ;; CHECK-NEXT:     (nop)
  ;; CHECK-NEXT:     (call $outside-work)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $if-else-caller (param $x i32)
    (call $if-else (local.get $x))
    (call $if-else (local.get $x))
  )

  (func $if-else-value (param $x i32) (result i32)
    ;; As above, but with a result.
    (if (result i32)
      (local.get $x)
      (call $outside-work-result)
      (local.get $x)
    )
  )

  ;; CHECK:      (func $if-else-value-caller (param $x i32)
  ;; CHECK-NEXT:  (local $1 i32)
  ;; CHECK-NEXT:  (local $2 i32)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block (result i32)
  ;; CHECK-NEXT:    (block $__inlined_func$if-else-value (result i32)
  ;; CHECK-NEXT:     (local.set $1
  ;; CHECK-NEXT:      (local.get $x)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (if (result i32)
  ;; CHECK-NEXT:      (local.get $1)
  ;; CHECK-NEXT:      (call $outside-work-result)
  ;; CHECK-NEXT:      (local.get $1)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block (result i32)
  ;; CHECK-NEXT:    (block $__inlined_func$if-else-value0 (result i32)
  ;; CHECK-NEXT:     (local.set $2
  ;; CHECK-NEXT:      (local.get $x)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (if (result i32)
  ;; CHECK-NEXT:      (local.get $2)
  ;; CHECK-NEXT:      (call $outside-work-result)
  ;; CHECK-NEXT:      (local.get $2)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $if-else-value-caller (param $x i32)
    (drop (call $if-else-value (local.get $x)))
    (drop (call $if-else-value (local.get $x)))
  )

  (func $if-unreachable (param $x i32) (result i32)
    ;; The if arm does not return.
    (if
      (local.get $x)
      (throw $exception (i32.const 0))
    )
    (local.get $x)
  )

  ;; CHECK:      (func $if-unreachable-caller (param $x i32)
  ;; CHECK-NEXT:  (local $1 i32)
  ;; CHECK-NEXT:  (local $2 i32)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block (result i32)
  ;; CHECK-NEXT:    (block $__inlined_func$if-unreachable (result i32)
  ;; CHECK-NEXT:     (local.set $1
  ;; CHECK-NEXT:      (local.get $x)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (block (result i32)
  ;; CHECK-NEXT:      (if
  ;; CHECK-NEXT:       (local.get $1)
  ;; CHECK-NEXT:       (throw $exception
  ;; CHECK-NEXT:        (i32.const 0)
  ;; CHECK-NEXT:       )
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:      (local.get $1)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block (result i32)
  ;; CHECK-NEXT:    (block $__inlined_func$if-unreachable0 (result i32)
  ;; CHECK-NEXT:     (local.set $2
  ;; CHECK-NEXT:      (local.get $x)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (block (result i32)
  ;; CHECK-NEXT:      (if
  ;; CHECK-NEXT:       (local.get $2)
  ;; CHECK-NEXT:       (throw $exception
  ;; CHECK-NEXT:        (i32.const 0)
  ;; CHECK-NEXT:       )
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:      (local.get $2)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $if-unreachable-caller (param $x i32)
    (drop (call $if-unreachable (local.get $x)))
    (drop (call $if-unreachable (local.get $x)))
  )


  (func $if-some-unavoidable (param $x i32)
    ;; Do a little work in the condition, but not too much.
    (if
      (i32.eqz (i32.eqz (local.get $x)))
      (call $outside-work)
    )
  )

  ;; CHECK:      (func $if-some-unavoidable-caller (param $x i32)
  ;; CHECK-NEXT:  (local $1 i32)
  ;; CHECK-NEXT:  (local $2 i32)
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (block $__inlined_func$if-some-unavoidable
  ;; CHECK-NEXT:    (local.set $1
  ;; CHECK-NEXT:     (local.get $x)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (if
  ;; CHECK-NEXT:     (i32.eqz
  ;; CHECK-NEXT:      (i32.eqz
  ;; CHECK-NEXT:       (local.get $1)
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (call $outside-work)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (block $__inlined_func$if-some-unavoidable0
  ;; CHECK-NEXT:    (local.set $2
  ;; CHECK-NEXT:     (local.get $x)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (if
  ;; CHECK-NEXT:     (i32.eqz
  ;; CHECK-NEXT:      (i32.eqz
  ;; CHECK-NEXT:       (local.get $2)
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (call $outside-work)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $if-some-unavoidable-caller (param $x i32)
    (call $if-some-unavoidable (local.get $x))
    (call $if-some-unavoidable (local.get $x))
  )

  ;; CHECK:      (func $if-too-much (param $x i32)
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (i32.eqz
  ;; CHECK-NEXT:    (i32.eqz
  ;; CHECK-NEXT:     (i32.eqz
  ;; CHECK-NEXT:      (local.get $x)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (call $outside-work)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $if-too-much (param $x i32)
    ;; Do too much work in the condition. This should *not* be inlined.
    (if
      (i32.eqz (i32.eqz (i32.eqz (local.get $x))))
      (call $outside-work)
    )
  )

  ;; CHECK:      (func $if-too-much-caller (param $x i32)
  ;; CHECK-NEXT:  (call $if-too-much
  ;; CHECK-NEXT:   (local.get $x)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $if-too-much
  ;; CHECK-NEXT:   (local.get $x)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $if-too-much-caller (param $x i32)
    (call $if-too-much (local.get $x))
    (call $if-too-much (local.get $x))
  )

  (func $if-some-unavoidable-2 (param $x i32)
    ;; Do a little work in the condition, and a little after the if, but the
    ;; total is not too much.
    (if
      (i32.eqz (local.get $x))
      (call $outside-work)
    )
    (drop (i32.const 0))
  )

  ;; CHECK:      (func $if-some-unavoidable-2-caller (param $x i32)
  ;; CHECK-NEXT:  (local $1 i32)
  ;; CHECK-NEXT:  (local $2 i32)
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (block $__inlined_func$if-some-unavoidable-2
  ;; CHECK-NEXT:    (local.set $1
  ;; CHECK-NEXT:     (local.get $x)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (block
  ;; CHECK-NEXT:     (if
  ;; CHECK-NEXT:      (i32.eqz
  ;; CHECK-NEXT:       (local.get $1)
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:      (call $outside-work)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (drop
  ;; CHECK-NEXT:      (i32.const 0)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (block $__inlined_func$if-some-unavoidable-20
  ;; CHECK-NEXT:    (local.set $2
  ;; CHECK-NEXT:     (local.get $x)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (block
  ;; CHECK-NEXT:     (if
  ;; CHECK-NEXT:      (i32.eqz
  ;; CHECK-NEXT:       (local.get $2)
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:      (call $outside-work)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (drop
  ;; CHECK-NEXT:      (i32.const 0)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $if-some-unavoidable-2-caller (param $x i32)
    (call $if-some-unavoidable-2 (local.get $x))
    (call $if-some-unavoidable-2 (local.get $x))
  )

  ;; CHECK:      (func $if-too-much-2 (param $x i32)
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (i32.eqz
  ;; CHECK-NEXT:    (local.get $x)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (call $outside-work)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.eqz
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $if-too-much-2 (param $x i32)
    ;; Do too much work after the if condition. This should *not* be inlined.
    (if
      (i32.eqz (local.get $x))
      (call $outside-work)
    )
    (drop (i32.eqz (i32.const 0)))
  )

  ;; CHECK:      (func $if-too-much-2-caller (param $x i32)
  ;; CHECK-NEXT:  (call $if-too-much-2
  ;; CHECK-NEXT:   (local.get $x)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $if-too-much-2
  ;; CHECK-NEXT:   (local.get $x)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $if-too-much-2-caller (param $x i32)
    (call $if-too-much-2 (local.get $x))
    (call $if-too-much-2 (local.get $x))
  )

  (func $if-null (param $x anyref) (result anyref)
    ;; A "throw if null" function.
    (if
      (ref.is_null (local.get $x))
      (throw $exception (i32.const 0))
    )
    (local.get $x)
  )

  ;; CHECK:      (func $if-null-caller (param $x i32)
  ;; CHECK-NEXT:  (local $1 anyref)
  ;; CHECK-NEXT:  (local $2 anyref)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block (result anyref)
  ;; CHECK-NEXT:    (block $__inlined_func$if-null (result anyref)
  ;; CHECK-NEXT:     (local.set $1
  ;; CHECK-NEXT:      (ref.null any)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (block (result anyref)
  ;; CHECK-NEXT:      (if
  ;; CHECK-NEXT:       (ref.is_null
  ;; CHECK-NEXT:        (local.get $1)
  ;; CHECK-NEXT:       )
  ;; CHECK-NEXT:       (throw $exception
  ;; CHECK-NEXT:        (i32.const 0)
  ;; CHECK-NEXT:       )
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:      (local.get $1)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block (result anyref)
  ;; CHECK-NEXT:    (block $__inlined_func$if-null0 (result anyref)
  ;; CHECK-NEXT:     (local.set $2
  ;; CHECK-NEXT:      (ref.null any)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (block (result anyref)
  ;; CHECK-NEXT:      (if
  ;; CHECK-NEXT:       (ref.is_null
  ;; CHECK-NEXT:        (local.get $2)
  ;; CHECK-NEXT:       )
  ;; CHECK-NEXT:       (throw $exception
  ;; CHECK-NEXT:        (i32.const 0)
  ;; CHECK-NEXT:       )
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:      (local.get $2)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $if-null-caller (param $x i32)
    (drop (call $if-null (ref.null any)))
    (drop (call $if-null (ref.null any)))
  )
)
