;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --instrument-memory-grow --enable-memory64 -S -o - | filecheck %s

(module
  (memory i64 256 256)

  ;; CHECK:      (type $0 (func (param i32 i64) (result i64)))

  ;; CHECK:      (type $1 (func))
  (type $1 (func))

  ;; CHECK:      (import "env" "pre_memory_grow" (func $pre_memory_grow (param i32 i64) (result i64)))

  ;; CHECK:      (import "env" "post_memory_grow" (func $post_memory_grow (param i32 i64) (result i64)))

  ;; CHECK:      (memory $0 i64 256 256)

  ;; CHECK:      (func $A
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (call $post_memory_grow
  ;; CHECK-NEXT:    (i32.const 1)
  ;; CHECK-NEXT:    (memory.grow
  ;; CHECK-NEXT:     (call $pre_memory_grow
  ;; CHECK-NEXT:      (i32.const 1)
  ;; CHECK-NEXT:      (i64.const 4)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $A (type $1)
    (drop (memory.grow (i64.const 4)))
  )
)
