;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --flatten --rereloop --dce --remove-unused-brs --remove-unused-names --coalesce-locals --simplify-locals --reorder-locals --remove-unused-brs --merge-blocks --vacuum -S -o - | filecheck %s

(module
  ;; CHECK:      (type $0 (func (param i32)))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (type $2 (func (result i32)))

  ;; CHECK:      (type $3 (func (param i32) (result i32)))

  ;; CHECK:      (func $trivial
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $trivial
    (nop)
  )
  ;; CHECK:      (func $trivial2
  ;; CHECK-NEXT:  (call $trivial)
  ;; CHECK-NEXT:  (call $trivial)
  ;; CHECK-NEXT: )
  (func $trivial2
    (call $trivial)
    (call $trivial)
  )
  ;; CHECK:      (func $return-void
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $return-void
    (return)
  )
  ;; CHECK:      (func $return-val (result i32)
  ;; CHECK-NEXT:  (i32.const 1)
  ;; CHECK-NEXT: )
  (func $return-val (result i32)
    (return (i32.const 1))
  )
  ;; CHECK:      (func $ifs (param $0 i32) (result i32)
  ;; CHECK-NEXT:  (select
  ;; CHECK-NEXT:   (select
  ;; CHECK-NEXT:    (i32.const 2)
  ;; CHECK-NEXT:    (i32.const 3)
  ;; CHECK-NEXT:    (local.get $0)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (select
  ;; CHECK-NEXT:    (i32.const 4)
  ;; CHECK-NEXT:    (i32.const 5)
  ;; CHECK-NEXT:    (local.get $0)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (local.get $0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $ifs (param $x i32) (result i32)
    (if
      (local.get $x)
      (then
        (if
          (local.get $x)
          (then
            (return (i32.const 2))
          )
          (else
            (return (i32.const 3))
          )
        )
      )
    )
    (if
      (local.get $x)
      (then
        (return (i32.const 4))
      )
    )
    (return (i32.const 5))
  )
  ;; CHECK:      (func $loops (param $0 i32)
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (local.get $0)
  ;; CHECK-NEXT:   (then
  ;; CHECK-NEXT:    (loop $shape$2$continue
  ;; CHECK-NEXT:     (call $trivial)
  ;; CHECK-NEXT:     (br $shape$2$continue)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (loop $shape$4$continue
  ;; CHECK-NEXT:   (call $trivial)
  ;; CHECK-NEXT:   (if
  ;; CHECK-NEXT:    (local.get $0)
  ;; CHECK-NEXT:    (then
  ;; CHECK-NEXT:     (br $shape$4$continue)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (loop $shape$6$continue
  ;; CHECK-NEXT:   (call $trivial)
  ;; CHECK-NEXT:   (if
  ;; CHECK-NEXT:    (local.get $0)
  ;; CHECK-NEXT:    (then
  ;; CHECK-NEXT:     (br $shape$6$continue)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $loops (param $x i32)
    (if (local.get $x)
      (then
        (loop $top
          (call $trivial)
          (br $top)
        )
      )
    )
    (loop $top2
      (call $trivial)
      (br_if $top2 (local.get $x))
    )
    (loop $top3
      (call $trivial)
      (if (local.get $x) (then (br $top3)))
    )
  )
  ;; CHECK:      (func $br-out (param $0 i32)
  ;; CHECK-NEXT:  (call $br-out
  ;; CHECK-NEXT:   (i32.const 5)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $br-out (param $x i32)
    (block $out
      (call $br-out (i32.const 5))
      (br $out)
    )
  )
  ;; CHECK:      (func $unreachable (param $0 i32)
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (i32.eqz
  ;; CHECK-NEXT:    (local.get $0)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (then
  ;; CHECK-NEXT:    (call $unreachable
  ;; CHECK-NEXT:     (i32.const 5)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (return)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (local.get $0)
  ;; CHECK-NEXT:   (then
  ;; CHECK-NEXT:    (call $unreachable
  ;; CHECK-NEXT:     (i32.const 1)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (else
  ;; CHECK-NEXT:    (call $unreachable
  ;; CHECK-NEXT:     (i32.const 3)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $unreachable (param $x i32)
    (if (local.get $x)
      (then
        (if (local.get $x)
          (then
            (block
              (call $unreachable (i32.const 1))
              (unreachable)
              (call $unreachable (i32.const 2))
            )
          )
          (else
            (block
              (call $unreachable (i32.const 3))
              (return)
              (call $unreachable (i32.const 4))
            )
          )
        )
      )
    )
    (block $out
      (call $unreachable (i32.const 5))
      (br $out)
      (call $unreachable (i32.const 6))
    )
  )
  ;; CHECK:      (func $empty-blocks (param $0 i32)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $empty-blocks (param $x i32)
    (block)
    (block)
  )
  ;; CHECK:      (func $before-and-after (param $0 i32)
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 2)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 3)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 4)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (i32.eqz
  ;; CHECK-NEXT:    (local.get $0)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (then
  ;; CHECK-NEXT:    (call $before-and-after
  ;; CHECK-NEXT:     (i32.const 5)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 6)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 7)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 8)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (loop $shape$4$continue
  ;; CHECK-NEXT:   (call $before-and-after
  ;; CHECK-NEXT:    (i32.const 9)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (if
  ;; CHECK-NEXT:    (local.get $0)
  ;; CHECK-NEXT:    (then
  ;; CHECK-NEXT:     (br $shape$4$continue)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 11)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (local.get $0)
  ;; CHECK-NEXT:   (then
  ;; CHECK-NEXT:    (call $before-and-after
  ;; CHECK-NEXT:     (i32.const 12)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 13)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (local.get $0)
  ;; CHECK-NEXT:   (then
  ;; CHECK-NEXT:    (call $before-and-after
  ;; CHECK-NEXT:     (i32.const 14)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (else
  ;; CHECK-NEXT:    (call $before-and-after
  ;; CHECK-NEXT:     (i32.const 15)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (local.get $0)
  ;; CHECK-NEXT:   (then
  ;; CHECK-NEXT:    (call $before-and-after
  ;; CHECK-NEXT:     (i32.const 16)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 17)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 18)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 19)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 21)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 22)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 23)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 24)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $before-and-after
  ;; CHECK-NEXT:   (i32.const 25)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $before-and-after (param $x i32)
    (call $before-and-after (i32.const 1))
    (block
      (call $before-and-after (i32.const 2))
    )
    (call $before-and-after (i32.const 3))
    (block $out
      (call $before-and-after (i32.const 4))
      (br_if $out (local.get $x))
      (call $before-and-after (i32.const 5))
    )
    (call $before-and-after (i32.const 6))
    (loop)
    (call $before-and-after (i32.const 7))
    (loop $top)
    (call $before-and-after (i32.const 8))
    (loop $top2
      (call $before-and-after (i32.const 9))
      (br_if $top2 (local.get $x))
      (call $before-and-after (i32.const 10))
    )
    (call $before-and-after (i32.const 11))
    (if (local.get $x)
      (then
        (call $before-and-after (i32.const 12))
      )
    )
    (call $before-and-after (i32.const 13))
    (if (local.get $x)
      (then
        (call $before-and-after (i32.const 14))
      )
      (else
        (call $before-and-after (i32.const 15))
      )
    )
    (if (local.get $x)
      (then
        (block
          (call $before-and-after (i32.const 16))
        )
      )
    )
    (call $before-and-after (i32.const 17))
    (block
      (call $before-and-after (i32.const 18))
      (block
        (call $before-and-after (i32.const 19))
      )
      (call $before-and-after (i32.const 20))
    )
    (call $before-and-after (i32.const 21))
    (block
      (block
        (call $before-and-after (i32.const 22))
      )
    )
    (call $before-and-after (i32.const 23))
    (block $no1
      (block $no2
        (call $before-and-after (i32.const 24))
      )
    )
    (call $before-and-after (i32.const 25))
  )
  ;; CHECK:      (func $switch (param $0 i32)
  ;; CHECK-NEXT:  (call $switch
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block $block$7$break
  ;; CHECK-NEXT:   (block $switch$3$default
  ;; CHECK-NEXT:    (block $switch$3$case$7
  ;; CHECK-NEXT:     (br_table $switch$3$case$7 $switch$3$case$7 $switch$3$case$7 $switch$3$default
  ;; CHECK-NEXT:      (local.get $0)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (br $block$7$break)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (call $switch
  ;; CHECK-NEXT:    (i32.const 2)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $switch
  ;; CHECK-NEXT:   (i32.const 3)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $switch (param $x i32)
    (block $out
      (block $a
        (br_table $a $a (local.get $x))
      )
      (call $switch (i32.const 1))
      (block $b
        (block $c
          (br_table $b $b $b $c (local.get $x))
        )
        (call $switch (i32.const 2))
      )
      (call $switch (i32.const 3))
    )
  )
  ;; CHECK:      (func $no-return
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $no-return
    (if (i32.const 1)
      (then
        (drop (i32.const 2))
      )
      (else
        (drop (i32.const 3))
      )
    )
  )
  ;; CHECK:      (func $if-br-wat (param $0 i32)
  ;; CHECK-NEXT:  (call $if-br-wat
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block $block$2$break
  ;; CHECK-NEXT:   (if
  ;; CHECK-NEXT:    (local.get $0)
  ;; CHECK-NEXT:    (then
  ;; CHECK-NEXT:     (call $if-br-wat
  ;; CHECK-NEXT:      (i32.const 1)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (else
  ;; CHECK-NEXT:     (if
  ;; CHECK-NEXT:      (local.get $0)
  ;; CHECK-NEXT:      (then
  ;; CHECK-NEXT:       (br $block$2$break)
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (call $if-br-wat
  ;; CHECK-NEXT:    (i32.const 2)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $if-br-wat
  ;; CHECK-NEXT:   (i32.const 3)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $if-br-wat (param $x i32)
   (call $if-br-wat
    (i32.const 0)
   )
   (block $label$2
    (if
     (local.get $x)
     (then
      (call $if-br-wat
       (i32.const 1)
      )
     )
     (else
      (if
       (local.get $x)
       (then
        (br $label$2) ;; waka
       )
      )
     )
    )
    (call $if-br-wat
     (i32.const 2)
    )
   )
   (call $if-br-wat
    (i32.const 3)
   )
  )
)

