;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; (--remove-unused-names avoids names on blocks, which would hamper the
;; work in getFallthrough, as a name implies possible breaks)
;; RUN: wasm-opt %s --traps-never-happen -all --ldse -S -o - | filecheck %s

(module
 ;; CHECK:      (type $A (struct (field (mut i32))))
 (type $A (struct (field (mut i32))))

 ;; CHECK:      (global $global$0 (mut i32) (i32.const 0))
 (global $global$0 (mut i32) (i32.const 0))

 ;; CHECK:      (func $simple-reaching-trap (type $0)
 ;; CHECK-NEXT:  (local $x (ref null $A))
 ;; CHECK-NEXT:  (block
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (local.get $x)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 10)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:   (i32.const 20)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $simple-reaching-trap
  (local $x (ref null $A))

  ;; This would normally not be dead due to the unreachable but we're running with --traps-never-happen
  (struct.set $A 0
   (local.get $x)
   (i32.const 10)
  )

  (unreachable)

  (struct.set $A 0
   (local.get $x)
   (i32.const 20)
  )
 )

 ;; CHECK:      (func $global-trap (type $0)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 10)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (unreachable)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (global.set $global$0
 ;; CHECK-NEXT:   (i32.const 20)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $global-trap
  (global.set $global$0
   (i32.const 10)
  )

  ;; Conditional trap ignored when trapsNeverHappen.
  (if
   (i32.const 1)
   (then
    (unreachable)
   )
  )
  (global.set $global$0
   (i32.const 20)
  )
 )

)
