;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: foreach %s %t wasm-opt -all --licm -S -o - | filecheck %s

(module
  ;; CHECK:      (type $struct (shared (struct (field (mut i32)))))
  (type $struct (shared (struct (field (mut i32)))))

  ;; CHECK:      (memory $mem 1 1 shared)
  (memory $mem 1 1 shared)

  ;; Test 1: Allowed reordering (GC read moved before Wasm release store)
  ;; CHECK:      (func $allowed (type $1) (param $x (ref $struct))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (struct.get $struct 0
  ;; CHECK-NEXT:    (local.get $x)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (loop $loop
  ;; CHECK-NEXT:   (i32.atomic.store acqrel
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:    (i32.const 42)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (nop)
  ;; CHECK-NEXT:   (br $loop)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $allowed (param $x (ref $struct))
    (loop $loop
      ;; X: release store (Wasm memory)
      (i32.atomic.store acqrel (i32.const 0) (i32.const 42))
      ;; E: memory access (shared GC read)
      (drop
        (struct.get $struct 0 (local.get $x))
      )
      (br $loop)
    )
  )

  ;; Test 2: Disallowed reordering (GC read moved before Wasm acquire load)
  ;; CHECK:      (func $disallowed (type $1) (param $x (ref $struct))
  ;; CHECK-NEXT:  (loop $loop
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.atomic.load acqrel
  ;; CHECK-NEXT:     (i32.const 0)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (struct.get $struct 0
  ;; CHECK-NEXT:     (local.get $x)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (br $loop)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $disallowed (param $x (ref $struct))
    (loop $loop
      ;; X: acquire load (Wasm memory)
      (drop
        (i32.atomic.load acqrel (i32.const 0))
      )
      ;; E: memory access (shared GC read)
      (drop
        (struct.get $struct 0 (local.get $x))
      )
      (br $loop)
    )
  )
)
