;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: foreach %s %t wasm-opt --local-cse --intrinsic-lowering -all -S -o - | filecheck %s

(module
 ;; CHECK:      (import "binaryen-intrinsics" "call.without.effects" (func $cwe-ii-i (type $1) (param i32 i32 funcref) (result i32)))
 (import "binaryen-intrinsics" "call.without.effects" (func $cwe-ii-i (param i32 i32 funcref) (result i32)))

 ;; CHECK:      (func $add (type $0) (param $0 i32) (param $1 i32) (result i32)
 ;; CHECK-NEXT:  (i32.add
 ;; CHECK-NEXT:   (local.get $0)
 ;; CHECK-NEXT:   (local.get $1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $add (param $0 i32) (param $1 i32) (result i32)
  (i32.add (local.get $0) (local.get $1))
 )

 ;; CHECK:      (func $test (type $0) (param $0 i32) (param $1 i32) (result i32)
 ;; CHECK-NEXT:  (local $2 i32)
 ;; CHECK-NEXT:  (local $3 i32)
 ;; CHECK-NEXT:  (local $4 i32)
 ;; CHECK-NEXT:  (local.set $2
 ;; CHECK-NEXT:   (local.tee $4
 ;; CHECK-NEXT:    (call $add
 ;; CHECK-NEXT:     (local.get $0)
 ;; CHECK-NEXT:     (local.get $1)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.set $3
 ;; CHECK-NEXT:   (local.get $4)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (return
 ;; CHECK-NEXT:   (i32.add
 ;; CHECK-NEXT:    (local.get $2)
 ;; CHECK-NEXT:    (local.get $3)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $test (param $0 i32) (param $1 i32) (result i32)
  (local $2 i32)
  (local $3 i32)
  (local.set $2
   (call $cwe-ii-i
    (local.get $0)
    (local.get $1)
    (ref.func $add)
   )
  )
  (local.set $3
   (call $cwe-ii-i
    (local.get $0)
    (local.get $1)
    (ref.func $add)
   )
  )
  (return (i32.add (local.get $2) (local.get $3)))
 )
)
