;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; Test the option to provide the module name as an argument.
;; RUN: foreach %s %t wasm-opt --log-execution=foo -S -o - | filecheck %s

(module
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (type $1 (func (param i32)))

  ;; CHECK:      (import "env" "func" (func $import))
  (import "env" "func" (func $import))
  ;; CHECK:      (import "foo" "log_execution" (func $log_execution (param i32)))

  ;; CHECK:      (func $nopp
  ;; CHECK-NEXT:  (call $log_execution
  ;; CHECK-NEXT:   (i32.const 2)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $nopp
    (nop)
  )
)

