;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --mark-js-called -all -S -o - | filecheck %s

;; $configured will be marked as @binaryen.js.called. $already is already marked,
;; and nothing changes. $unconfigured* are not in configureAll so they are left
;; alone.

(module
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (type $externs (array (mut externref)))
  (type $externs (array (mut externref)))

  ;; CHECK:      (type $funcs (array (mut funcref)))
  (type $funcs (array (mut funcref)))

  ;; CHECK:      (type $bytes (array (mut i8)))
  (type $bytes (array (mut i8)))

  ;; CHECK:      (type $configureAll (func (param (ref null $externs) (ref null $funcs) (ref null $bytes) externref)))
  (type $configureAll (func (param (ref null $externs)) (param (ref null $funcs)) (param (ref null $bytes)) (param externref)))

  ;; CHECK:      (import "wasm:js-prototypes" "configureAll" (func $configureAll (type $configureAll) (param (ref null $externs) (ref null $funcs) (ref null $bytes) externref)))
  (import "wasm:js-prototypes" "configureAll" (func $configureAll (type $configureAll)))

  ;; CHECK:      (data $bytes "12345678")
  (data $bytes "12345678")

  ;; CHECK:      (elem $externs externref (item (ref.null noextern)))
  (elem $externs externref
    (ref.null extern)
  )

  ;; CHECK:      (elem $funcs func $configured $already)
  (elem $funcs funcref
    (ref.func $configured)
    (ref.func $already)
  )

  ;; CHECK:      (elem $other func $unconfigured)
  (elem $other funcref
    (ref.func $unconfigured)
  )

  ;; CHECK:      (start $start)
  (start $start)

  ;; CHECK:      (func $start (type $0)
  ;; CHECK-NEXT:  (call $configureAll
  ;; CHECK-NEXT:   (array.new_elem $externs $externs
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:    (i32.const 1)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (array.new_elem $funcs $funcs
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:    (i32.const 2)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (array.new_data $bytes $bytes
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:    (i32.const 8)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (ref.null noextern)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $start
    (call $configureAll
      (array.new_elem $externs $externs
        (i32.const 0) (i32.const 1))
      (array.new_elem $funcs $funcs
        (i32.const 0) (i32.const 2))
      (array.new_data $bytes $bytes
        (i32.const 0) (i32.const 8))
      (ref.null extern)
    )
  )

  ;; CHECK:      (@binaryen.js.called)
  ;; CHECK-NEXT: (func $configured (type $0)
  ;; CHECK-NEXT: )
  (func $configured
  )

  ;; CHECK:      (@binaryen.js.called)
  ;; CHECK-NEXT: (func $already (type $0)
  ;; CHECK-NEXT: )
  (@binaryen.js.called)
  (func $already
  )

  ;; CHECK:      (func $unconfigured (type $0)
  ;; CHECK-NEXT: )
  (func $unconfigured
  )

  ;; CHECK:      (@binaryen.js.called)
  ;; CHECK-NEXT: (func $unconfigured-already (type $0)
  ;; CHECK-NEXT: )
  (@binaryen.js.called)
  (func $unconfigured-already
  )
)
