;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --memory-packing --all-features -S -o - | filecheck %s

;; Imported memory with passive segments should still be optimized. Zero ranges
;; in passive segments are handled with memory.fill, so they don't depend on
;; the zero-fill assumption that only holds for module-declared memory.
(module
 ;; CHECK:      (type $0 (func))

 ;; CHECK:      (import "env" "memory" (memory $0 1 1))
 (import "env" "memory" (memory $0 1 1))
 (data "hello\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00world")
 ;; CHECK:      (data $0 "hello")

 ;; CHECK:      (data $0.1 "world")

 ;; CHECK:      (func $0 (type $0)
 ;; CHECK-NEXT:  (memory.init $0
 ;; CHECK-NEXT:   (i32.const 0)
 ;; CHECK-NEXT:   (i32.const 0)
 ;; CHECK-NEXT:   (i32.const 5)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (memory.fill
 ;; CHECK-NEXT:   (i32.const 5)
 ;; CHECK-NEXT:   (i32.const 0)
 ;; CHECK-NEXT:   (i32.const 30)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (memory.init $0.1
 ;; CHECK-NEXT:   (i32.const 35)
 ;; CHECK-NEXT:   (i32.const 0)
 ;; CHECK-NEXT:   (i32.const 5)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $0
  (memory.init 0
   (i32.const 0)
   (i32.const 0)
   (i32.const 40)
  )
 )
 ;; CHECK:      (func $drop (type $0)
 ;; CHECK-NEXT:  (data.drop $0)
 ;; CHECK-NEXT:  (data.drop $0.1)
 ;; CHECK-NEXT: )
 (func $drop
  (data.drop 0)
 )
)

;; Imported memory with active segments: zero-only segments must be preserved
;; because we cannot assume the imported memory is zero-filled.
(module
 ;; CHECK:      (import "env" "memory" (memory $0 1 1))
 (import "env" "memory" (memory $0 1 1))
 (data (i32.const 1024) "hello")
 (data (i32.const 2048) "\00\00\00\00\00")
)

;; Imported memory with active segments: segments with embedded zeros must
;; not have their zero ranges elided.
;; CHECK:      (data $0 (i32.const 1024) "hello")

;; CHECK:      (data $1 (i32.const 2048) "\00\00\00\00\00")
(module
 ;; CHECK:      (import "env" "memory" (memory $0 1 1))
 (import "env" "memory" (memory $0 1 1))
 (data (i32.const 0) "abc\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00xyz")
)
;; CHECK:      (data $0 (i32.const 0) "abc")

;; CHECK:      (data $0.1 (i32.const 3) "\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00")

;; CHECK:      (data $0.2 (i32.const 20) "xyz")
