;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --memory64-lowering --enable-memory64 --enable-reference-types -S -o - | filecheck %s

;; Test that table.grow on a 64-bit table correctly handles the -1 failure
;; return value, matching the behavior of memory.grow lowering.
(module
  ;; CHECK:      (type $0 (func (result i64)))

  ;; CHECK:      (table $t64 0 funcref)
  (table $t64 i64 0 funcref)

  ;; CHECK:      (func $table-grow-minus-one (result i64)
  ;; CHECK-NEXT:  (local $0 i32)
  ;; CHECK-NEXT:  (if (result i64)
  ;; CHECK-NEXT:   (i32.eq
  ;; CHECK-NEXT:    (i32.const -1)
  ;; CHECK-NEXT:    (local.tee $0
  ;; CHECK-NEXT:     (table.grow $t64
  ;; CHECK-NEXT:      (ref.null nofunc)
  ;; CHECK-NEXT:      (i32.wrap_i64
  ;; CHECK-NEXT:       (i64.const 10)
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (then
  ;; CHECK-NEXT:    (i64.const -1)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (else
  ;; CHECK-NEXT:    (i64.extend_i32_u
  ;; CHECK-NEXT:     (local.get $0)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $table-grow-minus-one (result i64)
    ;; table.grow returns -1 on failure. The lowering must check for -1 and
    ;; return i64(-1) instead of i64.extend_i32_u(i32(-1)) which would be
    ;; 4294967295.
    (table.grow $t64 (ref.null func) (i64.const 10))
  )
)
