;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; Check that merge-similar-functions does not introduce functions with more
;; than 255 parameters. 255 is allowed, but 256 is not.

;; RUN: wasm-opt %s --merge-similar-functions -S -o - | filecheck %s

(module
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (type $1 (func (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32)))

  ;; CHECK:      (func $at-limit-1
  ;; CHECK-NEXT:  (call $byn$mgfn-shared$at-limit-1
  ;; CHECK-NEXT:   (i32.const 255)
  ;; CHECK-NEXT:   (i32.const 254)
  ;; CHECK-NEXT:   (i32.const 253)
  ;; CHECK-NEXT:   (i32.const 252)
  ;; CHECK-NEXT:   (i32.const 251)
  ;; CHECK-NEXT:   (i32.const 250)
  ;; CHECK-NEXT:   (i32.const 249)
  ;; CHECK-NEXT:   (i32.const 248)
  ;; CHECK-NEXT:   (i32.const 247)
  ;; CHECK-NEXT:   (i32.const 246)
  ;; CHECK-NEXT:   (i32.const 245)
  ;; CHECK-NEXT:   (i32.const 244)
  ;; CHECK-NEXT:   (i32.const 243)
  ;; CHECK-NEXT:   (i32.const 242)
  ;; CHECK-NEXT:   (i32.const 241)
  ;; CHECK-NEXT:   (i32.const 240)
  ;; CHECK-NEXT:   (i32.const 239)
  ;; CHECK-NEXT:   (i32.const 238)
  ;; CHECK-NEXT:   (i32.const 237)
  ;; CHECK-NEXT:   (i32.const 236)
  ;; CHECK-NEXT:   (i32.const 235)
  ;; CHECK-NEXT:   (i32.const 234)
  ;; CHECK-NEXT:   (i32.const 233)
  ;; CHECK-NEXT:   (i32.const 232)
  ;; CHECK-NEXT:   (i32.const 231)
  ;; CHECK-NEXT:   (i32.const 230)
  ;; CHECK-NEXT:   (i32.const 229)
  ;; CHECK-NEXT:   (i32.const 228)
  ;; CHECK-NEXT:   (i32.const 227)
  ;; CHECK-NEXT:   (i32.const 226)
  ;; CHECK-NEXT:   (i32.const 225)
  ;; CHECK-NEXT:   (i32.const 224)
  ;; CHECK-NEXT:   (i32.const 223)
  ;; CHECK-NEXT:   (i32.const 222)
  ;; CHECK-NEXT:   (i32.const 221)
  ;; CHECK-NEXT:   (i32.const 220)
  ;; CHECK-NEXT:   (i32.const 219)
  ;; CHECK-NEXT:   (i32.const 218)
  ;; CHECK-NEXT:   (i32.const 217)
  ;; CHECK-NEXT:   (i32.const 216)
  ;; CHECK-NEXT:   (i32.const 215)
  ;; CHECK-NEXT:   (i32.const 214)
  ;; CHECK-NEXT:   (i32.const 213)
  ;; CHECK-NEXT:   (i32.const 212)
  ;; CHECK-NEXT:   (i32.const 211)
  ;; CHECK-NEXT:   (i32.const 210)
  ;; CHECK-NEXT:   (i32.const 209)
  ;; CHECK-NEXT:   (i32.const 208)
  ;; CHECK-NEXT:   (i32.const 207)
  ;; CHECK-NEXT:   (i32.const 206)
  ;; CHECK-NEXT:   (i32.const 205)
  ;; CHECK-NEXT:   (i32.const 204)
  ;; CHECK-NEXT:   (i32.const 203)
  ;; CHECK-NEXT:   (i32.const 202)
  ;; CHECK-NEXT:   (i32.const 201)
  ;; CHECK-NEXT:   (i32.const 200)
  ;; CHECK-NEXT:   (i32.const 199)
  ;; CHECK-NEXT:   (i32.const 198)
  ;; CHECK-NEXT:   (i32.const 197)
  ;; CHECK-NEXT:   (i32.const 196)
  ;; CHECK-NEXT:   (i32.const 195)
  ;; CHECK-NEXT:   (i32.const 194)
  ;; CHECK-NEXT:   (i32.const 193)
  ;; CHECK-NEXT:   (i32.const 192)
  ;; CHECK-NEXT:   (i32.const 191)
  ;; CHECK-NEXT:   (i32.const 190)
  ;; CHECK-NEXT:   (i32.const 189)
  ;; CHECK-NEXT:   (i32.const 188)
  ;; CHECK-NEXT:   (i32.const 187)
  ;; CHECK-NEXT:   (i32.const 186)
  ;; CHECK-NEXT:   (i32.const 185)
  ;; CHECK-NEXT:   (i32.const 184)
  ;; CHECK-NEXT:   (i32.const 183)
  ;; CHECK-NEXT:   (i32.const 182)
  ;; CHECK-NEXT:   (i32.const 181)
  ;; CHECK-NEXT:   (i32.const 180)
  ;; CHECK-NEXT:   (i32.const 179)
  ;; CHECK-NEXT:   (i32.const 178)
  ;; CHECK-NEXT:   (i32.const 177)
  ;; CHECK-NEXT:   (i32.const 176)
  ;; CHECK-NEXT:   (i32.const 175)
  ;; CHECK-NEXT:   (i32.const 174)
  ;; CHECK-NEXT:   (i32.const 173)
  ;; CHECK-NEXT:   (i32.const 172)
  ;; CHECK-NEXT:   (i32.const 171)
  ;; CHECK-NEXT:   (i32.const 170)
  ;; CHECK-NEXT:   (i32.const 169)
  ;; CHECK-NEXT:   (i32.const 168)
  ;; CHECK-NEXT:   (i32.const 167)
  ;; CHECK-NEXT:   (i32.const 166)
  ;; CHECK-NEXT:   (i32.const 165)
  ;; CHECK-NEXT:   (i32.const 164)
  ;; CHECK-NEXT:   (i32.const 163)
  ;; CHECK-NEXT:   (i32.const 162)
  ;; CHECK-NEXT:   (i32.const 161)
  ;; CHECK-NEXT:   (i32.const 160)
  ;; CHECK-NEXT:   (i32.const 159)
  ;; CHECK-NEXT:   (i32.const 158)
  ;; CHECK-NEXT:   (i32.const 157)
  ;; CHECK-NEXT:   (i32.const 156)
  ;; CHECK-NEXT:   (i32.const 155)
  ;; CHECK-NEXT:   (i32.const 154)
  ;; CHECK-NEXT:   (i32.const 153)
  ;; CHECK-NEXT:   (i32.const 152)
  ;; CHECK-NEXT:   (i32.const 151)
  ;; CHECK-NEXT:   (i32.const 150)
  ;; CHECK-NEXT:   (i32.const 149)
  ;; CHECK-NEXT:   (i32.const 148)
  ;; CHECK-NEXT:   (i32.const 147)
  ;; CHECK-NEXT:   (i32.const 146)
  ;; CHECK-NEXT:   (i32.const 145)
  ;; CHECK-NEXT:   (i32.const 144)
  ;; CHECK-NEXT:   (i32.const 143)
  ;; CHECK-NEXT:   (i32.const 142)
  ;; CHECK-NEXT:   (i32.const 141)
  ;; CHECK-NEXT:   (i32.const 140)
  ;; CHECK-NEXT:   (i32.const 139)
  ;; CHECK-NEXT:   (i32.const 138)
  ;; CHECK-NEXT:   (i32.const 137)
  ;; CHECK-NEXT:   (i32.const 136)
  ;; CHECK-NEXT:   (i32.const 135)
  ;; CHECK-NEXT:   (i32.const 134)
  ;; CHECK-NEXT:   (i32.const 133)
  ;; CHECK-NEXT:   (i32.const 132)
  ;; CHECK-NEXT:   (i32.const 131)
  ;; CHECK-NEXT:   (i32.const 130)
  ;; CHECK-NEXT:   (i32.const 129)
  ;; CHECK-NEXT:   (i32.const 128)
  ;; CHECK-NEXT:   (i32.const 127)
  ;; CHECK-NEXT:   (i32.const 126)
  ;; CHECK-NEXT:   (i32.const 125)
  ;; CHECK-NEXT:   (i32.const 124)
  ;; CHECK-NEXT:   (i32.const 123)
  ;; CHECK-NEXT:   (i32.const 122)
  ;; CHECK-NEXT:   (i32.const 121)
  ;; CHECK-NEXT:   (i32.const 120)
  ;; CHECK-NEXT:   (i32.const 119)
  ;; CHECK-NEXT:   (i32.const 118)
  ;; CHECK-NEXT:   (i32.const 117)
  ;; CHECK-NEXT:   (i32.const 116)
  ;; CHECK-NEXT:   (i32.const 115)
  ;; CHECK-NEXT:   (i32.const 114)
  ;; CHECK-NEXT:   (i32.const 113)
  ;; CHECK-NEXT:   (i32.const 112)
  ;; CHECK-NEXT:   (i32.const 111)
  ;; CHECK-NEXT:   (i32.const 110)
  ;; CHECK-NEXT:   (i32.const 109)
  ;; CHECK-NEXT:   (i32.const 108)
  ;; CHECK-NEXT:   (i32.const 107)
  ;; CHECK-NEXT:   (i32.const 106)
  ;; CHECK-NEXT:   (i32.const 105)
  ;; CHECK-NEXT:   (i32.const 104)
  ;; CHECK-NEXT:   (i32.const 103)
  ;; CHECK-NEXT:   (i32.const 102)
  ;; CHECK-NEXT:   (i32.const 101)
  ;; CHECK-NEXT:   (i32.const 100)
  ;; CHECK-NEXT:   (i32.const 99)
  ;; CHECK-NEXT:   (i32.const 98)
  ;; CHECK-NEXT:   (i32.const 97)
  ;; CHECK-NEXT:   (i32.const 96)
  ;; CHECK-NEXT:   (i32.const 95)
  ;; CHECK-NEXT:   (i32.const 94)
  ;; CHECK-NEXT:   (i32.const 93)
  ;; CHECK-NEXT:   (i32.const 92)
  ;; CHECK-NEXT:   (i32.const 91)
  ;; CHECK-NEXT:   (i32.const 90)
  ;; CHECK-NEXT:   (i32.const 89)
  ;; CHECK-NEXT:   (i32.const 88)
  ;; CHECK-NEXT:   (i32.const 87)
  ;; CHECK-NEXT:   (i32.const 86)
  ;; CHECK-NEXT:   (i32.const 85)
  ;; CHECK-NEXT:   (i32.const 84)
  ;; CHECK-NEXT:   (i32.const 83)
  ;; CHECK-NEXT:   (i32.const 82)
  ;; CHECK-NEXT:   (i32.const 81)
  ;; CHECK-NEXT:   (i32.const 80)
  ;; CHECK-NEXT:   (i32.const 79)
  ;; CHECK-NEXT:   (i32.const 78)
  ;; CHECK-NEXT:   (i32.const 77)
  ;; CHECK-NEXT:   (i32.const 76)
  ;; CHECK-NEXT:   (i32.const 75)
  ;; CHECK-NEXT:   (i32.const 74)
  ;; CHECK-NEXT:   (i32.const 73)
  ;; CHECK-NEXT:   (i32.const 72)
  ;; CHECK-NEXT:   (i32.const 71)
  ;; CHECK-NEXT:   (i32.const 70)
  ;; CHECK-NEXT:   (i32.const 69)
  ;; CHECK-NEXT:   (i32.const 68)
  ;; CHECK-NEXT:   (i32.const 67)
  ;; CHECK-NEXT:   (i32.const 66)
  ;; CHECK-NEXT:   (i32.const 65)
  ;; CHECK-NEXT:   (i32.const 64)
  ;; CHECK-NEXT:   (i32.const 63)
  ;; CHECK-NEXT:   (i32.const 62)
  ;; CHECK-NEXT:   (i32.const 61)
  ;; CHECK-NEXT:   (i32.const 60)
  ;; CHECK-NEXT:   (i32.const 59)
  ;; CHECK-NEXT:   (i32.const 58)
  ;; CHECK-NEXT:   (i32.const 57)
  ;; CHECK-NEXT:   (i32.const 56)
  ;; CHECK-NEXT:   (i32.const 55)
  ;; CHECK-NEXT:   (i32.const 54)
  ;; CHECK-NEXT:   (i32.const 53)
  ;; CHECK-NEXT:   (i32.const 52)
  ;; CHECK-NEXT:   (i32.const 51)
  ;; CHECK-NEXT:   (i32.const 50)
  ;; CHECK-NEXT:   (i32.const 49)
  ;; CHECK-NEXT:   (i32.const 48)
  ;; CHECK-NEXT:   (i32.const 47)
  ;; CHECK-NEXT:   (i32.const 46)
  ;; CHECK-NEXT:   (i32.const 45)
  ;; CHECK-NEXT:   (i32.const 44)
  ;; CHECK-NEXT:   (i32.const 43)
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:   (i32.const 41)
  ;; CHECK-NEXT:   (i32.const 40)
  ;; CHECK-NEXT:   (i32.const 39)
  ;; CHECK-NEXT:   (i32.const 38)
  ;; CHECK-NEXT:   (i32.const 37)
  ;; CHECK-NEXT:   (i32.const 36)
  ;; CHECK-NEXT:   (i32.const 35)
  ;; CHECK-NEXT:   (i32.const 34)
  ;; CHECK-NEXT:   (i32.const 33)
  ;; CHECK-NEXT:   (i32.const 32)
  ;; CHECK-NEXT:   (i32.const 31)
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:   (i32.const 29)
  ;; CHECK-NEXT:   (i32.const 28)
  ;; CHECK-NEXT:   (i32.const 27)
  ;; CHECK-NEXT:   (i32.const 26)
  ;; CHECK-NEXT:   (i32.const 25)
  ;; CHECK-NEXT:   (i32.const 24)
  ;; CHECK-NEXT:   (i32.const 23)
  ;; CHECK-NEXT:   (i32.const 22)
  ;; CHECK-NEXT:   (i32.const 21)
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:   (i32.const 19)
  ;; CHECK-NEXT:   (i32.const 18)
  ;; CHECK-NEXT:   (i32.const 17)
  ;; CHECK-NEXT:   (i32.const 16)
  ;; CHECK-NEXT:   (i32.const 15)
  ;; CHECK-NEXT:   (i32.const 14)
  ;; CHECK-NEXT:   (i32.const 13)
  ;; CHECK-NEXT:   (i32.const 12)
  ;; CHECK-NEXT:   (i32.const 11)
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:   (i32.const 9)
  ;; CHECK-NEXT:   (i32.const 8)
  ;; CHECK-NEXT:   (i32.const 7)
  ;; CHECK-NEXT:   (i32.const 6)
  ;; CHECK-NEXT:   (i32.const 5)
  ;; CHECK-NEXT:   (i32.const 4)
  ;; CHECK-NEXT:   (i32.const 3)
  ;; CHECK-NEXT:   (i32.const 2)
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $at-limit-1
    (drop
      (i32.const 1)
    )
    (drop
      (i32.const 2)
    )
    (drop
      (i32.const 3)
    )
    (drop
      (i32.const 4)
    )
    (drop
      (i32.const 5)
    )
    (drop
      (i32.const 6)
    )
    (drop
      (i32.const 7)
    )
    (drop
      (i32.const 8)
    )
    (drop
      (i32.const 9)
    )
    (drop
      (i32.const 10)
    )
    (drop
      (i32.const 11)
    )
    (drop
      (i32.const 12)
    )
    (drop
      (i32.const 13)
    )
    (drop
      (i32.const 14)
    )
    (drop
      (i32.const 15)
    )
    (drop
      (i32.const 16)
    )
    (drop
      (i32.const 17)
    )
    (drop
      (i32.const 18)
    )
    (drop
      (i32.const 19)
    )
    (drop
      (i32.const 20)
    )
    (drop
      (i32.const 21)
    )
    (drop
      (i32.const 22)
    )
    (drop
      (i32.const 23)
    )
    (drop
      (i32.const 24)
    )
    (drop
      (i32.const 25)
    )
    (drop
      (i32.const 26)
    )
    (drop
      (i32.const 27)
    )
    (drop
      (i32.const 28)
    )
    (drop
      (i32.const 29)
    )
    (drop
      (i32.const 30)
    )
    (drop
      (i32.const 31)
    )
    (drop
      (i32.const 32)
    )
    (drop
      (i32.const 33)
    )
    (drop
      (i32.const 34)
    )
    (drop
      (i32.const 35)
    )
    (drop
      (i32.const 36)
    )
    (drop
      (i32.const 37)
    )
    (drop
      (i32.const 38)
    )
    (drop
      (i32.const 39)
    )
    (drop
      (i32.const 40)
    )
    (drop
      (i32.const 41)
    )
    (drop
      (i32.const 42)
    )
    (drop
      (i32.const 43)
    )
    (drop
      (i32.const 44)
    )
    (drop
      (i32.const 45)
    )
    (drop
      (i32.const 46)
    )
    (drop
      (i32.const 47)
    )
    (drop
      (i32.const 48)
    )
    (drop
      (i32.const 49)
    )
    (drop
      (i32.const 50)
    )
    (drop
      (i32.const 51)
    )
    (drop
      (i32.const 52)
    )
    (drop
      (i32.const 53)
    )
    (drop
      (i32.const 54)
    )
    (drop
      (i32.const 55)
    )
    (drop
      (i32.const 56)
    )
    (drop
      (i32.const 57)
    )
    (drop
      (i32.const 58)
    )
    (drop
      (i32.const 59)
    )
    (drop
      (i32.const 60)
    )
    (drop
      (i32.const 61)
    )
    (drop
      (i32.const 62)
    )
    (drop
      (i32.const 63)
    )
    (drop
      (i32.const 64)
    )
    (drop
      (i32.const 65)
    )
    (drop
      (i32.const 66)
    )
    (drop
      (i32.const 67)
    )
    (drop
      (i32.const 68)
    )
    (drop
      (i32.const 69)
    )
    (drop
      (i32.const 70)
    )
    (drop
      (i32.const 71)
    )
    (drop
      (i32.const 72)
    )
    (drop
      (i32.const 73)
    )
    (drop
      (i32.const 74)
    )
    (drop
      (i32.const 75)
    )
    (drop
      (i32.const 76)
    )
    (drop
      (i32.const 77)
    )
    (drop
      (i32.const 78)
    )
    (drop
      (i32.const 79)
    )
    (drop
      (i32.const 80)
    )
    (drop
      (i32.const 81)
    )
    (drop
      (i32.const 82)
    )
    (drop
      (i32.const 83)
    )
    (drop
      (i32.const 84)
    )
    (drop
      (i32.const 85)
    )
    (drop
      (i32.const 86)
    )
    (drop
      (i32.const 87)
    )
    (drop
      (i32.const 88)
    )
    (drop
      (i32.const 89)
    )
    (drop
      (i32.const 90)
    )
    (drop
      (i32.const 91)
    )
    (drop
      (i32.const 92)
    )
    (drop
      (i32.const 93)
    )
    (drop
      (i32.const 94)
    )
    (drop
      (i32.const 95)
    )
    (drop
      (i32.const 96)
    )
    (drop
      (i32.const 97)
    )
    (drop
      (i32.const 98)
    )
    (drop
      (i32.const 99)
    )
    (drop
      (i32.const 100)
    )
    (drop
      (i32.const 101)
    )
    (drop
      (i32.const 102)
    )
    (drop
      (i32.const 103)
    )
    (drop
      (i32.const 104)
    )
    (drop
      (i32.const 105)
    )
    (drop
      (i32.const 106)
    )
    (drop
      (i32.const 107)
    )
    (drop
      (i32.const 108)
    )
    (drop
      (i32.const 109)
    )
    (drop
      (i32.const 110)
    )
    (drop
      (i32.const 111)
    )
    (drop
      (i32.const 112)
    )
    (drop
      (i32.const 113)
    )
    (drop
      (i32.const 114)
    )
    (drop
      (i32.const 115)
    )
    (drop
      (i32.const 116)
    )
    (drop
      (i32.const 117)
    )
    (drop
      (i32.const 118)
    )
    (drop
      (i32.const 119)
    )
    (drop
      (i32.const 120)
    )
    (drop
      (i32.const 121)
    )
    (drop
      (i32.const 122)
    )
    (drop
      (i32.const 123)
    )
    (drop
      (i32.const 124)
    )
    (drop
      (i32.const 125)
    )
    (drop
      (i32.const 126)
    )
    (drop
      (i32.const 127)
    )
    (drop
      (i32.const 128)
    )
    (drop
      (i32.const 129)
    )
    (drop
      (i32.const 130)
    )
    (drop
      (i32.const 131)
    )
    (drop
      (i32.const 132)
    )
    (drop
      (i32.const 133)
    )
    (drop
      (i32.const 134)
    )
    (drop
      (i32.const 135)
    )
    (drop
      (i32.const 136)
    )
    (drop
      (i32.const 137)
    )
    (drop
      (i32.const 138)
    )
    (drop
      (i32.const 139)
    )
    (drop
      (i32.const 140)
    )
    (drop
      (i32.const 141)
    )
    (drop
      (i32.const 142)
    )
    (drop
      (i32.const 143)
    )
    (drop
      (i32.const 144)
    )
    (drop
      (i32.const 145)
    )
    (drop
      (i32.const 146)
    )
    (drop
      (i32.const 147)
    )
    (drop
      (i32.const 148)
    )
    (drop
      (i32.const 149)
    )
    (drop
      (i32.const 150)
    )
    (drop
      (i32.const 151)
    )
    (drop
      (i32.const 152)
    )
    (drop
      (i32.const 153)
    )
    (drop
      (i32.const 154)
    )
    (drop
      (i32.const 155)
    )
    (drop
      (i32.const 156)
    )
    (drop
      (i32.const 157)
    )
    (drop
      (i32.const 158)
    )
    (drop
      (i32.const 159)
    )
    (drop
      (i32.const 160)
    )
    (drop
      (i32.const 161)
    )
    (drop
      (i32.const 162)
    )
    (drop
      (i32.const 163)
    )
    (drop
      (i32.const 164)
    )
    (drop
      (i32.const 165)
    )
    (drop
      (i32.const 166)
    )
    (drop
      (i32.const 167)
    )
    (drop
      (i32.const 168)
    )
    (drop
      (i32.const 169)
    )
    (drop
      (i32.const 170)
    )
    (drop
      (i32.const 171)
    )
    (drop
      (i32.const 172)
    )
    (drop
      (i32.const 173)
    )
    (drop
      (i32.const 174)
    )
    (drop
      (i32.const 175)
    )
    (drop
      (i32.const 176)
    )
    (drop
      (i32.const 177)
    )
    (drop
      (i32.const 178)
    )
    (drop
      (i32.const 179)
    )
    (drop
      (i32.const 180)
    )
    (drop
      (i32.const 181)
    )
    (drop
      (i32.const 182)
    )
    (drop
      (i32.const 183)
    )
    (drop
      (i32.const 184)
    )
    (drop
      (i32.const 185)
    )
    (drop
      (i32.const 186)
    )
    (drop
      (i32.const 187)
    )
    (drop
      (i32.const 188)
    )
    (drop
      (i32.const 189)
    )
    (drop
      (i32.const 190)
    )
    (drop
      (i32.const 191)
    )
    (drop
      (i32.const 192)
    )
    (drop
      (i32.const 193)
    )
    (drop
      (i32.const 194)
    )
    (drop
      (i32.const 195)
    )
    (drop
      (i32.const 196)
    )
    (drop
      (i32.const 197)
    )
    (drop
      (i32.const 198)
    )
    (drop
      (i32.const 199)
    )
    (drop
      (i32.const 200)
    )
    (drop
      (i32.const 201)
    )
    (drop
      (i32.const 202)
    )
    (drop
      (i32.const 203)
    )
    (drop
      (i32.const 204)
    )
    (drop
      (i32.const 205)
    )
    (drop
      (i32.const 206)
    )
    (drop
      (i32.const 207)
    )
    (drop
      (i32.const 208)
    )
    (drop
      (i32.const 209)
    )
    (drop
      (i32.const 210)
    )
    (drop
      (i32.const 211)
    )
    (drop
      (i32.const 212)
    )
    (drop
      (i32.const 213)
    )
    (drop
      (i32.const 214)
    )
    (drop
      (i32.const 215)
    )
    (drop
      (i32.const 216)
    )
    (drop
      (i32.const 217)
    )
    (drop
      (i32.const 218)
    )
    (drop
      (i32.const 219)
    )
    (drop
      (i32.const 220)
    )
    (drop
      (i32.const 221)
    )
    (drop
      (i32.const 222)
    )
    (drop
      (i32.const 223)
    )
    (drop
      (i32.const 224)
    )
    (drop
      (i32.const 225)
    )
    (drop
      (i32.const 226)
    )
    (drop
      (i32.const 227)
    )
    (drop
      (i32.const 228)
    )
    (drop
      (i32.const 229)
    )
    (drop
      (i32.const 230)
    )
    (drop
      (i32.const 231)
    )
    (drop
      (i32.const 232)
    )
    (drop
      (i32.const 233)
    )
    (drop
      (i32.const 234)
    )
    (drop
      (i32.const 235)
    )
    (drop
      (i32.const 236)
    )
    (drop
      (i32.const 237)
    )
    (drop
      (i32.const 238)
    )
    (drop
      (i32.const 239)
    )
    (drop
      (i32.const 240)
    )
    (drop
      (i32.const 241)
    )
    (drop
      (i32.const 242)
    )
    (drop
      (i32.const 243)
    )
    (drop
      (i32.const 244)
    )
    (drop
      (i32.const 245)
    )
    (drop
      (i32.const 246)
    )
    (drop
      (i32.const 247)
    )
    (drop
      (i32.const 248)
    )
    (drop
      (i32.const 249)
    )
    (drop
      (i32.const 250)
    )
    (drop
      (i32.const 251)
    )
    (drop
      (i32.const 252)
    )
    (drop
      (i32.const 253)
    )
    (drop
      (i32.const 254)
    )
    (drop
      (i32.const 255)
    )
    ;; Add nops to increase the benefit of merging
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
  )

  ;; CHECK:      (func $at-limit-2
  ;; CHECK-NEXT:  (call $byn$mgfn-shared$at-limit-1
  ;; CHECK-NEXT:   (i32.const -255)
  ;; CHECK-NEXT:   (i32.const -254)
  ;; CHECK-NEXT:   (i32.const -253)
  ;; CHECK-NEXT:   (i32.const -252)
  ;; CHECK-NEXT:   (i32.const -251)
  ;; CHECK-NEXT:   (i32.const -250)
  ;; CHECK-NEXT:   (i32.const -249)
  ;; CHECK-NEXT:   (i32.const -248)
  ;; CHECK-NEXT:   (i32.const -247)
  ;; CHECK-NEXT:   (i32.const -246)
  ;; CHECK-NEXT:   (i32.const -245)
  ;; CHECK-NEXT:   (i32.const -244)
  ;; CHECK-NEXT:   (i32.const -243)
  ;; CHECK-NEXT:   (i32.const -242)
  ;; CHECK-NEXT:   (i32.const -241)
  ;; CHECK-NEXT:   (i32.const -240)
  ;; CHECK-NEXT:   (i32.const -239)
  ;; CHECK-NEXT:   (i32.const -238)
  ;; CHECK-NEXT:   (i32.const -237)
  ;; CHECK-NEXT:   (i32.const -236)
  ;; CHECK-NEXT:   (i32.const -235)
  ;; CHECK-NEXT:   (i32.const -234)
  ;; CHECK-NEXT:   (i32.const -233)
  ;; CHECK-NEXT:   (i32.const -232)
  ;; CHECK-NEXT:   (i32.const -231)
  ;; CHECK-NEXT:   (i32.const -230)
  ;; CHECK-NEXT:   (i32.const -229)
  ;; CHECK-NEXT:   (i32.const -228)
  ;; CHECK-NEXT:   (i32.const -227)
  ;; CHECK-NEXT:   (i32.const -226)
  ;; CHECK-NEXT:   (i32.const -225)
  ;; CHECK-NEXT:   (i32.const -224)
  ;; CHECK-NEXT:   (i32.const -223)
  ;; CHECK-NEXT:   (i32.const -222)
  ;; CHECK-NEXT:   (i32.const -221)
  ;; CHECK-NEXT:   (i32.const -220)
  ;; CHECK-NEXT:   (i32.const -219)
  ;; CHECK-NEXT:   (i32.const -218)
  ;; CHECK-NEXT:   (i32.const -217)
  ;; CHECK-NEXT:   (i32.const -216)
  ;; CHECK-NEXT:   (i32.const -215)
  ;; CHECK-NEXT:   (i32.const -214)
  ;; CHECK-NEXT:   (i32.const -213)
  ;; CHECK-NEXT:   (i32.const -212)
  ;; CHECK-NEXT:   (i32.const -211)
  ;; CHECK-NEXT:   (i32.const -210)
  ;; CHECK-NEXT:   (i32.const -209)
  ;; CHECK-NEXT:   (i32.const -208)
  ;; CHECK-NEXT:   (i32.const -207)
  ;; CHECK-NEXT:   (i32.const -206)
  ;; CHECK-NEXT:   (i32.const -205)
  ;; CHECK-NEXT:   (i32.const -204)
  ;; CHECK-NEXT:   (i32.const -203)
  ;; CHECK-NEXT:   (i32.const -202)
  ;; CHECK-NEXT:   (i32.const -201)
  ;; CHECK-NEXT:   (i32.const -200)
  ;; CHECK-NEXT:   (i32.const -199)
  ;; CHECK-NEXT:   (i32.const -198)
  ;; CHECK-NEXT:   (i32.const -197)
  ;; CHECK-NEXT:   (i32.const -196)
  ;; CHECK-NEXT:   (i32.const -195)
  ;; CHECK-NEXT:   (i32.const -194)
  ;; CHECK-NEXT:   (i32.const -193)
  ;; CHECK-NEXT:   (i32.const -192)
  ;; CHECK-NEXT:   (i32.const -191)
  ;; CHECK-NEXT:   (i32.const -190)
  ;; CHECK-NEXT:   (i32.const -189)
  ;; CHECK-NEXT:   (i32.const -188)
  ;; CHECK-NEXT:   (i32.const -187)
  ;; CHECK-NEXT:   (i32.const -186)
  ;; CHECK-NEXT:   (i32.const -185)
  ;; CHECK-NEXT:   (i32.const -184)
  ;; CHECK-NEXT:   (i32.const -183)
  ;; CHECK-NEXT:   (i32.const -182)
  ;; CHECK-NEXT:   (i32.const -181)
  ;; CHECK-NEXT:   (i32.const -180)
  ;; CHECK-NEXT:   (i32.const -179)
  ;; CHECK-NEXT:   (i32.const -178)
  ;; CHECK-NEXT:   (i32.const -177)
  ;; CHECK-NEXT:   (i32.const -176)
  ;; CHECK-NEXT:   (i32.const -175)
  ;; CHECK-NEXT:   (i32.const -174)
  ;; CHECK-NEXT:   (i32.const -173)
  ;; CHECK-NEXT:   (i32.const -172)
  ;; CHECK-NEXT:   (i32.const -171)
  ;; CHECK-NEXT:   (i32.const -170)
  ;; CHECK-NEXT:   (i32.const -169)
  ;; CHECK-NEXT:   (i32.const -168)
  ;; CHECK-NEXT:   (i32.const -167)
  ;; CHECK-NEXT:   (i32.const -166)
  ;; CHECK-NEXT:   (i32.const -165)
  ;; CHECK-NEXT:   (i32.const -164)
  ;; CHECK-NEXT:   (i32.const -163)
  ;; CHECK-NEXT:   (i32.const -162)
  ;; CHECK-NEXT:   (i32.const -161)
  ;; CHECK-NEXT:   (i32.const -160)
  ;; CHECK-NEXT:   (i32.const -159)
  ;; CHECK-NEXT:   (i32.const -158)
  ;; CHECK-NEXT:   (i32.const -157)
  ;; CHECK-NEXT:   (i32.const -156)
  ;; CHECK-NEXT:   (i32.const -155)
  ;; CHECK-NEXT:   (i32.const -154)
  ;; CHECK-NEXT:   (i32.const -153)
  ;; CHECK-NEXT:   (i32.const -152)
  ;; CHECK-NEXT:   (i32.const -151)
  ;; CHECK-NEXT:   (i32.const -150)
  ;; CHECK-NEXT:   (i32.const -149)
  ;; CHECK-NEXT:   (i32.const -148)
  ;; CHECK-NEXT:   (i32.const -147)
  ;; CHECK-NEXT:   (i32.const -146)
  ;; CHECK-NEXT:   (i32.const -145)
  ;; CHECK-NEXT:   (i32.const -144)
  ;; CHECK-NEXT:   (i32.const -143)
  ;; CHECK-NEXT:   (i32.const -142)
  ;; CHECK-NEXT:   (i32.const -141)
  ;; CHECK-NEXT:   (i32.const -140)
  ;; CHECK-NEXT:   (i32.const -139)
  ;; CHECK-NEXT:   (i32.const -138)
  ;; CHECK-NEXT:   (i32.const -137)
  ;; CHECK-NEXT:   (i32.const -136)
  ;; CHECK-NEXT:   (i32.const -135)
  ;; CHECK-NEXT:   (i32.const -134)
  ;; CHECK-NEXT:   (i32.const -133)
  ;; CHECK-NEXT:   (i32.const -132)
  ;; CHECK-NEXT:   (i32.const -131)
  ;; CHECK-NEXT:   (i32.const -130)
  ;; CHECK-NEXT:   (i32.const -129)
  ;; CHECK-NEXT:   (i32.const -128)
  ;; CHECK-NEXT:   (i32.const -127)
  ;; CHECK-NEXT:   (i32.const -126)
  ;; CHECK-NEXT:   (i32.const -125)
  ;; CHECK-NEXT:   (i32.const -124)
  ;; CHECK-NEXT:   (i32.const -123)
  ;; CHECK-NEXT:   (i32.const -122)
  ;; CHECK-NEXT:   (i32.const -121)
  ;; CHECK-NEXT:   (i32.const -120)
  ;; CHECK-NEXT:   (i32.const -119)
  ;; CHECK-NEXT:   (i32.const -118)
  ;; CHECK-NEXT:   (i32.const -117)
  ;; CHECK-NEXT:   (i32.const -116)
  ;; CHECK-NEXT:   (i32.const -115)
  ;; CHECK-NEXT:   (i32.const -114)
  ;; CHECK-NEXT:   (i32.const -113)
  ;; CHECK-NEXT:   (i32.const -112)
  ;; CHECK-NEXT:   (i32.const -111)
  ;; CHECK-NEXT:   (i32.const -110)
  ;; CHECK-NEXT:   (i32.const -109)
  ;; CHECK-NEXT:   (i32.const -108)
  ;; CHECK-NEXT:   (i32.const -107)
  ;; CHECK-NEXT:   (i32.const -106)
  ;; CHECK-NEXT:   (i32.const -105)
  ;; CHECK-NEXT:   (i32.const -104)
  ;; CHECK-NEXT:   (i32.const -103)
  ;; CHECK-NEXT:   (i32.const -102)
  ;; CHECK-NEXT:   (i32.const -101)
  ;; CHECK-NEXT:   (i32.const -100)
  ;; CHECK-NEXT:   (i32.const -99)
  ;; CHECK-NEXT:   (i32.const -98)
  ;; CHECK-NEXT:   (i32.const -97)
  ;; CHECK-NEXT:   (i32.const -96)
  ;; CHECK-NEXT:   (i32.const -95)
  ;; CHECK-NEXT:   (i32.const -94)
  ;; CHECK-NEXT:   (i32.const -93)
  ;; CHECK-NEXT:   (i32.const -92)
  ;; CHECK-NEXT:   (i32.const -91)
  ;; CHECK-NEXT:   (i32.const -90)
  ;; CHECK-NEXT:   (i32.const -89)
  ;; CHECK-NEXT:   (i32.const -88)
  ;; CHECK-NEXT:   (i32.const -87)
  ;; CHECK-NEXT:   (i32.const -86)
  ;; CHECK-NEXT:   (i32.const -85)
  ;; CHECK-NEXT:   (i32.const -84)
  ;; CHECK-NEXT:   (i32.const -83)
  ;; CHECK-NEXT:   (i32.const -82)
  ;; CHECK-NEXT:   (i32.const -81)
  ;; CHECK-NEXT:   (i32.const -80)
  ;; CHECK-NEXT:   (i32.const -79)
  ;; CHECK-NEXT:   (i32.const -78)
  ;; CHECK-NEXT:   (i32.const -77)
  ;; CHECK-NEXT:   (i32.const -76)
  ;; CHECK-NEXT:   (i32.const -75)
  ;; CHECK-NEXT:   (i32.const -74)
  ;; CHECK-NEXT:   (i32.const -73)
  ;; CHECK-NEXT:   (i32.const -72)
  ;; CHECK-NEXT:   (i32.const -71)
  ;; CHECK-NEXT:   (i32.const -70)
  ;; CHECK-NEXT:   (i32.const -69)
  ;; CHECK-NEXT:   (i32.const -68)
  ;; CHECK-NEXT:   (i32.const -67)
  ;; CHECK-NEXT:   (i32.const -66)
  ;; CHECK-NEXT:   (i32.const -65)
  ;; CHECK-NEXT:   (i32.const -64)
  ;; CHECK-NEXT:   (i32.const -63)
  ;; CHECK-NEXT:   (i32.const -62)
  ;; CHECK-NEXT:   (i32.const -61)
  ;; CHECK-NEXT:   (i32.const -60)
  ;; CHECK-NEXT:   (i32.const -59)
  ;; CHECK-NEXT:   (i32.const -58)
  ;; CHECK-NEXT:   (i32.const -57)
  ;; CHECK-NEXT:   (i32.const -56)
  ;; CHECK-NEXT:   (i32.const -55)
  ;; CHECK-NEXT:   (i32.const -54)
  ;; CHECK-NEXT:   (i32.const -53)
  ;; CHECK-NEXT:   (i32.const -52)
  ;; CHECK-NEXT:   (i32.const -51)
  ;; CHECK-NEXT:   (i32.const -50)
  ;; CHECK-NEXT:   (i32.const -49)
  ;; CHECK-NEXT:   (i32.const -48)
  ;; CHECK-NEXT:   (i32.const -47)
  ;; CHECK-NEXT:   (i32.const -46)
  ;; CHECK-NEXT:   (i32.const -45)
  ;; CHECK-NEXT:   (i32.const -44)
  ;; CHECK-NEXT:   (i32.const -43)
  ;; CHECK-NEXT:   (i32.const -42)
  ;; CHECK-NEXT:   (i32.const -41)
  ;; CHECK-NEXT:   (i32.const -40)
  ;; CHECK-NEXT:   (i32.const -39)
  ;; CHECK-NEXT:   (i32.const -38)
  ;; CHECK-NEXT:   (i32.const -37)
  ;; CHECK-NEXT:   (i32.const -36)
  ;; CHECK-NEXT:   (i32.const -35)
  ;; CHECK-NEXT:   (i32.const -34)
  ;; CHECK-NEXT:   (i32.const -33)
  ;; CHECK-NEXT:   (i32.const -32)
  ;; CHECK-NEXT:   (i32.const -31)
  ;; CHECK-NEXT:   (i32.const -30)
  ;; CHECK-NEXT:   (i32.const -29)
  ;; CHECK-NEXT:   (i32.const -28)
  ;; CHECK-NEXT:   (i32.const -27)
  ;; CHECK-NEXT:   (i32.const -26)
  ;; CHECK-NEXT:   (i32.const -25)
  ;; CHECK-NEXT:   (i32.const -24)
  ;; CHECK-NEXT:   (i32.const -23)
  ;; CHECK-NEXT:   (i32.const -22)
  ;; CHECK-NEXT:   (i32.const -21)
  ;; CHECK-NEXT:   (i32.const -20)
  ;; CHECK-NEXT:   (i32.const -19)
  ;; CHECK-NEXT:   (i32.const -18)
  ;; CHECK-NEXT:   (i32.const -17)
  ;; CHECK-NEXT:   (i32.const -16)
  ;; CHECK-NEXT:   (i32.const -15)
  ;; CHECK-NEXT:   (i32.const -14)
  ;; CHECK-NEXT:   (i32.const -13)
  ;; CHECK-NEXT:   (i32.const -12)
  ;; CHECK-NEXT:   (i32.const -11)
  ;; CHECK-NEXT:   (i32.const -10)
  ;; CHECK-NEXT:   (i32.const -9)
  ;; CHECK-NEXT:   (i32.const -8)
  ;; CHECK-NEXT:   (i32.const -7)
  ;; CHECK-NEXT:   (i32.const -6)
  ;; CHECK-NEXT:   (i32.const -5)
  ;; CHECK-NEXT:   (i32.const -4)
  ;; CHECK-NEXT:   (i32.const -3)
  ;; CHECK-NEXT:   (i32.const -2)
  ;; CHECK-NEXT:   (i32.const -1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $at-limit-2
    (drop
      (i32.const -1)
    )
    (drop
      (i32.const -2)
    )
    (drop
      (i32.const -3)
    )
    (drop
      (i32.const -4)
    )
    (drop
      (i32.const -5)
    )
    (drop
      (i32.const -6)
    )
    (drop
      (i32.const -7)
    )
    (drop
      (i32.const -8)
    )
    (drop
      (i32.const -9)
    )
    (drop
      (i32.const -10)
    )
    (drop
      (i32.const -11)
    )
    (drop
      (i32.const -12)
    )
    (drop
      (i32.const -13)
    )
    (drop
      (i32.const -14)
    )
    (drop
      (i32.const -15)
    )
    (drop
      (i32.const -16)
    )
    (drop
      (i32.const -17)
    )
    (drop
      (i32.const -18)
    )
    (drop
      (i32.const -19)
    )
    (drop
      (i32.const -20)
    )
    (drop
      (i32.const -21)
    )
    (drop
      (i32.const -22)
    )
    (drop
      (i32.const -23)
    )
    (drop
      (i32.const -24)
    )
    (drop
      (i32.const -25)
    )
    (drop
      (i32.const -26)
    )
    (drop
      (i32.const -27)
    )
    (drop
      (i32.const -28)
    )
    (drop
      (i32.const -29)
    )
    (drop
      (i32.const -30)
    )
    (drop
      (i32.const -31)
    )
    (drop
      (i32.const -32)
    )
    (drop
      (i32.const -33)
    )
    (drop
      (i32.const -34)
    )
    (drop
      (i32.const -35)
    )
    (drop
      (i32.const -36)
    )
    (drop
      (i32.const -37)
    )
    (drop
      (i32.const -38)
    )
    (drop
      (i32.const -39)
    )
    (drop
      (i32.const -40)
    )
    (drop
      (i32.const -41)
    )
    (drop
      (i32.const -42)
    )
    (drop
      (i32.const -43)
    )
    (drop
      (i32.const -44)
    )
    (drop
      (i32.const -45)
    )
    (drop
      (i32.const -46)
    )
    (drop
      (i32.const -47)
    )
    (drop
      (i32.const -48)
    )
    (drop
      (i32.const -49)
    )
    (drop
      (i32.const -50)
    )
    (drop
      (i32.const -51)
    )
    (drop
      (i32.const -52)
    )
    (drop
      (i32.const -53)
    )
    (drop
      (i32.const -54)
    )
    (drop
      (i32.const -55)
    )
    (drop
      (i32.const -56)
    )
    (drop
      (i32.const -57)
    )
    (drop
      (i32.const -58)
    )
    (drop
      (i32.const -59)
    )
    (drop
      (i32.const -60)
    )
    (drop
      (i32.const -61)
    )
    (drop
      (i32.const -62)
    )
    (drop
      (i32.const -63)
    )
    (drop
      (i32.const -64)
    )
    (drop
      (i32.const -65)
    )
    (drop
      (i32.const -66)
    )
    (drop
      (i32.const -67)
    )
    (drop
      (i32.const -68)
    )
    (drop
      (i32.const -69)
    )
    (drop
      (i32.const -70)
    )
    (drop
      (i32.const -71)
    )
    (drop
      (i32.const -72)
    )
    (drop
      (i32.const -73)
    )
    (drop
      (i32.const -74)
    )
    (drop
      (i32.const -75)
    )
    (drop
      (i32.const -76)
    )
    (drop
      (i32.const -77)
    )
    (drop
      (i32.const -78)
    )
    (drop
      (i32.const -79)
    )
    (drop
      (i32.const -80)
    )
    (drop
      (i32.const -81)
    )
    (drop
      (i32.const -82)
    )
    (drop
      (i32.const -83)
    )
    (drop
      (i32.const -84)
    )
    (drop
      (i32.const -85)
    )
    (drop
      (i32.const -86)
    )
    (drop
      (i32.const -87)
    )
    (drop
      (i32.const -88)
    )
    (drop
      (i32.const -89)
    )
    (drop
      (i32.const -90)
    )
    (drop
      (i32.const -91)
    )
    (drop
      (i32.const -92)
    )
    (drop
      (i32.const -93)
    )
    (drop
      (i32.const -94)
    )
    (drop
      (i32.const -95)
    )
    (drop
      (i32.const -96)
    )
    (drop
      (i32.const -97)
    )
    (drop
      (i32.const -98)
    )
    (drop
      (i32.const -99)
    )
    (drop
      (i32.const -100)
    )
    (drop
      (i32.const -101)
    )
    (drop
      (i32.const -102)
    )
    (drop
      (i32.const -103)
    )
    (drop
      (i32.const -104)
    )
    (drop
      (i32.const -105)
    )
    (drop
      (i32.const -106)
    )
    (drop
      (i32.const -107)
    )
    (drop
      (i32.const -108)
    )
    (drop
      (i32.const -109)
    )
    (drop
      (i32.const -110)
    )
    (drop
      (i32.const -111)
    )
    (drop
      (i32.const -112)
    )
    (drop
      (i32.const -113)
    )
    (drop
      (i32.const -114)
    )
    (drop
      (i32.const -115)
    )
    (drop
      (i32.const -116)
    )
    (drop
      (i32.const -117)
    )
    (drop
      (i32.const -118)
    )
    (drop
      (i32.const -119)
    )
    (drop
      (i32.const -120)
    )
    (drop
      (i32.const -121)
    )
    (drop
      (i32.const -122)
    )
    (drop
      (i32.const -123)
    )
    (drop
      (i32.const -124)
    )
    (drop
      (i32.const -125)
    )
    (drop
      (i32.const -126)
    )
    (drop
      (i32.const -127)
    )
    (drop
      (i32.const -128)
    )
    (drop
      (i32.const -129)
    )
    (drop
      (i32.const -130)
    )
    (drop
      (i32.const -131)
    )
    (drop
      (i32.const -132)
    )
    (drop
      (i32.const -133)
    )
    (drop
      (i32.const -134)
    )
    (drop
      (i32.const -135)
    )
    (drop
      (i32.const -136)
    )
    (drop
      (i32.const -137)
    )
    (drop
      (i32.const -138)
    )
    (drop
      (i32.const -139)
    )
    (drop
      (i32.const -140)
    )
    (drop
      (i32.const -141)
    )
    (drop
      (i32.const -142)
    )
    (drop
      (i32.const -143)
    )
    (drop
      (i32.const -144)
    )
    (drop
      (i32.const -145)
    )
    (drop
      (i32.const -146)
    )
    (drop
      (i32.const -147)
    )
    (drop
      (i32.const -148)
    )
    (drop
      (i32.const -149)
    )
    (drop
      (i32.const -150)
    )
    (drop
      (i32.const -151)
    )
    (drop
      (i32.const -152)
    )
    (drop
      (i32.const -153)
    )
    (drop
      (i32.const -154)
    )
    (drop
      (i32.const -155)
    )
    (drop
      (i32.const -156)
    )
    (drop
      (i32.const -157)
    )
    (drop
      (i32.const -158)
    )
    (drop
      (i32.const -159)
    )
    (drop
      (i32.const -160)
    )
    (drop
      (i32.const -161)
    )
    (drop
      (i32.const -162)
    )
    (drop
      (i32.const -163)
    )
    (drop
      (i32.const -164)
    )
    (drop
      (i32.const -165)
    )
    (drop
      (i32.const -166)
    )
    (drop
      (i32.const -167)
    )
    (drop
      (i32.const -168)
    )
    (drop
      (i32.const -169)
    )
    (drop
      (i32.const -170)
    )
    (drop
      (i32.const -171)
    )
    (drop
      (i32.const -172)
    )
    (drop
      (i32.const -173)
    )
    (drop
      (i32.const -174)
    )
    (drop
      (i32.const -175)
    )
    (drop
      (i32.const -176)
    )
    (drop
      (i32.const -177)
    )
    (drop
      (i32.const -178)
    )
    (drop
      (i32.const -179)
    )
    (drop
      (i32.const -180)
    )
    (drop
      (i32.const -181)
    )
    (drop
      (i32.const -182)
    )
    (drop
      (i32.const -183)
    )
    (drop
      (i32.const -184)
    )
    (drop
      (i32.const -185)
    )
    (drop
      (i32.const -186)
    )
    (drop
      (i32.const -187)
    )
    (drop
      (i32.const -188)
    )
    (drop
      (i32.const -189)
    )
    (drop
      (i32.const -190)
    )
    (drop
      (i32.const -191)
    )
    (drop
      (i32.const -192)
    )
    (drop
      (i32.const -193)
    )
    (drop
      (i32.const -194)
    )
    (drop
      (i32.const -195)
    )
    (drop
      (i32.const -196)
    )
    (drop
      (i32.const -197)
    )
    (drop
      (i32.const -198)
    )
    (drop
      (i32.const -199)
    )
    (drop
      (i32.const -200)
    )
    (drop
      (i32.const -201)
    )
    (drop
      (i32.const -202)
    )
    (drop
      (i32.const -203)
    )
    (drop
      (i32.const -204)
    )
    (drop
      (i32.const -205)
    )
    (drop
      (i32.const -206)
    )
    (drop
      (i32.const -207)
    )
    (drop
      (i32.const -208)
    )
    (drop
      (i32.const -209)
    )
    (drop
      (i32.const -210)
    )
    (drop
      (i32.const -211)
    )
    (drop
      (i32.const -212)
    )
    (drop
      (i32.const -213)
    )
    (drop
      (i32.const -214)
    )
    (drop
      (i32.const -215)
    )
    (drop
      (i32.const -216)
    )
    (drop
      (i32.const -217)
    )
    (drop
      (i32.const -218)
    )
    (drop
      (i32.const -219)
    )
    (drop
      (i32.const -220)
    )
    (drop
      (i32.const -221)
    )
    (drop
      (i32.const -222)
    )
    (drop
      (i32.const -223)
    )
    (drop
      (i32.const -224)
    )
    (drop
      (i32.const -225)
    )
    (drop
      (i32.const -226)
    )
    (drop
      (i32.const -227)
    )
    (drop
      (i32.const -228)
    )
    (drop
      (i32.const -229)
    )
    (drop
      (i32.const -230)
    )
    (drop
      (i32.const -231)
    )
    (drop
      (i32.const -232)
    )
    (drop
      (i32.const -233)
    )
    (drop
      (i32.const -234)
    )
    (drop
      (i32.const -235)
    )
    (drop
      (i32.const -236)
    )
    (drop
      (i32.const -237)
    )
    (drop
      (i32.const -238)
    )
    (drop
      (i32.const -239)
    )
    (drop
      (i32.const -240)
    )
    (drop
      (i32.const -241)
    )
    (drop
      (i32.const -242)
    )
    (drop
      (i32.const -243)
    )
    (drop
      (i32.const -244)
    )
    (drop
      (i32.const -245)
    )
    (drop
      (i32.const -246)
    )
    (drop
      (i32.const -247)
    )
    (drop
      (i32.const -248)
    )
    (drop
      (i32.const -249)
    )
    (drop
      (i32.const -250)
    )
    (drop
      (i32.const -251)
    )
    (drop
      (i32.const -252)
    )
    (drop
      (i32.const -253)
    )
    (drop
      (i32.const -254)
    )
    (drop
      (i32.const -255)
    )
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
  )

  ;; CHECK:      (func $over-limit-1
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 2)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 3)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 4)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 5)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 6)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 7)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 8)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 9)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 11)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 12)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 13)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 14)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 15)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 16)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 17)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 18)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 19)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 21)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 22)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 23)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 24)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 25)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 26)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 27)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 28)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 29)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 31)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 32)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 33)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 34)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 35)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 36)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 37)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 38)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 39)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 40)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 41)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 43)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 44)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 45)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 46)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 47)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 48)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 49)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 50)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 51)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 52)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 53)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 54)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 55)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 56)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 57)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 58)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 59)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 60)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 61)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 62)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 63)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 64)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 65)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 66)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 67)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 68)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 69)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 70)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 71)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 72)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 73)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 74)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 75)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 76)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 77)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 78)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 79)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 80)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 81)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 82)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 83)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 84)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 85)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 86)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 87)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 88)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 89)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 90)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 91)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 92)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 93)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 94)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 95)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 96)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 97)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 98)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 99)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 100)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 101)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 102)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 103)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 104)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 105)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 106)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 107)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 108)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 109)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 110)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 111)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 112)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 113)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 114)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 115)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 116)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 117)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 118)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 119)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 120)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 121)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 122)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 123)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 124)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 125)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 126)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 127)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 128)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 129)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 130)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 131)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 132)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 133)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 134)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 135)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 136)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 137)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 138)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 139)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 140)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 141)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 142)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 143)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 144)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 145)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 146)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 147)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 148)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 149)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 150)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 151)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 152)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 153)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 154)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 155)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 156)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 157)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 158)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 159)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 160)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 161)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 162)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 163)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 164)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 165)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 166)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 167)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 168)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 169)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 170)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 171)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 172)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 173)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 174)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 175)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 176)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 177)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 178)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 179)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 180)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 181)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 182)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 183)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 184)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 185)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 186)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 187)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 188)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 189)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 190)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 191)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 192)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 193)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 194)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 195)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 196)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 197)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 198)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 199)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 200)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 201)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 202)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 203)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 204)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 205)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 206)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 207)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 208)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 209)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 210)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 211)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 212)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 213)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 214)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 215)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 216)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 217)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 218)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 219)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 220)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 221)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 222)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 223)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 224)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 225)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 226)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 227)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 228)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 229)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 230)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 231)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 232)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 233)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 234)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 235)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 236)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 237)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 238)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 239)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 240)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 241)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 242)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 243)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 244)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 245)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 246)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 247)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 248)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 249)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 250)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 251)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 252)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 253)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 254)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 255)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 256)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $over-limit-1
    (drop
      (i32.const 1)
    )
    (drop
      (i32.const 2)
    )
    (drop
      (i32.const 3)
    )
    (drop
      (i32.const 4)
    )
    (drop
      (i32.const 5)
    )
    (drop
      (i32.const 6)
    )
    (drop
      (i32.const 7)
    )
    (drop
      (i32.const 8)
    )
    (drop
      (i32.const 9)
    )
    (drop
      (i32.const 10)
    )
    (drop
      (i32.const 11)
    )
    (drop
      (i32.const 12)
    )
    (drop
      (i32.const 13)
    )
    (drop
      (i32.const 14)
    )
    (drop
      (i32.const 15)
    )
    (drop
      (i32.const 16)
    )
    (drop
      (i32.const 17)
    )
    (drop
      (i32.const 18)
    )
    (drop
      (i32.const 19)
    )
    (drop
      (i32.const 20)
    )
    (drop
      (i32.const 21)
    )
    (drop
      (i32.const 22)
    )
    (drop
      (i32.const 23)
    )
    (drop
      (i32.const 24)
    )
    (drop
      (i32.const 25)
    )
    (drop
      (i32.const 26)
    )
    (drop
      (i32.const 27)
    )
    (drop
      (i32.const 28)
    )
    (drop
      (i32.const 29)
    )
    (drop
      (i32.const 30)
    )
    (drop
      (i32.const 31)
    )
    (drop
      (i32.const 32)
    )
    (drop
      (i32.const 33)
    )
    (drop
      (i32.const 34)
    )
    (drop
      (i32.const 35)
    )
    (drop
      (i32.const 36)
    )
    (drop
      (i32.const 37)
    )
    (drop
      (i32.const 38)
    )
    (drop
      (i32.const 39)
    )
    (drop
      (i32.const 40)
    )
    (drop
      (i32.const 41)
    )
    (drop
      (i32.const 42)
    )
    (drop
      (i32.const 43)
    )
    (drop
      (i32.const 44)
    )
    (drop
      (i32.const 45)
    )
    (drop
      (i32.const 46)
    )
    (drop
      (i32.const 47)
    )
    (drop
      (i32.const 48)
    )
    (drop
      (i32.const 49)
    )
    (drop
      (i32.const 50)
    )
    (drop
      (i32.const 51)
    )
    (drop
      (i32.const 52)
    )
    (drop
      (i32.const 53)
    )
    (drop
      (i32.const 54)
    )
    (drop
      (i32.const 55)
    )
    (drop
      (i32.const 56)
    )
    (drop
      (i32.const 57)
    )
    (drop
      (i32.const 58)
    )
    (drop
      (i32.const 59)
    )
    (drop
      (i32.const 60)
    )
    (drop
      (i32.const 61)
    )
    (drop
      (i32.const 62)
    )
    (drop
      (i32.const 63)
    )
    (drop
      (i32.const 64)
    )
    (drop
      (i32.const 65)
    )
    (drop
      (i32.const 66)
    )
    (drop
      (i32.const 67)
    )
    (drop
      (i32.const 68)
    )
    (drop
      (i32.const 69)
    )
    (drop
      (i32.const 70)
    )
    (drop
      (i32.const 71)
    )
    (drop
      (i32.const 72)
    )
    (drop
      (i32.const 73)
    )
    (drop
      (i32.const 74)
    )
    (drop
      (i32.const 75)
    )
    (drop
      (i32.const 76)
    )
    (drop
      (i32.const 77)
    )
    (drop
      (i32.const 78)
    )
    (drop
      (i32.const 79)
    )
    (drop
      (i32.const 80)
    )
    (drop
      (i32.const 81)
    )
    (drop
      (i32.const 82)
    )
    (drop
      (i32.const 83)
    )
    (drop
      (i32.const 84)
    )
    (drop
      (i32.const 85)
    )
    (drop
      (i32.const 86)
    )
    (drop
      (i32.const 87)
    )
    (drop
      (i32.const 88)
    )
    (drop
      (i32.const 89)
    )
    (drop
      (i32.const 90)
    )
    (drop
      (i32.const 91)
    )
    (drop
      (i32.const 92)
    )
    (drop
      (i32.const 93)
    )
    (drop
      (i32.const 94)
    )
    (drop
      (i32.const 95)
    )
    (drop
      (i32.const 96)
    )
    (drop
      (i32.const 97)
    )
    (drop
      (i32.const 98)
    )
    (drop
      (i32.const 99)
    )
    (drop
      (i32.const 100)
    )
    (drop
      (i32.const 101)
    )
    (drop
      (i32.const 102)
    )
    (drop
      (i32.const 103)
    )
    (drop
      (i32.const 104)
    )
    (drop
      (i32.const 105)
    )
    (drop
      (i32.const 106)
    )
    (drop
      (i32.const 107)
    )
    (drop
      (i32.const 108)
    )
    (drop
      (i32.const 109)
    )
    (drop
      (i32.const 110)
    )
    (drop
      (i32.const 111)
    )
    (drop
      (i32.const 112)
    )
    (drop
      (i32.const 113)
    )
    (drop
      (i32.const 114)
    )
    (drop
      (i32.const 115)
    )
    (drop
      (i32.const 116)
    )
    (drop
      (i32.const 117)
    )
    (drop
      (i32.const 118)
    )
    (drop
      (i32.const 119)
    )
    (drop
      (i32.const 120)
    )
    (drop
      (i32.const 121)
    )
    (drop
      (i32.const 122)
    )
    (drop
      (i32.const 123)
    )
    (drop
      (i32.const 124)
    )
    (drop
      (i32.const 125)
    )
    (drop
      (i32.const 126)
    )
    (drop
      (i32.const 127)
    )
    (drop
      (i32.const 128)
    )
    (drop
      (i32.const 129)
    )
    (drop
      (i32.const 130)
    )
    (drop
      (i32.const 131)
    )
    (drop
      (i32.const 132)
    )
    (drop
      (i32.const 133)
    )
    (drop
      (i32.const 134)
    )
    (drop
      (i32.const 135)
    )
    (drop
      (i32.const 136)
    )
    (drop
      (i32.const 137)
    )
    (drop
      (i32.const 138)
    )
    (drop
      (i32.const 139)
    )
    (drop
      (i32.const 140)
    )
    (drop
      (i32.const 141)
    )
    (drop
      (i32.const 142)
    )
    (drop
      (i32.const 143)
    )
    (drop
      (i32.const 144)
    )
    (drop
      (i32.const 145)
    )
    (drop
      (i32.const 146)
    )
    (drop
      (i32.const 147)
    )
    (drop
      (i32.const 148)
    )
    (drop
      (i32.const 149)
    )
    (drop
      (i32.const 150)
    )
    (drop
      (i32.const 151)
    )
    (drop
      (i32.const 152)
    )
    (drop
      (i32.const 153)
    )
    (drop
      (i32.const 154)
    )
    (drop
      (i32.const 155)
    )
    (drop
      (i32.const 156)
    )
    (drop
      (i32.const 157)
    )
    (drop
      (i32.const 158)
    )
    (drop
      (i32.const 159)
    )
    (drop
      (i32.const 160)
    )
    (drop
      (i32.const 161)
    )
    (drop
      (i32.const 162)
    )
    (drop
      (i32.const 163)
    )
    (drop
      (i32.const 164)
    )
    (drop
      (i32.const 165)
    )
    (drop
      (i32.const 166)
    )
    (drop
      (i32.const 167)
    )
    (drop
      (i32.const 168)
    )
    (drop
      (i32.const 169)
    )
    (drop
      (i32.const 170)
    )
    (drop
      (i32.const 171)
    )
    (drop
      (i32.const 172)
    )
    (drop
      (i32.const 173)
    )
    (drop
      (i32.const 174)
    )
    (drop
      (i32.const 175)
    )
    (drop
      (i32.const 176)
    )
    (drop
      (i32.const 177)
    )
    (drop
      (i32.const 178)
    )
    (drop
      (i32.const 179)
    )
    (drop
      (i32.const 180)
    )
    (drop
      (i32.const 181)
    )
    (drop
      (i32.const 182)
    )
    (drop
      (i32.const 183)
    )
    (drop
      (i32.const 184)
    )
    (drop
      (i32.const 185)
    )
    (drop
      (i32.const 186)
    )
    (drop
      (i32.const 187)
    )
    (drop
      (i32.const 188)
    )
    (drop
      (i32.const 189)
    )
    (drop
      (i32.const 190)
    )
    (drop
      (i32.const 191)
    )
    (drop
      (i32.const 192)
    )
    (drop
      (i32.const 193)
    )
    (drop
      (i32.const 194)
    )
    (drop
      (i32.const 195)
    )
    (drop
      (i32.const 196)
    )
    (drop
      (i32.const 197)
    )
    (drop
      (i32.const 198)
    )
    (drop
      (i32.const 199)
    )
    (drop
      (i32.const 200)
    )
    (drop
      (i32.const 201)
    )
    (drop
      (i32.const 202)
    )
    (drop
      (i32.const 203)
    )
    (drop
      (i32.const 204)
    )
    (drop
      (i32.const 205)
    )
    (drop
      (i32.const 206)
    )
    (drop
      (i32.const 207)
    )
    (drop
      (i32.const 208)
    )
    (drop
      (i32.const 209)
    )
    (drop
      (i32.const 210)
    )
    (drop
      (i32.const 211)
    )
    (drop
      (i32.const 212)
    )
    (drop
      (i32.const 213)
    )
    (drop
      (i32.const 214)
    )
    (drop
      (i32.const 215)
    )
    (drop
      (i32.const 216)
    )
    (drop
      (i32.const 217)
    )
    (drop
      (i32.const 218)
    )
    (drop
      (i32.const 219)
    )
    (drop
      (i32.const 220)
    )
    (drop
      (i32.const 221)
    )
    (drop
      (i32.const 222)
    )
    (drop
      (i32.const 223)
    )
    (drop
      (i32.const 224)
    )
    (drop
      (i32.const 225)
    )
    (drop
      (i32.const 226)
    )
    (drop
      (i32.const 227)
    )
    (drop
      (i32.const 228)
    )
    (drop
      (i32.const 229)
    )
    (drop
      (i32.const 230)
    )
    (drop
      (i32.const 231)
    )
    (drop
      (i32.const 232)
    )
    (drop
      (i32.const 233)
    )
    (drop
      (i32.const 234)
    )
    (drop
      (i32.const 235)
    )
    (drop
      (i32.const 236)
    )
    (drop
      (i32.const 237)
    )
    (drop
      (i32.const 238)
    )
    (drop
      (i32.const 239)
    )
    (drop
      (i32.const 240)
    )
    (drop
      (i32.const 241)
    )
    (drop
      (i32.const 242)
    )
    (drop
      (i32.const 243)
    )
    (drop
      (i32.const 244)
    )
    (drop
      (i32.const 245)
    )
    (drop
      (i32.const 246)
    )
    (drop
      (i32.const 247)
    )
    (drop
      (i32.const 248)
    )
    (drop
      (i32.const 249)
    )
    (drop
      (i32.const 250)
    )
    (drop
      (i32.const 251)
    )
    (drop
      (i32.const 252)
    )
    (drop
      (i32.const 253)
    )
    (drop
      (i32.const 254)
    )
    (drop
      (i32.const 255)
    )
    (drop
      (i32.const 256)
    )
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
  )

  ;; CHECK:      (func $over-limit-2
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -2)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -3)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -4)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -5)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -6)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -7)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -8)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -9)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -11)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -12)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -13)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -14)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -15)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -16)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -17)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -18)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -19)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -21)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -22)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -23)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -24)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -25)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -26)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -27)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -28)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -29)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -31)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -32)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -33)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -34)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -35)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -36)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -37)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -38)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -39)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -40)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -41)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -42)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -43)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -44)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -45)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -46)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -47)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -48)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -49)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -50)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -51)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -52)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -53)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -54)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -55)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -56)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -57)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -58)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -59)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -60)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -61)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -62)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -63)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -64)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -65)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -66)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -67)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -68)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -69)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -70)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -71)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -72)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -73)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -74)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -75)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -76)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -77)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -78)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -79)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -80)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -81)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -82)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -83)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -84)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -85)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -86)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -87)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -88)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -89)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -90)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -91)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -92)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -93)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -94)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -95)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -96)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -97)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -98)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -99)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -100)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -101)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -102)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -103)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -104)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -105)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -106)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -107)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -108)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -109)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -110)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -111)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -112)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -113)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -114)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -115)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -116)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -117)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -118)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -119)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -120)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -121)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -122)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -123)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -124)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -125)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -126)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -127)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -128)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -129)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -130)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -131)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -132)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -133)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -134)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -135)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -136)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -137)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -138)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -139)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -140)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -141)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -142)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -143)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -144)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -145)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -146)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -147)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -148)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -149)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -150)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -151)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -152)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -153)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -154)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -155)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -156)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -157)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -158)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -159)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -160)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -161)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -162)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -163)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -164)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -165)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -166)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -167)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -168)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -169)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -170)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -171)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -172)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -173)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -174)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -175)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -176)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -177)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -178)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -179)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -180)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -181)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -182)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -183)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -184)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -185)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -186)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -187)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -188)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -189)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -190)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -191)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -192)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -193)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -194)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -195)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -196)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -197)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -198)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -199)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -200)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -201)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -202)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -203)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -204)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -205)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -206)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -207)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -208)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -209)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -210)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -211)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -212)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -213)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -214)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -215)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -216)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -217)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -218)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -219)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -220)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -221)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -222)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -223)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -224)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -225)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -226)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -227)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -228)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -229)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -230)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -231)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -232)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -233)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -234)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -235)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -236)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -237)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -238)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -239)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -240)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -241)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -242)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -243)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -244)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -245)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -246)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -247)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -248)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -249)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -250)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -251)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -252)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -253)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -254)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -255)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const -256)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $over-limit-2
    (drop
      (i32.const -1)
    )
    (drop
      (i32.const -2)
    )
    (drop
      (i32.const -3)
    )
    (drop
      (i32.const -4)
    )
    (drop
      (i32.const -5)
    )
    (drop
      (i32.const -6)
    )
    (drop
      (i32.const -7)
    )
    (drop
      (i32.const -8)
    )
    (drop
      (i32.const -9)
    )
    (drop
      (i32.const -10)
    )
    (drop
      (i32.const -11)
    )
    (drop
      (i32.const -12)
    )
    (drop
      (i32.const -13)
    )
    (drop
      (i32.const -14)
    )
    (drop
      (i32.const -15)
    )
    (drop
      (i32.const -16)
    )
    (drop
      (i32.const -17)
    )
    (drop
      (i32.const -18)
    )
    (drop
      (i32.const -19)
    )
    (drop
      (i32.const -20)
    )
    (drop
      (i32.const -21)
    )
    (drop
      (i32.const -22)
    )
    (drop
      (i32.const -23)
    )
    (drop
      (i32.const -24)
    )
    (drop
      (i32.const -25)
    )
    (drop
      (i32.const -26)
    )
    (drop
      (i32.const -27)
    )
    (drop
      (i32.const -28)
    )
    (drop
      (i32.const -29)
    )
    (drop
      (i32.const -30)
    )
    (drop
      (i32.const -31)
    )
    (drop
      (i32.const -32)
    )
    (drop
      (i32.const -33)
    )
    (drop
      (i32.const -34)
    )
    (drop
      (i32.const -35)
    )
    (drop
      (i32.const -36)
    )
    (drop
      (i32.const -37)
    )
    (drop
      (i32.const -38)
    )
    (drop
      (i32.const -39)
    )
    (drop
      (i32.const -40)
    )
    (drop
      (i32.const -41)
    )
    (drop
      (i32.const -42)
    )
    (drop
      (i32.const -43)
    )
    (drop
      (i32.const -44)
    )
    (drop
      (i32.const -45)
    )
    (drop
      (i32.const -46)
    )
    (drop
      (i32.const -47)
    )
    (drop
      (i32.const -48)
    )
    (drop
      (i32.const -49)
    )
    (drop
      (i32.const -50)
    )
    (drop
      (i32.const -51)
    )
    (drop
      (i32.const -52)
    )
    (drop
      (i32.const -53)
    )
    (drop
      (i32.const -54)
    )
    (drop
      (i32.const -55)
    )
    (drop
      (i32.const -56)
    )
    (drop
      (i32.const -57)
    )
    (drop
      (i32.const -58)
    )
    (drop
      (i32.const -59)
    )
    (drop
      (i32.const -60)
    )
    (drop
      (i32.const -61)
    )
    (drop
      (i32.const -62)
    )
    (drop
      (i32.const -63)
    )
    (drop
      (i32.const -64)
    )
    (drop
      (i32.const -65)
    )
    (drop
      (i32.const -66)
    )
    (drop
      (i32.const -67)
    )
    (drop
      (i32.const -68)
    )
    (drop
      (i32.const -69)
    )
    (drop
      (i32.const -70)
    )
    (drop
      (i32.const -71)
    )
    (drop
      (i32.const -72)
    )
    (drop
      (i32.const -73)
    )
    (drop
      (i32.const -74)
    )
    (drop
      (i32.const -75)
    )
    (drop
      (i32.const -76)
    )
    (drop
      (i32.const -77)
    )
    (drop
      (i32.const -78)
    )
    (drop
      (i32.const -79)
    )
    (drop
      (i32.const -80)
    )
    (drop
      (i32.const -81)
    )
    (drop
      (i32.const -82)
    )
    (drop
      (i32.const -83)
    )
    (drop
      (i32.const -84)
    )
    (drop
      (i32.const -85)
    )
    (drop
      (i32.const -86)
    )
    (drop
      (i32.const -87)
    )
    (drop
      (i32.const -88)
    )
    (drop
      (i32.const -89)
    )
    (drop
      (i32.const -90)
    )
    (drop
      (i32.const -91)
    )
    (drop
      (i32.const -92)
    )
    (drop
      (i32.const -93)
    )
    (drop
      (i32.const -94)
    )
    (drop
      (i32.const -95)
    )
    (drop
      (i32.const -96)
    )
    (drop
      (i32.const -97)
    )
    (drop
      (i32.const -98)
    )
    (drop
      (i32.const -99)
    )
    (drop
      (i32.const -100)
    )
    (drop
      (i32.const -101)
    )
    (drop
      (i32.const -102)
    )
    (drop
      (i32.const -103)
    )
    (drop
      (i32.const -104)
    )
    (drop
      (i32.const -105)
    )
    (drop
      (i32.const -106)
    )
    (drop
      (i32.const -107)
    )
    (drop
      (i32.const -108)
    )
    (drop
      (i32.const -109)
    )
    (drop
      (i32.const -110)
    )
    (drop
      (i32.const -111)
    )
    (drop
      (i32.const -112)
    )
    (drop
      (i32.const -113)
    )
    (drop
      (i32.const -114)
    )
    (drop
      (i32.const -115)
    )
    (drop
      (i32.const -116)
    )
    (drop
      (i32.const -117)
    )
    (drop
      (i32.const -118)
    )
    (drop
      (i32.const -119)
    )
    (drop
      (i32.const -120)
    )
    (drop
      (i32.const -121)
    )
    (drop
      (i32.const -122)
    )
    (drop
      (i32.const -123)
    )
    (drop
      (i32.const -124)
    )
    (drop
      (i32.const -125)
    )
    (drop
      (i32.const -126)
    )
    (drop
      (i32.const -127)
    )
    (drop
      (i32.const -128)
    )
    (drop
      (i32.const -129)
    )
    (drop
      (i32.const -130)
    )
    (drop
      (i32.const -131)
    )
    (drop
      (i32.const -132)
    )
    (drop
      (i32.const -133)
    )
    (drop
      (i32.const -134)
    )
    (drop
      (i32.const -135)
    )
    (drop
      (i32.const -136)
    )
    (drop
      (i32.const -137)
    )
    (drop
      (i32.const -138)
    )
    (drop
      (i32.const -139)
    )
    (drop
      (i32.const -140)
    )
    (drop
      (i32.const -141)
    )
    (drop
      (i32.const -142)
    )
    (drop
      (i32.const -143)
    )
    (drop
      (i32.const -144)
    )
    (drop
      (i32.const -145)
    )
    (drop
      (i32.const -146)
    )
    (drop
      (i32.const -147)
    )
    (drop
      (i32.const -148)
    )
    (drop
      (i32.const -149)
    )
    (drop
      (i32.const -150)
    )
    (drop
      (i32.const -151)
    )
    (drop
      (i32.const -152)
    )
    (drop
      (i32.const -153)
    )
    (drop
      (i32.const -154)
    )
    (drop
      (i32.const -155)
    )
    (drop
      (i32.const -156)
    )
    (drop
      (i32.const -157)
    )
    (drop
      (i32.const -158)
    )
    (drop
      (i32.const -159)
    )
    (drop
      (i32.const -160)
    )
    (drop
      (i32.const -161)
    )
    (drop
      (i32.const -162)
    )
    (drop
      (i32.const -163)
    )
    (drop
      (i32.const -164)
    )
    (drop
      (i32.const -165)
    )
    (drop
      (i32.const -166)
    )
    (drop
      (i32.const -167)
    )
    (drop
      (i32.const -168)
    )
    (drop
      (i32.const -169)
    )
    (drop
      (i32.const -170)
    )
    (drop
      (i32.const -171)
    )
    (drop
      (i32.const -172)
    )
    (drop
      (i32.const -173)
    )
    (drop
      (i32.const -174)
    )
    (drop
      (i32.const -175)
    )
    (drop
      (i32.const -176)
    )
    (drop
      (i32.const -177)
    )
    (drop
      (i32.const -178)
    )
    (drop
      (i32.const -179)
    )
    (drop
      (i32.const -180)
    )
    (drop
      (i32.const -181)
    )
    (drop
      (i32.const -182)
    )
    (drop
      (i32.const -183)
    )
    (drop
      (i32.const -184)
    )
    (drop
      (i32.const -185)
    )
    (drop
      (i32.const -186)
    )
    (drop
      (i32.const -187)
    )
    (drop
      (i32.const -188)
    )
    (drop
      (i32.const -189)
    )
    (drop
      (i32.const -190)
    )
    (drop
      (i32.const -191)
    )
    (drop
      (i32.const -192)
    )
    (drop
      (i32.const -193)
    )
    (drop
      (i32.const -194)
    )
    (drop
      (i32.const -195)
    )
    (drop
      (i32.const -196)
    )
    (drop
      (i32.const -197)
    )
    (drop
      (i32.const -198)
    )
    (drop
      (i32.const -199)
    )
    (drop
      (i32.const -200)
    )
    (drop
      (i32.const -201)
    )
    (drop
      (i32.const -202)
    )
    (drop
      (i32.const -203)
    )
    (drop
      (i32.const -204)
    )
    (drop
      (i32.const -205)
    )
    (drop
      (i32.const -206)
    )
    (drop
      (i32.const -207)
    )
    (drop
      (i32.const -208)
    )
    (drop
      (i32.const -209)
    )
    (drop
      (i32.const -210)
    )
    (drop
      (i32.const -211)
    )
    (drop
      (i32.const -212)
    )
    (drop
      (i32.const -213)
    )
    (drop
      (i32.const -214)
    )
    (drop
      (i32.const -215)
    )
    (drop
      (i32.const -216)
    )
    (drop
      (i32.const -217)
    )
    (drop
      (i32.const -218)
    )
    (drop
      (i32.const -219)
    )
    (drop
      (i32.const -220)
    )
    (drop
      (i32.const -221)
    )
    (drop
      (i32.const -222)
    )
    (drop
      (i32.const -223)
    )
    (drop
      (i32.const -224)
    )
    (drop
      (i32.const -225)
    )
    (drop
      (i32.const -226)
    )
    (drop
      (i32.const -227)
    )
    (drop
      (i32.const -228)
    )
    (drop
      (i32.const -229)
    )
    (drop
      (i32.const -230)
    )
    (drop
      (i32.const -231)
    )
    (drop
      (i32.const -232)
    )
    (drop
      (i32.const -233)
    )
    (drop
      (i32.const -234)
    )
    (drop
      (i32.const -235)
    )
    (drop
      (i32.const -236)
    )
    (drop
      (i32.const -237)
    )
    (drop
      (i32.const -238)
    )
    (drop
      (i32.const -239)
    )
    (drop
      (i32.const -240)
    )
    (drop
      (i32.const -241)
    )
    (drop
      (i32.const -242)
    )
    (drop
      (i32.const -243)
    )
    (drop
      (i32.const -244)
    )
    (drop
      (i32.const -245)
    )
    (drop
      (i32.const -246)
    )
    (drop
      (i32.const -247)
    )
    (drop
      (i32.const -248)
    )
    (drop
      (i32.const -249)
    )
    (drop
      (i32.const -250)
    )
    (drop
      (i32.const -251)
    )
    (drop
      (i32.const -252)
    )
    (drop
      (i32.const -253)
    )
    (drop
      (i32.const -254)
    )
    (drop
      (i32.const -255)
    )
    (drop
      (i32.const -256)
    )
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
    (nop)
  )
)
;; CHECK:      (func $byn$mgfn-shared$at-limit-1 (param $0 i32) (param $1 i32) (param $2 i32) (param $3 i32) (param $4 i32) (param $5 i32) (param $6 i32) (param $7 i32) (param $8 i32) (param $9 i32) (param $10 i32) (param $11 i32) (param $12 i32) (param $13 i32) (param $14 i32) (param $15 i32) (param $16 i32) (param $17 i32) (param $18 i32) (param $19 i32) (param $20 i32) (param $21 i32) (param $22 i32) (param $23 i32) (param $24 i32) (param $25 i32) (param $26 i32) (param $27 i32) (param $28 i32) (param $29 i32) (param $30 i32) (param $31 i32) (param $32 i32) (param $33 i32) (param $34 i32) (param $35 i32) (param $36 i32) (param $37 i32) (param $38 i32) (param $39 i32) (param $40 i32) (param $41 i32) (param $42 i32) (param $43 i32) (param $44 i32) (param $45 i32) (param $46 i32) (param $47 i32) (param $48 i32) (param $49 i32) (param $50 i32) (param $51 i32) (param $52 i32) (param $53 i32) (param $54 i32) (param $55 i32) (param $56 i32) (param $57 i32) (param $58 i32) (param $59 i32) (param $60 i32) (param $61 i32) (param $62 i32) (param $63 i32) (param $64 i32) (param $65 i32) (param $66 i32) (param $67 i32) (param $68 i32) (param $69 i32) (param $70 i32) (param $71 i32) (param $72 i32) (param $73 i32) (param $74 i32) (param $75 i32) (param $76 i32) (param $77 i32) (param $78 i32) (param $79 i32) (param $80 i32) (param $81 i32) (param $82 i32) (param $83 i32) (param $84 i32) (param $85 i32) (param $86 i32) (param $87 i32) (param $88 i32) (param $89 i32) (param $90 i32) (param $91 i32) (param $92 i32) (param $93 i32) (param $94 i32) (param $95 i32) (param $96 i32) (param $97 i32) (param $98 i32) (param $99 i32) (param $100 i32) (param $101 i32) (param $102 i32) (param $103 i32) (param $104 i32) (param $105 i32) (param $106 i32) (param $107 i32) (param $108 i32) (param $109 i32) (param $110 i32) (param $111 i32) (param $112 i32) (param $113 i32) (param $114 i32) (param $115 i32) (param $116 i32) (param $117 i32) (param $118 i32) (param $119 i32) (param $120 i32) (param $121 i32) (param $122 i32) (param $123 i32) (param $124 i32) (param $125 i32) (param $126 i32) (param $127 i32) (param $128 i32) (param $129 i32) (param $130 i32) (param $131 i32) (param $132 i32) (param $133 i32) (param $134 i32) (param $135 i32) (param $136 i32) (param $137 i32) (param $138 i32) (param $139 i32) (param $140 i32) (param $141 i32) (param $142 i32) (param $143 i32) (param $144 i32) (param $145 i32) (param $146 i32) (param $147 i32) (param $148 i32) (param $149 i32) (param $150 i32) (param $151 i32) (param $152 i32) (param $153 i32) (param $154 i32) (param $155 i32) (param $156 i32) (param $157 i32) (param $158 i32) (param $159 i32) (param $160 i32) (param $161 i32) (param $162 i32) (param $163 i32) (param $164 i32) (param $165 i32) (param $166 i32) (param $167 i32) (param $168 i32) (param $169 i32) (param $170 i32) (param $171 i32) (param $172 i32) (param $173 i32) (param $174 i32) (param $175 i32) (param $176 i32) (param $177 i32) (param $178 i32) (param $179 i32) (param $180 i32) (param $181 i32) (param $182 i32) (param $183 i32) (param $184 i32) (param $185 i32) (param $186 i32) (param $187 i32) (param $188 i32) (param $189 i32) (param $190 i32) (param $191 i32) (param $192 i32) (param $193 i32) (param $194 i32) (param $195 i32) (param $196 i32) (param $197 i32) (param $198 i32) (param $199 i32) (param $200 i32) (param $201 i32) (param $202 i32) (param $203 i32) (param $204 i32) (param $205 i32) (param $206 i32) (param $207 i32) (param $208 i32) (param $209 i32) (param $210 i32) (param $211 i32) (param $212 i32) (param $213 i32) (param $214 i32) (param $215 i32) (param $216 i32) (param $217 i32) (param $218 i32) (param $219 i32) (param $220 i32) (param $221 i32) (param $222 i32) (param $223 i32) (param $224 i32) (param $225 i32) (param $226 i32) (param $227 i32) (param $228 i32) (param $229 i32) (param $230 i32) (param $231 i32) (param $232 i32) (param $233 i32) (param $234 i32) (param $235 i32) (param $236 i32) (param $237 i32) (param $238 i32) (param $239 i32) (param $240 i32) (param $241 i32) (param $242 i32) (param $243 i32) (param $244 i32) (param $245 i32) (param $246 i32) (param $247 i32) (param $248 i32) (param $249 i32) (param $250 i32) (param $251 i32) (param $252 i32) (param $253 i32) (param $254 i32)
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $254)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $253)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $252)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $251)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $250)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $249)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $248)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $247)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $246)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $245)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $244)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $243)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $242)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $241)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $240)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $239)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $238)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $237)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $236)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $235)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $234)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $233)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $232)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $231)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $230)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $229)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $228)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $227)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $226)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $225)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $224)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $223)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $222)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $221)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $220)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $219)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $218)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $217)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $216)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $215)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $214)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $213)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $212)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $211)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $210)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $209)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $208)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $207)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $206)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $205)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $204)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $203)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $202)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $201)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $200)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $199)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $198)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $197)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $196)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $195)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $194)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $193)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $192)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $191)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $190)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $189)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $188)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $187)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $186)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $185)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $184)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $183)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $182)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $181)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $180)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $179)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $178)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $177)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $176)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $175)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $174)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $173)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $172)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $171)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $170)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $169)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $168)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $167)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $166)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $165)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $164)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $163)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $162)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $161)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $160)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $159)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $158)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $157)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $156)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $155)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $154)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $153)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $152)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $151)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $150)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $149)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $148)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $147)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $146)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $145)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $144)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $143)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $142)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $141)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $140)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $139)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $138)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $137)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $136)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $135)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $134)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $133)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $132)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $131)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $130)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $129)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $128)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $127)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $126)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $125)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $124)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $123)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $122)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $121)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $120)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $119)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $118)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $117)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $116)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $115)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $114)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $113)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $112)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $111)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $110)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $109)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $108)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $107)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $106)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $105)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $104)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $103)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $102)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $101)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $100)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $99)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $98)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $97)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $96)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $95)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $94)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $93)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $92)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $91)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $90)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $89)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $88)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $87)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $86)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $85)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $84)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $83)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $82)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $81)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $80)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $79)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $78)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $77)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $76)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $75)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $74)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $73)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $72)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $71)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $70)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $69)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $68)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $67)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $66)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $65)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $64)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $63)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $62)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $61)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $60)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $59)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $58)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $57)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $56)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $55)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $54)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $53)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $52)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $51)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $50)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $49)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $48)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $47)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $46)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $45)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $44)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $43)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $42)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $41)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $40)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $39)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $38)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $37)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $36)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $35)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $34)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $33)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $32)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $31)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $30)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $29)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $28)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $27)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $26)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $25)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $24)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $23)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $22)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $21)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $20)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $19)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $18)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $17)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $16)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $15)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $14)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $13)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $12)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $11)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $10)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $9)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $8)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $7)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $6)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $5)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $4)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $3)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $2)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $1)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (drop
;; CHECK-NEXT:   (local.get $0)
;; CHECK-NEXT:  )
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT:  (nop)
;; CHECK-NEXT: )
