;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt %s --merge-blocks -all -S -o - | filecheck %s

(module
  ;; CHECK:      (type $struct (shared (struct (field (mut i32)))))
  (type $struct (shared (struct (field (mut i32)))))

  ;; CHECK:      (memory $mem 1 1 shared)
  (memory $mem 1 1 shared)

  ;; CHECK:      (func $foo (type $2) (param $0 i32) (param $1 i32)
  ;; CHECK-NEXT: )
  (func $foo (param i32 i32))

  ;; CHECK:      (func $disallowed (type $1) (param $x (ref $struct))
  ;; CHECK-NEXT:  (call $foo
  ;; CHECK-NEXT:   (block $label1 (result i32)
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (i32.atomic.load acqrel
  ;; CHECK-NEXT:      (i32.const 0)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (block (result i32)
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (struct.get $struct 0
  ;; CHECK-NEXT:      (local.get $x)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $disallowed (param $x (ref $struct))
    ;; Test 1: Disallowed reordering (GC read NOT moved before acquire load).
    (call $foo
      ;; This block is left behind because it is named.
      (block $block (result i32)
        (drop (i32.atomic.load acqrel (i32.const 0)))
        (i32.const 0)
      )
      ;; This block tries to move back past $block and out of $foo, but cannot.
      (block (result i32)
        (drop (struct.get $struct 0 (local.get $x)))
        (i32.const 0)
      )
    )
  )

  ;; CHECK:      (func $allowed (type $1) (param $x (ref $struct))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (struct.get $struct 0
  ;; CHECK-NEXT:    (local.get $x)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $foo
  ;; CHECK-NEXT:   (block $label2 (result i32)
  ;; CHECK-NEXT:    (i32.atomic.store acqrel
  ;; CHECK-NEXT:     (i32.const 0)
  ;; CHECK-NEXT:     (i32.const 42)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $allowed (param $x (ref $struct))
    ;; Test 2: Allowed reordering (GC read moved before Wasm release store)
    (call $foo
      ;; This block is left behind because it is named.
      (block $block (result i32)
        (i32.atomic.store acqrel (i32.const 0) (i32.const 42))
        (i32.const 0)
      )
      ;; This block can move back past $block and out of $foo.
      (block (result i32)
        (drop (struct.get $struct 0 (local.get $x)))
        (i32.const 0)
      )
    )
  )
)
