;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; RUN: foreach %s %t wasm-opt -all --merge-data-segments -S -o - | filecheck %s

;; Basic tests for the merge algorithm: it should merge adjacent and overlapping
;; segments in their order of appearance. The name of the merged segment should
;; be the name of an input segment with the lowest start address. As a
;; tiebreaker, when multiple input segments have the same start address, the
;; name is taken from the first-appearing input segment with the lowest start
;; address.

;; A typical forward merge of adjacent segments. Segments that are directly
;; adjacent can always be merged, except in the edge case that the merged data
;; would be too long for a single data segment.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $0 (i32.const 3) "foobarpezqux")
  (data $0 (i32.const 3) "foo")
  (data $1 (i32.const 6) "bar")
  (data $2 (i32.const 9) "pez")
  (data $3 (i32.const 12) "qux")
)

;; The same merge, but with the segments appearing in reverse order. The
;; resulting data should be the same, since adjacent merge respects address
;; order instead of appearance order. Even though segment $3 appears last, the
;; merged segment takes its name since it has the lowest start address.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  (data $0 (i32.const 12) "qux")
  (data $1 (i32.const 9) "pez")
  (data $2 (i32.const 6) "bar")
  ;; CHECK:      (data $3 (i32.const 3) "foobarpezqux")
  (data $3 (i32.const 3) "foo")
)

;; The following tests cover overlapping merge cases. Per the spec, active data
;; segments are written to their memories in order of appearance, so when they
;; overlap, we should take the data from the last-appearing segment for each
;; address.

;; Growing segments with a common start address. We take the name of segment $0
;; since it is the first-appearing segment at address 0.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $0 (i32.const 0) "quuuux")
  (data $0 (i32.const 0) "foo")
  (data $1 (i32.const 0) "baar")
  (data $2 (i32.const 0) "peeez")
  (data $3 (i32.const 0) "quuuux")
)

;; Growing segments with a common end address.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  (data $0 (i32.const 3) "foo")
  (data $1 (i32.const 2) "baar")
  (data $2 (i32.const 1) "peeez")
  ;; CHECK:      (data $3 (i32.const 0) "quuuux")
  (data $3 (i32.const 0) "quuuux")
)

;; Growing segments with differing start and end addresses.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  (data $0 (i32.const 3) "foo")
  (data $1 (i32.const 2) "baaar")
  (data $2 (i32.const 1) "peeeeez")
  ;; CHECK:      (data $3 (i32.const 0) "quuuuuuux")
  (data $3 (i32.const 0) "quuuuuuux")
)

;; Shrinking segments with a common start address. Again, we take the name of
;; segment $0 since it is the first-appearing segment at address 0.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $0 (i32.const 0) "foorzx")
  (data $0 (i32.const 0) "quuuux")
  (data $1 (i32.const 0) "peeez")
  (data $2 (i32.const 0) "baar")
  (data $3 (i32.const 0) "foo")
)

;; Shrinking segments with a common end address.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $0 (i32.const 0) "qpbfoo")
  (data $0 (i32.const 0) "quuuux")
  (data $1 (i32.const 1) "peeez")
  (data $2 (i32.const 2) "baar")
  (data $3 (i32.const 3) "foo")
)

;; Shrinking segments with differing start and end addresses.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $0 (i32.const 0) "qpbfoorzx")
  (data $0 (i32.const 0) "quuuuuuux")
  (data $1 (i32.const 1) "peeeeez")
  (data $2 (i32.const 2) "baaar")
  (data $3 (i32.const 3) "foo")
)

;; Long forward chain of partially overlapping merges.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $0 (i32.const 0) "fobapequFOBAPEQUX")
  (data $0 (i32.const 0) "foo")
  (data $1 (i32.const 2) "bar")
  (data $2 (i32.const 4) "pez")
  (data $3 (i32.const 6) "qux")
  (data $4 (i32.const 8) "FOO")
  (data $5 (i32.const 10) "BAR")
  (data $6 (i32.const 12) "PEZ")
  (data $7 (i32.const 14) "QUX")
)

;; Long reverse chain of partially overlapping merges. We take the name of
;; segment $7 since it has the lowest start address.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  (data $0 (i32.const 14) "QUX")
  (data $1 (i32.const 12) "PEZ")
  (data $2 (i32.const 10) "BAR")
  (data $3 (i32.const 8) "FOO")
  (data $4 (i32.const 6) "qux")
  (data $5 (i32.const 4) "pez")
  (data $6 (i32.const 2) "bar")
  ;; CHECK:      (data $7 (i32.const 0) "fooarezuxOOAREZUX")
  (data $7 (i32.const 0) "foo")
)

;; Repeatedly overwriting different parts of a merged segment.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $0 (i32.const 0) "QUXPEZ")
  (data $0 (i32.const 0) "foo")
  (data $1 (i32.const 3) "bar")
  (data $2 (i32.const 0) "pez")
  (data $3 (i32.const 3) "qux")
  (data $4 (i32.const 3) "FOO")
  (data $5 (i32.const 0) "BAR")
  (data $6 (i32.const 3) "PEZ")
  (data $7 (i32.const 0) "QUX")
)

;; Overwriting a merged segment while expanding it on both sides. We use the
;; name of segment $2 since it has the lowest start address.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  (data $0 (i32.const 3) "foobar")
  (data $1 (i32.const 2) "qux")
  ;; CHECK:      (data $2 (i32.const 1) "quxxobfooux")
  (data $2 (i32.const 1) "qux")
  (data $3 (i32.const 9) "qux")
  (data $4 (i32.const 7) "foo")
)

;; Interleaving merges between two different merged segments, in forward and
;; reverse.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $0 (i32.const 0) "fobapez")
  (data $0 (i32.const 0) "foo")
  (data $1 (i32.const 20) "PEZ")
  (data $2 (i32.const 2) "bar")
  (data $3 (i32.const 18) "BAR")
  (data $4 (i32.const 4) "pez")
  ;; CHECK:      (data $5 (i32.const 16) "FOOAREZ")
  (data $5 (i32.const 16) "FOO")
)

;; The merge algorithm should operate independently on different memories, and
;; it should ensure that the offset types on merged segments correspond to their
;; respective memories.
(module
  ;; CHECK:      (memory $0 i64 1 1)
  (memory $0 i64 1 1)
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  (data $0 (memory $1) (i32.const 5) "PEZ")
  ;; CHECK:      (data $1 (i64.const 0) "fobapez")
  (data $1 (i64.const 0) "foo")
  (data $2 (memory $1) (i32.const 3) "BAR")
  (data $3 (i64.const 2) "bar")
  ;; CHECK:      (data $4 (memory $1) (i32.const 1) "FOOAREZ")
  (data $4 (memory $1) (i32.const 1) "FOO")
  (data $5 (i64.const 4) "pez")
)

;; More shuffling between data segments of different memories.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  ;; CHECK:      (memory $2 1 1)
  (memory $2 1 1)
  ;; CHECK:      (memory $3 1 1)
  (memory $3 1 1)
  ;; CHECK:      (data $4 (i32.const 0) "foobar")

  ;; CHECK:      (data $5 (memory $1) (i32.const 1) "foor")

  ;; CHECK:      (data $1 (memory $2) (i32.const 1) "bfoo")

  ;; CHECK:      (data $0 (memory $3) (i32.const 0) "barfoo")
  (data $0 (memory $3) (i32.const 0) "bar")
  (data $1 (memory $2) (i32.const 1) "bar")
  (data $2 (memory $1) (i32.const 2) "bar")
  (data $3 (i32.const 3) "bar")
  (data $4 (i32.const 0) "foo")
  (data $5 (memory $1) (i32.const 1) "foo")
  (data $6 (memory $2) (i32.const 2) "foo")
  (data $7 (memory $3) (i32.const 3) "foo")
)

;; Tests for passive segments and instruction rewriting. The spec demands that
;; every active segment effectively go through data.drop after initialization,
;; so every time an explicit instruction refers to an active segment, it has the
;; same effect as referring to an empty passive segment. When manipulating
;; segments, we just have to find some active segment name in the output to
;; replace all active segment names appearing in instructions in the input.

;; Basic rewriting: All passive segments appear first in the output, and
;; references to them are unmodified; references to active segments are renamed
;; to the first-appearing active segment in the output.
(module
  ;; CHECK:      (type $1 (array (mut i8)))

  ;; CHECK:      (type $0 (func))
  (type $0 (func))
  (type $1 (array (mut i8)))
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  (data $0 (i32.const 3) "qux")
  ;; CHECK:      (data $1 "foo")
  (data $1 "foo")
  ;; CHECK:      (data $3 "pez")

  ;; CHECK:      (data $2 (i32.const 0) "barqux")
  (data $2 (i32.const 0) "bar")
  (data $3 "pez")
  ;; CHECK:      (data $4 (i32.const 16) "FOO")
  (data $4 (i32.const 16) "FOO")
  ;; CHECK:      (func $0 (type $0)
  ;; CHECK-NEXT:  (memory.init $3
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (data.drop $1)
  ;; CHECK-NEXT:  (array.init_data $1 $1
  ;; CHECK-NEXT:   (array.new_data $1 $3
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (memory.init $2
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (data.drop $2)
  ;; CHECK-NEXT:  (array.init_data $1 $2
  ;; CHECK-NEXT:   (array.new_data $1 $2
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $0 (type $0)
    (memory.init $3
      (i32.const 0)
      (i32.const 0)
      (i32.const 0)
    )
    (data.drop $1)
    (array.init_data $1 $1
      (array.new_data $1 $3
        (i32.const 0)
        (i32.const 0)
      )
      (i32.const 0)
      (i32.const 0)
      (i32.const 0)
    )
    (memory.init $2
      (i32.const 0)
      (i32.const 0)
      (i32.const 0)
    )
    (data.drop $0)
    (array.init_data $1 $0
      (array.new_data $1 $2
        (i32.const 0)
        (i32.const 0)
      )
      (i32.const 0)
      (i32.const 0)
      (i32.const 0)
    )
  )
)

;; Usage of the empty target segment. Again, all passive segments appear first
;; in the output, and references to them are left unmodified. But in this case,
;; no active segments are left in the output to act as the target segment to
;; rename into. So if the renamer detects a reference to an active segment, we
;; add back the first-appearing empty active segment in the input to act as the
;; target, in this case segment $1.
(module
  ;; CHECK:      (type $1 (array (mut i8)))

  ;; CHECK:      (type $0 (func))
  (type $0 (func))
  (type $1 (array (mut i8)))
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $0 "foo")
  (data $0 "foo")
  ;; CHECK:      (data $5 "bar")

  ;; CHECK:      (data $1 (i32.const 64) "")
  (data $1 (i32.const 64) "")
  (data $2 (i32.const 48) "")
  (data $3 (i32.const 32) "")
  (data $4 (i32.const 16) "")
  (data $5 "bar")
  ;; CHECK:      (func $0 (type $0)
  ;; CHECK-NEXT:  (memory.init $5
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (data.drop $0)
  ;; CHECK-NEXT:  (array.init_data $1 $0
  ;; CHECK-NEXT:   (array.new_data $1 $5
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (memory.init $1
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (data.drop $1)
  ;; CHECK-NEXT:  (array.init_data $1 $1
  ;; CHECK-NEXT:   (array.new_data $1 $1
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $0 (type $0)
    (memory.init $5
      (i32.const 0)
      (i32.const 0)
      (i32.const 0)
    )
    (data.drop $0)
    (array.init_data $1 $0
      (array.new_data $1 $5
        (i32.const 0)
        (i32.const 0)
      )
      (i32.const 0)
      (i32.const 0)
      (i32.const 0)
    )
    (memory.init $4
      (i32.const 0)
      (i32.const 0)
      (i32.const 0)
    )
    (data.drop $3)
    (array.init_data $1 $2
      (array.new_data $1 $1
        (i32.const 0)
        (i32.const 0)
      )
      (i32.const 0)
      (i32.const 0)
      (i32.const 0)
    )
  )
)

;; Tests for guaranteed traps. A "trap segment" is an active segment which is
;; statically out-of-bounds and whose initialization will always raise a trap
;; during module instantiation. After a trap segment, all remaining active
;; segments should be dropped. In most of these tests, we use a second memory
;; for the dead segment to distinguish between the trap behavior and the drop
;; behavior, since dropping should not depend on the memory.

;; Passive segments following a trap segment should be retained, and references
;; to dead active segments should be renamed to a live segment.
(module
  ;; CHECK:      (type $0 (func))
  (type $0 (func))
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $2 "bar")

  ;; CHECK:      (data $4 "qux")

  ;; CHECK:      (data $0 (i32.const 0) "foo")
  (data $0 (i32.const 0) "foo")
  ;; CHECK:      (data $1 (i32.const 65536) "trap")
  (data $1 (i32.const 65536) "trap")
  (data $2 "bar")
  (data $3 (i32.const 3) "pez")
  (data $4 "qux")
  ;; CHECK:      (func $0 (type $0)
  ;; CHECK-NEXT:  (data.drop $4)
  ;; CHECK-NEXT:  (data.drop $0)
  ;; CHECK-NEXT: )
  (func $0 (type $0)
    (data.drop $4)
    (data.drop $3)
  )
)

;; Segment $1 ends outside memory $0's max size.
(module
  ;; CHECK:      (memory $0 0 0)
  (memory $0 0 0)
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  (data $0 (i32.const 0) "")
  ;; CHECK:      (data $1 (i32.const 1) "")
  (data $1 (i32.const 1) "")
  (data $2 (memory $1) (i32.const 0) "dead")
)

;; An imported segment's max size must be no greater than its declared max size.
;; Thus, segment $1 must still end outside the imported memory $0's max size.
(module
  ;; CHECK:      (import "" "" (memory $0 0 0))
  (import "" "" (memory $0 0 0))
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  (data $0 (i32.const 0) "")
  ;; CHECK:      (data $1 (i32.const 1) "")
  (data $1 (i32.const 1) "")
  (data $2 (memory $1) (i32.const 0) "dead")
)

;; Segment $1 ends outside memory $0's initial size. Since the memory is not
;; imported, its actual size during initialization is equal to its initial size,
;; so the trap is still guaranteed.
(module
  ;; CHECK:      (memory $0 0)
  (memory $0 0)
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  (data $0 (i32.const 0) "")
  ;; CHECK:      (data $1 (i32.const 1) "")
  (data $1 (i32.const 1) "")
  (data $2 (memory $1) (i32.const 0) "dead")
)

;; Not a guaranteed trap: the initial size of an imported memory may be greater
;; than its initial size. When simulating bounds-check behavior, we use the
;; "known size" of a memory to track how large it must presently be, for all
;; previous initializations to have succeeded.
(module
  ;; CHECK:      (import "" "" (memory $0 0))
  (import "" "" (memory $0 0))
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  (data $0 (i32.const 0) "")
  ;; CHECK:      (data $1 (i32.const 1) "")
  (data $1 (i32.const 1) "")
  ;; CHECK:      (data $2 (memory $1) (i32.const 0) "dead")
  (data $2 (memory $1) (i32.const 0) "dead")
)

;; Two in-bounds segments and an out-of-bounds segment for a small memory.
(module
  ;; CHECK:      (global $0 i32 (i32.const 64))
  (global $0 i32 (i32.const 64))
  ;; CHECK:      (memory $0 4 4 (pagesize 1))
  (memory $0 4 4 (pagesize 1))
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  ;; CHECK:      (data $0 (global.get $0) "foo")
  (data $0 (global.get $0) "foo")
  ;; CHECK:      (data $1 (global.get $0) "baar")
  (data $1 (global.get $0) "baar")
  ;; CHECK:      (data $2 (global.get $0) "peeez")
  (data $2 (global.get $0) "peeez")
  (data $3 (memory $1) (i32.const 0) "dead")
)

;; Merged segment, trap segment, and two dead segments.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $0 (i32.const 65532) "ffoo")
  (data $0 (i32.const 65532) "foo")
  (data $1 (i32.const 65533) "foo")
  ;; CHECK:      (data $2 (i32.const 65534) "foo")
  (data $2 (i32.const 65534) "foo")
  (data $3 (i32.const 65535) "foo")
  (data $4 (i32.const 65536) "foo")
)

;; Test for address overflow. Note that a module may validly contain a 2^64-byte
;; memory and active data segments ending at offset 2^64 exactly, but the pass
;; rejects that particular edge case as a fatal error.
(module
  ;; CHECK:      (import "" "" (memory $0 i64 0))
  (import "" "" (memory $0 i64 0))
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  ;; CHECK:      (data $0 (i64.const 0) "foo")
  (data $0 (i64.const 0) "foo")
  ;; CHECK:      (data $1 (i64.const -4) "bar")
  (data $1 (i64.const -4) "bar")
  ;; CHECK:      (data $2 (i64.const -4) "barpez")
  (data $2 (i64.const -4) "barpez")
  (data $3 (memory $1) (i32.const 0) "dead")
)

;; Tests for bounds checks and flushing. We use a separate memory to distinguish
;; between bounds-check behavior and flushing behavior, since after a potential
;; bounds-check trap, all memories should be flushed at once.

;; Before each point that a bounds-check trap may occur, all merged segments in
;; all memories should be flushed. After a trap, the embedder can observe any
;; prior modifications to imported memories, and all of these modifications
;; should be preserved to avoid differences in behavior. To simplify the logic,
;; we flush all memories, not just imported memories.
(module
  ;; CHECK:      (import "" "" (memory $0 0))
  (import "" "" (memory $0 0))
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  ;; CHECK:      (data $0 (memory $1) (i32.const 0) "pre")
  (data $0 (memory $1) (i32.const 0) "pre")
  ;; CHECK:      (data $1 (i32.const 0) "fooFOO")
  (data $1 (i32.const 0) "foo")
  (data $2 (i32.const 3) "FOO")
  ;; CHECK:      (data $3 (i32.const 65536) "bar")
  (data $3 (i32.const 65536) "bar")
  ;; CHECK:      (data $4 (i32.const 3) "BAR")
  (data $4 (i32.const 3) "BAR")
  ;; CHECK:      (data $5 (i32.const 131072) "pez")
  (data $5 (i32.const 131072) "pez")
  ;; CHECK:      (data $6 (i32.const 3) "PEZ")
  (data $6 (i32.const 3) "PEZ")
  ;; CHECK:      (data $7 (i32.const 196608) "qux")
  (data $7 (i32.const 196608) "qux")
  ;; CHECK:      (data $8 (i32.const 3) "QUX")
  (data $8 (i32.const 3) "QUX")
  ;; CHECK:      (data $9 (memory $1) (i32.const 0) "post")
  (data $9 (memory $1) (i32.const 0) "post")
)

;; The same test, but writing in reverse order. Only segment $1 may trigger a
;; bounds-check trap: all future segments end earlier than $1 does.
(module
  ;; CHECK:      (import "" "" (memory $0 0))
  (import "" "" (memory $0 0))
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  ;; CHECK:      (data $0 (memory $1) (i32.const 0) "pre")
  (data $0 (memory $1) (i32.const 0) "pre")
  ;; CHECK:      (data $1 (i32.const 196608) "qux")
  (data $1 (i32.const 196608) "qux")
  (data $2 (i32.const 3) "QUX")
  ;; CHECK:      (data $7 (i32.const 0) "fooFOO")

  ;; CHECK:      (data $5 (i32.const 65536) "bar")

  ;; CHECK:      (data $3 (i32.const 131072) "pez")
  (data $3 (i32.const 131072) "pez")
  (data $4 (i32.const 3) "PEZ")
  (data $5 (i32.const 65536) "bar")
  (data $6 (i32.const 3) "BAR")
  (data $7 (i32.const 0) "foo")
  (data $8 (i32.const 3) "FOO")
  ;; CHECK:      (data $9 (memory $1) (i32.const 0) "post")
  (data $9 (memory $1) (i32.const 0) "post")
)

;; Segments written in forward and reverse order. Segments $1 to $4 each cause a
;; flush: but after segment $5 causes a flush, segments $5 to $8 may be freely
;; merged.
(module
  ;; CHECK:      (import "" "" (memory $0 0 (pagesize 1)))
  (import "" "" (memory $0 0 (pagesize 1)))
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  ;; CHECK:      (data $0 (memory $1) (i32.const 0) "pre")
  (data $0 (memory $1) (i32.const 0) "pre")
  ;; CHECK:      (data $1 (i32.const 0) "foo")
  (data $1 (i32.const 0) "foo")
  ;; CHECK:      (data $2 (i32.const 1) "bar")
  (data $2 (i32.const 1) "bar")
  ;; CHECK:      (data $3 (i32.const 2) "pez")
  (data $3 (i32.const 2) "pez")
  ;; CHECK:      (data $4 (i32.const 3) "qux")
  (data $4 (i32.const 3) "qux")
  (data $5 (i32.const 19) "QUX")
  (data $6 (i32.const 18) "PEZ")
  (data $7 (i32.const 17) "BAR")
  ;; CHECK:      (data $8 (i32.const 16) "FOORZX")
  (data $8 (i32.const 16) "FOO")
  ;; CHECK:      (data $9 (memory $1) (i32.const 0) "post")
  (data $9 (memory $1) (i32.const 0) "post")
)

;; Bounds-check behavior approaching the offset 2^64-1 boundary.
(module
  ;; CHECK:      (import "" "" (memory $0 i64 0 (pagesize 1)))
  (import "" "" (memory $0 i64 0 (pagesize 1)))
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  ;; CHECK:      (data $0 (memory $1) (i32.const 0) "pre")
  (data $0 (memory $1) (i32.const 0) "pre")
  ;; CHECK:      (data $1 (i64.const -7) "foo")
  (data $1 (i64.const -7) "foo")
  ;; CHECK:      (data $2 (i64.const -6) "bar")
  (data $2 (i64.const -6) "bar")
  ;; CHECK:      (data $3 (i64.const -5) "pez")
  (data $3 (i64.const -5) "pez")
  (data $4 (i64.const -4) "qux")
  ;; CHECK:      (data $5 (i64.const -5) "PEZx")
  (data $5 (i64.const -5) "PEZ")
  ;; CHECK:      (data $6 (memory $1) (i32.const 0) "post")
  (data $6 (memory $1) (i32.const 0) "post")
)

;; After previous segments are flushed, the data in a bounds-check segment need
;; not be flushed immediately: it can be freely merged with and overwritten by
;; later segments. But at the next flush, we must be careful to output this
;; merged segment before any other segments, so that it has the same
;; bounds-check behavior. We track this based on the start address of the last
;; page asserted to exist from a bounds check.
(module
  ;; CHECK:      (import "" "" (memory $0 0 (pagesize 1)))
  (import "" "" (memory $0 0 (pagesize 1)))
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  ;; CHECK:      (data $0 (memory $1) (i32.const 0) "pre")
  (data $0 (memory $1) (i32.const 0) "pre")
  ;; CHECK:      (data $1 (i32.const 0) "fooo")
  (data $1 (i32.const 0) "fooo")
  (data $2 (i32.const 12) "QUUX")
  (data $3 (i32.const 8) "PEEZ")
  (data $4 (i32.const 4) "BAAR")
  ;; CHECK:      (data $5 (i32.const 0) "FOOOBAARPEEZquux")
  (data $5 (i32.const 0) "FOOO")
  (data $6 (i32.const 12) "quux")
  ;; CHECK:      (data $7 (memory $1) (i32.const 0) "post")
  (data $7 (memory $1) (i32.const 0) "post")
)

;; Tests for near-adjacent merge algorithm and zero-fill tracking.

;; Basic near-adjacent merge, in forward and reverse order. It should operate
;; independently on different memories.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  ;; CHECK:      (data $0 (i32.const 0) "foo\00bar\00pez\00qux")
  (data $0 (i32.const 0) "foo")
  (data $1 (memory $1) (i32.const 12) "QUX")
  (data $2 (i32.const 4) "bar")
  (data $3 (memory $1) (i32.const 8) "PEZ")
  (data $4 (i32.const 8) "pez")
  (data $5 (memory $1) (i32.const 4) "BAR")
  (data $6 (i32.const 12) "qux")
  ;; CHECK:      (data $7 (memory $1) (i32.const 0) "FOO\00BAR\00PEZ\00QUX")
  (data $7 (memory $1) (i32.const 0) "FOO")
)

;; Since the memories are imported in this case, we don't know what data lies
;; in the gaps, so a near-adjacent merge is not possible.
(module
  ;; CHECK:      (import "" "" (memory $0 1 1))
  (import "" "" (memory $0 1 1))
  ;; CHECK:      (import "" "" (memory $1 1 1))
  (import "" "" (memory $1 1 1))
  ;; CHECK:      (data $0 (i32.const 0) "foo")
  (data $0 (i32.const 0) "foo")
  ;; CHECK:      (data $2 (i32.const 4) "bar")

  ;; CHECK:      (data $4 (i32.const 8) "pez")

  ;; CHECK:      (data $6 (i32.const 12) "qux")

  ;; CHECK:      (data $7 (memory $1) (i32.const 0) "FOO")

  ;; CHECK:      (data $5 (memory $1) (i32.const 4) "BAR")

  ;; CHECK:      (data $3 (memory $1) (i32.const 8) "PEZ")

  ;; CHECK:      (data $1 (memory $1) (i32.const 12) "QUX")
  (data $1 (memory $1) (i32.const 12) "QUX")
  (data $2 (i32.const 4) "bar")
  (data $3 (memory $1) (i32.const 8) "PEZ")
  (data $4 (i32.const 8) "pez")
  (data $5 (memory $1) (i32.const 4) "BAR")
  (data $6 (i32.const 12) "qux")
  (data $7 (memory $1) (i32.const 0) "FOO")
)

;; Near-adjacent merge, in forward and reverse order, is possible before a
;; nonempty non-constant-offset segment, but not afterward, since we don't know
;; where it may have written its data.
(module
  ;; CHECK:      (global $0 i32 (i32.const 0))
  (global $0 i32 (i32.const 0))
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  ;; CHECK:      (data $0 (i32.const 0) "foo\00bar")
  (data $0 (i32.const 0) "foo")
  (data $1 (memory $1) (i32.const 12) "QUX")
  (data $2 (i32.const 4) "bar")
  ;; CHECK:      (data $3 (memory $1) (i32.const 8) "PEZ\00QUX")
  (data $3 (memory $1) (i32.const 8) "PEZ")
  ;; CHECK:      (data $4 (global.get $0) "\00")
  (data $4 (global.get $0) "\00")
  ;; CHECK:      (data $5 (memory $1) (global.get $0) "\00")
  (data $5 (memory $1) (global.get $0) "\00")
  ;; CHECK:      (data $6 (i32.const 8) "pez")
  (data $6 (i32.const 8) "pez")
  ;; CHECK:      (data $8 (i32.const 12) "qux")

  ;; CHECK:      (data $9 (memory $1) (i32.const 0) "FOO")

  ;; CHECK:      (data $7 (memory $1) (i32.const 4) "BAR")
  (data $7 (memory $1) (i32.const 4) "BAR")
  (data $8 (i32.const 12) "qux")
  (data $9 (memory $1) (i32.const 0) "FOO")
)

;; Tests for near-adjacent merge algorithm and size heuristic.

;; Near-adjacent merge is universally applied for small gaps, acting as an
;; extension of overlapping and adjacent merge. It works in forward and reverse
;; order.
(module
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $0 (i32.const 0) "bar")
  (data $0 (i32.const 0) "foo")
  (data $1 (i32.const 0) "bar")
  (data $2 (i32.const 17) "bar")
  ;; CHECK:      (data $3 (i32.const 16) "foor")
  (data $3 (i32.const 16) "foo")
  ;; CHECK:      (data $4 (i32.const 32) "fobar")
  (data $4 (i32.const 32) "foo")
  (data $5 (i32.const 34) "bar")
  (data $6 (i32.const 51) "bar")
  ;; CHECK:      (data $7 (i32.const 48) "foobar")
  (data $7 (i32.const 48) "foo")
  ;; CHECK:      (data $8 (i32.const 64) "foo\00bar")
  (data $8 (i32.const 64) "foo")
  (data $9 (i32.const 68) "bar")
  (data $10 (i32.const 85) "bar")
  ;; CHECK:      (data $11 (i32.const 80) "foo\00\00bar")
  (data $11 (i32.const 80) "foo")
  ;; CHECK:      (data $12 (i32.const 96) "foo\00\00\00bar")
  (data $12 (i32.const 96) "foo")
  (data $13 (i32.const 102) "bar")
  (data $14 (i32.const 119) "bar")
  ;; CHECK:      (data $15 (i32.const 112) "foo\00\00\00\00bar")
  (data $15 (i32.const 112) "foo")
)

;; For large gaps, the size heuristic depends on the encoded size of the offset.
;; In this case, we influence the merge decision by alternately increasing the
;; gap size and increasing the offset size. (The heuristic similarly depends on
;; the encoded size of the data length, but that is more difficult to test.)
(module
  ;; CHECK:      (memory $0 17 17)
  (memory $0 17 17)
  ;; CHECK:      (data $0 (i32.const 0) "foo\00\00\00\00\00bar")
  (data $0 (i32.const 0) "foo")
  (data $1 (i32.const 8) "bar")
  ;; CHECK:      (data $3 (i32.const 32) "foo")

  ;; CHECK:      (data $2 (i32.const 41) "bar")
  (data $2 (i32.const 41) "bar")
  (data $3 (i32.const 32) "foo")
  ;; CHECK:      (data $4 (i32.const 64) "foo\00\00\00\00\00\00bar")
  (data $4 (i32.const 64) "foo")
  (data $5 (i32.const 73) "bar")
  ;; CHECK:      (data $7 (i32.const 96) "foo")

  ;; CHECK:      (data $6 (i32.const 106) "bar")
  (data $6 (i32.const 106) "bar")
  (data $7 (i32.const 96) "foo")
  ;; CHECK:      (data $8 (i32.const 4096) "foo")
  (data $8 (i32.const 4096) "foo")
  ;; CHECK:      (data $9 (i32.const 4106) "bar")
  (data $9 (i32.const 4106) "bar")
  (data $10 (i32.const 8202) "bar")
  ;; CHECK:      (data $11 (i32.const 8192) "foo\00\00\00\00\00\00\00bar")
  (data $11 (i32.const 8192) "foo")
  ;; CHECK:      (data $12 (i32.const 8224) "foo")
  (data $12 (i32.const 8224) "foo")
  ;; CHECK:      (data $13 (i32.const 8235) "bar")
  (data $13 (i32.const 8235) "bar")
  ;; CHECK:      (data $15 (i32.const 524288) "foo")

  ;; CHECK:      (data $14 (i32.const 524299) "bar")
  (data $14 (i32.const 524299) "bar")
  (data $15 (i32.const 524288) "foo")
  ;; CHECK:      (data $16 (i32.const 1048576) "foo\00\00\00\00\00\00\00\00bar")
  (data $16 (i32.const 1048576) "foo")
  (data $17 (i32.const 1048587) "bar")
  ;; CHECK:      (data $19 (i32.const 1048608) "foo")

  ;; CHECK:      (data $18 (i32.const 1048620) "bar")
  (data $18 (i32.const 1048620) "bar")
  (data $19 (i32.const 1048608) "foo")
)

;; Tests for near-adjacent merge algorithm and flushing. We use empty
;; non-constant-offset segments simply to force a flush.

;; Near-adjacent merge uses data from previously flushed segments to fill gaps.
(module
  ;; CHECK:      (global $0 i32 (i32.const 0))
  (global $0 i32 (i32.const 0))
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $0 (i32.const 4) "bar")
  (data $0 (i32.const 4) "bar")
  ;; CHECK:      (data $1 (global.get $0) "")
  (data $1 (global.get $0) "")
  (data $2 (i32.const 8) "pez")
  ;; CHECK:      (data $3 (i32.const 0) "foo\00bar\00pez")
  (data $3 (i32.const 0) "foo")
)

;; Flushed segment data is combined across repeated flushes.
(module
  ;; CHECK:      (global $0 i32 (i32.const 0))
  (global $0 i32 (i32.const 0))
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $0 (i32.const 6) "B")
  (data $0 (i32.const 6) "B")
  ;; CHECK:      (data $1 (global.get $0) "")
  (data $1 (global.get $0) "")
  ;; CHECK:      (data $2 (i32.const 4) "A")
  (data $2 (i32.const 4) "A")
  ;; CHECK:      (data $3 (global.get $0) "")
  (data $3 (global.get $0) "")
  (data $4 (i32.const 8) "bar")
  ;; CHECK:      (data $5 (i32.const 0) "foo\00A\00B\00bar")
  (data $5 (i32.const 0) "foo")
)

;; In this case, the memory is imported, and the flushed segment data is too
;; short to fill the gap, so near-adjacent merge is not possible.
(module
  ;; CHECK:      (import "" "" (memory $0 1 1))
  (import "" "" (memory $0 1 1))
  ;; CHECK:      (global $0 i32 (i32.const 0))
  (global $0 i32 (i32.const 0))
  ;; CHECK:      (data $0 (i32.const 4) "B")
  (data $0 (i32.const 4) "B")
  ;; CHECK:      (data $1 (global.get $0) "")
  (data $1 (global.get $0) "")
  ;; CHECK:      (data $2 (i32.const 0) "foo")
  (data $2 (i32.const 0) "foo")
  ;; CHECK:      (data $3 (i32.const 6) "pez")
  (data $3 (i32.const 6) "pez")
)

;; In this case, even though the memory is imported, the flushed segment data
;; completely fills the gap, so near-adjacent merge is possible.
(module
  ;; CHECK:      (import "" "" (memory $0 1 1))
  (import "" "" (memory $0 1 1))
  ;; CHECK:      (global $0 i32 (i32.const 0))
  (global $0 i32 (i32.const 0))
  ;; CHECK:      (data $0 (i32.const 3) "bar")
  (data $0 (i32.const 3) "bar")
  ;; CHECK:      (data $1 (global.get $0) "")
  (data $1 (global.get $0) "")
  ;; CHECK:      (data $2 (i32.const 0) "foobarpez")
  (data $2 (i32.const 0) "foo")
  (data $3 (i32.const 6) "pez")
)

;; Additional segments can be merged into a bounds-check segment via
;; near-adjacent merge, and it is still flushed before any other segments.
(module
  ;; CHECK:      (import "" "" (memory $0 1))
  (import "" "" (memory $0 1))
  ;; CHECK:      (global $0 i32 (i32.const 0))
  (global $0 i32 (i32.const 0))
  ;; CHECK:      (data $0 (i32.const 65535) ".")
  (data $0 (i32.const 65535) ".")
  ;; CHECK:      (data $1 (global.get $0) "")
  (data $1 (global.get $0) "")
  (data $2 (i32.const 65536) "pez")
  ;; CHECK:      (data $3 (i32.const 65532) "bar.pez")
  (data $3 (i32.const 65532) "bar")
  ;; CHECK:      (data $4 (i32.const 0) "foo")
  (data $4 (i32.const 0) "foo")
)
