;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; RUN: foreach %s %t wasm-opt -all --merge-data-segments -tnh -S -o - | filecheck %s

;; Guaranteed traps remain guaranteed under TNH. It's nontrivial to "drop
;; absolutely everything" from a module that can never be instantiated, so to
;; simplify the implementation, we just reuse the non-TNH behavior. Thus, these
;; are identical to the non-TNH tests for guaranteed traps. We use a second
;; memory for the dead segment to distinguish between the trap behavior and the
;; drop behavior.

;; Segment $1 ends outside memory $0's max size.
(module
  ;; CHECK:      (memory $0 0 0)
  (memory $0 0 0)
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  (data $0 (i32.const 0) "")
  ;; CHECK:      (data $1 (i32.const 1) "")
  (data $1 (i32.const 1) "")
  (data $2 (memory $1) (i32.const 0) "dead")
)

;; Segment $1 ends outside memory $0's max size.
(module
  ;; CHECK:      (import "" "" (memory $0 0 0))
  (import "" "" (memory $0 0 0))
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  (data $0 (i32.const 0) "")
  ;; CHECK:      (data $1 (i32.const 1) "")
  (data $1 (i32.const 1) "")
  (data $2 (memory $1) (i32.const 0) "dead")
)

;; Segment $1 ends outside memory $0's initial size, and the memory cannot be
;; any larger since it is not imported.
(module
  ;; CHECK:      (memory $0 0)
  (memory $0 0)
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  (data $0 (i32.const 0) "")
  ;; CHECK:      (data $1 (i32.const 1) "")
  (data $1 (i32.const 1) "")
  (data $2 (memory $1) (i32.const 0) "dead")
)

;; Empty non-constant-offset segments are dropped under TNH.
(module
  ;; CHECK:      (global $0 i32 (i32.const 0))
  (global $0 i32 (i32.const 0))
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $0 (i32.const 0) "foobar")
  (data $0 (i32.const 0) "foo")
  (data $1 (global.get $0) "")
  (data $2 (i32.const 3) "bar")
)

;; Nonempty non-constant-offset segments trigger no bounds checks under TNH:
;; segment $1 overwriting memory $1 does not cause memory $0 to be flushed, so
;; the other segments are merged freely.
(module
  ;; CHECK:      (global $0 i32 (i32.const 0))
  (global $0 i32 (i32.const 0))
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  ;; CHECK:      (data $1 (memory $1) (global.get $0) "bar")

  ;; CHECK:      (data $0 (i32.const 0) "foopez")
  (data $0 (i32.const 0) "foo")
  (data $1 (memory $1) (global.get $0) "bar")
  (data $2 (i32.const 3) "pez")
)

;; Nonempty non-constant-offset segments still flush their own memory: segment
;; $1 causes memory $0 to be flushed.
(module
  ;; CHECK:      (global $0 i32 (i32.const 0))
  (global $0 i32 (i32.const 0))
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $0 (i32.const 0) "foo")
  (data $0 (i32.const 0) "foo")
  ;; CHECK:      (data $1 (global.get $0) "bar")
  (data $1 (global.get $0) "bar")
  ;; CHECK:      (data $2 (i32.const 3) "pez")
  (data $2 (i32.const 3) "pez")
)

;; Nonempty non-constant-offset segments still invalidate flushed data: the data
;; in segment $0 cannot be used to merge the near-adjacent segments $2 and $3.
(module
  ;; CHECK:      (global $0 i32 (i32.const 0))
  (global $0 i32 (i32.const 0))
  ;; CHECK:      (memory $0 1 1)
  (memory $0 1 1)
  ;; CHECK:      (data $0 (i32.const 3) "bar")
  (data $0 (i32.const 3) "bar")
  ;; CHECK:      (data $1 (global.get $0) "\00")
  (data $1 (global.get $0) "\00")
  ;; CHECK:      (data $2 (i32.const 0) "foo")
  (data $2 (i32.const 0) "foo")
  ;; CHECK:      (data $3 (i32.const 6) "pez")
  (data $3 (i32.const 6) "pez")
)

;; Bounds checks within memory limits are assumed to succeed under TNH: no
;; flushes occur, and segments are merged freely.
(module
  ;; CHECK:      (import "" "" (memory $0 0))
  (import "" "" (memory $0 0))
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  ;; CHECK:      (data $1 (i32.const 0) "fooQUX")

  ;; CHECK:      (data $3 (i32.const 65536) "bar")

  ;; CHECK:      (data $5 (i32.const 131072) "pez")

  ;; CHECK:      (data $7 (i32.const 196608) "qux")

  ;; CHECK:      (data $0 (memory $1) (i32.const 0) "post")
  (data $0 (memory $1) (i32.const 0) "pre")
  (data $1 (i32.const 0) "foo")
  (data $2 (i32.const 3) "FOO")
  (data $3 (i32.const 65536) "bar")
  (data $4 (i32.const 3) "BAR")
  (data $5 (i32.const 131072) "pez")
  (data $6 (i32.const 3) "PEZ")
  (data $7 (i32.const 196608) "qux")
  (data $8 (i32.const 3) "QUX")
  (data $9 (memory $1) (i32.const 0) "post")
)

;; Since no flushes occur, reordering input segments in the previous test does
;; not change the shape of the final data segments, only their contents.
(module
  ;; CHECK:      (import "" "" (memory $0 0))
  (import "" "" (memory $0 0))
  ;; CHECK:      (memory $1 1 1)
  (memory $1 1 1)
  ;; CHECK:      (data $7 (i32.const 0) "fooFOO")

  ;; CHECK:      (data $5 (i32.const 65536) "bar")

  ;; CHECK:      (data $3 (i32.const 131072) "pez")

  ;; CHECK:      (data $1 (i32.const 196608) "qux")

  ;; CHECK:      (data $0 (memory $1) (i32.const 0) "post")
  (data $0 (memory $1) (i32.const 0) "pre")
  (data $1 (i32.const 196608) "qux")
  (data $2 (i32.const 3) "QUX")
  (data $3 (i32.const 131072) "pez")
  (data $4 (i32.const 3) "PEZ")
  (data $5 (i32.const 65536) "bar")
  (data $6 (i32.const 3) "BAR")
  (data $7 (i32.const 0) "foo")
  (data $8 (i32.const 3) "FOO")
  (data $9 (memory $1) (i32.const 0) "post")
)
