;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --merge-locals --all-features -S -o - | filecheck %s

(module
 ;; CHECK:      (type $0 (func (param i32 i32)))

 ;; CHECK:      (type $1 (func (param i32 i32) (result i32)))

 ;; CHECK:      (type $2 (func (param i32 f32 f32) (result i64)))

 ;; CHECK:      (type $3 (func (param i32 i32 i32)))

 ;; CHECK:      (type $4 (func))

 ;; CHECK:      (global $global$0 (mut i32) (i32.const 10))
 (global $global$0 (mut i32) (i32.const 10))
 ;; CHECK:      (func $test (type $1) (param $x i32) (param $y i32) (result i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (if (result i32)
 ;; CHECK-NEXT:    (local.tee $x
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (i32.const 100)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (else
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $x)
 ;; CHECK-NEXT: )
 (func $test (param $x i32) (param $y i32) (result i32)
  (drop
   (if (result i32)
    (local.tee $x
     (local.get $y)
    )
    (then
     (i32.const 100)
    )
    (else
     (local.get $x)
    )
   )
  )
  (local.get $y) ;; turn this into $x
 )
 ;; CHECK:      (func $test2 (type $1) (param $x i32) (param $y i32) (result i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (if (result i32)
 ;; CHECK-NEXT:    (local.tee $x
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (i32.const 100)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (else
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $x)
 ;; CHECK-NEXT: )
 (func $test2 (param $x i32) (param $y i32) (result i32)
  (drop
   (if (result i32)
    (local.tee $x
     (local.get $y)
    )
    (then
     (i32.const 100)
    )
    (else
     (local.get $x)
    )
   )
  )
  (local.get $x)
 )
 ;; CHECK:      (func $test-multiple (type $1) (param $x i32) (param $y i32) (result i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (if (result i32)
 ;; CHECK-NEXT:    (local.tee $x
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (i32.const 100)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (else
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $x)
 ;; CHECK-NEXT: )
 (func $test-multiple (param $x i32) (param $y i32) (result i32)
  (drop
   (if (result i32)
    (local.tee $x
     (local.get $y)
    )
    (then
     (i32.const 100)
    )
    (else
     (local.get $x)
    )
   )
  )
  (drop (local.get $y)) ;; turn this into $x
  (local.get $y) ;; turn this into $x
 )
 ;; CHECK:      (func $test-just-some (type $1) (param $x i32) (param $y i32) (result i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (if (result i32)
 ;; CHECK-NEXT:    (local.tee $x
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (i32.const 100)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (else
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.set $y
 ;; CHECK-NEXT:   (i32.const 200)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $y)
 ;; CHECK-NEXT: )
 (func $test-just-some (param $x i32) (param $y i32) (result i32)
  (drop
   (if (result i32)
    (local.tee $x
     (local.get $y)
    )
    (then
     (i32.const 100)
    )
    (else
     (local.get $x)
    )
   )
  )
  (drop (local.get $y)) ;; turn this into $x
  (local.set $y (i32.const 200))
  (local.get $y) ;; but not this one!
 )
 ;; CHECK:      (func $test-just-some2 (type $1) (param $x i32) (param $y i32) (result i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (if (result i32)
 ;; CHECK-NEXT:    (local.tee $x
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (i32.const 100)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (else
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (i32.const 300)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (local.set $y
 ;; CHECK-NEXT:     (i32.const 400)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (else
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (i32.const 500)
 ;; CHECK-NEXT: )
 (func $test-just-some2 (param $x i32) (param $y i32) (result i32)
  (drop
   (if (result i32)
    (local.tee $x
     (local.get $y)
    )
    (then
     (i32.const 100)
    )
    (else
     (local.get $x)
    )
   )
  )
  (if
   (i32.const 300)
   (then
    (local.set $y (i32.const 400))
   )
   (else
    (drop (local.get $y)) ;; turn this into $x
   )
  )
  (i32.const 500)
 )
 ;; CHECK:      (func $test-just-some3 (type $1) (param $x i32) (param $y i32) (result i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (if (result i32)
 ;; CHECK-NEXT:    (local.tee $x
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (i32.const 100)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (else
 ;; CHECK-NEXT:     (i32.const 200)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (i32.const 300)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (local.set $y
 ;; CHECK-NEXT:     (i32.const 400)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (else
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $y)
 ;; CHECK-NEXT: )
 (func $test-just-some3 (param $x i32) (param $y i32) (result i32)
  (drop
   (if (result i32)
    (local.tee $x
     (local.get $y)
    )
    (then
     (i32.const 100)
    )
    (else
     (i32.const 200)
    )
   )
  )
  (if
   (i32.const 300)
   (then
    (local.set $y (i32.const 400))
   )
   (else
    (drop (local.get $y)) ;; can turn this into $x, but another exists we can't, so do nothing
   )
  )
  (local.get $y) ;; but not this one!
 )
 ;; CHECK:      (func $silly-self (type $1) (param $x i32) (param $y i32) (result i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (if (result i32)
 ;; CHECK-NEXT:    (local.tee $x
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (i32.const 100)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (else
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $y)
 ;; CHECK-NEXT: )
 (func $silly-self (param $x i32) (param $y i32) (result i32)
  (drop
   (if (result i32)
    (local.tee $x
     (local.get $x)
    )
    (then
     (i32.const 100)
    )
    (else
     (local.get $x)
    )
   )
  )
  (local.get $y) ;; turn this into $x
 )
 ;; CHECK:      (func $silly-multi (type $1) (param $x i32) (param $y i32) (result i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (if (result i32)
 ;; CHECK-NEXT:    (local.tee $x
 ;; CHECK-NEXT:     (local.tee $y
 ;; CHECK-NEXT:      (local.get $x)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (i32.const 100)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (else
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $y)
 ;; CHECK-NEXT: )
 (func $silly-multi (param $x i32) (param $y i32) (result i32)
  (drop
   (if (result i32)
    (local.tee $x
     (local.tee $y
      (local.get $x)
     )
    )
    (then
     (i32.const 100)
    )
    (else
     (local.get $x)
    )
   )
  )
  (local.get $y) ;; turn this into $x
 )
 ;; CHECK:      (func $undo-1 (type $0) (param $var$1 i32) (param $var$2 i32)
 ;; CHECK-NEXT:  (local $var$5 i32)
 ;; CHECK-NEXT:  (local.set $var$2
 ;; CHECK-NEXT:   (local.get $var$1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.set $var$2
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $var$1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $undo-1 (param $var$1 i32) (param $var$2 i32)
  (local $var$5 i32)
  (local.set $var$2 ;; copy 1 to 2
   (local.get $var$1)
  )
  (local.set $var$2 ;; overwrite 2
   (i32.const 1)
  )
  (drop
   (local.get $var$1) ;; can't be changed to $var$2, as it changes
  )
 )
 ;; CHECK:      (func $undo-2 (type $0) (param $var$1 i32) (param $var$2 i32)
 ;; CHECK-NEXT:  (local $var$5 i32)
 ;; CHECK-NEXT:  (local.set $var$2
 ;; CHECK-NEXT:   (local.get $var$1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (local.get $var$1)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (local.set $var$2
 ;; CHECK-NEXT:     (i32.const 1)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $var$1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $undo-2 (param $var$1 i32) (param $var$2 i32)
  (local $var$5 i32)
  (local.set $var$2 ;; copy 1 to 2
   (local.get $var$1)
  )
  (if (local.get $var$1)
   (then
    (local.set $var$2 ;; conditional overwrite 2
     (i32.const 1)
    )
   )
  )
  (drop
   (local.get $var$1) ;; can't be changed to $var$2, as it changes
  )
 )
 ;; CHECK:      (func $reverse (type $0) (param $x i32) (param $y i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (if (result i32)
 ;; CHECK-NEXT:    (local.tee $x
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (i32.const 100)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (else
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (local.set $y
 ;; CHECK-NEXT:     (i32.const 200)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $reverse (param $x i32) (param $y i32)
  (drop
   (if (result i32)
    (local.tee $x
     (local.get $y)
    )
    (then
     (i32.const 100)
    )
    (else
     (local.get $x)
    )
   )
  )
  (drop (local.get $x)) ;; (read lower down first) but the reverse can work!
  (if (i32.const 1)
   (then
    (local.set $y (i32.const 200))
   )
  )
  (drop (local.get $y)) ;; cannot this into $x, since this $y has multiple sources
 )
 ;; CHECK:      (func $reverse-end (type $0) (param $x i32) (param $y i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (if (result i32)
 ;; CHECK-NEXT:    (local.tee $x
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (i32.const 100)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (else
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $reverse-end (param $x i32) (param $y i32)
  (drop
   (if (result i32)
    (local.tee $x
     (local.get $y)
    )
    (then
     (i32.const 100)
    )
    (else
     (local.get $x) ;; don't change to $y, as its lifetime ended. leave it ended
    )
   )
  )
 )
 ;; CHECK:      (func $reverse-lone-end-2 (type $0) (param $x i32) (param $y i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (if (result i32)
 ;; CHECK-NEXT:    (local.tee $x
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (i32.const 100)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (else
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.set $y
 ;; CHECK-NEXT:   (i32.const 200)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $reverse-lone-end-2 (param $x i32) (param $y i32)
  (drop
   (if (result i32)
    (local.tee $x
     (local.get $y)
    )
    (then
     (i32.const 100)
    )
    (else
     (local.get $x) ;; don't change to $y, as its lifetime ended. leave it ended
    )
   )
  )
  (local.set $y (i32.const 200))
  (drop (local.get $y)) ;; cannot this into $x, since this $y has multiple sources
 )
 ;; CHECK:      (func $reverse-undo (type $0) (param $x i32) (param $y i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (if (result i32)
 ;; CHECK-NEXT:    (local.tee $x
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (i32.const 100)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (else
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.set $x
 ;; CHECK-NEXT:   (i32.const 300)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (local.set $y
 ;; CHECK-NEXT:     (i32.const 200)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $reverse-undo (param $x i32) (param $y i32)
  (drop
   (if (result i32)
    (local.tee $x
     (local.get $y)
    )
    (then
     (i32.const 100)
    )
    (else
     (local.get $x) ;; can optimize this ($y lives on)
    )
   )
  )
  (local.set $x (i32.const 300)) ;; force an undo
  (drop (local.get $x)) ;; (read lower down first) but the reverse can almost work
  (if (i32.const 1)
   (then
    (local.set $y (i32.const 200))
   )
  )
  (drop (local.get $y)) ;; cannot this into $x, since this $y has multiple sources
 )
 ;; CHECK:      (func $reverse-undo2 (type $0) (param $x i32) (param $y i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (if (result i32)
 ;; CHECK-NEXT:    (local.tee $x
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (i32.const 100)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (else
 ;; CHECK-NEXT:     (i32.const 150)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.set $x
 ;; CHECK-NEXT:   (i32.const 300)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (local.set $y
 ;; CHECK-NEXT:     (i32.const 200)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $reverse-undo2 (param $x i32) (param $y i32)
  (drop
   (if (result i32)
    (local.tee $x
     (local.get $y)
    )
    (then
     (i32.const 100)
    )
    (else
     (i32.const 150)
    )
   )
  )
  (local.set $x (i32.const 300)) ;; force an undo
  (drop (local.get $x)) ;; (read lower down first) but the reverse can almost work
  (if (i32.const 1)
   (then
    (local.set $y (i32.const 200))
   )
  )
  (drop (local.get $y)) ;; cannot this into $x, since this $y has multiple sources
 )
 ;; CHECK:      (func $reverse-undo3-conditional (type $0) (param $x i32) (param $y i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (if (result i32)
 ;; CHECK-NEXT:    (local.tee $x
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (i32.const 100)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (else
 ;; CHECK-NEXT:     (i32.const 150)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (local.set $x
 ;; CHECK-NEXT:     (i32.const 300)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (local.set $y
 ;; CHECK-NEXT:     (i32.const 200)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $reverse-undo3-conditional (param $x i32) (param $y i32)
  (drop
   (if (result i32)
    (local.tee $x
     (local.get $y)
    )
    (then
     (i32.const 100)
    )
    (else
     (i32.const 150)
    )
   )
  )
  (if (i32.const 1)
   (then
    (local.set $x (i32.const 300)) ;; force an undo
   )
  )
  (drop (local.get $x)) ;; (read lower down first) but the reverse can almost work
  (if (i32.const 1)
   (then
    (local.set $y (i32.const 200))
   )
  )
  (drop (local.get $y)) ;; cannot this into $x, since this $y has multiple sources
 )
 ;; CHECK:      (func $reverse-undo3-conditional-b (type $0) (param $x i32) (param $y i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (if (result i32)
 ;; CHECK-NEXT:    (local.tee $x
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (i32.const 100)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (else
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (local.set $x
 ;; CHECK-NEXT:     (i32.const 300)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (local.set $y
 ;; CHECK-NEXT:     (i32.const 200)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $reverse-undo3-conditional-b (param $x i32) (param $y i32)
  (drop
   (if (result i32)
    (local.tee $x
     (local.get $y)
    )
    (then
     (i32.const 100)
    )
    (else
     (local.get $x)
    )
   )
  )
  (if (i32.const 1)
   (then
    (local.set $x (i32.const 300)) ;; force an undo
   )
  )
  (drop (local.get $x)) ;; (read lower down first) but the reverse can almost work
  (if (i32.const 1)
   (then
    (local.set $y (i32.const 200))
   )
  )
  (drop (local.get $y)) ;; cannot this into $x, since this $y has multiple sources
 )
 ;; CHECK:      (func $reverse-undo3-conditional-c (type $0) (param $x i32) (param $y i32)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (if (result i32)
 ;; CHECK-NEXT:    (local.tee $x
 ;; CHECK-NEXT:     (local.get $y)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (i32.const 100)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (else
 ;; CHECK-NEXT:     (i32.const 150)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (else
 ;; CHECK-NEXT:    (if
 ;; CHECK-NEXT:     (i32.const 1)
 ;; CHECK-NEXT:     (then
 ;; CHECK-NEXT:      (local.set $x
 ;; CHECK-NEXT:       (i32.const 300)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (local.get $x)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (local.set $y
 ;; CHECK-NEXT:     (i32.const 200)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $reverse-undo3-conditional-c (param $x i32) (param $y i32)
  (drop
   (if (result i32)
    (local.tee $x
     (local.get $y)
    )
    (then
     (i32.const 100)
    )
    (else
     (i32.const 150)
    )
   )
  )
  (if (i32.const 1)
   (then
    (drop (local.get $x))
   )
   (else
    (block
     (if (i32.const 1)
      (then
       (local.set $x (i32.const 300)) ;; force an undo
      )
     )
     (drop (local.get $x)) ;; (read lower down first) but the reverse can almost work
    )
   )
  )
  (if (i32.const 1)
   (then
    (local.set $y (i32.const 200))
   )
  )
  (drop (local.get $y)) ;; cannot this into $x, since this $y has multiple sources
 )
 ;; CHECK:      (func $fuzz (type $2) (param $var$0 i32) (param $var$1 f32) (param $var$2 f32) (result i64)
 ;; CHECK-NEXT:  (local $var$3 i32)
 ;; CHECK-NEXT:  (global.set $global$0
 ;; CHECK-NEXT:   (i32.sub
 ;; CHECK-NEXT:    (global.get $global$0)
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $label$1 (result i64)
 ;; CHECK-NEXT:   (global.set $global$0
 ;; CHECK-NEXT:    (i32.sub
 ;; CHECK-NEXT:     (global.get $global$0)
 ;; CHECK-NEXT:     (i32.const 1)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $label$1
 ;; CHECK-NEXT:    (block $label$2 (result i32)
 ;; CHECK-NEXT:     (drop
 ;; CHECK-NEXT:      (if (result i32)
 ;; CHECK-NEXT:       (block $label$3 (result i32)
 ;; CHECK-NEXT:        (global.set $global$0
 ;; CHECK-NEXT:         (i32.sub
 ;; CHECK-NEXT:          (global.get $global$0)
 ;; CHECK-NEXT:          (i32.const 3)
 ;; CHECK-NEXT:         )
 ;; CHECK-NEXT:        )
 ;; CHECK-NEXT:        (local.set $var$3
 ;; CHECK-NEXT:         (i32.const 1)
 ;; CHECK-NEXT:        )
 ;; CHECK-NEXT:        (local.tee $var$3
 ;; CHECK-NEXT:         (local.get $var$0)
 ;; CHECK-NEXT:        )
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:       (then
 ;; CHECK-NEXT:        (i32.const 0)
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:       (else
 ;; CHECK-NEXT:        (local.set $var$3
 ;; CHECK-NEXT:         (if (result i32)
 ;; CHECK-NEXT:          (i32.const 0)
 ;; CHECK-NEXT:          (then
 ;; CHECK-NEXT:           (block $label$7
 ;; CHECK-NEXT:            (block $label$8
 ;; CHECK-NEXT:             (local.set $var$0
 ;; CHECK-NEXT:              (i32.const 34738786)
 ;; CHECK-NEXT:             )
 ;; CHECK-NEXT:            )
 ;; CHECK-NEXT:           )
 ;; CHECK-NEXT:           (local.get $var$3)
 ;; CHECK-NEXT:          )
 ;; CHECK-NEXT:          (else
 ;; CHECK-NEXT:           (if
 ;; CHECK-NEXT:            (i32.eqz
 ;; CHECK-NEXT:             (global.get $global$0)
 ;; CHECK-NEXT:            )
 ;; CHECK-NEXT:            (then
 ;; CHECK-NEXT:             (return
 ;; CHECK-NEXT:              (i64.const 137438953472)
 ;; CHECK-NEXT:             )
 ;; CHECK-NEXT:            )
 ;; CHECK-NEXT:           )
 ;; CHECK-NEXT:           (global.set $global$0
 ;; CHECK-NEXT:            (i32.sub
 ;; CHECK-NEXT:             (global.get $global$0)
 ;; CHECK-NEXT:             (i32.const 1)
 ;; CHECK-NEXT:            )
 ;; CHECK-NEXT:           )
 ;; CHECK-NEXT:           (br_if $label$1
 ;; CHECK-NEXT:            (i32.eqz
 ;; CHECK-NEXT:             (local.get $var$3)
 ;; CHECK-NEXT:            )
 ;; CHECK-NEXT:           )
 ;; CHECK-NEXT:           (return
 ;; CHECK-NEXT:            (i64.const 44125)
 ;; CHECK-NEXT:           )
 ;; CHECK-NEXT:          )
 ;; CHECK-NEXT:         )
 ;; CHECK-NEXT:        )
 ;; CHECK-NEXT:        (i32.const -129)
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (i64.const -36028797018963968)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $fuzz (param $var$0 i32) (param $var$1 f32) (param $var$2 f32) (result i64)
  (local $var$3 i32)
  (global.set $global$0
   (i32.sub
    (global.get $global$0)
    (i32.const 1)
   )
  )
  (loop $label$1 (result i64)
   (global.set $global$0
    (i32.sub
     (global.get $global$0)
     (i32.const 1)
    )
   )
   (br_if $label$1
    (block $label$2 (result i32)
     (drop
      (if (result i32)
       (block $label$3 (result i32)
        (global.set $global$0
         (i32.sub
          (global.get $global$0)
          (i32.const 3)
         )
        )
        (local.set $var$3
         (i32.const 1)
        )
        (local.tee $var$3
         (local.get $var$0)
        )
       )
       (then
        (i32.const 0)
       )
       (else
        (block (result i32)
         (local.set $var$3
          (if (result i32)
           (i32.const 0)
           (then
            (block (result i32)
             (block $label$7
              (block $label$8
               (local.set $var$0
                (i32.const 34738786)
               )
              )
             )
             (local.get $var$3)
            )
           )
           (else
            (block (result i32)
             (if
              (i32.eqz
               (global.get $global$0)
              )
              (then
               (return
                (i64.const 137438953472)
               )
              )
             )
             (global.set $global$0
              (i32.sub
               (global.get $global$0)
               (i32.const 1)
              )
             )
             (br_if $label$1
              (i32.eqz
               (local.get $var$3)
              )
             )
             (return
              (i64.const 44125)
             )
            )
           )
          )
         )
         (i32.const -129)
        )
       )
      )
     )
     (i32.const 0)
    )
   )
   (i64.const -36028797018963968)
  )
 )
 ;; CHECK:      (func $trivial-confusion (type $3) (param $unused i32) (param $param i32) (param $result i32)
 ;; CHECK-NEXT:  (loop $label$1
 ;; CHECK-NEXT:   (if
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (drop
 ;; CHECK-NEXT:      (local.get $result)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (local.set $result
 ;; CHECK-NEXT:    (local.get $param)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $label$1
 ;; CHECK-NEXT:    (local.tee $unused
 ;; CHECK-NEXT:     (local.get $param)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $trivial-confusion (param $unused i32) (param $param i32) (param $result i32)
  (loop $label$1
   (if
    (i32.const 1)
    (then
     (drop
      (local.get $result)
     )
    )
   )
   (local.set $result ;; vanishes
    (local.get $param)
   )
   (br_if $label$1
    (local.tee $unused ;; unused, but forms part of a copy, with $result - the trivial tee we add here should not confuse us
     (local.get $result) ;; flips
    )
   )
  )
 )
 ;; CHECK:      (func $subtype-test (type $4)
 ;; CHECK-NEXT:  (local $0 anyref)
 ;; CHECK-NEXT:  (local $1 i31ref)
 ;; CHECK-NEXT:  (local $2 i31ref)
 ;; CHECK-NEXT:  (local.set $0
 ;; CHECK-NEXT:   (local.get $1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.set $2
 ;; CHECK-NEXT:   (local.get $1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $subtype-test
  (local $0 anyref)
  (local $1 (ref null i31))
  (local $2 (ref null i31))
  (local.set $0
   (local.get $1)
  )
  (local.set $2
    ;; This should NOT become $0, because types of $0 and $1 are different
   (local.get $1)
  )
 )
)
