;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --nominal --monomorphize-always --gufa -all -S -o - | filecheck %s

;; Monomorphize will generate a version of the function $foo that calls a null
;; type. Gufa should not crash on that. (We must run both passes in sequence, as
;; either text or binary parsing will turn a call_ref of null into an
;; unreachable, which would avoid the issue.) 

(module
 (type $ret-i32 (func_subtype (result i32) func))

 (func $call_reffer (param $0 (ref null $ret-i32)) (result i32)
  (call_ref $ret-i32
   (local.get $0)
  )
 )

 (func $main (type $ret-i32) (result i32)
  (call $call_reffer
   (ref.null nofunc)
  )
 )
)
