;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --nm -S -o - | filecheck %s

(module
  (memory 0)
  ;; CHECK:      (type $0 (func))
  (type $0 (func))
  ;; CHECK:      (memory $0 0)

  ;; CHECK:      (func $a
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $a (type $0)
    (nop)
  )
  ;; CHECK:      (func $b
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (loop $loop-in1 (result i32)
  ;; CHECK-NEXT:    (nop)
  ;; CHECK-NEXT:    (i32.const 1000)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $b (type $0)
    (drop
      (loop $loop-in1 (result i32)
        (nop)
        (i32.const 1000)
      )
    )
  )
  ;; CHECK:      (func $c
  ;; CHECK-NEXT:  (block $top
  ;; CHECK-NEXT:   (nop)
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 1000)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.add
  ;; CHECK-NEXT:     (i32.add
  ;; CHECK-NEXT:      (i32.const 1001)
  ;; CHECK-NEXT:      (i32.const 1002)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (i32.add
  ;; CHECK-NEXT:      (i32.const 1003)
  ;; CHECK-NEXT:      (i32.const 1004)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (br $top)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $c (type $0)
    (block $top
      (nop)
      (drop
        (i32.const 1000)
      )
      (drop
        (i32.add
          (i32.add
            (i32.const 1001)
            (i32.const 1002)
          )
          (i32.add
            (i32.const 1003)
            (i32.const 1004)
          )
        )
      )
      (br $top)
    )
  )
)
