;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt %s --optimize-instructions -S -o -                  | filecheck %s --check-prefix=DEFAULT
;; RUN: wasm-opt %s --shrink-level=1 --optimize-instructions -S -o - | filecheck %s --check-prefix=SHRINK

;; Test the LSB→ctz fold: under shrink modes (-Os, -Oz, equivalent to
;; --shrink-level >= 1) `(if (i32.and X 1) T E)` becomes
;; `(if (i32.ctz X) E T)`, and `(br_if N V (i32.eqz (i32.and X 1)))`
;; becomes `(br_if N V (i32.ctz X))` — one instruction less, but
;; potentially 1-2 cycles slower on JIT VMs and unconditionally slower
;; on JIT-less interpreters. The fold is therefore suppressed under
;; default and speed-optimised modes, and only fires when the user has
;; opted into shrinking. See WebAssembly/binaryen#8562.

(module
  ;; DEFAULT:      (func $lsb-if (param $x i32) (result i32)
  ;; DEFAULT-NEXT:  (if (result i32)
  ;; DEFAULT-NEXT:   (i32.and
  ;; DEFAULT-NEXT:    (local.get $x)
  ;; DEFAULT-NEXT:    (i32.const 1)
  ;; DEFAULT-NEXT:   )
  ;; DEFAULT-NEXT:   (then
  ;; DEFAULT-NEXT:    (i32.const 1)
  ;; DEFAULT-NEXT:   )
  ;; DEFAULT-NEXT:   (else
  ;; DEFAULT-NEXT:    (i32.const 0)
  ;; DEFAULT-NEXT:   )
  ;; DEFAULT-NEXT:  )
  ;; DEFAULT-NEXT: )
  ;; SHRINK:      (func $lsb-if (param $x i32) (result i32)
  ;; SHRINK-NEXT:  (if (result i32)
  ;; SHRINK-NEXT:   (i32.ctz
  ;; SHRINK-NEXT:    (local.get $x)
  ;; SHRINK-NEXT:   )
  ;; SHRINK-NEXT:   (then
  ;; SHRINK-NEXT:    (i32.const 0)
  ;; SHRINK-NEXT:   )
  ;; SHRINK-NEXT:   (else
  ;; SHRINK-NEXT:    (i32.const 1)
  ;; SHRINK-NEXT:   )
  ;; SHRINK-NEXT:  )
  ;; SHRINK-NEXT: )
  (func $lsb-if (param $x i32) (result i32)
    ;; if LSB is set, return 1; else return 0
    (if (result i32)
      (i32.and (local.get $x) (i32.const 1))
      (then (i32.const 1))
      (else (i32.const 0))
    )
  )

  ;; DEFAULT:      (func $lsb-if-const-left (param $x i32) (result i32)
  ;; DEFAULT-NEXT:  (if (result i32)
  ;; DEFAULT-NEXT:   (i32.and
  ;; DEFAULT-NEXT:    (local.get $x)
  ;; DEFAULT-NEXT:    (i32.const 1)
  ;; DEFAULT-NEXT:   )
  ;; DEFAULT-NEXT:   (then
  ;; DEFAULT-NEXT:    (i32.const 1)
  ;; DEFAULT-NEXT:   )
  ;; DEFAULT-NEXT:   (else
  ;; DEFAULT-NEXT:    (i32.const 0)
  ;; DEFAULT-NEXT:   )
  ;; DEFAULT-NEXT:  )
  ;; DEFAULT-NEXT: )
  ;; SHRINK:      (func $lsb-if-const-left (param $x i32) (result i32)
  ;; SHRINK-NEXT:  (if (result i32)
  ;; SHRINK-NEXT:   (i32.ctz
  ;; SHRINK-NEXT:    (local.get $x)
  ;; SHRINK-NEXT:   )
  ;; SHRINK-NEXT:   (then
  ;; SHRINK-NEXT:    (i32.const 0)
  ;; SHRINK-NEXT:   )
  ;; SHRINK-NEXT:   (else
  ;; SHRINK-NEXT:    (i32.const 1)
  ;; SHRINK-NEXT:   )
  ;; SHRINK-NEXT:  )
  ;; SHRINK-NEXT: )
  (func $lsb-if-const-left (param $x i32) (result i32)
    ;; same but constant on the left
    (if (result i32)
      (i32.and (i32.const 1) (local.get $x))
      (then (i32.const 1))
      (else (i32.const 0))
    )
  )

  ;; DEFAULT:      (func $lsb-brif (param $x i32) (result i32)
  ;; DEFAULT-NEXT:  (block $done (result i32)
  ;; DEFAULT-NEXT:   (drop
  ;; DEFAULT-NEXT:    (br_if $done
  ;; DEFAULT-NEXT:     (i32.const 99)
  ;; DEFAULT-NEXT:     (i32.eqz
  ;; DEFAULT-NEXT:      (i32.and
  ;; DEFAULT-NEXT:       (local.get $x)
  ;; DEFAULT-NEXT:       (i32.const 1)
  ;; DEFAULT-NEXT:      )
  ;; DEFAULT-NEXT:     )
  ;; DEFAULT-NEXT:    )
  ;; DEFAULT-NEXT:   )
  ;; DEFAULT-NEXT:   (i32.const 42)
  ;; DEFAULT-NEXT:  )
  ;; DEFAULT-NEXT: )
  ;; SHRINK:      (func $lsb-brif (param $x i32) (result i32)
  ;; SHRINK-NEXT:  (block $done (result i32)
  ;; SHRINK-NEXT:   (drop
  ;; SHRINK-NEXT:    (br_if $done
  ;; SHRINK-NEXT:     (i32.const 99)
  ;; SHRINK-NEXT:     (i32.ctz
  ;; SHRINK-NEXT:      (local.get $x)
  ;; SHRINK-NEXT:     )
  ;; SHRINK-NEXT:    )
  ;; SHRINK-NEXT:   )
  ;; SHRINK-NEXT:   (i32.const 42)
  ;; SHRINK-NEXT:  )
  ;; SHRINK-NEXT: )
  (func $lsb-brif (param $x i32) (result i32)
    ;; br_if (eqz (and X 1)) — the typical is_skewed/is_scalar pattern
    (block $done (result i32)
      (drop
        (br_if $done
          (i32.const 99)
          (i32.eqz (i32.and (local.get $x) (i32.const 1)))
        )
      )
      (i32.const 42)
    )
  )

  ;; DEFAULT:      (func $lsb-select (param $x i32) (param $a i32) (param $b i32) (result i32)
  ;; DEFAULT-NEXT:  (select
  ;; DEFAULT-NEXT:   (local.get $b)
  ;; DEFAULT-NEXT:   (local.get $a)
  ;; DEFAULT-NEXT:   (i32.and
  ;; DEFAULT-NEXT:    (local.get $x)
  ;; DEFAULT-NEXT:    (i32.const 1)
  ;; DEFAULT-NEXT:   )
  ;; DEFAULT-NEXT:  )
  ;; DEFAULT-NEXT: )
  ;; SHRINK:      (func $lsb-select (param $x i32) (param $a i32) (param $b i32) (result i32)
  ;; SHRINK-NEXT:  (select
  ;; SHRINK-NEXT:   (local.get $a)
  ;; SHRINK-NEXT:   (local.get $b)
  ;; SHRINK-NEXT:   (i32.ctz
  ;; SHRINK-NEXT:    (local.get $x)
  ;; SHRINK-NEXT:   )
  ;; SHRINK-NEXT:  )
  ;; SHRINK-NEXT: )
  (func $lsb-select (param $x i32) (param $a i32) (param $b i32) (result i32)
    ;; select with the eqz-and-1 boolean condition.
    ;; Non-constant arms keep the select itself in the IR — otherwise
    ;; an unrelated `select c1 c0 P` simplification would eat it.
    (select
      (local.get $a)
      (local.get $b)
      (i32.eqz (i32.and (local.get $x) (i32.const 1)))
    )
  )

  ;; DEFAULT:      (func $lsb-select-const-left (param $x i32) (param $a i32) (param $b i32) (result i32)
  ;; DEFAULT-NEXT:  (select
  ;; DEFAULT-NEXT:   (local.get $b)
  ;; DEFAULT-NEXT:   (local.get $a)
  ;; DEFAULT-NEXT:   (i32.and
  ;; DEFAULT-NEXT:    (local.get $x)
  ;; DEFAULT-NEXT:    (i32.const 1)
  ;; DEFAULT-NEXT:   )
  ;; DEFAULT-NEXT:  )
  ;; DEFAULT-NEXT: )
  ;; SHRINK:      (func $lsb-select-const-left (param $x i32) (param $a i32) (param $b i32) (result i32)
  ;; SHRINK-NEXT:  (select
  ;; SHRINK-NEXT:   (local.get $a)
  ;; SHRINK-NEXT:   (local.get $b)
  ;; SHRINK-NEXT:   (i32.ctz
  ;; SHRINK-NEXT:    (local.get $x)
  ;; SHRINK-NEXT:   )
  ;; SHRINK-NEXT:  )
  ;; SHRINK-NEXT: )
  (func $lsb-select-const-left (param $x i32) (param $a i32) (param $b i32) (result i32)
    ;; same but with the constant on the left of the AND.
    (select
      (local.get $a)
      (local.get $b)
      (i32.eqz (i32.and (i32.const 1) (local.get $x)))
    )
  )
)
