;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt --generate-global-effects --optimize-instructions -all -S -o - %s | filecheck %s

(module
  ;; CHECK:      (type $struct (shared (struct (field (mut i32)))))
  (type $struct (shared (struct (field (mut i32)))))

  ;; CHECK:      (global $g i31ref (ref.i31
  ;; CHECK-NEXT:  (i32.const 0)
  ;; CHECK-NEXT: ))

  ;; CHECK:      (memory $mem 1 1 shared)
  (memory $mem 1 1 shared)

  (global $g i31ref (ref.i31 (i32.const 0)))

  ;; CHECK:      (@binaryen.idempotent)
  ;; CHECK-NEXT: (func $acquire-mem (type $1) (param $0 i32) (result eqref)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.atomic.load acqrel
  ;; CHECK-NEXT:    (local.get $0)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.get $g)
  ;; CHECK-NEXT: )
  (@binaryen.idempotent)
  (func $acquire-mem (param i32) (result eqref)
    (drop
      (i32.atomic.load acqrel (local.get 0))
    )
    (global.get $g)
  )

  ;; CHECK:      (@binaryen.idempotent)
  ;; CHECK-NEXT: (func $release-mem (type $1) (param $0 i32) (result eqref)
  ;; CHECK-NEXT:  (i32.atomic.store acqrel
  ;; CHECK-NEXT:   (local.get $0)
  ;; CHECK-NEXT:   (local.get $0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (global.get $g)
  ;; CHECK-NEXT: )
  (@binaryen.idempotent)
  (func $release-mem (param i32) (result eqref)
    (i32.atomic.store acqrel (local.get 0) (local.get 0))
    (global.get $g)
  )

  ;; CHECK:      (func $fold (type $2) (param $s (ref $struct)) (result i32)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (call $release-mem
  ;; CHECK-NEXT:    (struct.get $struct 0
  ;; CHECK-NEXT:     (local.get $s)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (i32.const 1)
  ;; CHECK-NEXT: )
  (func $fold (param $s (ref $struct)) (result i32)
    ;; The value loaded by the second struct.get cannot be forced to be
    ;; different by the release operation done by the first call, so we can
    ;; assume the same value is passed to both calls. That lets us fold them
    ;; because they are marked idempotent.
    (ref.eq
      (call $release-mem (struct.get $struct 0 (local.get $s)))
      (call $release-mem (struct.get $struct 0 (local.get $s)))
    )
  )

  ;; CHECK:      (func $no-fold (type $2) (param $s (ref $struct)) (result i32)
  ;; CHECK-NEXT:  (ref.eq
  ;; CHECK-NEXT:   (call $acquire-mem
  ;; CHECK-NEXT:    (struct.get $struct 0
  ;; CHECK-NEXT:     (local.get $s)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (call $acquire-mem
  ;; CHECK-NEXT:    (struct.get $struct 0
  ;; CHECK-NEXT:     (local.get $s)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $no-fold (param $s (ref $struct)) (result i32)
    ;; The second struct.get might see a different value because of
    ;; synchronization established by the first call, so the calls might receive
    ;; different arguments and therefore cannot be folded even though the callee
    ;; is marked idempotent.
    (ref.eq
      (call $acquire-mem (struct.get $struct 0 (local.get $s)))
      (call $acquire-mem (struct.get $struct 0 (local.get $s)))
    )
  )
)
