;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.

;; RUN: wasm-opt %s --remove-unused-names --precompute-propagate --fuzz-exec -all -S -o - \
;; RUN:   | filecheck %s

(module
 ;; CHECK:      (func $loop (type $0)
 ;; CHECK-NEXT:  (local $temp i32)
 ;; CHECK-NEXT:  (local.set $temp
 ;; CHECK-NEXT:   (i32.const 10)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $loop
  (local $temp i32)
  ;; We should not try to precompute this loop. If we attempted to replace it
  ;; with its children, we'd need to handle them properly, which we do not do in
  ;; this pass.
  (loop
   (local.set $temp
    (i32.const 10)
   )
  )
 )
)
