;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.

;; RUN: wasm-opt %s --range-analysis -all -S -o - | filecheck %s

;; Also run after optimize-instructions, which canonicalizes the order of
;; things like binary children. We want to see that this pass optimizes the
;; IR that optimize-instructions emits.

;; RUN: wasm-opt %s --optimize-instructions --range-analysis -all -S -o - | filecheck %s --check-prefix=OPTIN

(module
  ;; CHECK:      (func $simple (type $1)
  ;; CHECK-NEXT:  (local $x i32)
  ;; CHECK-NEXT:  (local.set $x
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; OPTIN:      (func $simple (type $1)
  ;; OPTIN-NEXT:  (local $x i32)
  ;; OPTIN-NEXT:  (local.set $x
  ;; OPTIN-NEXT:   (i32.const 10)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.const 1)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.const 0)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.const 0)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.const 1)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT: )
  (func $simple
    (local $x i32)
    ;; Set x to 10, and then compare it to 10 and 20 using == and !=, all in a
    ;; single basic block.
    (local.set $x
      (i32.const 10)
    )
    (drop
      (i32.eq
        (local.get $x)
        (i32.const 10)
      )
    )
    (drop
      (i32.eq
        (local.get $x)
        (i32.const 20)
      )
    )
    (drop
      (i32.ne
        (local.get $x)
        (i32.const 10)
      )
    )
    (drop
      (i32.ne
        (local.get $x)
        (i32.const 20)
      )
    )
  )

  ;; CHECK:      (func $multi-local (type $1)
  ;; CHECK-NEXT:  (local $x i32)
  ;; CHECK-NEXT:  (local $y i32)
  ;; CHECK-NEXT:  (local.set $x
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (local.set $y
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (local.set $x
  ;; CHECK-NEXT:   (i32.const 15)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; OPTIN:      (func $multi-local (type $1)
  ;; OPTIN-NEXT:  (local $x i32)
  ;; OPTIN-NEXT:  (local $y i32)
  ;; OPTIN-NEXT:  (local.set $x
  ;; OPTIN-NEXT:   (i32.const 10)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (local.set $y
  ;; OPTIN-NEXT:   (i32.const 20)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.const 1)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.const 1)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (local.set $x
  ;; OPTIN-NEXT:   (i32.const 15)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.const 0)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.const 1)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.const 1)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT: )
  (func $multi-local
    (local $x i32)
    (local $y i32)
    ;; x is 10, y is 20
    (local.set $x
      (i32.const 10)
    )
    (local.set $y
      (i32.const 20)
    )
    ;; Verify those values.
    (drop
      (i32.eq
        (local.get $x)
        (i32.const 10)
      )
    )
    (drop
      (i32.eq
        (local.get $y)
        (i32.const 20)
      )
    )
    ;; Overwrite x to 15.
    (local.set $x
      (i32.const 15)
    )
    (drop
      (i32.eq
        (local.get $x)
        (i32.const 10)
      )
    )
    (drop
      (i32.eq
        (local.get $x)
        (i32.const 15)
      )
    )
    ;; y is unchanged.
    (drop
      (i32.eq
        (local.get $y)
        (i32.const 20)
      )
    )
  )

  ;; CHECK:      (func $multi-block (type $0) (param $param i32)
  ;; CHECK-NEXT:  (local $x i32)
  ;; CHECK-NEXT:  (local.set $x
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (local.get $param)
  ;; CHECK-NEXT:   (then
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (i32.const 1)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (else
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (i32.const 0)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; OPTIN:      (func $multi-block (type $0) (param $param i32)
  ;; OPTIN-NEXT:  (local $x i32)
  ;; OPTIN-NEXT:  (local.set $x
  ;; OPTIN-NEXT:   (i32.const 10)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (if (result i32)
  ;; OPTIN-NEXT:    (local.get $param)
  ;; OPTIN-NEXT:    (then
  ;; OPTIN-NEXT:     (i32.const 1)
  ;; OPTIN-NEXT:    )
  ;; OPTIN-NEXT:    (else
  ;; OPTIN-NEXT:     (i32.const 0)
  ;; OPTIN-NEXT:    )
  ;; OPTIN-NEXT:   )
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.const 1)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT: )
  (func $multi-block (param $param i32)
    (local $x i32)
    (local.set $x
      (i32.const 10)
    )
    ;; We can infer into these basic blocks.
    (if
      (local.get $param)
      (then
        (drop
          (i32.eq
            (local.get $x)
            (i32.const 10)
          )
        )
      )
      (else
        (drop
          (i32.ne           ;; also test a not-equals here; result is 0
            (local.get $x)
            (i32.const 10)
          )
        )
      )
    )
    ;; We can infer after the merge.
    (drop
      (i32.eq
        (local.get $x)
        (i32.const 10)
      )
    )
  )

  ;; CHECK:      (func $multi-block-split (type $0) (param $param i32)
  ;; CHECK-NEXT:  (local $x i32)
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (local.get $param)
  ;; CHECK-NEXT:   (then
  ;; CHECK-NEXT:    (local.set $x
  ;; CHECK-NEXT:     (i32.const 10)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (else
  ;; CHECK-NEXT:    (local.set $x
  ;; CHECK-NEXT:     (i32.const 20)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.eq
  ;; CHECK-NEXT:    (local.get $x)
  ;; CHECK-NEXT:    (i32.const 10)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.eq
  ;; CHECK-NEXT:    (local.get $x)
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; OPTIN:      (func $multi-block-split (type $0) (param $param i32)
  ;; OPTIN-NEXT:  (local $x i32)
  ;; OPTIN-NEXT:  (local.set $x
  ;; OPTIN-NEXT:   (if (result i32)
  ;; OPTIN-NEXT:    (local.get $param)
  ;; OPTIN-NEXT:    (then
  ;; OPTIN-NEXT:     (i32.const 10)
  ;; OPTIN-NEXT:    )
  ;; OPTIN-NEXT:    (else
  ;; OPTIN-NEXT:     (i32.const 20)
  ;; OPTIN-NEXT:    )
  ;; OPTIN-NEXT:   )
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.const 0)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.const 0)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT: )
  (func $multi-block-split (param $param i32)
    (local $x i32)
    (if
      (local.get $param)
      (then
        (local.set $x
          (i32.const 10)
        )
      )
      (else
        (local.set $x
          (i32.const 20)
        )
      )
    )
    ;; x is either 10 or 20, but not known to be one or the other.
    (drop
      (i32.eq
        (local.get $x)
        (i32.const 10)
      )
    )
    (drop
      (i32.eq
        (local.get $x)
        (i32.const 20)
      )
    )
    ;; TODO: test we can infer x >= 10 etc.
  )

  ;; CHECK:      (func $multi-block-split-2 (type $0) (param $param i32)
  ;; CHECK-NEXT:  (local $x i32)
  ;; CHECK-NEXT:  (local.set $x
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (local.get $param)
  ;; CHECK-NEXT:   (then
  ;; CHECK-NEXT:    (local.set $x
  ;; CHECK-NEXT:     (i32.const 20)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.eq
  ;; CHECK-NEXT:    (local.get $x)
  ;; CHECK-NEXT:    (i32.const 10)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.eq
  ;; CHECK-NEXT:    (local.get $x)
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; OPTIN:      (func $multi-block-split-2 (type $0) (param $param i32)
  ;; OPTIN-NEXT:  (local $x i32)
  ;; OPTIN-NEXT:  (local.set $x
  ;; OPTIN-NEXT:   (i32.const 10)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (if
  ;; OPTIN-NEXT:   (local.get $param)
  ;; OPTIN-NEXT:   (then
  ;; OPTIN-NEXT:    (local.set $x
  ;; OPTIN-NEXT:     (i32.const 20)
  ;; OPTIN-NEXT:    )
  ;; OPTIN-NEXT:   )
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.eq
  ;; OPTIN-NEXT:    (local.get $x)
  ;; OPTIN-NEXT:    (i32.const 10)
  ;; OPTIN-NEXT:   )
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.eq
  ;; OPTIN-NEXT:    (local.get $x)
  ;; OPTIN-NEXT:    (i32.const 20)
  ;; OPTIN-NEXT:   )
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT: )
  (func $multi-block-split-2 (param $param i32)
    (local $x i32)
    ;; As above, but one if arm, and a set before the if.
    (local.set $x
      (i32.const 10)
    )
    (if
      (local.get $param)
      (then
        (local.set $x
          (i32.const 20)
        )
      )
    )
    ;; Again, we cannot infer.
    (drop
      (i32.eq
        (local.get $x)
        (i32.const 10)
      )
    )
    (drop
      (i32.eq
        (local.get $x)
        (i32.const 20)
      )
    )
  )

  ;; CHECK:      (func $default-var (type $0) (param $param i32)
  ;; CHECK-NEXT:  (local $x i32)
  ;; CHECK-NEXT:  (local $eq eqref)
  ;; CHECK-NEXT:  (local $nn-eq (ref eq))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.eq
  ;; CHECK-NEXT:    (local.get $param)
  ;; CHECK-NEXT:    (i32.const 0)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  ;; OPTIN:      (func $default-var (type $0) (param $param i32)
  ;; OPTIN-NEXT:  (local $x i32)
  ;; OPTIN-NEXT:  (local $eq eqref)
  ;; OPTIN-NEXT:  (local $nn-eq (ref eq))
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.const 1)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.const 1)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.eqz
  ;; OPTIN-NEXT:    (local.get $param)
  ;; OPTIN-NEXT:   )
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.const 1)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT:  (drop
  ;; OPTIN-NEXT:   (i32.const 1)
  ;; OPTIN-NEXT:  )
  ;; OPTIN-NEXT: )
  (func $default-var (param $param i32)
    (local $x i32)
    (local $eq eqref)
    ;; A non-nullable local. We cannot add a get for it (it would not validate),
    ;; but check we do not error.
    (local $nn-eq (ref eq))
    ;; locals begin with default values, so we can infer here.
    (drop
      (i32.eq
        (local.get $x)
        (i32.const 0)
      )
    )
    (drop
      (i32.eqz
        (local.get $x)
      )
    )
    ;; We can infer nothing for a param.
    (drop
      (i32.eq
        (local.get $param)
        (i32.const 0)
      )
    )
    ;; We can infer a null reference.
    (drop
      (ref.eq
        (local.get $eq)
        (ref.null eq)
      )
    )
    (drop
      (ref.is_null
        (local.get $eq)
      )
    )
  )
)

;; TODO eqz
;; todo -split
