;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --remove-unused-names --vacuum --ignore-implicit-traps -S -o - | filecheck %s

(module
 ;; CHECK:      (type $FUNCSIG$vj (func (param i32 i32)))

 ;; CHECK:      (type $FUNCSIG$j (func (result i32)))

 ;; CHECK:      (type $2 (func (param i32) (result i32)))

 ;; CHECK:      (type $3 (func (result f32)))

 ;; CHECK:      (type $4 (func (param f32)))

 ;; CHECK:      (type $5 (func (result f64)))

 ;; CHECK:      (type $6 (func (param f64)))

 ;; CHECK:      (type $7 (func (result i64)))

 ;; CHECK:      (type $8 (func (param i64)))

 ;; CHECK:      (type $0 (func))
 (type $0 (func))
 (type $FUNCSIG$j (func (result i32)))
 (type $FUNCSIG$i (func (result i32)))
 (type $legaltype$wasm2js_scratch_load_i64 (func (result i32)))
 (type $FUNCSIG$vj (func (param i32 i32)))
 (type $legaltype$wasm2js_scratch_store_i64 (func (param i32 i32)))
 ;; CHECK:      (import "env" "wasm2js_scratch_load_i32" (func $wasm2js_scratch_load_i32 (param i32) (result i32)))
 (import "env" "wasm2js_scratch_load_i32" (func $wasm2js_scratch_load_i32 (param i32) (result i32)))
 ;; CHECK:      (import "env" "wasm2js_scratch_store_i32" (func $wasm2js_scratch_store_i32 (param i32 i32)))
 (import "env" "wasm2js_scratch_store_i32" (func $wasm2js_scratch_store_i32 (param i32 i32)))
 ;; CHECK:      (import "env" "wasm2js_scratch_load_f32" (func $wasm2js_scratch_load_f32 (result f32)))
 (import "env" "wasm2js_scratch_load_f32" (func $wasm2js_scratch_load_f32 (result f32)))
 ;; CHECK:      (import "env" "wasm2js_scratch_store_f32" (func $wasm2js_scratch_store_f32 (param f32)))
 (import "env" "wasm2js_scratch_store_f32" (func $wasm2js_scratch_store_f32 (param f32)))
 ;; CHECK:      (import "env" "wasm2js_scratch_load_f64" (func $wasm2js_scratch_load_f64 (result f64)))
 (import "env" "wasm2js_scratch_load_f64" (func $wasm2js_scratch_load_f64 (result f64)))
 ;; CHECK:      (import "env" "wasm2js_scratch_store_f64" (func $wasm2js_scratch_store_f64 (param f64)))
 (import "env" "wasm2js_scratch_store_f64" (func $wasm2js_scratch_store_f64 (param f64)))
 ;; CHECK:      (import "env" "getTempRet0" (func $getTempRet0 (result i32)))
 (import "env" "getTempRet0" (func $getTempRet0 (result i32)))
 ;; CHECK:      (import "env" "wasm2js_scratch_load_i64" (func $legalimport$wasm2js_scratch_load_i64 (result i32)))
 (import "env" "wasm2js_scratch_load_i64" (func $legalimport$wasm2js_scratch_load_i64 (result i32)))
 ;; CHECK:      (import "env" "wasm2js_scratch_store_i64" (func $legalimport$wasm2js_scratch_store_i64 (param i32 i32)))
 (import "env" "wasm2js_scratch_store_i64" (func $legalimport$wasm2js_scratch_store_i64 (param i32 i32)))
 ;; CHECK:      (import "env" "wasm2js_scratch_load_i64" (func $wasm2js_scratch_load_i64 (result i64)))
 (import "env" "wasm2js_scratch_load_i64" (func $wasm2js_scratch_load_i64 (result i64)))
 ;; CHECK:      (import "env" "wasm2js_scratch_store_i64" (func $wasm2js_scratch_store_i64 (param i64)))
 (import "env" "wasm2js_scratch_store_i64" (func $wasm2js_scratch_store_i64 (param i64)))
 ;; CHECK:      (global $i64toi32_i32$HIGH_BITS (mut i32) (i32.const 0))

 ;; CHECK:      (memory $0 1 1)
 (memory $0 1 1)
 (global $i64toi32_i32$HIGH_BITS (mut i32) (i32.const 0))
 ;; CHECK:      (func $0
 ;; CHECK-NEXT:  (local $0 f64)
 ;; CHECK-NEXT:  (local $1 i32)
 ;; CHECK-NEXT:  (nop)
 ;; CHECK-NEXT: )
 (func $0 (; 11 ;) (type $0)
  (local $0 f64)
  (local $1 i32)
  (block $label$1
   (block
    (nop)
    (drop
     (if (result f64)
      (i32.const 1)
      (then
       (block (result f64)
        (nop)
        (f64.load
         (i32.const 19)
        )
       )
      )
      (else
       (block
        (drop
         (f64.const 1)
        )
        (br $label$1)
        (nop)
       )
      )
     )
    )
   )
   (nop)
  )
 )
 ;; CHECK:      (func $legalfunc$wasm2js_scratch_load_i64 (result i32)
 ;; CHECK-NEXT:  (local $0 i32)
 ;; CHECK-NEXT:  (local $1 i32)
 ;; CHECK-NEXT:  (local.set $1
 ;; CHECK-NEXT:   (i32.or
 ;; CHECK-NEXT:    (call $legalimport$wasm2js_scratch_load_i64)
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (global.set $i64toi32_i32$HIGH_BITS
 ;; CHECK-NEXT:   (call $getTempRet0)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $1)
 ;; CHECK-NEXT: )
 (func $legalfunc$wasm2js_scratch_load_i64 (; 12 ;) (result i32)
  (local $0 i32)
  (local $1 i32)
  (local.set $1
   (i32.or
    (call $legalimport$wasm2js_scratch_load_i64)
    (block (result i32)
     (nop)
     (block (result i32)
      (nop)
      (i32.const 0)
     )
    )
   )
  )
  (global.set $i64toi32_i32$HIGH_BITS
   (call $getTempRet0)
  )
  (local.get $1)
 )
 ;; CHECK:      (func $legalfunc$wasm2js_scratch_store_i64 (param $0 i32) (param $1 i32)
 ;; CHECK-NEXT:  (call $legalimport$wasm2js_scratch_store_i64
 ;; CHECK-NEXT:   (local.get $0)
 ;; CHECK-NEXT:   (local.get $1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $legalfunc$wasm2js_scratch_store_i64 (; 13 ;) (param $0 i32) (param $1 i32)
  (call $legalimport$wasm2js_scratch_store_i64
   (block (result i32)
    (nop)
    (local.get $0)
   )
   (block (result i32)
    (nop)
    (local.get $1)
   )
  )
 )
)
