;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --remove-unused-names --merge-blocks --all-features -S -o - | filecheck %s

(module
  (memory 256 256 shared)
  ;; CHECK:      (type $3 (func))

  ;; CHECK:      (type $i (func (param i32)))
  (type $i (func (param i32)))
  ;; CHECK:      (type $2 (func (result i32)))

  ;; CHECK:      (type $ii (func (param i32 i32)))
  (type $ii (func (param i32 i32)))
  ;; CHECK:      (type $iii (func (param i32 i32 i32)))
  (type $iii (func (param i32 i32 i32)))
  (type $3 (func))
  (table 1 1 funcref)
  (elem (i32.const 0) $call-i)
  ;; CHECK:      (type $5 (func (result f64)))

  ;; CHECK:      (memory $0 256 256 shared)

  ;; CHECK:      (table $0 1 1 funcref)

  ;; CHECK:      (elem $0 (i32.const 0) $call-i)

  ;; CHECK:      (func $call-i (type $i) (param $0 i32)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $call-i (type $i) (param $0 i32)
    (nop)
  )
  ;; CHECK:      (func $call-ii (type $ii) (param $0 i32) (param $1 i32)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $call-ii (type $ii) (param $0 i32) (param $1 i32)
    (nop)
  )
  ;; CHECK:      (func $call-iii (type $iii) (param $0 i32) (param $1 i32) (param $2 i32)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $call-iii (type $iii) (param $0 i32) (param $1 i32) (param $2 i32)
    (nop)
  )
  ;; CHECK:      (func $b0-yes (type $i) (param $i1 i32)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $b0-yes (type $i) (param $i1 i32)
    (block $topmost
      (block $block0
        (drop
          (i32.const 10)
        )
      )
    )
  )
  ;; CHECK:      (func $b0-no (type $i) (param $i1 i32)
  ;; CHECK-NEXT:  (block $topmost
  ;; CHECK-NEXT:   (block $block0
  ;; CHECK-NEXT:    (br $block0)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (br $topmost)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $b0-no (type $i) (param $i1 i32)
    (block $topmost
      (block $block0
        (br $block0)
      )
      (br $topmost)
    )
  )
  ;; CHECK:      (func $b0-br-but-ok (type $i) (param $i1 i32)
  ;; CHECK-NEXT:  (block $topmost
  ;; CHECK-NEXT:   (br $topmost)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $b0-br-but-ok (type $i) (param $i1 i32)
    (block $topmost
      (block $block0
        (br $topmost)
      )
    )
  )
  ;; CHECK:      (func $b1-yes (type $i) (param $i1 i32)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $b1-yes (type $i) (param $i1 i32)
    (block $topmost
      (block $block0
        (block $block1
          (drop
            (i32.const 10)
          )
        )
      )
    )
  )
  ;; CHECK:      (func $b2-yes (type $i) (param $i1 i32)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 5)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 15)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $b2-yes (type $i) (param $i1 i32)
    (block $topmost
      (drop
        (i32.const 5)
      )
      (block $block0
        (drop
          (i32.const 10)
        )
      )
      (drop
        (i32.const 15)
      )
    )
  )
  ;; CHECK:      (func $b3-yes (type $i) (param $i1 i32)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 3)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 6)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 15)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $b3-yes (type $i) (param $i1 i32)
    (block $topmost
      (drop
        (i32.const 3)
      )
      (block $block0
        (drop
          (i32.const 6)
        )
        (block $block1
          (drop
            (i32.const 10)
          )
        )
        (drop
          (i32.const 15)
        )
      )
      (drop
        (i32.const 20)
      )
    )
  )
  ;; CHECK:      (func $b4 (type $i) (param $i1 i32)
  ;; CHECK-NEXT:  (block $inner
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 10)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (br $inner)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $b4 (type $i) (param $i1 i32)
    (block $topmost
      (block $inner
        (drop
          (i32.const 10)
        )
        (br $inner)
      )
    )
  )
  ;; CHECK:      (func $b5 (type $i) (param $i1 i32)
  ;; CHECK-NEXT:  (block $middle
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 10)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (block $inner
  ;; CHECK-NEXT:    (br $inner)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (br $middle)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $b5 (type $i) (param $i1 i32)
    (block $topmost
      (block $middle
        (block $inner
          (drop
            (i32.const 10)
          )
          (br $inner)
        )
        (br $middle)
      )
    )
  )
  ;; CHECK:      (func $b6 (type $i) (param $i1 i32)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 5)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block $inner
  ;; CHECK-NEXT:   (br $inner)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 15)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $b6 (type $i) (param $i1 i32)
    (block $topmost
      (drop
        (i32.const 5)
      )
      (block $inner
        (drop
          (i32.const 10)
        )
        (br $inner)
      )
      (drop
        (i32.const 15)
      )
    )
  )
  ;; CHECK:      (func $b7 (type $i) (param $i1 i32)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 3)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 6)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block $inner
  ;; CHECK-NEXT:   (br $inner)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 15)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block $middle
  ;; CHECK-NEXT:   (br $middle)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $b7 (type $i) (param $i1 i32)
    (block $topmost
      (drop
        (i32.const 3)
      )
      (block $middle
        (drop
          (i32.const 6)
        )
        (block $inner
          (drop
            (i32.const 10)
          )
          (br $inner)
        )
        (drop
          (i32.const 15)
        )
        (br $middle)
      )
      (drop
        (i32.const 20)
      )
    )
  )
  ;; CHECK:      (func $unary (type $3)
  ;; CHECK-NEXT:  (local $x i32)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.eqz
  ;; CHECK-NEXT:    (block (result i32)
  ;; CHECK-NEXT:     (i32.const 10)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.eqz
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.eqz
  ;; CHECK-NEXT:    (i32.const 30)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (local.set $x
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.load
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (unreachable)
  ;; CHECK-NEXT:  (return)
  ;; CHECK-NEXT: )
  (func $unary (type $3)
    (local $x i32)
    (drop
      (i32.eqz
        (block $block0 (result i32)
          (i32.const 10)
        )
      )
    )
    (drop
      (i32.eqz
        (block $block1 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
      )
    )
    (drop
      (i32.eqz
        (block $block2 (result i32)
          (drop
            (i32.const 10)
          )
          (drop
            (i32.const 20)
          )
          (i32.const 30)
        )
      )
    )
    (local.set $x
      (block $block3 (result i32)
        (drop
          (i32.const 10)
        )
        (i32.const 20)
      )
    )
    (drop
      (i32.load
        (block $block4 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
      )
    )
    (return
      (block $block5
        (drop
          (i32.const 10)
        )
        (unreachable)
      )
    )
  )
  ;; CHECK:      (func $binary (type $3)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.add
  ;; CHECK-NEXT:    (block (result i32)
  ;; CHECK-NEXT:     (i32.const 10)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.add
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:    (i32.const 30)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.add
  ;; CHECK-NEXT:    (i32.const 30)
  ;; CHECK-NEXT:    (i32.const 40)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.add
  ;; CHECK-NEXT:    (i32.const 10)
  ;; CHECK-NEXT:    (block (result i32)
  ;; CHECK-NEXT:     (i32.const 20)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.add
  ;; CHECK-NEXT:    (i32.const 10)
  ;; CHECK-NEXT:    (i32.const 30)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.add
  ;; CHECK-NEXT:    (i32.const 10)
  ;; CHECK-NEXT:    (i32.const 40)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.add
  ;; CHECK-NEXT:    (block (result i32)
  ;; CHECK-NEXT:     (i32.const 10)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (block (result i32)
  ;; CHECK-NEXT:     (i32.const 20)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.add
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:    (i32.const 40)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 40)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 50)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.add
  ;; CHECK-NEXT:    (i32.const 30)
  ;; CHECK-NEXT:    (i32.const 60)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (i32.store
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (i32.store
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (i32.add
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.add
  ;; CHECK-NEXT:     (i32.const 10)
  ;; CHECK-NEXT:     (i32.const 30)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $binary (type $3)
    (drop
      (i32.add
        (block $block0 (result i32)
          (i32.const 10)
        )
        (i32.const 20)
      )
    )
    (drop
      (i32.add
        (block $block1 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
        (i32.const 30)
      )
    )
    (drop
      (i32.add
        (block $block2 (result i32)
          (drop
            (i32.const 10)
          )
          (drop
            (i32.const 20)
          )
          (i32.const 30)
        )
        (i32.const 40)
      )
    )
    (drop
      (i32.add
        (i32.const 10)
        (block $block3 (result i32)
          (i32.const 20)
        )
      )
    )
    (drop
      (i32.add
        (i32.const 10)
        (block $block4 (result i32)
          (drop
            (i32.const 20)
          )
          (i32.const 30)
        )
      )
    )
    (drop
      (i32.add
        (i32.const 10)
        (block $block5 (result i32)
          (drop
            (i32.const 20)
          )
          (drop
            (i32.const 30)
          )
          (i32.const 40)
        )
      )
    )
    (drop
      (i32.add
        (block $block6 (result i32)
          (i32.const 10)
        )
        (block $block7 (result i32)
          (i32.const 20)
        )
      )
    )
    (drop
      (i32.add
        (block $block8 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
        (block $block9 (result i32)
          (drop
            (i32.const 30)
          )
          (i32.const 40)
        )
      )
    )
    (drop
      (i32.add
        (block $block10 (result i32)
          (drop
            (i32.const 10)
          )
          (drop
            (i32.const 20)
          )
          (i32.const 30)
        )
        (block $block11 (result i32)
          (drop
            (i32.const 40)
          )
          (drop
            (i32.const 50)
          )
          (i32.const 60)
        )
      )
    )
    (i32.store
      (i32.const 10)
      (block $block12 (result i32)
        (drop
          (i32.const 20)
        )
        (i32.const 30)
      )
    )
    (i32.store
      (block $block13 (result i32)
        (drop
          (i32.const 10)
        )
        (i32.const 20)
      )
      (i32.const 30)
    )
    (drop
      (i32.add
        (unreachable)
        (block $block14 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
      )
    )
    (drop
      (i32.add
        (block $block15 (result i32)
          (unreachable)
          (i32.const 10)
        )
        (block $block16 (result i32)
          (drop
            (i32.const 20)
          )
          (i32.const 30)
        )
      )
    )
  )
  ;; CHECK:      (func $trinary (type $3)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 50)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (select
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:    (i32.const 40)
  ;; CHECK-NEXT:    (i32.const 60)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 40)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (select
  ;; CHECK-NEXT:    (block (result i32)
  ;; CHECK-NEXT:     (i32.const 10)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (i32.const 30)
  ;; CHECK-NEXT:    (i32.const 50)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 40)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (select
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:    (block (result i32)
  ;; CHECK-NEXT:     (i32.const 30)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (i32.const 50)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (select
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:    (i32.const 40)
  ;; CHECK-NEXT:    (block (result i32)
  ;; CHECK-NEXT:     (i32.const 50)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (select
  ;; CHECK-NEXT:    (block (result i32)
  ;; CHECK-NEXT:     (i32.const 10)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (block (result i32)
  ;; CHECK-NEXT:     (i32.const 20)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (i32.const 40)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (select
  ;; CHECK-NEXT:    (block (result i32)
  ;; CHECK-NEXT:     (i32.const 10)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (i32.const 30)
  ;; CHECK-NEXT:    (block (result i32)
  ;; CHECK-NEXT:     (i32.const 40)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (select
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:    (block (result i32)
  ;; CHECK-NEXT:     (i32.const 30)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (block (result i32)
  ;; CHECK-NEXT:     (i32.const 40)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 30)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 50)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (select
  ;; CHECK-NEXT:     (i32.const 20)
  ;; CHECK-NEXT:     (i32.const 40)
  ;; CHECK-NEXT:     (i32.const 60)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 50)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (select
  ;; CHECK-NEXT:    (block
  ;; CHECK-NEXT:     (drop
  ;; CHECK-NEXT:      (i32.const 10)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (unreachable)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (i32.const 40)
  ;; CHECK-NEXT:    (i32.const 60)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 10)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 50)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (select
  ;; CHECK-NEXT:     (i32.const 20)
  ;; CHECK-NEXT:     (i32.const 40)
  ;; CHECK-NEXT:     (i32.const 60)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 50)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (select
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:    (block
  ;; CHECK-NEXT:     (drop
  ;; CHECK-NEXT:      (i32.const 30)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (unreachable)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (i32.const 60)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 10)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 30)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (select
  ;; CHECK-NEXT:     (i32.const 20)
  ;; CHECK-NEXT:     (i32.const 40)
  ;; CHECK-NEXT:     (i32.const 60)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (select
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:    (i32.const 40)
  ;; CHECK-NEXT:    (block
  ;; CHECK-NEXT:     (drop
  ;; CHECK-NEXT:      (i32.const 50)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (unreachable)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $trinary (type $3)
    (drop
      (select
        (block $block0 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
        (block $block1 (result i32)
          (drop
            (i32.const 30)
          )
          (i32.const 40)
        )
        (block $block2 (result i32)
          (drop
            (i32.const 50)
          )
          (i32.const 60)
        )
      )
    )
    (drop
      (select
        (block $block3 (result i32)
          (i32.const 10)
        )
        (block $block4 (result i32)
          (drop
            (i32.const 20)
          )
          (i32.const 30)
        )
        (block $block5 (result i32)
          (drop
            (i32.const 40)
          )
          (i32.const 50)
        )
      )
    )
    (drop
      (select
        (block $block6 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
        (block $block7 (result i32)
          (i32.const 30)
        )
        (block $block8 (result i32)
          (drop
            (i32.const 40)
          )
          (i32.const 50)
        )
      )
    )
    (drop
      (select
        (block $block9 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
        (block $block10 (result i32)
          (drop
            (i32.const 30)
          )
          (i32.const 40)
        )
        (block $block11 (result i32)
          (i32.const 50)
        )
      )
    )
    (drop
      (select
        (block $block12 (result i32)
          (i32.const 10)
        )
        (block $block13 (result i32)
          (i32.const 20)
        )
        (block $block14 (result i32)
          (drop
            (i32.const 30)
          )
          (i32.const 40)
        )
      )
    )
    (drop
      (select
        (block $block15 (result i32)
          (i32.const 10)
        )
        (block $block16 (result i32)
          (drop
            (i32.const 20)
          )
          (i32.const 30)
        )
        (block $block17 (result i32)
          (i32.const 40)
        )
      )
    )
    (drop
      (select
        (block $block18 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
        (block $block19 (result i32)
          (i32.const 30)
        )
        (block $block20 (result i32)
          (i32.const 40)
        )
      )
    )
    (drop
      (select
        (block $block21 (result i32)
          (unreachable)
          (i32.const 20)
        )
        (block $block22 (result i32)
          (drop
            (i32.const 30)
          )
          (i32.const 40)
        )
        (block $block23 (result i32)
          (drop
            (i32.const 50)
          )
          (i32.const 60)
        )
      )
    )
    (drop
      (select
        (block $block24 (result i32)
          (drop
            (i32.const 10)
          )
          (unreachable)
        )
        (block $block25 (result i32)
          (drop
            (i32.const 30)
          )
          (i32.const 40)
        )
        (block $block26 (result i32)
          (drop
            (i32.const 50)
          )
          (i32.const 60)
        )
      )
    )
    (drop
      (select
        (block $block27 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
        (block $block28 (result i32)
          (unreachable)
          (i32.const 40)
        )
        (block $block29 (result i32)
          (drop
            (i32.const 50)
          )
          (i32.const 60)
        )
      )
    )
    (drop
      (select
        (block $block30 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
        (block $block31 (result i32)
          (drop
            (i32.const 30)
          )
          (unreachable)
        )
        (block $block32 (result i32)
          (drop
            (i32.const 50)
          )
          (i32.const 60)
        )
      )
    )
    (drop
      (select
        (block $block33 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
        (block $block34 (result i32)
          (drop
            (i32.const 30)
          )
          (i32.const 40)
        )
        (block $block35 (result i32)
          (unreachable)
          (i32.const 60)
        )
      )
    )
    (drop
      (select
        (block $block36 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
        (block $block37 (result i32)
          (drop
            (i32.const 30)
          )
          (i32.const 40)
        )
        (block $block38 (result i32)
          (drop
            (i32.const 50)
          )
          (unreachable)
        )
      )
    )
  )
  ;; CHECK:      (func $breaks (type $3)
  ;; CHECK-NEXT:  (block $out
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 10)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (br $out)
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 10)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (br_if $out
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 10)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 30)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (br_if $out
  ;; CHECK-NEXT:    (i32.const 40)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 10)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (br_table $out $out
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (block $out2 (result i32)
  ;; CHECK-NEXT:     (drop
  ;; CHECK-NEXT:      (i32.const 10)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (drop
  ;; CHECK-NEXT:      (i32.const 30)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (br_table $out2 $out2
  ;; CHECK-NEXT:      (i32.const 20)
  ;; CHECK-NEXT:      (i32.const 40)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $breaks (type $3)
    (block $out
      (block
        (drop
          (block $block0 (result i32)
            (drop
              (i32.const 10)
            )
            (i32.const 20)
          )
        )
        (br $out)
      )
      (br_if $out
        (block $block1 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
      )
      (block
        (drop
          (block $block2 (result i32)
            (drop
              (i32.const 10)
            )
            (i32.const 20)
          )
        )
        (br_if $out
          (block $block3 (result i32)
            (drop
              (i32.const 30)
            )
            (i32.const 40)
          )
        )
      )
      (br_table $out $out
        (block $block4 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
      )
      (drop
        (block $out2 (result i32)
          (br_table $out2 $out2
            (block $block5 (result i32)
              (drop
                (i32.const 10)
              )
              (i32.const 20)
            )
            (block $block6 (result i32)
              (drop
                (i32.const 30)
              )
              (i32.const 40)
            )
          )
        )
      )
      (unreachable)
    )
  )
  ;; CHECK:      (func $calls (type $3)
  ;; CHECK-NEXT:  (call $call-i
  ;; CHECK-NEXT:   (block (result i32)
  ;; CHECK-NEXT:    (i32.const 10)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $call-i
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $call-i
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $call-ii
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:   (i32.const 40)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (call $call-ii
  ;; CHECK-NEXT:    (i32.const 10)
  ;; CHECK-NEXT:    (i32.const 30)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $call-ii
  ;; CHECK-NEXT:   (block
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (i32.const 10)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (i32.const 10)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:   (call $call-ii
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:    (i32.const 30)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $call-ii
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:   (block
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (i32.const 30)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 50)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $call-iii
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:   (i32.const 40)
  ;; CHECK-NEXT:   (i32.const 60)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 40)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call $call-iii
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:   (i32.const 50)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 50)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call_indirect $0 (type $ii)
  ;; CHECK-NEXT:   (i32.const 20)
  ;; CHECK-NEXT:   (i32.const 40)
  ;; CHECK-NEXT:   (i32.const 60)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 50)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call_indirect $0 (type $ii)
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:   (i32.const 40)
  ;; CHECK-NEXT:   (i32.const 60)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 31)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 51)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call_indirect $0 (type $ii)
  ;; CHECK-NEXT:   (i32.const 41)
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:   (i32.const 61)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 32)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 52)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (call_indirect $0 (type $ii)
  ;; CHECK-NEXT:   (i32.const 42)
  ;; CHECK-NEXT:   (i32.const 62)
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $calls (type $3)
    (call $call-i
      (block $block0 (result i32)
        (i32.const 10)
      )
    )
    (call $call-i
      (block $block1 (result i32)
        (drop
          (i32.const 10)
        )
        (i32.const 20)
      )
    )
    (call $call-i
      (block $block2 (result i32)
        (drop
          (i32.const 10)
        )
        (drop
          (i32.const 20)
        )
        (i32.const 30)
      )
    )
    (call $call-ii
      (block $block3 (result i32)
        (drop
          (i32.const 10)
        )
        (i32.const 20)
      )
      (block $block4 (result i32)
        (drop
          (i32.const 30)
        )
        (i32.const 40)
      )
    )
    (call $call-ii
      (block $block5 (result i32)
        (unreachable)
        (i32.const 10)
      )
      (block $block6 (result i32)
        (drop
          (i32.const 20)
        )
        (i32.const 30)
      )
    )
    (call $call-ii
      (block $block7 (result i32)
        (drop
          (i32.const 10)
        )
        (unreachable)
      )
      (block $block8 (result i32)
        (drop
          (i32.const 20)
        )
        (i32.const 30)
      )
    )
    (call $call-ii
      (block $block9 (result i32)
        (drop
          (i32.const 10)
        )
        (i32.const 20)
      )
      (block $block10 (result i32)
        (unreachable)
        (i32.const 30)
      )
    )
    (call $call-ii
      (block $block11 (result i32)
        (drop
          (i32.const 10)
        )
        (i32.const 20)
      )
      (block $block12 (result i32)
        (drop
          (i32.const 30)
        )
        (unreachable)
      )
    )
    (call $call-iii
      (block $block13 (result i32)
        (drop
          (i32.const 10)
        )
        (i32.const 20)
      )
      (block $block14 (result i32)
        (drop
          (i32.const 30)
        )
        (i32.const 40)
      )
      (block $block15 (result i32)
        (drop
          (i32.const 50)
        )
        (i32.const 60)
      )
    )
    (call $call-iii
      (block $block16 (result i32)
        (drop
          (i32.const 10)
        )
        (i32.const 20)
      )
      (i32.const 30)
      (block $block17 (result i32)
        (drop
          (i32.const 40)
        )
        (i32.const 50)
      )
    )
    (call_indirect (type $ii)
      (block $block18 (result i32)
        (drop
          (i32.const 10)
        )
        (i32.const 20)
      )
      (block $block19 (result i32)
        (drop
          (i32.const 30)
        )
        (i32.const 40)
      )
      (block $block20 (result i32)
        (drop
          (i32.const 50)
        )
        (i32.const 60)
      )
    )
    (call_indirect (type $ii)
      (unreachable)
      (block $block21 (result i32)
        (drop
          (i32.const 30)
        )
        (i32.const 40)
      )
      (block $block22 (result i32)
        (drop
          (i32.const 50)
        )
        (i32.const 60)
      )
    )
    (call_indirect (type $ii)
      (block $block21 (result i32)
        (drop
          (i32.const 31)
        )
        (i32.const 41)
      )
      (unreachable)
      (block $block22 (result i32)
        (drop
          (i32.const 51)
        )
        (i32.const 61)
      )
    )
    (call_indirect (type $ii)
      (block $block21 (result i32)
        (drop
          (i32.const 32)
        )
        (i32.const 42)
      )
      (block $block22 (result i32)
        (drop
          (i32.const 52)
        )
        (i32.const 62)
      )
      (unreachable)
    )
  )
  ;; CHECK:      (func $atomics (type $3)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 30)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 50)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.atomic.rmw.cmpxchg
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:    (i32.const 40)
  ;; CHECK-NEXT:    (i32.const 60)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.atomic.rmw.add
  ;; CHECK-NEXT:    (i32.const 20)
  ;; CHECK-NEXT:    (i32.const 30)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $atomics (type $3)
    (drop
      (i32.atomic.rmw.cmpxchg ;; mergeblock logic should be same as select
        (block $block0 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
        (block $block1 (result i32)
          (drop
            (i32.const 30)
          )
          (i32.const 40)
        )
        (block $block2 (result i32)
          (drop
            (i32.const 50)
          )
          (i32.const 60)
        )
      )
    )
    (drop
      (i32.atomic.rmw.add ;; atomicrmw is like a binary
        (block $block1 (result i32)
          (drop
            (i32.const 10)
          )
          (i32.const 20)
        )
        (i32.const 30)
      )
    )
  )
  ;; CHECK:      (func $mix-select (type $i) (param $x i32)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (select
  ;; CHECK-NEXT:    (local.get $x)
  ;; CHECK-NEXT:    (local.get $x)
  ;; CHECK-NEXT:    (block (result i32)
  ;; CHECK-NEXT:     (local.set $x
  ;; CHECK-NEXT:      (i32.const 1)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (i32.const 2)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $mix-select (param $x i32)
    (drop
      (select
        (local.get $x)
        (local.get $x)
        (block (result i32)
          (local.set $x ;; cannot be moved before the gets
            (i32.const 1)
          )
          (i32.const 2)
        )
      )
    )
  )
  ;; CHECK:      (func $block-type-change (type $3)
  ;; CHECK-NEXT:  (local $0 f64)
  ;; CHECK-NEXT:  (local $1 f64)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (f64.gt
  ;; CHECK-NEXT:    (local.get $0)
  ;; CHECK-NEXT:    (local.get $1)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (then
  ;; CHECK-NEXT:    (nop)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $block-type-change (type $3)
    (local $0 f64)
    (local $1 f64)
    (if
      (f64.gt
        (local.get $0)
        (block $block0 (result f64)
          (nop)
          (local.get $1)
        )
      )
      (then
        (nop)
      )
    )
  )
  ;; CHECK:      (func $do-reorder (type $i) (param $x i32)
  ;; CHECK-NEXT:  (local $y i32)
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:   (then
  ;; CHECK-NEXT:    (local.set $y
  ;; CHECK-NEXT:     (i32.const 5)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (local.set $x
  ;; CHECK-NEXT:     (i32.le_u
  ;; CHECK-NEXT:      (local.get $x)
  ;; CHECK-NEXT:      (i32.const 10)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $do-reorder (param $x i32)
    (local $y i32)
    (if (i32.const 1)
      (then
        (block
          (local.set $x
            (i32.le_u
              (local.get $x)
              (block (result i32)
                (local.set $y (i32.const 5))
                (i32.const 10)
              )
            )
          )
        )
      )
    )
  )
  ;; CHECK:      (func $do-not-reorder (type $i) (param $x i32)
  ;; CHECK-NEXT:  (local $y i32)
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:   (then
  ;; CHECK-NEXT:    (local.set $x
  ;; CHECK-NEXT:     (i32.le_u
  ;; CHECK-NEXT:      (local.get $y)
  ;; CHECK-NEXT:      (block (result i32)
  ;; CHECK-NEXT:       (local.set $y
  ;; CHECK-NEXT:        (i32.const 5)
  ;; CHECK-NEXT:       )
  ;; CHECK-NEXT:       (i32.const 10)
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $do-not-reorder (param $x i32)
    (local $y i32)
    (if (i32.const 1)
      (then
        (block
          (local.set $x
            (i32.le_u
              (local.get $y)
              (block (result i32)
                (local.set $y (i32.const 5))
                (i32.const 10)
              )
            )
          )
        )
      )
    )
  )
  ;; CHECK:      (func $return-different-type (type $2) (result i32)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 2)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (f64.abs
  ;; CHECK-NEXT:   (return
  ;; CHECK-NEXT:    (i32.const 1)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (unreachable)
  ;; CHECK-NEXT: )
  (func $return-different-type (result i32)
    (drop
      (f64.abs
        (return
          (block (result i32) ;; when we flip the block out, it should have an ok type for the (dead) f64 op
            (drop (i32.const 2))
            (i32.const 1)
          )
        )
      )
    )
    (unreachable)
  )

 ;; CHECK:      (func $drop-unreachable (type $2) (result i32)
 ;; CHECK-NEXT:  (local $0 i32)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $drop-unreachable (result i32)
  (local $0 i32)
  (block $label$1 (result i32)
   (drop
    (block (result i32)
     (unreachable)
    )
   )
   (unreachable)
  )
 )
 ;; CHECK:      (func $concrete_finale_in_unreachable (type $5) (result f64)
 ;; CHECK-NEXT:  (block
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (f64.const 6.322092475576799e-96)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (f64.const -1)
 ;; CHECK-NEXT: )
 (func $concrete_finale_in_unreachable (result f64)
  (block $label$0 (result f64)
   (drop
    (block (result f64)
     (unreachable)
     (f64.const 6.322092475576799e-96)
    )
   )
   (f64.const -1)
  )
 )
 ;; CHECK:      (func $dont-move-unreachable (type $3)
 ;; CHECK-NEXT:  (loop $label$0
 ;; CHECK-NEXT:   (br $label$0)
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $dont-move-unreachable
  (loop $label$0
   (drop
    (block $label$3 (result i32)
     (br $label$0)
     (i32.const 1)
    )
   )
  )
 )
 ;; CHECK:      (func $dont-move-unreachable-last (type $3)
 ;; CHECK-NEXT:  (loop $label$0
 ;; CHECK-NEXT:   (call $dont-move-unreachable-last)
 ;; CHECK-NEXT:   (br $label$0)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $dont-move-unreachable-last
  (loop $label$0
   (drop
    (block $label$3 (result i32)
     (call $dont-move-unreachable-last)
     (br $label$0)
    )
   )
  )
 )
 ;; CHECK:      (func $move-around-unreachable-in-middle (type $3)
 ;; CHECK-NEXT:  (loop $label$0
 ;; CHECK-NEXT:   (nop)
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (block $label$3 (result i32)
 ;; CHECK-NEXT:     (drop
 ;; CHECK-NEXT:      (block
 ;; CHECK-NEXT:       (br $label$0)
 ;; CHECK-NEXT:       (drop
 ;; CHECK-NEXT:        (i32.const 0)
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (i32.const 1)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $move-around-unreachable-in-middle
  (loop $label$0
   (drop
    (block $label$2 (result i32)
     (block $block2
      (nop)
     )
     (block $label$3 (result i32)
      (drop
       (br_if $label$3
        (br $label$0)
        (i32.const 0)
       )
      )
      (i32.const 1)
     )
    )
   )
  )
 )
 ;; CHECK:      (func $drop-unreachable-block-with-concrete-final (type $3)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (return)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const -452)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $drop-unreachable-block-with-concrete-final
  (drop
   (block (result i32)
    (drop
     (block
      (drop
       (return)
      )
     )
    )
    (i32.const -452)
   )
  )
 )
 ;; CHECK:      (func $merging-with-unreachable-in-middle (type $2) (result i32)
 ;; CHECK-NEXT:  (block (result i32)
 ;; CHECK-NEXT:   (return
 ;; CHECK-NEXT:    (i32.const 21536)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (block $label$15
 ;; CHECK-NEXT:    (br $label$15)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (i32.const 19299)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $merging-with-unreachable-in-middle (result i32)
  (block $label$1 (result i32)
   (block (result i32)
    (return
     (i32.const 21536)
    )
    (block $label$15
     (br $label$15)
    )
    (i32.const 19299)
   )
  )
 )
 ;; CHECK:      (func $remove-br-after-unreachable (type $3)
 ;; CHECK-NEXT:  (block $label$9
 ;; CHECK-NEXT:   (block
 ;; CHECK-NEXT:    (return)
 ;; CHECK-NEXT:    (br $label$9)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $remove-br-after-unreachable
  (block $label$9
   (drop
    (block
     (block
      (return)
      (br $label$9) ;; removing this leads to the block becoming unreachable
     )
    )
   )
  )
 )
 ;; CHECK:      (func $block-tails (type $3)
 ;; CHECK-NEXT:  (block $l1
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const -2)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const -1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br $l1)
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $l2
 ;; CHECK-NEXT:   (br_if $l2
 ;; CHECK-NEXT:    (i32.const 2)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 3)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $l3
 ;; CHECK-NEXT:   (br_if $l3
 ;; CHECK-NEXT:    (i32.const 4)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $l3
 ;; CHECK-NEXT:    (i32.const 5)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 6)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $l4
 ;; CHECK-NEXT:   (br_if $l4
 ;; CHECK-NEXT:    (i32.const 7)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $l4
 ;; CHECK-NEXT:    (i32.const 8)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 9)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $l5
 ;; CHECK-NEXT:   (if
 ;; CHECK-NEXT:    (i32.const 10)
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (br_if $l5
 ;; CHECK-NEXT:      (i32.const 11)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 12)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $l8
 ;; CHECK-NEXT:   (br_if $l8
 ;; CHECK-NEXT:    (i32.const 13)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $l8
 ;; CHECK-NEXT:    (i32.const 14)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $l8
 ;; CHECK-NEXT:    (i32.const 15)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 16)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $l11
 ;; CHECK-NEXT:   (br_if $l11
 ;; CHECK-NEXT:    (i32.const 17)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $l11
 ;; CHECK-NEXT:    (i32.const 18)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $l11
 ;; CHECK-NEXT:    (i32.const 19)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 20)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $l12
 ;; CHECK-NEXT:   (br_if $l12
 ;; CHECK-NEXT:    (i32.const 21)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (block $l13
 ;; CHECK-NEXT:    (br_if $l13
 ;; CHECK-NEXT:     (i32.const 22)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (block $l14
 ;; CHECK-NEXT:     (br_if $l14
 ;; CHECK-NEXT:      (i32.const 23)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (drop
 ;; CHECK-NEXT:      (i32.const 24)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 25)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 26)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 27)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $l17
 ;; CHECK-NEXT:   (br_if $l17
 ;; CHECK-NEXT:    (i32.const 28)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 29)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $l16
 ;; CHECK-NEXT:   (br_if $l16
 ;; CHECK-NEXT:    (i32.const 30)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 31)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $l15
 ;; CHECK-NEXT:   (br_if $l15
 ;; CHECK-NEXT:    (i32.const 32)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 33)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $block-tails
  (block $l1
   (drop (i32.const -2))
   (drop (i32.const -1))
   (br $l1)
   (drop (i32.const 0))
   (drop (i32.const 1))
  )
  (block $l2
   (br_if $l2 (i32.const 2))
   (drop (i32.const 3))
  )
  (block $b1
   (block $l3
    (br_if $b1 (i32.const 4))
    (br_if $l3 (i32.const 5))
    (drop (i32.const 6))
   )
  )
  (block $b2
   (block $l4
    (br_if $l4 (i32.const 7))
    (br_if $b2 (i32.const 8))
    (drop (i32.const 9))
   )
  )
  (block $l5
   (if (i32.const 10)
    (then
     (br_if $l5 (i32.const 11))
    )
   )
   (drop (i32.const 12))
  )
  (block $l6
   (block $l7
    (block $l8
     (br_if $l6 (i32.const 13))
     (br_if $l7 (i32.const 14))
     (br_if $l8 (i32.const 15))
     (drop (i32.const 16))
    )
   )
  )
  (block $l9
   (block $l10
    (block $l11
     (br_if $l11 (i32.const 17))
     (br_if $l10 (i32.const 18))
     (br_if $l9  (i32.const 19))
     (drop (i32.const 20))
    )
   )
  )
  (block $l12
   (block $l13
    (block $l14
     (br_if $l12 (i32.const 21))
     (br_if $l13 (i32.const 22))
     (br_if $l14 (i32.const 23))
     (drop (i32.const 24))
    )
    (drop (i32.const 25))
   )
   (drop (i32.const 26))
  )
  (block $l15
   (block $l16
    (block $l17
     (drop (i32.const 27))
     (br_if $l17 (i32.const 28))
     (drop (i32.const 29))
    )
    (br_if $l16 (i32.const 30))
    (drop (i32.const 31))
   )
   (br_if $l15 (i32.const 32))
   (drop (i32.const 33))
  )
 )
 ;; CHECK:      (func $loop-tails (type $3)
 ;; CHECK-NEXT:  (loop $l1
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const -2)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const -1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br $l1)
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l2
 ;; CHECK-NEXT:   (br_if $l2
 ;; CHECK-NEXT:    (i32.const 2)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 3)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $b1
 ;; CHECK-NEXT:   (loop $l3
 ;; CHECK-NEXT:    (br_if $b1
 ;; CHECK-NEXT:     (i32.const 4)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br_if $l3
 ;; CHECK-NEXT:     (i32.const 5)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 6)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l4
 ;; CHECK-NEXT:   (br_if $l4
 ;; CHECK-NEXT:    (i32.const 7)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $b2
 ;; CHECK-NEXT:   (br_if $b2
 ;; CHECK-NEXT:    (i32.const 8)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 9)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l5
 ;; CHECK-NEXT:   (if
 ;; CHECK-NEXT:    (i32.const 10)
 ;; CHECK-NEXT:    (then
 ;; CHECK-NEXT:     (br_if $l5
 ;; CHECK-NEXT:      (i32.const 11)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 12)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l6
 ;; CHECK-NEXT:   (loop $l7
 ;; CHECK-NEXT:    (loop $l8
 ;; CHECK-NEXT:     (br_if $l6
 ;; CHECK-NEXT:      (i32.const 13)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (br_if $l7
 ;; CHECK-NEXT:      (i32.const 14)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (br_if $l8
 ;; CHECK-NEXT:      (i32.const 15)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (drop
 ;; CHECK-NEXT:      (i32.const 16)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l9
 ;; CHECK-NEXT:   (loop $l10
 ;; CHECK-NEXT:    (loop $l11
 ;; CHECK-NEXT:     (br_if $l11
 ;; CHECK-NEXT:      (i32.const 17)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (br_if $l10
 ;; CHECK-NEXT:      (i32.const 18)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (br_if $l9
 ;; CHECK-NEXT:      (i32.const 19)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (drop
 ;; CHECK-NEXT:      (i32.const 20)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l12
 ;; CHECK-NEXT:   (loop $l13
 ;; CHECK-NEXT:    (loop $l14
 ;; CHECK-NEXT:     (br_if $l12
 ;; CHECK-NEXT:      (i32.const 21)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (br_if $l13
 ;; CHECK-NEXT:      (i32.const 22)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (br_if $l14
 ;; CHECK-NEXT:      (i32.const 23)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 24)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 25)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 26)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l15
 ;; CHECK-NEXT:   (loop $l16
 ;; CHECK-NEXT:    (loop $l17
 ;; CHECK-NEXT:     (drop
 ;; CHECK-NEXT:      (i32.const 27)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:     (br_if $l17
 ;; CHECK-NEXT:      (i32.const 28)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 29)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br_if $l16
 ;; CHECK-NEXT:     (i32.const 30)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 31)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $l15
 ;; CHECK-NEXT:    (i32.const 32)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 33)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $loop-tails
  (loop $l1
   (drop (i32.const -2))
   (drop (i32.const -1))
   (br $l1)
   (drop (i32.const 0))
   (drop (i32.const 1))
  )
  (loop $l2
   (br_if $l2 (i32.const 2))
   (drop (i32.const 3))
  )
  (block $b1
   (loop $l3
    (br_if $b1 (i32.const 4))
    (br_if $l3 (i32.const 5))
    (drop (i32.const 6))
   )
  )
  (block $b2
   (loop $l4
    (br_if $l4 (i32.const 7))
    (br_if $b2 (i32.const 8))
    (drop (i32.const 9))
   )
  )
  (loop $l5
   (if (i32.const 10)
    (then
     (br_if $l5 (i32.const 11))
    )
   )
   (drop (i32.const 12))
  )
  (loop $l6
   (loop $l7
    (loop $l8
     (br_if $l6 (i32.const 13))
     (br_if $l7 (i32.const 14))
     (br_if $l8 (i32.const 15))
     (drop (i32.const 16))
    )
   )
  )
  (loop $l9
   (loop $l10
    (loop $l11
     (br_if $l11 (i32.const 17))
     (br_if $l10 (i32.const 18))
     (br_if $l9  (i32.const 19))
     (drop (i32.const 20))
    )
   )
  )
  (loop $l12
   (loop $l13
    (loop $l14
     (br_if $l12 (i32.const 21))
     (br_if $l13 (i32.const 22))
     (br_if $l14 (i32.const 23))
     (drop (i32.const 24))
    )
    (drop (i32.const 25))
   )
   (drop (i32.const 26))
  )
  (loop $l15
   (loop $l16
    (loop $l17
     (drop (i32.const 27))
     (br_if $l17 (i32.const 28))
     (drop (i32.const 29))
    )
    (br_if $l16 (i32.const 30))
    (drop (i32.const 31))
   )
   (br_if $l15 (i32.const 32))
   (drop (i32.const 33))
  )
 )
 ;; CHECK:      (func $block-tail-one (type $3)
 ;; CHECK-NEXT:  (block $l1
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const -2)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const -1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br $l1)
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 2)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $block-tail-one
  (block $outer
   (block $l1
    (drop (i32.const -2))
    (drop (i32.const -1))
    (br $l1)
    (drop (i32.const 0))
    (drop (i32.const 1))
   )
   (drop (i32.const 2))
  )
 )
 ;; CHECK:      (func $loop-tail-one (type $3)
 ;; CHECK-NEXT:  (loop $l1
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const -2)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const -1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br $l1)
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 2)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $loop-tail-one
  (block $outer
   (loop $l1
    (drop (i32.const -2))
    (drop (i32.const -1))
    (br $l1)
    (drop (i32.const 0))
    (drop (i32.const 1))
   )
   (drop (i32.const 2))
  )
 )
 ;; CHECK:      (func $block-tail-value (type $2) (result i32)
 ;; CHECK-NEXT:  (block $l1 (result i32)
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const -1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br $l1
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (i32.const 2)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $block-tail-value (result i32)
  (block $outer (result i32)
   (block $l1 (result i32)
    (drop (i32.const -1))
    (br $l1 (i32.const 0))
    (drop (i32.const 1))
    (i32.const 2)
   )
  )
 )
 ;; CHECK:      (func $block-tail-empty (type $3)
 ;; CHECK-NEXT:  (block $l1
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const -1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br $l1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $block-tail-empty
  (block $outer
   (block $l1
    (drop (i32.const -1))
    (br $l1)
   )
  )
 )
 ;; CHECK:      (func $loop-tail-empty (type $3)
 ;; CHECK-NEXT:  (loop $l1
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const -1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br $l1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $loop-tail-empty
  (block $outer
   (loop $l1
    (drop (i32.const -1))
    (br $l1)
   )
  )
 )
 ;; CHECK:      (func $block-tail-unreachable (type $2) (result i32)
 ;; CHECK-NEXT:  (block $l1 (result i32)
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const -1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (br_if $l1
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:     (i32.const 1)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $block-tail-unreachable (result i32)
  (block $outer (result i32)
   (block $l1 (result i32)
    (drop (i32.const -1))
    (drop (br_if $l1 (i32.const 0) (i32.const 1)))
    (drop (i32.const 1))
    (unreachable)
   )
  )
 )
 ;; CHECK:      (func $loop-tail-unreachable (type $2) (result i32)
 ;; CHECK-NEXT:  (loop $l1
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const -1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $l1
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (unreachable)
 ;; CHECK-NEXT: )
 (func $loop-tail-unreachable (result i32)
  (block $outer (result i32)
   (loop $l1 (result i32)
    (drop (i32.const -1))
    (br_if $l1 (i32.const 1))
    (drop (i32.const 1))
    (unreachable)
   )
  )
 )
)
(module
 ;; CHECK:      (type $0 (func (result i32)))

 ;; CHECK:      (type $1 (func (param f64 i32) (result i32)))

 ;; CHECK:      (func $unreachable-in-sub-block (type $1) (param $0 f64) (param $1 i32) (result i32)
 ;; CHECK-NEXT:  (local $2 i32)
 ;; CHECK-NEXT:  (local $9 i32)
 ;; CHECK-NEXT:  (loop $label$1
 ;; CHECK-NEXT:   (local.set $9
 ;; CHECK-NEXT:    (local.tee $2
 ;; CHECK-NEXT:     (block $label$2 (result i32)
 ;; CHECK-NEXT:      (drop
 ;; CHECK-NEXT:       (br_if $label$2
 ;; CHECK-NEXT:        (local.tee $2
 ;; CHECK-NEXT:         (i32.const 0)
 ;; CHECK-NEXT:        )
 ;; CHECK-NEXT:        (i32.const 0)
 ;; CHECK-NEXT:       )
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:      (br_if $label$1
 ;; CHECK-NEXT:       (i32.const 0)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:      (block
 ;; CHECK-NEXT:       (unreachable)
 ;; CHECK-NEXT:       (nop)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (nop)
 ;; CHECK-NEXT:  (local.get $9)
 ;; CHECK-NEXT: )
 (func $unreachable-in-sub-block (param $0 f64) (param $1 i32) (result i32)
  (local $2 i32)
  (local $9 i32)
  (loop $label$1
   (local.set $9
    (local.tee $2
     (block $label$2 (result i32)
      (block
       (drop
        (br_if $label$2
         (local.tee $2
          (i32.const 0)
         )
         (i32.const 0)
        )
       )
      )
      (br_if $label$1
       (i32.const 0)
      )
      (block
       (unreachable)
       (nop) ;; bad if moved out to the outer block which is i32. current state works since this block is unreachable!
      )
     )
    )
   )
  )
  (nop)
  (local.get $9)
 )
 ;; CHECK:      (func $trivial (type $0) (result i32)
 ;; CHECK-NEXT:  (block
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT:   (nop)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $trivial (result i32)
   (block (result i32)
     (block
       (unreachable)
       (nop)
     )
   )
 )
 ;; CHECK:      (func $trivial-more (type $0) (result i32)
 ;; CHECK-NEXT:  (block
 ;; CHECK-NEXT:   (nop)
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT:   (nop)
 ;; CHECK-NEXT:   (nop)
 ;; CHECK-NEXT:   (nop)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block
 ;; CHECK-NEXT:   (nop)
 ;; CHECK-NEXT:   (unreachable)
 ;; CHECK-NEXT:   (nop)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $trivial-more (result i32)
   (block (result i32)
     (block
       (nop)
       (unreachable)
       (nop)
       (nop)
       (nop)
     )
     (block
       (nop)
       (unreachable)
       (nop)
     )
   )
 )
)
(module
 ;; CHECK:      (type $0 (func))

 ;; CHECK:      (func $merge-some-block (type $0)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $b1
 ;; CHECK-NEXT:   (br_if $b1
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $b2
 ;; CHECK-NEXT:   (br_if $b2
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 2)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 3)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $b3
 ;; CHECK-NEXT:   (br_if $b3
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 4)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $b3-dead-code-so-ignore
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 3)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br $b3-dead-code-so-ignore)
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 4)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 5)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $b4
 ;; CHECK-NEXT:   (br_if $b4
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 6)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $b4
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $b5
 ;; CHECK-NEXT:   (br_if $b5
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 7)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $b5
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 8)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 9)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 10)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $b6
 ;; CHECK-NEXT:   (br_if $b6
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $merge-some-block
  (block $b1
   (drop (i32.const 1))
   (br_if $b1 (i32.const 0))
  )
  (block $b2
   (br_if $b2 (i32.const 0))
   (drop (i32.const 2))
  )
  (block $b3
   (drop (i32.const 3))
   (br_if $b3 (i32.const 0))
   (drop (i32.const 4))
  )
  (block $b3-dead-code-so-ignore
   (drop (i32.const 3))
   (br $b3-dead-code-so-ignore)
   (drop (i32.const 4))
  )
  (block $b4
   (drop (i32.const 5))
   (br_if $b4 (i32.const 0))
   (drop (i32.const 6))
   (br_if $b4 (i32.const 0))
  )
  (block $b5
   (br_if $b5 (i32.const 0))
   (drop (i32.const 7))
   (br_if $b5 (i32.const 0))
   (drop (i32.const 8))
  )
  (block $b6
   (drop (i32.const 9))
   (drop (i32.const 10))
   (br_if $b6 (i32.const 0))
  )
 )
 ;; CHECK:      (func $merge-some-loop (type $0)
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $b1
 ;; CHECK-NEXT:   (br_if $b1
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $b2
 ;; CHECK-NEXT:   (br_if $b2
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 2)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 3)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $b3
 ;; CHECK-NEXT:   (br_if $b3
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 4)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 5)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $b4
 ;; CHECK-NEXT:   (br_if $b4
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 6)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $b4
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $b5
 ;; CHECK-NEXT:   (br_if $b5
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 7)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $b5
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 8)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 9)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 10)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block $b6
 ;; CHECK-NEXT:   (br_if $b6
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $merge-some-loop
  (loop $l1
   (block $b1
    (drop (i32.const 1))
    (br_if $b1 (i32.const 0))
   )
  )
  (loop $l2
   (block $b2
    (br_if $b2 (i32.const 0))
    (drop (i32.const 2))
   )
  )
  (loop $l3
   (block $b3
    (drop (i32.const 3))
    (br_if $b3 (i32.const 0))
    (drop (i32.const 4))
   )
  )
  (loop $l4
   (block $b4
    (drop (i32.const 5))
    (br_if $b4 (i32.const 0))
    (drop (i32.const 6))
    (br_if $b4 (i32.const 0))
   )
  )
  (loop $l5
   (block $b5
    (br_if $b5 (i32.const 0))
    (drop (i32.const 7))
    (br_if $b5 (i32.const 0))
    (drop (i32.const 8))
   )
  )
  (loop $l6
   (block $b6
    (drop (i32.const 9))
    (drop (i32.const 10))
    (br_if $b6 (i32.const 0))
   )
  )
 )
 ;; CHECK:      (func $merge-some-loop-taken (type $0)
 ;; CHECK-NEXT:  (loop $l1
 ;; CHECK-NEXT:   (block $b1
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 1)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br_if $l1
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 2)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br_if $b1
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 3)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l2
 ;; CHECK-NEXT:   (block $b2
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 4)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br_if $b2
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 5)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br_if $l2
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 6)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l3
 ;; CHECK-NEXT:   (block $b3
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 7)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br_if $b3
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 8)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br_if $l3
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l4
 ;; CHECK-NEXT:   (block $b4
 ;; CHECK-NEXT:    (br_if $l4
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 9)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br_if $b4
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 10)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l5
 ;; CHECK-NEXT:   (block $b5
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 7)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br_if $b5
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br_if $l5
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l6
 ;; CHECK-NEXT:   (block $b6
 ;; CHECK-NEXT:    (br_if $l6
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br_if $b6
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 10)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l7
 ;; CHECK-NEXT:   (block $b7
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 11)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br_if $l7
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br_if $b7
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 13)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l8
 ;; CHECK-NEXT:   (block $b8
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 14)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br_if $b8
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (br_if $l8
 ;; CHECK-NEXT:     (i32.const 0)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (i32.const 16)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l9
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 17)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $l9
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 18)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $l9
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 19)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l10
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 20)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $l10
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 21)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l11
 ;; CHECK-NEXT:   (br_if $l11
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (i32.const 23)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $l12
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (i32.const 24)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $l12
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $merge-some-loop-taken
  (loop $l1
   (block $b1
    (drop (i32.const 1))
    (br_if $l1 (i32.const 0))
    (drop (i32.const 2))
    (br_if $b1 (i32.const 0))
    (drop (i32.const 3))
   )
  )
  (loop $l2
   (block $b2
    (drop (i32.const 4))
    (br_if $b2 (i32.const 0))
    (drop (i32.const 5))
    (br_if $l2 (i32.const 0))
    (drop (i32.const 6))
   )
  )
  (loop $l3
   (block $b3
    (drop (i32.const 7))
    (br_if $b3 (i32.const 0))
    (drop (i32.const 8))
    (br_if $l3 (i32.const 0))
   )
  )
  (loop $l4
   (block $b4
    (br_if $l4 (i32.const 0))
    (drop (i32.const 9))
    (br_if $b4 (i32.const 0))
    (drop (i32.const 10))
   )
  )
  (loop $l5
   (block $b5
    (drop (i32.const 7))
    (br_if $b5 (i32.const 0))
    (br_if $l5 (i32.const 0))
   )
  )
  (loop $l6
   (block $b6
    (br_if $l6 (i32.const 0))
    (br_if $b6 (i32.const 0))
    (drop (i32.const 10))
   )
  )
  (loop $l7
   (block $b7
    (drop (i32.const 11))
    (br_if $l7 (i32.const 0))
    (br_if $b7 (i32.const 0))
    (drop (i32.const 13))
   )
  )
  (loop $l8
   (block $b8
    (drop (i32.const 14))
    (br_if $b8 (i32.const 0))
    (br_if $l8 (i32.const 0))
    (drop (i32.const 16))
   )
  )
  (loop $l9
   (block $b9
    (drop (i32.const 17))
    (br_if $l9 (i32.const 0))
    (drop (i32.const 18))
    (br_if $l9 (i32.const 0))
    (drop (i32.const 19))
   )
  )
  (loop $l10
   (block $b10
    (drop (i32.const 20))
    (br_if $l10 (i32.const 0))
    (drop (i32.const 21))
   )
  )
  (loop $l11
   (block $b11
    (br_if $l11 (i32.const 0))
    (drop (i32.const 23))
   )
  )
  (loop $l12
   (block $b12
    (drop (i32.const 24))
    (br_if $l12 (i32.const 0))
   )
  )
 )
)

(module
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (type $1 (func (param i32)))

  ;; CHECK:      (tag $e (type $1) (param i32))
  (tag $e (param i32))
  ;; CHECK:      (func $foo (type $0)
  ;; CHECK-NEXT: )
  (func $foo)

  ;; 'nop' within 'block' of `throw' can be hoisted
  ;; CHECK:      (func $throw (type $0)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (throw $e
  ;; CHECK-NEXT:   (i32.const 3)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $throw
    (throw $e
      (block (result i32)
        (nop)
        (i32.const 3)
      )
    )
  )
)
