;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.

;; RUN: wasm-opt -all %s --remove-unused-types -S -o - | filecheck %s --check-prefix=OPEN
;; RUN: wasm-opt -all %s --remove-unused-types --closed-world -S -o - | filecheck %s --check-prefix=CLOS

(module
  ;; OPEN:      (type $struct (sub (struct (field $field0 i32))))
  ;; CLOS:      (rec
  ;; CLOS-NEXT:  (type $struct (sub (struct (field $field0 i32))))
  (type $struct (sub (struct (field $field0 i32))))
  ;; OPEN:      (type $f (func (param (ref null $struct))))
  ;; CLOS:       (type $f (func (param (ref null $struct))))
  (type $f (func (param (ref null $struct))))

  (table $table (import "" "") 0 funcref)

  ;; OPEN:      (func $test (type $1)
  ;; OPEN-NEXT:  (call_indirect $table (type $f)
  ;; OPEN-NEXT:   (ref.null none)
  ;; OPEN-NEXT:   (i32.const 0)
  ;; OPEN-NEXT:  )
  ;; OPEN-NEXT: )
  ;; CLOS:      (func $test (type $2)
  ;; CLOS-NEXT:  (call_indirect $table (type $f)
  ;; CLOS-NEXT:   (ref.null none)
  ;; CLOS-NEXT:   (i32.const 0)
  ;; CLOS-NEXT:  )
  ;; CLOS-NEXT: )
  (func $test
    ;; Type $f should be considered public in an open world because `func` is
    ;; exposed. In a closed world it is still private.
    (call_indirect (type $f)
      (ref.null none)
      (i32.const 0)
    )
  )
)
