;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --remove-unused-names -S -o - | filecheck %s

(module
  (memory 256 256)
  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (type $0 (func (param i32) (result i32)))
  (type $0 (func (param i32) (result i32)))
  (type $1 (func))
  ;; CHECK:      (type $2 (func (result i32)))

  ;; CHECK:      (memory $0 256 256)

  ;; CHECK:      (func $b0 (param $i1 i32) (result i32)
  ;; CHECK-NEXT:  (i32.const 0)
  ;; CHECK-NEXT: )
  (func $b0 (type $0) (param $i1 i32) (result i32)
    (block $topmost (result i32)
      (i32.const 0)
    )
  )
  ;; CHECK:      (func $loops
  ;; CHECK-NEXT:  (block $out
  ;; CHECK-NEXT:   (loop $in
  ;; CHECK-NEXT:    (br $out)
  ;; CHECK-NEXT:    (br $in)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (loop $in0
  ;; CHECK-NEXT:   (br $in0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT:  (block $out1
  ;; CHECK-NEXT:   (loop $in3
  ;; CHECK-NEXT:    (br $out1)
  ;; CHECK-NEXT:    (br $in3)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block $out2
  ;; CHECK-NEXT:   (loop $in4
  ;; CHECK-NEXT:    (br $out2)
  ;; CHECK-NEXT:    (br $in4)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (loop $in5
  ;; CHECK-NEXT:   (block $out3
  ;; CHECK-NEXT:    (br $out3)
  ;; CHECK-NEXT:    (br $in5)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (loop $in6
  ;; CHECK-NEXT:   (block $out4
  ;; CHECK-NEXT:    (br $out4)
  ;; CHECK-NEXT:    (br $in6)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block $out5
  ;; CHECK-NEXT:   (loop $in7
  ;; CHECK-NEXT:    (br $out5)
  ;; CHECK-NEXT:    (br $in7)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $loops (type $1)
    (block $out
      (loop $in
        (br $out)
        (br $in)
      )
    )
    (loop $in
      (br $in)
    )
    (loop $in
      (nop)
    )
    (block $out
      (loop $in
        (block $out
          (loop $in
            (br $out)
            (br $in)
          )
        )
      )
    )
    (block $out
      (loop $in
        (br $out)
        (br $in)
      )
    )
    (loop $in
      (block $out
        (br $out)
        (br $in)
      )
    )
    (loop $in
      (block $out
        (br $out)
        (br $in)
      )
    )
    (block $out
      (loop $in
        (br $out)
        (br $in)
      )
    )
  )
  ;; CHECK:      (func $merges
  ;; CHECK-NEXT:  (block $b
  ;; CHECK-NEXT:   (br $b)
  ;; CHECK-NEXT:   (br $b)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block $b0
  ;; CHECK-NEXT:   (br_table $b0 $b0
  ;; CHECK-NEXT:    (i32.const 3)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (block $b1
  ;; CHECK-NEXT:   (br_table $b1 $b1
  ;; CHECK-NEXT:    (i32.const 3)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $merges (type $1)
    (block $a
      (block $b
        (br $a)
        (br $b)
      )
    )
    (block $a
      (block $b
        (br_table $a $b
          (i32.const 3)
        )
      )
    )
    (block $a
      (block $b
        (br_table $b $a
          (i32.const 3)
        )
      )
    )
  )
  ;; CHECK:      (func $merge-typed-with-unreachable-child (result i32)
  ;; CHECK-NEXT:  (local $0 f32)
  ;; CHECK-NEXT:  (block $label$1 (result i32)
  ;; CHECK-NEXT:   (br_if $label$1
  ;; CHECK-NEXT:    (i32.const 1)
  ;; CHECK-NEXT:    (br_if $label$1
  ;; CHECK-NEXT:     (i32.const 0)
  ;; CHECK-NEXT:     (br $label$1
  ;; CHECK-NEXT:      (i32.const 0)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $merge-typed-with-unreachable-child (result i32)
   (local $0 f32)
   (block $label$0 (result i32)
    (block $label$1 (result i32)
     (br_if $label$1
      (i32.const 1)
      (br_if $label$0
       (i32.const 0)
       (br $label$0
        (i32.const 0)
       )
      )
     )
    )
   )
  )
  ;; CHECK:      (func $loop-with-child-of-other-type
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (loop (result i32)
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $loop-with-child-of-other-type
   (drop
    (loop (result i32) ;; the loop has no name, but can't be replaced by the child
     (block $l         ;; as the type differs
      (unreachable)
     )
    )
   )
  )
)
