;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt %s -all --remove-catches -S -o - | filecheck %s

;; Remove all catch blocks.

(module
  ;; CHECK:      (tag $e (param i32))
  (tag $e (param i32))

  ;; CHECK:      (func $foo (type $none_=>_none)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $foo)
  ;; CHECK:      (func $bar (type $none_=>_none)
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $bar)

  ;; CHECK:      (func $try-catch (type $none_=>_none)
  ;; CHECK-NEXT:  (call $foo)
  ;; CHECK-NEXT: )
  (func $try-catch
    (try
      (do
        (call $foo)
      )
      (catch $e
        (drop (pop i32))
        (call $bar)
      )
    )
  )

  ;; CHECK:      (func $try-catch-all (type $none_=>_none)
  ;; CHECK-NEXT:  (throw $e
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $try-catch-all
    (try
      (do
        (throw $e (i32.const 0))
      )
      (catch_all
        (call $bar)
      )
    )
  )

  ;; CHECK:      (func $try-catch-nested (type $none_=>_none)
  ;; CHECK-NEXT:  (call $foo)
  ;; CHECK-NEXT: )
  (func $try-catch-nested
    (try
      (do
        (try
          (do
            (call $foo)
          )
          (catch $e
            (drop (pop i32))
          )
        )
      )
      (catch_all
        (try
          (do
            (call $bar)
          )
          (catch_all
            (call $bar)
          )
        )
      )
    )
  )
)
