;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --remove-unused-brs --precompute --vacuum --remove-unused-brs -S -o - | filecheck %s

(module
 ;; CHECK:      (type $0 (func (param i32) (result f64)))

 ;; CHECK:      (global $global$3 (mut f64) (f64.const 0))
 (global $global$3 (mut f64) (f64.const 0))
 ;; CHECK:      (func $1 (param $x i32) (result f64)
 ;; CHECK-NEXT:  (local $var$0 f64)
 ;; CHECK-NEXT:  (block $label$0 (result f64)
 ;; CHECK-NEXT:   (local.set $var$0
 ;; CHECK-NEXT:    (f64.const 0)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (f64.const -3.4)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $1 (param $x i32) (result f64)
  (local $var$0 f64)
  (block $label$0
   (local.set $var$0
    (f64.const 0)
   )
   (if
    (i32.gt_s
     (i32.const 9)
     (i32.const 0)
    )
    (then
     (return
      (f64.const -3.4)
     )
    )
   )
   (if
    (local.get $x)
    (then
     (return
      (f64.const 5.6)
     )
    )
   )
   (return
    (f64.const 1.2)
   )
  )
 )
)
