;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --remove-unused-names --vacuum -S -o - | filecheck %s

(module
  ;; CHECK:      (type $0 (func (result i32)))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (func $return-i32-but-body-is-unreachable3 (result i32)
  ;; CHECK-NEXT:  (local $label i32)
  ;; CHECK-NEXT:  (loop $while-in$1
  ;; CHECK-NEXT:   (br $while-in$1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $return-i32-but-body-is-unreachable3 (result i32)
    (local $label i32)
    (block ;; without a name here, vaccum had a too-eager bug
      (loop $while-in$1
        (br $while-in$1)
      )
    )
  )
  ;; CHECK:      (func $return-i32-but-body-is-unreachable4 (result i32)
  ;; CHECK-NEXT:  (local $label i32)
  ;; CHECK-NEXT:  (loop $while-in$1
  ;; CHECK-NEXT:   (br $while-in$1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $return-i32-but-body-is-unreachable4 (result i32)
    (local $label i32)
    (block ;; without a name here, vaccum had a too-eager bug
      (loop $while-in$1
        (br $while-in$1)
      )
    )
    (i32.const 0)
  )
  ;; CHECK:      (func $to-drop-unreachable
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $to-drop-unreachable
   (drop
    (block (result i32)
     (unreachable)
    )
   )
  )
  ;; CHECK:      (func $return-i32-but-body-is-unreachable5 (result i32)
  ;; CHECK-NEXT:  (local $label i32)
  ;; CHECK-NEXT:  (unreachable)
  ;; CHECK-NEXT: )
  (func $return-i32-but-body-is-unreachable5 (result i32)
    (local $label i32)
    (block ;; without a name here, vaccum had a too-eager bug
      (unreachable)
    )
  )
  ;; CHECK:      (func $return-i32-but-body-is-unreachable6 (result i32)
  ;; CHECK-NEXT:  (local $label i32)
  ;; CHECK-NEXT:  (unreachable)
  ;; CHECK-NEXT: )
  (func $return-i32-but-body-is-unreachable6 (result i32)
    (local $label i32)
    (block ;; without a name here, vaccum had a too-eager bug
      (unreachable)
    )
    (i32.const 0)
  )
)

