;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; RUN: wasm-opt %s --remove-unused-module-elements --closed-world -all -S -o - | filecheck %s

(module
  ;; CHECK:      (type $none_=>_none (func))

  ;; CHECK:      (elem declare func $unused)

  ;; CHECK:      (export "foo" (func $exported))

  ;; CHECK:      (func $unused (type $none_=>_none)
  ;; CHECK-NEXT:  (unreachable)
  ;; CHECK-NEXT: )
  (func $unused
    ;; Even though we take a reference to this function, we do not call it and
    ;; we are assuming the outside world won't call it, so we can optimize out
    ;; its body.
    (nop)
  )

  ;; CHECK:      (func $exported (type $none_=>_none)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.func $unused)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $exported (export "foo")
    ;; This pass can't prove that this reference won't escape.
    (drop
      (ref.func $unused)
    )
  )
)
