;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt --remove-unused-module-elements --closed-world -all -S -o - | filecheck %s

(module
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (elem declare func $js.called.referred)

  ;; CHECK:      (export "export" (func $export))

  ;; CHECK:      (@binaryen.js.called)
  ;; CHECK-NEXT: (func $js.called.referred (type $0)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 10)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (@binaryen.js.called)
  (func $js.called.referred
    ;; This is jsCalled, and referred below, so it is kept.
    (drop (i32.const 10))
  )

  ;; CHECK:      (func $export (type $0)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (ref.func $js.called.referred)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $export (export "export")
    (drop (ref.func $js.called.referred))
  )

  (@binaryen.js.called)
  (func $js.called.unreferred
    ;; This is jsCalled, and not referred anywhere. The annotation does not
    ;; stop the function from being removed entirely.
    (drop (i32.const 20))
  )
)
