;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt %s --remove-unused-brs -all -S -o - \
;; RUN:   | filecheck %s

(module
  ;; CHECK:      (func $if-br (type $0) (param $x i32)
  ;; CHECK-NEXT:  (block $out
  ;; CHECK-NEXT:   (@metadata.code.branch_hint "\01")
  ;; CHECK-NEXT:   (br_if $out
  ;; CHECK-NEXT:    (local.get $x)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT:  (unreachable)
  ;; CHECK-NEXT: )
  (func $if-br (param $x i32)
    (block $out
      ;; The if-br will turn into a br_if. The branch hint should then go on the
      ;; br_if, and remain 01.
      (@metadata.code.branch_hint "\01")
      (if
        (local.get $x)
        (then
          (br $out)
        )
      )
    )
    (unreachable)
  )
)
