;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --remove-unused-names --precompute -S -o - | filecheck %s

(module
 ;; CHECK:      (type $0 (func (param i32)))

 ;; CHECK:      (memory $0 256 256)
 (memory $0 256 256)
 ;; CHECK:      (func $__ZN10WasmAssertC2Ev__async_cb (param $$0 i32)
 ;; CHECK-NEXT:  (block $switch-default
 ;; CHECK-NEXT:   (nop)
 ;; CHECK-NEXT:   (block
 ;; CHECK-NEXT:    (i32.store
 ;; CHECK-NEXT:     (i32.const 12)
 ;; CHECK-NEXT:     (i32.const 26)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (return)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (block
 ;; CHECK-NEXT:   (local.set $$0
 ;; CHECK-NEXT:    (i32.const 4)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (i32.store
 ;; CHECK-NEXT:    (local.get $$0)
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $__ZN10WasmAssertC2Ev__async_cb (param $$0 i32)
  (block $switch-default
   (block $switch-case
    (br_table $switch-case $switch-default
     (i32.const 0)
    )
   )
   (block
    (i32.store
     (i32.const 12)
     (i32.const 26)
    )
    (return)
   )
  )
  (block
   (local.set $$0
    (i32.const 4)
   )
   (i32.store
    (local.get $$0)
    (i32.const 1)
   )
  )
 )
)
