;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.

;; RUN: wasm-opt %s -all --remove-unused-brs -S -o - | filecheck %s

;; Check that we optimize the cast correctly when the fallthrough has exact
;; type. In particular, we should not insert a ref.as_non_null, which would
;; trap.

(module
 ;; CHECK:      (type $struct (struct))
 (type $struct (struct))
 ;; CHECK:      (func $br_on_cast_fail (type $1) (param $0 (ref null exact $struct))
 ;; CHECK-NEXT:  (local $1 (ref null $struct))
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (block $block
 ;; CHECK-NEXT:    (drop
 ;; CHECK-NEXT:     (ref.cast (ref null exact $struct)
 ;; CHECK-NEXT:      (local.tee $1
 ;; CHECK-NEXT:       (local.get $0)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (return)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $br_on_cast_fail (param (ref null exact $struct))
  (local $1 (ref null $struct))
  (drop
   (block $block (result (ref $struct))
    (drop
     (br_on_cast_fail $block (ref null $struct) (ref null $struct)
      (local.tee $1
       (local.get 0)
      )
     )
    )
    (return)
   )
  )
 )
)
