;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt "--remove-exports=foo<x,y>,bar" -all -S -o - | filecheck %s

;; The two exports mentioned will be removed (note the handling of comma
;; separation, taking into account bracketing). The other will remain.
(module
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (export "keep" (func $keep))

  ;; CHECK:      (func $"foo<x,y>" (type $0)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 1)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $"foo<x,y>" (export "foo<x,y>")
    (drop (i32.const 1))
  )

  ;; CHECK:      (func $bar (type $0)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 2)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $bar (export "bar")
    (drop (i32.const 2))
  )

  ;; CHECK:      (func $keep (type $0)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 3)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $keep (export "keep")
    (drop (i32.const 3))
  )
)
