;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --reorder-functions -S -o - | filecheck %s

(module
  (memory 256 256)
  ;; CHECK:      (type $0 (func))
  (type $0 (func))
  ;; CHECK:      (memory $0 256 256)

  ;; CHECK:      (func $c
  ;; CHECK-NEXT:  (call $c)
  ;; CHECK-NEXT:  (call $c)
  ;; CHECK-NEXT:  (call $c)
  ;; CHECK-NEXT: )

  ;; CHECK:      (func $b
  ;; CHECK-NEXT:  (call $b)
  ;; CHECK-NEXT:  (call $b)
  ;; CHECK-NEXT: )

  ;; CHECK:      (func $a
  ;; CHECK-NEXT:  (call $a)
  ;; CHECK-NEXT: )
  (func $a (type $0)
    (call $a)
  )
  (func $b (type $0)
    (call $b)
    (call $b)
  )
  (func $c (type $0)
    (call $c)
    (call $c)
    (call $c)
  )
)
