;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --simplify-locals -S -o - | filecheck %s

(module
 ;; CHECK:      (type $0 (func (result i32)))

 ;; CHECK:      (func $sink-from-inside (result i32)
 ;; CHECK-NEXT:  (local $0 i32)
 ;; CHECK-NEXT:  (local $1 i32)
 ;; CHECK-NEXT:  (local $2 i32)
 ;; CHECK-NEXT:  (nop)
 ;; CHECK-NEXT:  (i32.and
 ;; CHECK-NEXT:   (select
 ;; CHECK-NEXT:    (i32.const 0)
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (block (result i32)
 ;; CHECK-NEXT:    (nop)
 ;; CHECK-NEXT:    (nop)
 ;; CHECK-NEXT:    (nop)
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $sink-from-inside (result i32)
  (local $0 i32)
  (local $1 i32)
  (local $2 i32)
  (local.set $2
   (block (result i32)
    (local.set $0
     (i32.const 1)
    )
    (drop
     (local.get $0)
    )
    (local.set $1 ;; after we sink this, must be careful about sinking the parent, to not reorder other things badly
     (select
      (i32.const 0)
      (i32.const 1)
      (local.get $0)
     )
    )
    (i32.const 1)
   )
  )
  (i32.and
   (local.get $1)
   (local.get $2)
  )
 )
)
