;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.

;; RUN: wasm-opt %s --simplify-locals -all -S -o - | filecheck %s

(module
 (rec
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $struct (descriptor $desc (struct)))
  (type $struct (descriptor $desc (struct)))
  ;; CHECK:       (type $desc (sub (describes $struct (struct))))
  (type $desc (sub (describes $struct (struct))))
 )

 ;; CHECK:      (func $test (type $2)
 ;; CHECK-NEXT:  (local $l (ref null $struct))
 ;; CHECK-NEXT:  (drop
 ;; CHECK-NEXT:   (struct.new_default $struct
 ;; CHECK-NEXT:    (ref.null none)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $test (export "test")
  (local $l (ref null $struct))
  (local.set $l
   ;; We should preserve this trap.
   (struct.new_default $struct
    (ref.null none)
   )
  )
 )
)
