;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --souperify -S -o - | filecheck %s

(module
  ;; This tests if we can create dataflow graph correctly in the presence of
  ;; loops.
  ;; CHECK:      (type $0 (func))

  ;; CHECK:      (func $if-loop-test
  ;; CHECK-NEXT:  (local $0 i32)
  ;; CHECK-NEXT:  (if
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:   (then
  ;; CHECK-NEXT:    (loop $label$0
  ;; CHECK-NEXT:     (local.set $0
  ;; CHECK-NEXT:      (i32.sub
  ;; CHECK-NEXT:       (i32.const 0)
  ;; CHECK-NEXT:       (i32.const 0)
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $if-loop-test (local $0 i32)
    (if
      (i32.const 0)
      (then
        (loop $label$0
          (local.set $0
            (i32.sub
              (i32.const 0)
              (i32.const 0)
            )
          )
        )
      )
    )
  )
)
