;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; Similar to string-lowering-imports but the strings are imported from a
;; custom module name. The string constant should be imported from "strings", as
;; the pass-arg specifies.

;; RUN: wasm-opt %s -all --string-lowering-magic-imports --pass-arg=string-constants-module@strings -S -o - | filecheck %s

(module
  ;; CHECK:      (type $0 (array (mut i16)))

  ;; CHECK:      (type $1 (shared (array (mut i16))))

  ;; CHECK:      (type $2 (func (param externref externref) (result i32)))

  ;; CHECK:      (type $3 (func (param externref) (result i32)))

  ;; CHECK:      (type $4 (func (param (ref null (shared extern)) (ref null (shared extern))) (result i32)))

  ;; CHECK:      (type $5 (func (param (ref null (shared extern))) (result i32)))

  ;; CHECK:      (type $6 (func))

  ;; CHECK:      (type $7 (func (param (ref null $0) i32 i32) (result (ref extern))))

  ;; CHECK:      (type $8 (func (param i32) (result (ref extern))))

  ;; CHECK:      (type $9 (func (param externref externref) (result (ref extern))))

  ;; CHECK:      (type $10 (func (param externref (ref null $0) i32) (result i32)))

  ;; CHECK:      (type $11 (func (param externref i32) (result i32)))

  ;; CHECK:      (type $12 (func (param externref i32 i32) (result (ref extern))))

  ;; CHECK:      (type $13 (func (param (ref null $1) i32 i32) (result (ref (shared extern)))))

  ;; CHECK:      (type $14 (func (param i32) (result (ref (shared extern)))))

  ;; CHECK:      (type $15 (func (param (ref null (shared extern)) (ref null (shared extern))) (result (ref (shared extern)))))

  ;; CHECK:      (type $16 (func (param (ref null (shared extern)) (ref null $1) i32) (result i32)))

  ;; CHECK:      (type $17 (func (param (ref null (shared extern)) i32) (result i32)))

  ;; CHECK:      (type $18 (func (param (ref null (shared extern)) i32 i32) (result (ref (shared extern)))))

  ;; CHECK:      (import "strings" "foo" (global $"string.const_\"foo\"" (ref extern)))

  ;; CHECK:      (import "wasm:js-string" "fromCharCodeArray" (func $fromCharCodeArray (type $7) (param (ref null $0) i32 i32) (result (ref extern))))

  ;; CHECK:      (import "wasm:js-string" "fromCodePoint" (func $fromCodePoint (type $8) (param i32) (result (ref extern))))

  ;; CHECK:      (import "wasm:js-string" "concat" (func $concat (type $9) (param externref externref) (result (ref extern))))

  ;; CHECK:      (import "wasm:js-string" "intoCharCodeArray" (func $intoCharCodeArray (type $10) (param externref (ref null $0) i32) (result i32)))

  ;; CHECK:      (import "wasm:js-string" "equals" (func $equals (type $2) (param externref externref) (result i32)))

  ;; CHECK:      (import "wasm:js-string" "test" (func $test (type $3) (param externref) (result i32)))

  ;; CHECK:      (import "wasm:js-string" "compare" (func $compare (type $2) (param externref externref) (result i32)))

  ;; CHECK:      (import "wasm:js-string" "length" (func $length (type $3) (param externref) (result i32)))

  ;; CHECK:      (import "wasm:js-string" "charCodeAt" (func $charCodeAt (type $11) (param externref i32) (result i32)))

  ;; CHECK:      (import "wasm:js-string" "substring" (func $substring (type $12) (param externref i32 i32) (result (ref extern))))

  ;; CHECK:      (import "wasm:js-string" "fromCharCodeArray" (func $fromCharCodeArray_11 (type $13) (param (ref null $1) i32 i32) (result (ref (shared extern)))))

  ;; CHECK:      (import "wasm:js-string" "fromCodePoint" (func $fromCodePoint_12 (type $14) (param i32) (result (ref (shared extern)))))

  ;; CHECK:      (import "wasm:js-string" "concat" (func $concat_13 (type $15) (param (ref null (shared extern)) (ref null (shared extern))) (result (ref (shared extern)))))

  ;; CHECK:      (import "wasm:js-string" "intoCharCodeArray" (func $intoCharCodeArray_14 (type $16) (param (ref null (shared extern)) (ref null $1) i32) (result i32)))

  ;; CHECK:      (import "wasm:js-string" "equals" (func $equals_15 (type $4) (param (ref null (shared extern)) (ref null (shared extern))) (result i32)))

  ;; CHECK:      (import "wasm:js-string" "test" (func $test_16 (type $5) (param (ref null (shared extern))) (result i32)))

  ;; CHECK:      (import "wasm:js-string" "compare" (func $compare_17 (type $4) (param (ref null (shared extern)) (ref null (shared extern))) (result i32)))

  ;; CHECK:      (import "wasm:js-string" "length" (func $length_18 (type $5) (param (ref null (shared extern))) (result i32)))

  ;; CHECK:      (import "wasm:js-string" "charCodeAt" (func $charCodeAt_19 (type $17) (param (ref null (shared extern)) i32) (result i32)))

  ;; CHECK:      (import "wasm:js-string" "substring" (func $substring_20 (type $18) (param (ref null (shared extern)) i32 i32) (result (ref (shared extern)))))

  ;; CHECK:      (export "const" (func $const))

  ;; CHECK:      (func $const (type $6)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (global.get $"string.const_\"foo\"")
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $const (export "const")
    (drop
      (string.const "foo")
    )
  )
)
