;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; Similar to string-lowering-imports but the strings are imported from a
;; custom module name.

;; RUN: wasm-opt %s -all --string-lowering-magic-imports --pass-arg=string-lowering-const-module@strings -S -o - | filecheck %s

(module
  (func $const (export "const")
    (drop
      (string.const "foo")
    )
  )
)
