;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; RUN: foreach %s %t wasm-opt -all --preserve-type-order --unsubtyping -all -S -o - | filecheck %s

;; No public types. We can still optimize.
(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:      (global $use-super (ref null $super) (ref.null none))
  (global $use-super (ref null $super) (ref.null none))
  ;; CHECK:      (global $use-sub (ref null $sub) (ref.null none))
  (global $use-sub (ref null $sub) (ref.null none))
)

;; func is public, so we cannot optimize any functions. We can still optimize
;; structs.
(module
  ;; CHECK:      (type $super-func (sub (func)))
  (type $super-func (sub (func)))
  ;; CHECK:      (type $sub-func (sub $super-func (func)))
  (type $sub-func (sub $super-func (func)))
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super-struct (sub (struct)))
  (type $super-struct (sub (struct)))
  ;; CHECK:       (type $sub-struct (sub (struct)))
  (type $sub-struct (sub $super-struct (struct)))

  ;; CHECK:      (global $g-func funcref (ref.null nofunc))
  (global $g-func funcref (ref.null nofunc))
  ;; CHECK:      (global $use-super-func (ref null $super-func) (ref.null nofunc))
  (global $use-super-func (ref null $super-func) (ref.null nofunc))
  ;; CHECK:      (global $use-sub-func (ref null $sub-func) (ref.null nofunc))
  (global $use-sub-func (ref null $sub-func) (ref.null nofunc))
  ;; CHECK:      (global $use-super-struct (ref null $super-struct) (ref.null none))
  (global $use-super-struct (ref null $super-struct) (ref.null none))
  ;; CHECK:      (global $use-sub-struct (ref null $sub-struct) (ref.null none))
  (global $use-sub-struct (ref null $sub-struct) (ref.null none))
  ;; CHECK:      (export "g-func" (global $g-func))
  (export "g-func" (global $g-func))
)

;; any is public, so we cannot optimize any structs or arrays. We can still
;; optimize functions.
(module
  ;; CHECK:      (type $super-struct (sub (struct)))
  (type $super-struct (sub (struct)))
  ;; CHECK:      (type $sub-struct (sub $super-struct (struct)))
  (type $sub-struct (sub $super-struct (struct)))
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super-func (sub (func)))
  (type $super-func (sub (func)))
  ;; CHECK:       (type $sub-func (sub (func)))
  (type $sub-func (sub $super-func (func)))

  ;; CHECK:      (global $g-any anyref (ref.null none))
  (global $g-any anyref (ref.null none))
  ;; CHECK:      (global $use-super-struct (ref null $super-struct) (ref.null none))
  (global $use-super-struct (ref null $super-struct) (ref.null none))
  ;; CHECK:      (global $use-sub-struct (ref null $sub-struct) (ref.null none))
  (global $use-sub-struct (ref null $sub-struct) (ref.null none))
  ;; CHECK:      (global $use-super-func (ref null $super-func) (ref.null nofunc))
  (global $use-super-func (ref null $super-func) (ref.null nofunc))
  ;; CHECK:      (global $use-sub-func (ref null $sub-func) (ref.null nofunc))
  (global $use-sub-func (ref null $sub-func) (ref.null nofunc))
  ;; CHECK:      (export "g-any" (global $g-any))
  (export "g-any" (global $g-any))
)

;; i31 is public. We can still optimize structs.
(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super-struct (sub (struct)))
  (type $super-struct (sub (struct)))
  ;; CHECK:       (type $sub-struct (sub (struct)))
  (type $sub-struct (sub $super-struct (struct)))

  ;; CHECK:      (global $g-i31 i31ref (ref.null none))
  (global $g-i31 i31ref (ref.null none))
  ;; CHECK:      (global $use-super-struct (ref null $super-struct) (ref.null none))
  (global $use-super-struct (ref null $super-struct) (ref.null none))
  ;; CHECK:      (global $use-sub-struct (ref null $sub-struct) (ref.null none))
  (global $use-sub-struct (ref null $sub-struct) (ref.null none))
  ;; CHECK:      (export "g-i31" (global $g-i31))
  (export "g-i31" (global $g-i31))
)

;; eq is public. We cannot optimize structs.
(module
  ;; CHECK:      (type $super-struct (sub (struct)))
  (type $super-struct (sub (struct)))
  ;; CHECK:      (type $sub-struct (sub $super-struct (struct)))
  (type $sub-struct (sub $super-struct (struct)))

  ;; CHECK:      (global $g-eq eqref (ref.null none))
  (global $g-eq eqref (ref.null none))
  ;; CHECK:      (global $use-super-struct (ref null $super-struct) (ref.null none))
  (global $use-super-struct (ref null $super-struct) (ref.null none))
  ;; CHECK:      (global $use-sub-struct (ref null $sub-struct) (ref.null none))
  (global $use-sub-struct (ref null $sub-struct) (ref.null none))
  ;; CHECK:      (export "g-eq" (global $g-eq))
  (export "g-eq" (global $g-eq))
)

;; We cannot optimize subtypes of a publicly exposed defined type. We can still
;; optimize unrelated types.
(module
  ;; CHECK:      (type $public-parent (sub (struct)))
  (type $public-parent (sub (struct)))
  ;; CHECK:      (type $public-child (sub $public-parent (struct)))
  (type $public-child (sub $public-parent (struct)))
  ;; CHECK:      (type $public-grandchild (sub $public-child (struct)))
  (type $public-grandchild (sub $public-child (struct)))
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $unrelated-super (sub (struct (field i32))))
  (type $unrelated-super (sub (struct (field i32))))
  ;; CHECK:       (type $unrelated-sub (sub (struct (field i32) (field f32))))
  (type $unrelated-sub (sub $unrelated-super (struct i32 f32)))

  ;; CHECK:      (global $g-public (ref null $public-parent) (ref.null none))
  (global $g-public (ref null $public-parent) (ref.null none))
  ;; CHECK:      (global $use-public-child (ref null $public-child) (ref.null none))
  (global $use-public-child (ref null $public-child) (ref.null none))
  ;; CHECK:      (global $use-public-grandchild (ref null $public-grandchild) (ref.null none))
  (global $use-public-grandchild (ref null $public-grandchild) (ref.null none))
  ;; CHECK:      (global $use-unrelated-super (ref null $unrelated-super) (ref.null none))
  (global $use-unrelated-super (ref null $unrelated-super) (ref.null none))
  ;; CHECK:      (global $use-unrelated-sub (ref null $unrelated-sub) (ref.null none))
  (global $use-unrelated-sub (ref null $unrelated-sub) (ref.null none))
  ;; CHECK:      (export "g-public" (global $g-public))
  (export "g-public" (global $g-public))
)

;; When a type is exposed exactly, we can still optimize its subtypes.
(module
  ;; CHECK:      (type $public-parent (sub (struct)))
  (type $public-parent (sub (struct)))
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $public-child (sub (struct)))
  (type $public-child (sub $public-parent (struct)))
  ;; CHECK:       (type $public-grandchild (sub (struct)))
  (type $public-grandchild (sub $public-child (struct)))

  ;; CHECK:      (global $g-public (ref (exact $public-parent)) (struct.new_default $public-parent))
  (global $g-public (ref (exact $public-parent)) (struct.new_default $public-parent))
  ;; CHECK:      (global $use-public-child (ref null $public-child) (ref.null none))
  (global $use-public-child (ref null $public-child) (ref.null none))
  ;; CHECK:      (global $use-public-grandchild (ref null $public-grandchild) (ref.null none))
  (global $use-public-grandchild (ref null $public-grandchild) (ref.null none))
  ;; CHECK:      (export "g-public" (global $g-public))
  (export "g-public" (global $g-public))
)

;; We cannot optimize a type referenced from a publicly exposed type, nor a
;; subtype of that type.
(module
  ;; CHECK:      (type $referenced-super (sub (struct)))
  (type $referenced-super (sub (struct)))
  ;; CHECK:      (type $referenced (sub $referenced-super (struct)))
  (type $referenced (sub $referenced-super (struct)))
  ;; CHECK:      (type $referenced-child (sub $referenced (struct)))
  (type $referenced-child (sub $referenced (struct)))
  ;; CHECK:      (type $public (sub (struct (field (ref $referenced)))))
  (type $public (sub (struct (field (ref $referenced)))))

  ;; CHECK:      (global $g-public (ref null $public) (ref.null none))
  (global $g-public (ref null $public) (ref.null none))
  ;; CHECK:      (global $use-referenced-super (ref null $referenced-super) (ref.null none))
  (global $use-referenced-super (ref null $referenced-super) (ref.null none))
  ;; CHECK:      (global $use-referenced (ref null $referenced) (ref.null none))
  (global $use-referenced (ref null $referenced) (ref.null none))
  ;; CHECK:      (global $use-referenced-child (ref null $referenced-child) (ref.null none))
  (global $use-referenced-child (ref null $referenced-child) (ref.null none))
  ;; CHECK:      (export "g-public" (global $g-public))
  (export "g-public" (global $g-public))
)

;; Same, but with the public type exposed exactly. We still cannot optimize
;; subtypes of the reachable type.
(module
  ;; CHECK:      (type $referenced-super (sub (struct)))
  (type $referenced-super (sub (struct)))
  ;; CHECK:      (type $referenced (sub $referenced-super (struct)))
  (type $referenced (sub $referenced-super (struct)))
  ;; CHECK:      (type $referenced-child (sub $referenced (struct)))
  (type $referenced-child (sub $referenced (struct)))
  ;; CHECK:      (type $public (sub (struct (field (ref null $referenced)))))
  (type $public (sub (struct (field (ref null $referenced)))))

  ;; CHECK:      (global $g-public (ref (exact $public)) (struct.new_default $public))
  (global $g-public (ref (exact $public)) (struct.new_default $public))
  ;; CHECK:      (global $use-referenced-super (ref null $referenced-super) (ref.null none))
  (global $use-referenced-super (ref null $referenced-super) (ref.null none))
  ;; CHECK:      (global $use-referenced (ref null $referenced) (ref.null none))
  (global $use-referenced (ref null $referenced) (ref.null none))
  ;; CHECK:      (global $use-referenced-child (ref null $referenced-child) (ref.null none))
  (global $use-referenced-child (ref null $referenced-child) (ref.null none))
  ;; CHECK:      (export "g-public" (global $g-public))
  (export "g-public" (global $g-public))
)

;; When the referenced type is referenced exactly, we still cannot optimize it,
;; but we can optimize its subtypes.
(module
  ;; CHECK:      (type $referenced-super (sub (struct)))
  (type $referenced-super (sub (struct)))
  ;; CHECK:      (type $referenced (sub $referenced-super (struct)))
  (type $referenced (sub $referenced-super (struct)))
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $referenced-child (sub (struct)))
  (type $referenced-child (sub $referenced (struct)))
  ;; CHECK:       (type $3 (struct))

  ;; CHECK:      (type $public (sub (struct (field (ref (exact $referenced))))))
  (type $public (sub (struct (field (ref (exact $referenced))))))

  ;; CHECK:      (global $g-public (ref null $public) (ref.null none))
  (global $g-public (ref null $public) (ref.null none))
  ;; CHECK:      (global $use-referenced-super (ref null $referenced-super) (ref.null none))
  (global $use-referenced-super (ref null $referenced-super) (ref.null none))
  ;; CHECK:      (global $use-referenced (ref null $referenced) (ref.null none))
  (global $use-referenced (ref null $referenced) (ref.null none))
  ;; CHECK:      (global $use-referenced-child (ref null $referenced-child) (ref.null none))
  (global $use-referenced-child (ref null $referenced-child) (ref.null none))
  ;; CHECK:      (export "g-public" (global $g-public))
  (export "g-public" (global $g-public))
)

;; When func is exposed indirectly because it is referenced by a publicly
;; exposed type, we still cannot optimize any function types.
(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super-struct (sub (struct)))
  (type $super-struct (sub (struct)))
  ;; CHECK:       (type $sub-struct (sub (struct)))
  (type $sub-struct (sub $super-struct (struct)))
  ;; CHECK:      (type $super-func (sub (func)))
  (type $super-func (sub (func)))
  ;; CHECK:      (type $sub-func (sub $super-func (func)))
  (type $sub-func (sub $super-func (func)))
  ;; CHECK:      (type $public (sub (struct (field funcref))))
  (type $public (sub (struct (field funcref))))

  ;; CHECK:      (global $g-public (ref null $public) (ref.null none))
  (global $g-public (ref null $public) (ref.null none))
  ;; CHECK:      (global $use-super-struct (ref null $super-struct) (ref.null none))
  (global $use-super-struct (ref null $super-struct) (ref.null none))
  ;; CHECK:      (global $use-sub-struct (ref null $sub-struct) (ref.null none))
  (global $use-sub-struct (ref null $sub-struct) (ref.null none))
  ;; CHECK:      (global $use-super-func (ref null $super-func) (ref.null nofunc))
  (global $use-super-func (ref null $super-func) (ref.null nofunc))
  ;; CHECK:      (global $use-sub-func (ref null $sub-func) (ref.null nofunc))
  (global $use-sub-func (ref null $sub-func) (ref.null nofunc))
  ;; CHECK:      (export "g-public" (global $g-public))
  (export "g-public" (global $g-public))
)

;; We cannot optimize the supertype of a publicly exposed type, but we can
;; optimize other subtypes of the supertype.
(module
  ;; CHECK:      (type $super-super (sub (struct)))
  (type $super-super (sub (struct)))
  ;; CHECK:      (type $super (sub $super-super (struct)))
  (type $super (sub $super-super (struct)))
  ;; CHECK:      (type $public (sub $super (struct)))
  (type $public (sub $super (struct)))
  ;; CHECK:      (type $sibling-private (sub (struct (field i32))))
  (type $sibling-private (sub $super (struct (field i32))))

  ;; CHECK:      (global $g-public (ref null $public) (ref.null none))
  (global $g-public (ref null $public) (ref.null none))
  ;; CHECK:      (global $use-super-super (ref null $super-super) (ref.null none))
  (global $use-super-super (ref null $super-super) (ref.null none))
  ;; CHECK:      (global $use-super (ref null $super) (ref.null none))
  (global $use-super (ref null $super) (ref.null none))
  ;; CHECK:      (global $use-sibling-private (ref null $sibling-private) (ref.null none))
  (global $use-sibling-private (ref null $sibling-private) (ref.null none))
  ;; CHECK:      (export "g-public" (global $g-public))
  (export "g-public" (global $g-public))
)

;; We cannot optimize the descriptor of a publicly exposed type, nor subtypes of
;; that descriptor.
(module
  (rec
    ;; CHECK:      (rec
    ;; CHECK-NEXT:  (type $public-super (sub (descriptor $desc-super) (struct)))
    (type $public-super (sub (descriptor $desc-super) (struct)))
    ;; CHECK:       (type $desc-super (sub (describes $public-super) (struct)))
    (type $desc-super (sub (describes $public-super) (struct)))
  )
  (rec
    ;; CHECK:      (rec
    ;; CHECK-NEXT:  (type $public (sub $public-super (descriptor $desc) (struct)))
    (type $public (sub $public-super (descriptor $desc) (struct)))
    ;; CHECK:       (type $desc (sub $desc-super (describes $public) (struct)))
    (type $desc (sub $desc-super (describes $public) (struct)))
  )
  (rec
    ;; CHECK:      (rec
    ;; CHECK-NEXT:  (type $public-child (sub $public (descriptor $desc-child) (struct)))
    (type $public-child (sub $public (descriptor $desc-child) (struct)))
    ;; CHECK:       (type $desc-child (sub $desc (describes $public-child) (struct)))
    (type $desc-child (sub $desc (describes $public-child) (struct)))
  )

  ;; CHECK:      (global $g-public (ref null $public) (ref.null none))
  (global $g-public (ref null $public) (ref.null none))
  ;; CHECK:      (global $use-public-super (ref null $public-super) (ref.null none))
  (global $use-public-super (ref null $public-super) (ref.null none))
  ;; CHECK:      (global $use-desc-super (ref null $desc-super) (ref.null none))
  (global $use-desc-super (ref null $desc-super) (ref.null none))
  ;; CHECK:      (global $use-public-child (ref null $public-child) (ref.null none))
  (global $use-public-child (ref null $public-child) (ref.null none))
  ;; CHECK:      (global $use-desc (ref null $desc) (ref.null none))
  (global $use-desc (ref null $desc) (ref.null none))
  ;; CHECK:      (global $use-desc-child (ref null $desc-child) (ref.null none))
  (global $use-desc-child (ref null $desc-child) (ref.null none))
  ;; CHECK:      (export "g-public" (global $g-public))
  (export "g-public" (global $g-public))
)

;; When the publicly exposed type is exact, we cannot optimize its descriptor,
;; but we can optimize subtypes of that descriptor.
(module
  (rec
    ;; CHECK:      (rec
    ;; CHECK-NEXT:  (type $public-super (sub (descriptor $desc-super) (struct)))
    (type $public-super (sub (descriptor $desc-super) (struct)))
    ;; CHECK:       (type $desc-super (sub (describes $public-super) (struct)))
    (type $desc-super (sub (describes $public-super) (struct)))
  )
  (rec
    ;; CHECK:      (rec
    ;; CHECK-NEXT:  (type $public (sub $public-super (descriptor $desc) (struct)))
    (type $public (sub $public-super (descriptor $desc) (struct)))
    ;; CHECK:       (type $desc (sub $desc-super (describes $public) (struct)))
    (type $desc (sub $desc-super (describes $public) (struct)))
  )
  (rec
    ;; CHECK:      (rec
    ;; CHECK-NEXT:  (type $public-child (sub (struct)))
    (type $public-child (sub $public (descriptor $desc-child) (struct)))
    ;; CHECK:       (type $desc-child (sub (struct)))
    (type $desc-child (sub $desc (describes $public-child) (struct)))
  )

  ;; CHECK:      (global $g-public (ref (exact $public)) (struct.new_default_desc $public
  ;; CHECK-NEXT:  (struct.new_default $desc)
  ;; CHECK-NEXT: ))
  (global $g-public (ref (exact $public)) (struct.new_default_desc $public (struct.new_default $desc)))
  ;; CHECK:      (global $use-public-super (ref null $public-super) (ref.null none))
  (global $use-public-super (ref null $public-super) (ref.null none))
  ;; CHECK:      (global $use-desc-super (ref null $desc-super) (ref.null none))
  (global $use-desc-super (ref null $desc-super) (ref.null none))
  ;; CHECK:      (global $use-public-child (ref null $public-child) (ref.null none))
  (global $use-public-child (ref null $public-child) (ref.null none))
  ;; CHECK:      (global $use-desc-child (ref null $desc-child) (ref.null none))
  (global $use-desc-child (ref null $desc-child) (ref.null none))
  ;; CHECK:      (global $use-desc (ref null $desc) (ref.null none))
  (global $use-desc (ref null $desc) (ref.null none))
  ;; CHECK:      (export "g-public" (global $g-public))
  (export "g-public" (global $g-public))
)

;; We cannot optimize the described type of a publicly exposed type. We could
;; optimize subtypes of that described type, except that they are necessarily in
;; the same rec group as exposed subtypes of the publicly exposed type.
(module
  (rec
    ;; CHECK:      (rec
    ;; CHECK-NEXT:  (type $described-super (sub (descriptor $public-desc-super) (struct)))
    (type $described-super (sub (descriptor $public-desc-super) (struct)))
    ;; CHECK:       (type $public-desc-super (sub (describes $described-super) (struct)))
    (type $public-desc-super (sub (describes $described-super) (struct)))
  )
  (rec
    ;; CHECK:      (rec
    ;; CHECK-NEXT:  (type $described (sub $described-super (descriptor $public-desc) (struct)))
    (type $described (sub $described-super (descriptor $public-desc) (struct)))
    ;; CHECK:       (type $public-desc (sub $public-desc-super (describes $described) (struct)))
    (type $public-desc (sub $public-desc-super (describes $described) (struct)))
  )
  (rec
    ;; CHECK:      (rec
    ;; CHECK-NEXT:  (type $described-child (sub $described (descriptor $desc-child) (struct)))
    (type $described-child (sub $described (descriptor $desc-child) (struct)))
    ;; CHECK:       (type $desc-child (sub $public-desc (describes $described-child) (struct)))
    (type $desc-child (sub $public-desc (describes $described-child) (struct)))
  )

  ;; CHECK:      (global $g-public (ref null $public-desc) (ref.null none))
  (global $g-public (ref null $public-desc) (ref.null none))
  ;; CHECK:      (global $use-described-super (ref null $described-super) (ref.null none))
  (global $use-described-super (ref null $described-super) (ref.null none))
  ;; CHECK:      (global $use-public-desc-super (ref null $public-desc-super) (ref.null none))
  (global $use-public-desc-super (ref null $public-desc-super) (ref.null none))
  ;; CHECK:      (global $use-described-child (ref null $described-child) (ref.null none))
  (global $use-described-child (ref null $described-child) (ref.null none))
  ;; CHECK:      (global $use-desc-child (ref null $desc-child) (ref.null none))
  (global $use-desc-child (ref null $desc-child) (ref.null none))
  ;; CHECK:      (global $use-described (ref null $described) (ref.null none))
  (global $use-described (ref null $described) (ref.null none))
  ;; CHECK:      (export "g-public" (global $g-public))
  (export "g-public" (global $g-public))
)

;; We can still optimize subtypes of the described type when the publicly
;; exposed descriptor is exact.
(module
  (rec
    ;; CHECK:      (rec
    ;; CHECK-NEXT:  (type $described-super (sub (descriptor $public-desc-super) (struct)))
    (type $described-super (sub (descriptor $public-desc-super) (struct)))
    ;; CHECK:       (type $public-desc-super (sub (describes $described-super) (struct)))
    (type $public-desc-super (sub (describes $described-super) (struct)))
  )
  (rec
    ;; CHECK:      (rec
    ;; CHECK-NEXT:  (type $described (sub $described-super (descriptor $public-desc) (struct)))
    (type $described (sub $described-super (descriptor $public-desc) (struct)))
    ;; CHECK:       (type $public-desc (sub $public-desc-super (describes $described) (struct)))
    (type $public-desc (sub $public-desc-super (describes $described) (struct)))
  )
  (rec
    ;; CHECK:      (rec
    ;; CHECK-NEXT:  (type $described-child (sub (struct)))
    (type $described-child (sub $described (descriptor $desc-child) (struct)))
    ;; CHECK:       (type $desc-child (sub (struct)))
    (type $desc-child (sub $public-desc (describes $described-child) (struct)))
  )

  ;; CHECK:      (global $g-public (ref (exact $public-desc)) (struct.new_default $public-desc))
  (global $g-public (ref (exact $public-desc)) (struct.new_default $public-desc))
  ;; CHECK:      (global $use-described-super (ref null $described-super) (ref.null none))
  (global $use-described-super (ref null $described-super) (ref.null none))
  ;; CHECK:      (global $use-public-desc-super (ref null $public-desc-super) (ref.null none))
  (global $use-public-desc-super (ref null $public-desc-super) (ref.null none))
  ;; CHECK:      (global $use-described-child (ref null $described-child) (ref.null none))
  (global $use-described-child (ref null $described-child) (ref.null none))
  ;; CHECK:      (global $use-desc-child (ref null $desc-child) (ref.null none))
  (global $use-desc-child (ref null $desc-child) (ref.null none))
  ;; CHECK:      (global $use-described (ref null $described) (ref.null none))
  (global $use-described (ref null $described) (ref.null none))
  ;; CHECK:      (export "g-public" (global $g-public))
  (export "g-public" (global $g-public))
)

;; We cannot optimize rec groups siblings of a public type, but we can optimize
;; subtypes of those siblings.
(module
  ;; CHECK:      (type $sibling-super (sub (struct)))
  (type $sibling-super (sub (struct)))
  (rec
    ;; CHECK:      (rec
    ;; CHECK-NEXT:  (type $public (sub (struct)))
    (type $public (sub (struct)))
    ;; CHECK:       (type $sibling (sub $sibling-super (struct (field i32))))
    (type $sibling (sub $sibling-super (struct (field i32))))
  )
  ;; CHECK:      (type $sibling-child (sub (struct (field i32) (field f32))))
  (type $sibling-child (sub $sibling (struct i32 f32)))

  ;; CHECK:      (global $g-public (ref null $public) (ref.null none))
  (global $g-public (ref null $public) (ref.null none))
  ;; CHECK:      (global $use-sibling-super (ref null $sibling-super) (ref.null none))
  (global $use-sibling-super (ref null $sibling-super) (ref.null none))
  ;; CHECK:      (global $use-sibling (ref null $sibling) (ref.null none))
  (global $use-sibling (ref null $sibling) (ref.null none))
  ;; CHECK:      (global $use-sibling-child (ref null $sibling-child) (ref.null none))
  (global $use-sibling-child (ref null $sibling-child) (ref.null none))
  ;; CHECK:      (export "g-public" (global $g-public))
  (export "g-public" (global $g-public))
)

;; Continuation function type is not exposed. We can optimize its subtypes and
;; the subtypes of other types it references.
(module
  ;; CHECK:      (type $other-super (sub (struct)))
  (type $other-super (sub (struct)))
  ;; CHECK:      (type $other (sub $other-super (struct)))
  (type $other (sub $other-super (struct)))
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $other-child (sub (struct)))
  (type $other-child (sub $other (struct)))

  ;; CHECK:       (type $func-sub-child (sub (func (result (ref null $other)))))

  ;; CHECK:      (type $func-super (sub (func (result (ref null $other-super)))))
  (type $func-super (sub (func (result (ref null $other-super)))))
  ;; CHECK:      (type $func-sub (sub $func-super (func (result (ref null $other)))))
  (type $func-sub (sub $func-super (func (result (ref null $other)))))
  (type $func-sub-child (sub $func-sub (func (result (ref null $other)))))
  ;; CHECK:      (type $cont (sub (cont $func-sub)))
  (type $cont (sub (cont $func-sub)))

  ;; CHECK:      (global $g-cont (ref null $cont) (ref.null nocont))
  (global $g-cont (ref null $cont) (ref.null nocont))
  ;; CHECK:      (global $use-func-super (ref null $func-super) (ref.null nofunc))
  (global $use-func-super (ref null $func-super) (ref.null nofunc))
  ;; CHECK:      (global $use-func-sub (ref null $func-sub) (ref.null nofunc))
  (global $use-func-sub (ref null $func-sub) (ref.null nofunc))
  ;; CHECK:      (global $use-func-sub-child (ref null $func-sub-child) (ref.null nofunc))
  (global $use-func-sub-child (ref null $func-sub-child) (ref.null nofunc))
  ;; CHECK:      (global $use-other-super (ref null $other-super) (ref.null none))
  (global $use-other-super (ref null $other-super) (ref.null none))
  ;; CHECK:      (global $use-other (ref null $other) (ref.null none))
  (global $use-other (ref null $other) (ref.null none))
  ;; CHECK:      (global $use-other-child (ref null $other-child) (ref.null none))
  (global $use-other-child (ref null $other-child) (ref.null none))
  ;; CHECK:      (export "g-cont" (global $g-cont))
  (export "g-cont" (global $g-cont))
)

;; structref is public. We can optimize arrays, functions, and continuations.
(module
  ;; CHECK:      (type $struct-super (sub (struct)))
  (type $struct-super (sub (struct)))
  ;; CHECK:      (type $struct-sub (sub $struct-super (struct)))
  (type $struct-sub (sub $struct-super (struct)))
  ;; CHECK:      (type $struct-sub-child (sub $struct-sub (struct)))
  (type $struct-sub-child (sub $struct-sub (struct)))

  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $array-super (sub (array i32)))
  (type $array-super (sub (array i32)))
  ;; CHECK:       (type $array-sub (sub (array i32)))
  (type $array-sub (sub $array-super (array i32)))

  ;; CHECK:       (type $func-super (sub (func)))
  (type $func-super (sub (func)))
  ;; CHECK:       (type $func-sub (sub (func)))
  (type $func-sub (sub $func-super (func)))

  ;; CHECK:       (type $cont-super (sub (cont $func-super)))
  (type $cont-super (sub (cont $func-super)))
  ;; CHECK:       (type $cont-sub (sub (cont $func-super)))
  (type $cont-sub (sub $cont-super (cont $func-super)))

  ;; CHECK:      (global $g (mut structref) (ref.null none))
  (global $g (mut structref) (ref.null none))
  ;; CHECK:      (global $use-struct-super (ref null $struct-super) (ref.null none))
  (global $use-struct-super (ref null $struct-super) (ref.null none))
  ;; CHECK:      (global $use-struct-sub (ref null $struct-sub) (ref.null none))
  (global $use-struct-sub (ref null $struct-sub) (ref.null none))
  ;; CHECK:      (global $use-struct-sub-child (ref null $struct-sub-child) (ref.null none))
  (global $use-struct-sub-child (ref null $struct-sub-child) (ref.null none))
  ;; CHECK:      (global $use-array-super (ref null $array-super) (ref.null none))
  (global $use-array-super (ref null $array-super) (ref.null none))
  ;; CHECK:      (global $use-array-sub (ref null $array-sub) (ref.null none))
  (global $use-array-sub (ref null $array-sub) (ref.null none))
  ;; CHECK:      (global $use-func-super (ref null $func-super) (ref.null nofunc))
  (global $use-func-super (ref null $func-super) (ref.null nofunc))
  ;; CHECK:      (global $use-func-sub (ref null $func-sub) (ref.null nofunc))
  (global $use-func-sub (ref null $func-sub) (ref.null nofunc))
  ;; CHECK:      (global $use-cont-super (ref null $cont-super) (ref.null nocont))
  (global $use-cont-super (ref null $cont-super) (ref.null nocont))
  ;; CHECK:      (global $use-cont-sub (ref null $cont-sub) (ref.null nocont))
  (global $use-cont-sub (ref null $cont-sub) (ref.null nocont))
  ;; CHECK:      (export "g" (global $g))
  (export "g" (global $g))
)

;; A is exposed and has an exact reference to B, which has an inexact reference
;; to C. Subtypes of B can be optimized, but not subtypes of A or C.
(module
  ;; CHECK:      (type $C-super (sub (struct)))
  (type $C-super (sub (struct)))
  ;; CHECK:      (type $C (sub $C-super (struct)))
  (type $C (sub $C-super (struct)))
  ;; CHECK:      (type $C-child (sub $C (struct)))
  (type $C-child (sub $C (struct)))

  (type $B-super (sub (struct)))
  ;; CHECK:      (type $B (sub $C-super (struct (field (ref $C)))))
  (type $B (sub $B-super (struct (field (ref $C)))))
  ;; CHECK:      (type $B-child (sub (struct (field (ref $C)))))
  (type $B-child (sub $B (struct (field (ref $C)))))

  (type $A-super (sub (struct)))
  ;; CHECK:      (type $A (sub $C-super (struct (field (ref (exact $B))))))
  (type $A (sub $A-super (struct (field (ref (exact $B))))))
  ;; CHECK:      (type $A-child (sub $A (struct (field (ref (exact $B))))))
  (type $A-child (sub $A (struct (field (ref (exact $B))))))

  ;; CHECK:      (global $g-public (ref null $A) (ref.null none))
  (global $g-public (ref null $A) (ref.null none))
  ;; CHECK:      (global $use-A-super (ref null $C-super) (ref.null none))
  (global $use-A-super (ref null $A-super) (ref.null none))
  ;; CHECK:      (global $use-A-child (ref null $A-child) (ref.null none))
  (global $use-A-child (ref null $A-child) (ref.null none))
  ;; CHECK:      (global $use-B-super (ref null $C-super) (ref.null none))
  (global $use-B-super (ref null $B-super) (ref.null none))
  ;; CHECK:      (global $use-B-child (ref null $B-child) (ref.null none))
  (global $use-B-child (ref null $B-child) (ref.null none))
  ;; CHECK:      (global $use-C-super (ref null $C-super) (ref.null none))
  (global $use-C-super (ref null $C-super) (ref.null none))
  ;; CHECK:      (global $use-C-child (ref null $C-child) (ref.null none))
  (global $use-C-child (ref null $C-child) (ref.null none))
  ;; CHECK:      (export "g-public" (global $g-public))
  (export "g-public" (global $g-public))
)

;; Array type exposed inexactly. We cannot optimize its subtypes.
(module
  ;; CHECK:      (type $array-super (sub (array (mut i32))))
  (type $array-super (sub (array (mut i32))))
  ;; CHECK:      (type $array-sub (sub $array-super (array (mut i32))))
  (type $array-sub (sub $array-super (array (mut i32))))
  ;; CHECK:      (type $array-sub-child (sub $array-sub (array (mut i32))))
  (type $array-sub-child (sub $array-sub (array (mut i32))))

  ;; CHECK:      (global $g (ref null $array-sub) (ref.null none))
  (global $g (ref null $array-sub) (ref.null none))
  ;; CHECK:      (global $use-super (ref null $array-super) (ref.null none))
  (global $use-super (ref null $array-super) (ref.null none))
  ;; CHECK:      (global $use-child (ref null $array-sub-child) (ref.null none))
  (global $use-child (ref null $array-sub-child) (ref.null none))
  ;; CHECK:      (export "g" (global $g))
  (export "g" (global $g))
)

;; Array type exposed exactly. We can optimize its subtypes.
(module
  ;; CHECK:      (type $array-super (sub (array (mut i32))))
  (type $array-super (sub (array (mut i32))))
  ;; CHECK:      (type $array-sub (sub $array-super (array (mut i32))))
  (type $array-sub (sub $array-super (array (mut i32))))
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $array-sub-child (sub (array (mut i32))))
  (type $array-sub-child (sub $array-sub (array (mut i32))))

  ;; CHECK:       (type $3 (struct))

  ;; CHECK:      (global $g (ref (exact $array-sub)) (array.new_default $array-sub
  ;; CHECK-NEXT:  (i32.const 1)
  ;; CHECK-NEXT: ))
  (global $g (ref (exact $array-sub)) (array.new_default $array-sub (i32.const 1)))
  ;; CHECK:      (global $use-super (ref null $array-super) (ref.null none))
  (global $use-super (ref null $array-super) (ref.null none))
  ;; CHECK:      (global $use-child (ref null $array-sub-child) (ref.null none))
  (global $use-child (ref null $array-sub-child) (ref.null none))
  ;; CHECK:      (export "g" (global $g))
  (export "g" (global $g))
)

;; Array element type is inexact. We cannot optimize its subtypes.
(module
  ;; CHECK:      (type $element-super (sub (struct)))
  (type $element-super (sub (struct)))
  ;; CHECK:      (type $element (sub $element-super (struct)))
  (type $element (sub $element-super (struct)))
  ;; CHECK:      (type $element-child (sub $element (struct)))
  (type $element-child (sub $element (struct)))
  ;; CHECK:      (type $array (sub (array (ref $element))))
  (type $array (sub (array (ref $element))))

  ;; CHECK:      (global $g (ref null $array) (ref.null none))
  (global $g (ref null $array) (ref.null none))
  ;; CHECK:      (global $use-element-super (ref null $element-super) (ref.null none))
  (global $use-element-super (ref null $element-super) (ref.null none))
  ;; CHECK:      (global $use-element (ref null $element) (ref.null none))
  (global $use-element (ref null $element) (ref.null none))
  ;; CHECK:      (global $use-element-child (ref null $element-child) (ref.null none))
  (global $use-element-child (ref null $element-child) (ref.null none))
  ;; CHECK:      (export "g" (global $g))
  (export "g" (global $g))
)

;; Array element type is exact. We can optimize its subtypes.
(module
  ;; CHECK:      (type $element-super (sub (struct)))
  (type $element-super (sub (struct)))
  ;; CHECK:      (type $element (sub $element-super (struct)))
  (type $element (sub $element-super (struct)))
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $element-child (sub (struct)))
  (type $element-child (sub $element (struct)))
  ;; CHECK:       (type $3 (struct))

  ;; CHECK:      (type $array (sub (array (ref (exact $element)))))
  (type $array (sub (array (ref (exact $element)))))

  ;; CHECK:      (global $g (ref null $array) (ref.null none))
  (global $g (ref null $array) (ref.null none))
  ;; CHECK:      (global $use-element-super (ref null $element-super) (ref.null none))
  (global $use-element-super (ref null $element-super) (ref.null none))
  ;; CHECK:      (global $use-element (ref null $element) (ref.null none))
  (global $use-element (ref null $element) (ref.null none))
  ;; CHECK:      (global $use-element-child (ref null $element-child) (ref.null none))
  (global $use-element-child (ref null $element-child) (ref.null none))
  ;; CHECK:      (export "g" (global $g))
  (export "g" (global $g))
)

;; Table type exposed inexactly. We cannot optimize its subtypes.
(module
  ;; CHECK:      (type $T-super (sub (struct)))
  (type $T-super (sub (struct)))
  ;; CHECK:      (type $T (sub $T-super (struct)))
  (type $T (sub $T-super (struct)))
  ;; CHECK:      (type $T-child (sub $T (struct)))
  (type $T-child (sub $T (struct)))

  (import "env" "table" (table 1 (ref null $T)))
  ;; CHECK:      (import "env" "table" (table $timport$0 1 (ref null $T)))

  ;; CHECK:      (global $use-super (ref null $T-super) (ref.null none))
  (global $use-super (ref null $T-super) (ref.null none))
  ;; CHECK:      (global $use-child (ref null $T-child) (ref.null none))
  (global $use-child (ref null $T-child) (ref.null none))
)

;; Table type exposed exactly. We can optimize its subtypes.
(module
  ;; CHECK:      (type $T-super (sub (struct)))
  (type $T-super (sub (struct)))
  ;; CHECK:      (type $T (sub $T-super (struct)))
  (type $T (sub $T-super (struct)))
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $T-child (sub (struct)))
  (type $T-child (sub $T (struct)))

  (import "env" "table" (table 1 (ref (exact $T))))
  ;; CHECK:       (type $3 (struct))

  ;; CHECK:      (import "env" "table" (table $timport$0 1 (ref (exact $T))))

  ;; CHECK:      (global $use-super (ref null $T-super) (ref.null none))
  (global $use-super (ref null $T-super) (ref.null none))
  ;; CHECK:      (global $use-child (ref null $T-child) (ref.null none))
  (global $use-child (ref null $T-child) (ref.null none))
)

;; Tag type and its children are exposed inexactly. We cannot optimize their
;; subtypes.
(module
  ;; CHECK:      (type $param-super (sub (struct)))
  (type $param-super (sub (struct)))
  ;; CHECK:      (type $param (sub $param-super (struct)))
  (type $param (sub $param-super (struct)))
  ;; CHECK:      (type $param-child (sub $param (struct)))
  (type $param-child (sub $param (struct)))
  ;; CHECK:      (type $sig (sub (func (param (ref $param)))))
  (type $sig (sub (func (param (ref $param)))))

  ;; CHECK:      (global $use-param-super (ref null $param-super) (ref.null none))

  ;; CHECK:      (global $use-param-child (ref null $param-child) (ref.null none))

  ;; CHECK:      (tag $t (type $sig) (param (ref $param)))
  (tag $t (type $sig))
  (global $use-param-super (ref null $param-super) (ref.null none))
  (global $use-param-child (ref null $param-child) (ref.null none))
  ;; CHECK:      (export "t" (tag $t))
  (export "t" (tag $t))
)

;; Function signature exact vs inexact params and results. None of the params or
;; results can be optimized, but the subtypes of the exactly referenced params
;; and results can.
(module
  ;; CHECK:      (type $param-exact-super (sub (struct (field i32))))
  (type $param-exact-super (sub (struct (field i32))))
  ;; CHECK:      (type $param-exact (sub $param-exact-super (struct (field i32) (field i32))))
  (type $param-exact (sub $param-exact-super (struct (field i32 i32))))
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $param-exact-child (sub (struct (field i32) (field i32) (field f32))))
  (type $param-exact-child (sub $param-exact (struct (field i32 i32 f32))))

  ;; CHECK:       (type $result-exact-child (sub (struct (field f32) (field f32) (field i32))))

  ;; CHECK:      (type $param-inexact-super (sub (struct (field i64))))
  (type $param-inexact-super (sub (struct (field i64))))
  ;; CHECK:      (type $param-inexact (sub $param-inexact-super (struct (field i64) (field i64))))
  (type $param-inexact (sub $param-inexact-super (struct (field i64 i64))))
  ;; CHECK:      (type $param-inexact-child (sub $param-inexact (struct (field i64) (field i64) (field f64))))
  (type $param-inexact-child (sub $param-inexact (struct (field i64 i64 f64))))

  ;; CHECK:      (type $result-exact-super (sub (struct (field f32))))
  (type $result-exact-super (sub (struct (field f32))))
  ;; CHECK:      (type $result-exact (sub $result-exact-super (struct (field f32) (field f32))))
  (type $result-exact (sub $result-exact-super (struct (field f32 f32))))
  (type $result-exact-child (sub $result-exact (struct (field f32 f32 i32))))

  ;; CHECK:      (type $result-inexact-super (sub (struct (field f64))))
  (type $result-inexact-super (sub (struct (field f64))))
  ;; CHECK:      (type $result-inexact (sub $result-inexact-super (struct (field f64) (field f64))))
  (type $result-inexact (sub $result-inexact-super (struct (field f64 f64))))
  ;; CHECK:      (type $result-inexact-child (sub $result-inexact (struct (field f64) (field f64) (field i64))))
  (type $result-inexact-child (sub $result-inexact (struct (field f64 f64 i64))))

  ;; CHECK:      (type $sig (sub (func (param (ref (exact $param-exact)) (ref $param-inexact)) (result (ref (exact $result-exact)) (ref $result-inexact)))))
  (type $sig (sub (func (param (ref (exact $param-exact)) (ref $param-inexact)) (result (ref (exact $result-exact)) (ref $result-inexact)))))


  ;; CHECK:      (global $use-param-exact-super (ref null $param-exact-super) (ref.null none))
  (global $use-param-exact-super (ref null $param-exact-super) (ref.null none))
  ;; CHECK:      (global $use-param-exact-child (ref null $param-exact-child) (ref.null none))
  (global $use-param-exact-child (ref null $param-exact-child) (ref.null none))
  ;; CHECK:      (global $use-param-inexact-super (ref null $param-inexact-super) (ref.null none))
  (global $use-param-inexact-super (ref null $param-inexact-super) (ref.null none))
  ;; CHECK:      (global $use-param-inexact-child (ref null $param-inexact-child) (ref.null none))
  (global $use-param-inexact-child (ref null $param-inexact-child) (ref.null none))
  ;; CHECK:      (global $use-result-exact-super (ref null $result-exact-super) (ref.null none))
  (global $use-result-exact-super (ref null $result-exact-super) (ref.null none))
  ;; CHECK:      (global $use-result-exact-child (ref null $result-exact-child) (ref.null none))
  (global $use-result-exact-child (ref null $result-exact-child) (ref.null none))
  ;; CHECK:      (global $use-result-inexact-super (ref null $result-inexact-super) (ref.null none))
  (global $use-result-inexact-super (ref null $result-inexact-super) (ref.null none))
  ;; CHECK:      (global $use-result-inexact-child (ref null $result-inexact-child) (ref.null none))
  (global $use-result-inexact-child (ref null $result-inexact-child) (ref.null none))
  ;; CHECK:      (export "f" (func $f))
  (export "f" (func $f))
  ;; CHECK:      (func $f (type $sig) (param $0 (ref (exact $param-exact))) (param $1 (ref $param-inexact)) (result (ref (exact $result-exact)) (ref $result-inexact))
  ;; CHECK-NEXT:  (unreachable)
  ;; CHECK-NEXT: )
  (func $f (type $sig) (param (ref (exact $param-exact)) (ref $param-inexact)) (result (ref (exact $result-exact)) (ref $result-inexact))
    (unreachable)
  )
)

;; contref is public. We can optimize structs, arrays, and functions.
(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $struct-super (sub (struct)))
  (type $struct-super (sub (struct)))
  ;; CHECK:       (type $struct-sub (sub (struct)))
  (type $struct-sub (sub $struct-super (struct)))

  ;; CHECK:       (type $array-super (sub (array i32)))
  (type $array-super (sub (array i32)))
  ;; CHECK:       (type $array-sub (sub (array i32)))
  (type $array-sub (sub $array-super (array i32)))

  ;; CHECK:       (type $func-sub (sub (func)))

  ;; CHECK:      (type $func-super (sub (func)))
  (type $func-super (sub (func)))
  (type $func-sub (sub $func-super (func)))

  ;; CHECK:      (type $cont-super (sub (cont $func-super)))
  (type $cont-super (sub (cont $func-super)))
  ;; CHECK:      (type $cont-sub (sub $cont-super (cont $func-super)))
  (type $cont-sub (sub $cont-super (cont $func-super)))
  ;; CHECK:      (type $cont-sub-child (sub $cont-sub (cont $func-super)))
  (type $cont-sub-child (sub $cont-sub (cont $func-super)))

  ;; CHECK:      (global $g (mut contref) (ref.null nocont))
  (global $g (mut contref) (ref.null nocont))
  ;; CHECK:      (global $use-struct-super (ref null $struct-super) (ref.null none))
  (global $use-struct-super (ref null $struct-super) (ref.null none))
  ;; CHECK:      (global $use-struct-sub (ref null $struct-sub) (ref.null none))
  (global $use-struct-sub (ref null $struct-sub) (ref.null none))
  ;; CHECK:      (global $use-array-super (ref null $array-super) (ref.null none))
  (global $use-array-super (ref null $array-super) (ref.null none))
  ;; CHECK:      (global $use-array-sub (ref null $array-sub) (ref.null none))
  (global $use-array-sub (ref null $array-sub) (ref.null none))
  ;; CHECK:      (global $use-func-super (ref null $func-super) (ref.null nofunc))
  (global $use-func-super (ref null $func-super) (ref.null nofunc))
  ;; CHECK:      (global $use-func-sub (ref null $func-sub) (ref.null nofunc))
  (global $use-func-sub (ref null $func-sub) (ref.null nofunc))
  ;; CHECK:      (global $use-cont-super (ref null $cont-super) (ref.null nocont))
  (global $use-cont-super (ref null $cont-super) (ref.null nocont))
  ;; CHECK:      (global $use-cont-sub (ref null $cont-sub) (ref.null nocont))
  (global $use-cont-sub (ref null $cont-sub) (ref.null nocont))
  ;; CHECK:      (global $use-cont-sub-child (ref null $cont-sub-child) (ref.null nocont))
  (global $use-cont-sub-child (ref null $cont-sub-child) (ref.null nocont))
  ;; CHECK:      (export "g" (global $g))
  (export "g" (global $g))
)

;; A is exposed exactly and has an inexact reference to B, which has an exact
;; reference to C. Subtypes of A and C but not B can be optimized.
(module
  ;; CHECK:      (type $C-super (sub (struct)))
  (type $C-super (sub (struct)))
  ;; CHECK:      (type $C (sub $C-super (struct)))
  (type $C (sub $C-super (struct)))
  ;; CHECK:      (type $B (sub $C-super (struct (field (ref null (exact $C))))))

  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $C-child (sub (struct)))
  (type $C-child (sub $C (struct)))

  (type $B-super (sub (struct)))
  (type $B (sub $B-super (struct (field (ref null (exact $C))))))
  ;; CHECK:       (type $A-child (sub (struct (field (ref null $B)))))

  ;; CHECK:      (type $B-child (sub $B (struct (field (ref null (exact $C))))))
  (type $B-child (sub $B (struct (field (ref null (exact $C))))))

  (type $A-super (sub (struct)))
  ;; CHECK:      (type $A (sub $C-super (struct (field (ref null $B)))))
  (type $A (sub $A-super (struct (field (ref null $B)))))
  (type $A-child (sub $A (struct (field (ref null $B)))))

  ;; CHECK:      (global $g-public (ref (exact $A)) (struct.new_default $A))
  (global $g-public (ref (exact $A)) (struct.new_default $A))
  ;; CHECK:      (global $use-A-super (ref null $C-super) (ref.null none))
  (global $use-A-super (ref null $A-super) (ref.null none))
  ;; CHECK:      (global $use-A-child (ref null $A-child) (ref.null none))
  (global $use-A-child (ref null $A-child) (ref.null none))
  ;; CHECK:      (global $use-B-super (ref null $C-super) (ref.null none))
  (global $use-B-super (ref null $B-super) (ref.null none))
  ;; CHECK:      (global $use-B-child (ref null $B-child) (ref.null none))
  (global $use-B-child (ref null $B-child) (ref.null none))
  ;; CHECK:      (global $use-C-super (ref null $C-super) (ref.null none))
  (global $use-C-super (ref null $C-super) (ref.null none))
  ;; CHECK:      (global $use-C-child (ref null $C-child) (ref.null none))
  (global $use-C-child (ref null $C-child) (ref.null none))
  ;; CHECK:      (export "g-public" (global $g-public))
  (export "g-public" (global $g-public))
)

;; A is exposed, making A-super and B public. The inexact reference from A-super
;; to B does not prevent B-child from being optimized, nor does it prevent the
;; subtypes of C (referenced inexactly from B) from being optimized.
(module
  ;; CHECK:      (type $C-super (sub (struct)))
  (type $C-super (sub (struct)))
  ;; CHECK:      (type $C (sub $C-super (struct)))
  (type $C (sub $C-super (struct)))
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $C-child (sub (struct)))
  (type $C-child (sub $C (struct)))

  ;; CHECK:       (type $B-child (sub (struct (field (ref null $C)))))

  ;; CHECK:      (type $B-super (sub (struct (field (ref null $C)))))
  (type $B-super (sub (struct (field (ref null $C)))))
  ;; CHECK:      (type $B (sub $B-super (struct (field (ref null $C)))))
  (type $B (sub $B-super (struct (field (ref null $C)))))
  (type $B-child (sub $B (struct (field (ref null $C)))))

  ;; CHECK:      (type $A-super (sub (struct (field (ref null $B)))))
  (type $A-super (sub (struct (field (ref null $B)))))
  ;; CHECK:      (type $A (sub $A-super (struct (field nullref))))
  (type $A (sub $A-super (struct (field (ref null none)))))

  ;; CHECK:      (global $g-public (ref null $A) (ref.null none))
  (global $g-public (ref null $A) (ref.null none))
  ;; CHECK:      (global $use-A-super (ref null $A-super) (ref.null none))
  (global $use-A-super (ref null $A-super) (ref.null none))
  ;; CHECK:      (global $use-B-super (ref null $B-super) (ref.null none))
  (global $use-B-super (ref null $B-super) (ref.null none))
  ;; CHECK:      (global $use-B (ref null $B) (ref.null none))
  (global $use-B (ref null $B) (ref.null none))
  ;; CHECK:      (global $use-B-child (ref null $B-child) (ref.null none))
  (global $use-B-child (ref null $B-child) (ref.null none))
  ;; CHECK:      (global $use-C-super (ref null $C-super) (ref.null none))
  (global $use-C-super (ref null $C-super) (ref.null none))
  ;; CHECK:      (global $use-C (ref null $C) (ref.null none))
  (global $use-C (ref null $C) (ref.null none))
  ;; CHECK:      (global $use-C-child (ref null $C-child) (ref.null none))
  (global $use-C-child (ref null $C-child) (ref.null none))
  ;; CHECK:      (export "g-public" (global $g-public))
  (export "g-public" (global $g-public))
)
