;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; RUN: foreach %s %t wasm-opt -all --closed-world --preserve-type-order \
;; RUN:     --unsubtyping --remove-unused-types -all -S -o - | filecheck %s

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (func)))
  (type $super (sub (func)))
  ;; CHECK:       (type $sub (sub $super (func)))
  (type $sub (sub $super (func)))
  ;; CHECK:       (type $cont (cont $super))
  (type $cont (cont $super))

  ;; CHECK:      (elem declare func $cont-new)

  ;; CHECK:      (func $cont-new (type $sub)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (cont.new $cont
  ;; CHECK-NEXT:    (ref.func $cont-new)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $cont-new (type $sub)
    (drop
      ;; This requires $sub <: $super because the operand is expected to be a
      ;; $super but is actually a $sub.
      (cont.new $cont
        (ref.func $cont-new)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $one (func (param (ref $super))))
  (type $one (func (param (ref $super))))
  ;; CHECK:       (type $none (func))
  (type $none (func))

  ;; CHECK:       (type $cont-one (cont $one))
  (type $cont-one (cont $one))
  ;; CHECK:       (type $cont-none (cont $none))
  (type $cont-none (cont $none))

  ;; CHECK:      (func $cont-bind-operand (type $none)
  ;; CHECK-NEXT:  (local $one (ref null $cont-one))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (cont.bind $cont-one $cont-none
  ;; CHECK-NEXT:    (struct.new_default $sub)
  ;; CHECK-NEXT:    (local.get $one)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $cont-bind-operand
    (local $one (ref null $cont-one))
    (drop
      ;; This requires $sub <: $super because the operand is expected to be a
      ;; $super.
      (cont.bind $cont-one $cont-none
        (struct.new $sub)
        (local.get $one)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $one (func (param (ref $super))))
  (type $one (func (param (ref $super))))
  ;; CHECK:       (type $none (func))
  (type $none (func))

  ;; CHECK:       (type $cont-one (cont $one))
  (type $cont-one (cont $one))
  (type $cont-none (cont $none))

  ;; CHECK:      (func $cont-bind-operand (type $none)
  ;; CHECK-NEXT:  (local $one (ref null $cont-one))
  ;; CHECK-NEXT:  (local $use-sub (ref null $sub))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block ;; (replaces unreachable ContBind we can't emit)
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (unreachable)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (local.get $one)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $cont-bind-operand
    (local $one (ref null $cont-one))
    (local $use-sub (ref null $sub))
    (drop
      ;; Same as above, but now the operand is unreachable. We can optimize and
      ;; should not crash.
      (cont.bind $cont-one $cont-none
        (unreachable)
        (local.get $one)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $one (func (param (ref $super))))
  (type $one (func (param (ref $super))))
  ;; CHECK:       (type $none (func))
  (type $none (func))

  ;; CHECK:       (type $cont-one (cont $one))
  (type $cont-one (cont $one))
  ;; CHECK:       (type $cont-none (cont $none))
  (type $cont-none (cont $none))

  ;; CHECK:      (func $cont-bind-operand (type $none)
  ;; CHECK-NEXT:  (local $one (ref null $cont-one))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block ;; (replaces unreachable ContBind we can't emit)
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (struct.new_default $sub)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (ref.null nocont)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $cont-bind-operand
    (local $one (ref null $cont-one))
    (drop
      ;; Same as above, but now the continuation is null so we can optimize.
      (cont.bind $cont-one $cont-none
        (struct.new $sub)
        (ref.null nocont)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $in (func (param (ref $super))))
  (type $in (func (param (ref $super))))
  ;; CHECK:       (type $out (func (param (ref $sub))))
  (type $out (func (param (ref $sub))))

  ;; CHECK:       (type $cont-in (cont $in))
  (type $cont-in (cont $in))
  ;; CHECK:       (type $cont-out (cont $out))
  (type $cont-out (cont $out))

  ;; CHECK:       (type $6 (func))

  ;; CHECK:      (func $cont-bind-param (type $6)
  ;; CHECK-NEXT:  (local $in (ref null $cont-in))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (cont.bind $cont-in $cont-out
  ;; CHECK-NEXT:    (local.get $in)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $cont-bind-param
    (local $in (ref null $cont-in))
    (drop
      ;; This requires $sub <: $super because the output continuation parameters
      ;; must be subtypes of the unbound input continuation parameters.
      (cont.bind $cont-in $cont-out
        (local.get $in)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $in (func (param (ref $super))))
  (type $in (func (param (ref $super))))
  ;; CHECK:       (type $out (func (param (ref $sub))))
  (type $out (func (param (ref $sub))))

  ;; CHECK:       (type $cont-in (cont $in))
  (type $cont-in (cont $in))
  ;; CHECK:       (type $cont-out (cont $out))
  (type $cont-out (cont $out))

  ;; CHECK:       (type $6 (func))

  ;; CHECK:      (func $cont-bind-param (type $6)
  ;; CHECK-NEXT:  (local $in (ref null $cont-in))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block ;; (replaces unreachable ContBind we can't emit)
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (ref.null nocont)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $cont-bind-param
    (local $in (ref null $cont-in))
    (drop
      ;; Same as above, but now the continuation is null so we can optimize.
      (cont.bind $cont-in $cont-out
        (ref.null nocont)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $in (func (result (ref null $sub))))
  (type $in (func (result (ref null $sub))))
  ;; CHECK:       (type $out (func (result (ref null $super))))
  (type $out (func (result (ref null $super))))

  ;; CHECK:       (type $cont-in (cont $in))
  (type $cont-in (cont $in))
  ;; CHECK:       (type $cont-out (cont $out))
  (type $cont-out (cont $out))

  ;; CHECK:       (type $6 (func))

  ;; CHECK:      (func $cont-bind-result (type $6)
  ;; CHECK-NEXT:  (local $in (ref null $cont-in))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (cont.bind $cont-in $cont-out
  ;; CHECK-NEXT:    (local.get $in)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $cont-bind-result
    (local $in (ref null $cont-in))
    (drop
      ;; This requires $sub <: $super because the result of the input
      ;; continuation must be a subtype of the result of the output
      ;; continuation.
      (cont.bind $cont-in $cont-out
        (local.get $in)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $in (func (result (ref null $sub))))
  (type $in (func (result (ref null $sub))))
  ;; CHECK:       (type $out (func (result (ref null $super))))
  (type $out (func (result (ref null $super))))

  ;; CHECK:       (type $cont-in (cont $in))
  (type $cont-in (cont $in))
  ;; CHECK:       (type $cont-out (cont $out))
  (type $cont-out (cont $out))

  ;; CHECK:       (type $6 (func))

  ;; CHECK:      (func $cont-bind-result (type $6)
  ;; CHECK-NEXT:  (local $in (ref null $cont-in))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block ;; (replaces unreachable ContBind we can't emit)
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (ref.null nocont)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $cont-bind-result
    (local $in (ref null $cont-in))
    (drop
      ;; Same as above, but now the continuation is null so we can optimize.
      (cont.bind $cont-in $cont-out
        (ref.null nocont)
      )
    )
  )
)


(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $2 (func (param (ref null $super))))

  ;; CHECK:       (type $3 (func))

  ;; CHECK:      (tag $take-super (type $2) (param (ref null $super)))
  (tag $take-super (param (ref null $super)))

  ;; CHECK:      (func $suspend-operand (type $3)
  ;; CHECK-NEXT:  (suspend $take-super
  ;; CHECK-NEXT:   (struct.new_default $sub)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $suspend-operand
    ;; This requires $sub <: $super.
    (suspend $take-super
      (struct.new $sub)
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func (param (ref null $super))))
  (type $f (func (param (ref null $super))))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; CHECK:       (type $4 (func))

  ;; CHECK:      (func $resume-param (type $4)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (resume $cont
  ;; CHECK-NEXT:   (struct.new_default $sub)
  ;; CHECK-NEXT:   (local.get $cont)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-param
    (local $cont (ref null $cont))
    ;; This requires $sub <: $super.
    (resume $cont
      (struct.new $sub)
      (local.get $cont)
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func (param (ref null $super))))
  (type $f (func (param (ref null $super))))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; CHECK:       (type $4 (func))

  ;; CHECK:      (func $resume-param (type $4)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (block ;; (replaces unreachable Resume we can't emit)
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (struct.new_default $sub)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-param
    (local $cont (ref null $cont))
    ;; Same as above, but now the continuation is null so we can optimize.
    (resume $cont
      (struct.new $sub)
      (ref.null nocont)
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $f (func))
  (type $f (func))

  (type $super (sub (cont $f)))
  ;; CHECK:       (type $sub (sub (cont $f)))
  (type $sub (sub $super (cont $f)))

  ;; CHECK:      (func $resume-ref (type $f)
  ;; CHECK-NEXT:  (local $sub (ref null $sub))
  ;; CHECK-NEXT:  (resume $sub
  ;; CHECK-NEXT:   (local.get $sub)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-ref
    (local $sub (ref null $sub))
    ;; This does NOT require $sub <: $super because we turn this into a
    ;; `resume $sub`.
    (resume $super
      (local.get $sub)
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func))
  (type $f (func))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; CHECK:       (type $4 (func (param (ref null $sub))))

  ;; CHECK:       (type $5 (func (result (ref null $super) (ref null $cont))))

  ;; CHECK:      (tag $send-sub (type $4) (param (ref null $sub)))
  (tag $send-sub (param (ref null $sub)))

  ;; CHECK:      (func $resume-tag-param (type $f)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (tuple.drop 2
  ;; CHECK-NEXT:   (block $l (type $5) (result (ref null $super) (ref null $cont))
  ;; CHECK-NEXT:    (resume $cont (on $send-sub $l)
  ;; CHECK-NEXT:     (local.get $cont)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-tag-param
    (local $cont (ref null $cont))
    (tuple.drop 2
      (block $l (result (ref null $super) (ref null $cont))
        ;; Sending the tag parameter to the block requires $sub <: $super.
        (resume $cont (on $send-sub $l)
          (local.get $cont)
        )
        (unreachable)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func))
  (type $f (func))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; CHECK:       (type $4 (func (param (ref null $sub))))

  ;; CHECK:       (type $5 (func (result (ref null $super) (ref null $cont))))

  ;; CHECK:      (tag $send-sub (type $4) (param (ref null $sub)))
  (tag $send-sub (param (ref null $sub)))

  ;; CHECK:      (func $resume-tag-param (type $f)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (tuple.drop 2
  ;; CHECK-NEXT:   (block $l (type $5) (result (ref null $super) (ref null $cont))
  ;; CHECK-NEXT:    (block ;; (replaces unreachable Resume we can't emit)
  ;; CHECK-NEXT:     (drop
  ;; CHECK-NEXT:      (ref.null nocont)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (unreachable)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-tag-param
    (local $cont (ref null $cont))
    (tuple.drop 2
      (block $l (result (ref null $super) (ref null $cont))
        ;; Same as above, but now the continuation is null so we can optimize.
        (resume $cont (on $send-sub $l)
          (ref.null nocont)
        )
        (unreachable)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func))
  (type $f (func))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; CHECK:       (type $receive-sub (func (param (ref null $sub))))
  (type $receive-sub (func (param (ref null $sub))))
  ;; CHECK:       (type $receive-sub-cont (cont $receive-sub))
  (type $receive-sub-cont (cont $receive-sub))

  ;; CHECK:       (type $6 (func (result (ref null $super))))

  ;; CHECK:      (tag $expect-super (type $6) (result (ref null $super)))
  (tag $expect-super (result (ref null $super)))

  ;; CHECK:      (func $resume-tag-result (type $f)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block $l (result (ref null $receive-sub-cont))
  ;; CHECK-NEXT:    (resume $cont (on $expect-super $l)
  ;; CHECK-NEXT:     (local.get $cont)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-tag-result
    (local $cont (ref null $cont))
    (drop
      (block $l (result (ref null $receive-sub-cont))
        ;; Based on the tag, the continuation expects a $super back. Based on
        ;; the type we give the next continuation, we will send it a $sub back.
        ;; This requires $sub <: $super.
        (resume $cont (on $expect-super $l)
          (local.get $cont)
        )
        (ref.null nocont)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func))
  (type $f (func))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; CHECK:       (type $receive-sub (func (param (ref null $sub))))
  (type $receive-sub (func (param (ref null $sub))))
  ;; CHECK:       (type $receive-sub-cont (cont $receive-sub))
  (type $receive-sub-cont (cont $receive-sub))

  ;; CHECK:       (type $6 (func (result (ref null $super))))

  ;; CHECK:      (tag $expect-super (type $6) (result (ref null $super)))
  (tag $expect-super (result (ref null $super)))

  ;; CHECK:      (func $resume-tag-result (type $f)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block $l (result (ref null $receive-sub-cont))
  ;; CHECK-NEXT:    (block ;; (replaces unreachable Resume we can't emit)
  ;; CHECK-NEXT:     (drop
  ;; CHECK-NEXT:      (ref.null nocont)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (unreachable)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-tag-result
    (local $cont (ref null $cont))
    (drop
      (block $l (result (ref null $receive-sub-cont))
        ;; Same as above, but now the continuation is null so we can optimize.
        (resume $cont (on $expect-super $l)
          (ref.null nocont)
        )
        (ref.null nocont)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $return-sub (func (result (ref null $sub))))
  (type $return-sub (func (result (ref null $sub))))
  ;; CHECK:       (type $return-super (func (result (ref null $super))))
  (type $return-super (func (result (ref null $super))))

  ;; CHECK:       (type $return-sub-cont (cont $return-sub))
  (type $return-sub-cont (cont $return-sub))
  ;; CHECK:       (type $return-super-cont (cont $return-super))
  (type $return-super-cont (cont $return-super))

  ;; CHECK:       (type $6 (func))

  ;; CHECK:      (tag $e (type $6))
  (tag $e)

  ;; CHECK:      (func $resume-cont-result (type $6)
  ;; CHECK-NEXT:  (local $cont (ref null $return-sub-cont))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block $l (result (ref null $return-super-cont))
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (resume $return-sub-cont (on $e $l)
  ;; CHECK-NEXT:      (local.get $cont)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-cont-result
    (local $cont (ref null $return-sub-cont))
    (drop
      (block $l (result (ref null $return-super-cont))
        (drop
          ;; The continuation we're resuming returns a $sub. In the next type we
          ;; give it, it returns a $super. This requires $sub <: $super.
          (resume $return-sub-cont (on $e $l)
            (local.get $cont)
          )
        )
        (ref.null nocont)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $return-sub (func (result (ref null $sub))))
  (type $return-sub (func (result (ref null $sub))))
  ;; CHECK:       (type $return-super (func (result (ref null $super))))
  (type $return-super (func (result (ref null $super))))

  ;; CHECK:       (type $return-sub-cont (cont $return-sub))
  (type $return-sub-cont (cont $return-sub))
  ;; CHECK:       (type $return-super-cont (cont $return-super))
  (type $return-super-cont (cont $return-super))

  ;; CHECK:       (type $6 (func))

  ;; CHECK:      (tag $e (type $6))
  (tag $e)

  ;; CHECK:      (func $resume-cont-result (type $6)
  ;; CHECK-NEXT:  (local $cont (ref null $return-sub-cont))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block $l (result (ref null $return-super-cont))
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (block ;; (replaces unreachable Resume we can't emit)
  ;; CHECK-NEXT:      (drop
  ;; CHECK-NEXT:       (ref.null nocont)
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:      (unreachable)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-cont-result
    (local $cont (ref null $return-sub-cont))
    (drop
      (block $l (result (ref null $return-super-cont))
        (drop
          ;; Same as above, but now the continuation is null so we can optimize.
          (resume $return-sub-cont (on $e $l)
            (ref.null nocont)
          )
        )
        (ref.null nocont)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func))
  (type $f (func))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; CHECK:       (type $4 (func (param (ref null $super))))

  ;; CHECK:      (tag $throw-super (type $4) (param (ref null $super)))
  (tag $throw-super (param (ref null $super)))

  ;; CHECK:      (func $resume-throw-param (type $f)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (resume_throw $cont $throw-super
  ;; CHECK-NEXT:   (struct.new_default $sub)
  ;; CHECK-NEXT:   (local.get $cont)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-throw-param
    (local $cont (ref null $cont))
    ;; This requires $sub <: $super
    (resume_throw $cont $throw-super
      (struct.new $sub)
      (local.get $cont)
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func))
  (type $f (func))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; CHECK:       (type $4 (func (param (ref null $super))))

  ;; CHECK:      (tag $throw-super (type $4) (param (ref null $super)))
  (tag $throw-super (param (ref null $super)))

  ;; CHECK:      (func $resume-throw-param (type $f)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (block ;; (replaces unreachable ResumeThrow we can't emit)
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (struct.new_default $sub)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-throw-param
    (local $cont (ref null $cont))
    ;; Same as above, but now the continuation is null so we can optimize.
    (resume_throw $cont $throw-super
      (struct.new $sub)
      (ref.null nocont)
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $f (func))
  (type $f (func))

  (type $super (sub (cont $f)))
  ;; CHECK:       (type $sub (sub (cont $f)))
  (type $sub (sub $super (cont $f)))

  ;; CHECK:      (tag $e (type $f))
  (tag $e)

  ;; CHECK:      (func $resume-throw-ref (type $f)
  ;; CHECK-NEXT:  (local $sub (ref null $sub))
  ;; CHECK-NEXT:  (resume_throw $sub $e
  ;; CHECK-NEXT:   (local.get $sub)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-throw-ref
    (local $sub (ref null $sub))
    ;; This does NOT require $sub <: $super because we turn this into a
    ;; `resume_throw $sub`.
    (resume_throw $super $e
      (local.get $sub)
    )
  )
)


(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func))
  (type $f (func))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; CHECK:       (type $4 (func (param (ref null $sub))))

  ;; CHECK:       (type $5 (func (result (ref null $super) (ref null $cont))))

  ;; CHECK:      (tag $send-sub (type $4) (param (ref null $sub)))
  (tag $send-sub (param (ref null $sub)))

  ;; CHECK:      (tag $e (type $f))
  (tag $e)

  ;; CHECK:      (func $resume-throw-tag-param (type $f)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (tuple.drop 2
  ;; CHECK-NEXT:   (block $l (type $5) (result (ref null $super) (ref null $cont))
  ;; CHECK-NEXT:    (resume_throw $cont $e (on $send-sub $l)
  ;; CHECK-NEXT:     (local.get $cont)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-throw-tag-param
    (local $cont (ref null $cont))
    (tuple.drop 2
      (block $l (result (ref null $super) (ref null $cont))
        ;; Sending the tag parameter to the block requires $sub <: $super.
        (resume_throw $cont $e (on $send-sub $l)
          (local.get $cont)
        )
        (unreachable)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func))
  (type $f (func))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; CHECK:       (type $4 (func (param (ref null $sub))))

  ;; CHECK:       (type $5 (func (result (ref null $super) (ref null $cont))))

  ;; CHECK:      (tag $send-sub (type $4) (param (ref null $sub)))
  (tag $send-sub (param (ref null $sub)))

  ;; CHECK:      (tag $e (type $f))
  (tag $e)

  ;; CHECK:      (func $resume-throw-tag-param (type $f)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (tuple.drop 2
  ;; CHECK-NEXT:   (block $l (type $5) (result (ref null $super) (ref null $cont))
  ;; CHECK-NEXT:    (block ;; (replaces unreachable ResumeThrow we can't emit)
  ;; CHECK-NEXT:     (drop
  ;; CHECK-NEXT:      (ref.null nocont)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (unreachable)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-throw-tag-param
    (local $cont (ref null $cont))
    (tuple.drop 2
      (block $l (result (ref null $super) (ref null $cont))
        ;; Same as above, but now the continuation is null so we can optimize.
        (resume_throw $cont $e (on $send-sub $l)
          (ref.null nocont)
        )
        (unreachable)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func))
  (type $f (func))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; CHECK:       (type $4 (func (param (ref null $sub))))

  ;; CHECK:       (type $5 (func (result (ref null $super) (ref null $cont))))

  ;; CHECK:      (tag $send-sub (type $4) (param (ref null $sub)))
  (tag $send-sub (param (ref null $sub)))

  ;; CHECK:      (func $resume-throw-ref-tag-param (type $f)
  ;; CHECK-NEXT:  (local $exn exnref)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (tuple.drop 2
  ;; CHECK-NEXT:   (block $l (type $5) (result (ref null $super) (ref null $cont))
  ;; CHECK-NEXT:    (resume_throw_ref $cont (on $send-sub $l)
  ;; CHECK-NEXT:     (local.get $exn)
  ;; CHECK-NEXT:     (local.get $cont)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-throw-ref-tag-param
    (local $exn exnref)
    (local $cont (ref null $cont))
    (tuple.drop 2
      (block $l (result (ref null $super) (ref null $cont))
        ;; Now with a resume_throw_ref. This requies $sub <: $super.
        (resume_throw_ref $cont (on $send-sub $l)
          (local.get $exn)
          (local.get $cont)
        )
        (unreachable)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func))
  (type $f (func))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; CHECK:       (type $4 (func (param (ref null $sub))))

  ;; CHECK:       (type $5 (func (result (ref null $super) (ref null $cont))))

  ;; CHECK:      (tag $send-sub (type $4) (param (ref null $sub)))
  (tag $send-sub (param (ref null $sub)))

  ;; CHECK:      (func $resume-throw-ref-tag-param (type $f)
  ;; CHECK-NEXT:  (local $exn exnref)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (tuple.drop 2
  ;; CHECK-NEXT:   (block $l (type $5) (result (ref null $super) (ref null $cont))
  ;; CHECK-NEXT:    (block ;; (replaces unreachable ResumeThrow we can't emit)
  ;; CHECK-NEXT:     (drop
  ;; CHECK-NEXT:      (local.get $exn)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (drop
  ;; CHECK-NEXT:      (ref.null nocont)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (unreachable)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-throw-ref-tag-param
    (local $exn exnref)
    (local $cont (ref null $cont))
    (tuple.drop 2
      (block $l (result (ref null $super) (ref null $cont))
        ;; Same as above, but now the continuation is null so we can optimize.
        (resume_throw_ref $cont (on $send-sub $l)
          (local.get $exn)
          (ref.null nocont)
        )
        (unreachable)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func))
  (type $f (func))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; CHECK:       (type $receive-sub (func (param (ref null $sub))))
  (type $receive-sub (func (param (ref null $sub))))
  ;; CHECK:       (type $receive-sub-cont (cont $receive-sub))
  (type $receive-sub-cont (cont $receive-sub))

  ;; CHECK:       (type $6 (func (result (ref null $super))))

  ;; CHECK:      (tag $expect-super (type $6) (result (ref null $super)))
  (tag $expect-super (result (ref null $super)))

  ;; CHECK:      (tag $e (type $f))
  (tag $e)

  ;; CHECK:      (func $resume-throw-tag-result (type $f)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block $l (result (ref null $receive-sub-cont))
  ;; CHECK-NEXT:    (resume_throw $cont $e (on $expect-super $l)
  ;; CHECK-NEXT:     (local.get $cont)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-throw-tag-result
    (local $cont (ref null $cont))
    (drop
      (block $l (result (ref null $receive-sub-cont))
        ;; Based on the tag, the continuation expects a $super back. Based on
        ;; the type we give the next continuation, we will send it a $sub back.
        ;; This requires $sub <: $super.
        (resume_throw $cont $e (on $expect-super $l)
          (local.get $cont)
        )
        (ref.null nocont)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func))
  (type $f (func))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; CHECK:       (type $receive-sub (func (param (ref null $sub))))
  (type $receive-sub (func (param (ref null $sub))))
  ;; CHECK:       (type $receive-sub-cont (cont $receive-sub))
  (type $receive-sub-cont (cont $receive-sub))

  ;; CHECK:       (type $6 (func (result (ref null $super))))

  ;; CHECK:      (tag $expect-super (type $6) (result (ref null $super)))
  (tag $expect-super (result (ref null $super)))

  ;; CHECK:      (tag $e (type $f))
  (tag $e)

  ;; CHECK:      (func $resume-throw-tag-result (type $f)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block $l (result (ref null $receive-sub-cont))
  ;; CHECK-NEXT:    (block ;; (replaces unreachable ResumeThrow we can't emit)
  ;; CHECK-NEXT:     (drop
  ;; CHECK-NEXT:      (ref.null nocont)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (unreachable)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-throw-tag-result
    (local $cont (ref null $cont))
    (drop
      (block $l (result (ref null $receive-sub-cont))
        ;; Same as above, but now the continuation is null so we can optimize.
        (resume_throw $cont $e (on $expect-super $l)
          (ref.null nocont)
        )
        (ref.null nocont)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func))
  (type $f (func))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; CHECK:       (type $receive-sub (func (param (ref null $sub))))
  (type $receive-sub (func (param (ref null $sub))))
  ;; CHECK:       (type $receive-sub-cont (cont $receive-sub))
  (type $receive-sub-cont (cont $receive-sub))

  ;; CHECK:       (type $6 (func (result (ref null $super))))

  ;; CHECK:      (tag $expect-super (type $6) (result (ref null $super)))
  (tag $expect-super (result (ref null $super)))

  ;; CHECK:      (func $resume-throw-ref-tag-result (type $f)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block $l (result (ref null $receive-sub-cont))
  ;; CHECK-NEXT:    (resume_throw_ref $cont (on $expect-super $l)
  ;; CHECK-NEXT:     (ref.null noexn)
  ;; CHECK-NEXT:     (local.get $cont)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-throw-ref-tag-result
    (local $cont (ref null $cont))
    (drop
      (block $l (result (ref null $receive-sub-cont))
        ;; Now with resume_throw_ref. This requirest $sub <: $super.
        (resume_throw_ref $cont (on $expect-super $l)
          (ref.null noexn)
          (local.get $cont)
        )
        (ref.null nocont)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func))
  (type $f (func))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; CHECK:       (type $receive-sub (func (param (ref null $sub))))
  (type $receive-sub (func (param (ref null $sub))))
  ;; CHECK:       (type $receive-sub-cont (cont $receive-sub))
  (type $receive-sub-cont (cont $receive-sub))

  ;; CHECK:       (type $6 (func (result (ref null $super))))

  ;; CHECK:      (tag $expect-super (type $6) (result (ref null $super)))
  (tag $expect-super (result (ref null $super)))

  ;; CHECK:      (func $resume-throw-ref-tag-result (type $f)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block $l (result (ref null $receive-sub-cont))
  ;; CHECK-NEXT:    (block ;; (replaces unreachable ResumeThrow we can't emit)
  ;; CHECK-NEXT:     (drop
  ;; CHECK-NEXT:      (ref.null noexn)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (drop
  ;; CHECK-NEXT:      (ref.null nocont)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:     (unreachable)
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-throw-ref-tag-result
    (local $cont (ref null $cont))
    (drop
      (block $l (result (ref null $receive-sub-cont))
        ;; Same as above, but now the continuation is null so we can optimize.
        (resume_throw_ref $cont (on $expect-super $l)
          (ref.null noexn)
          (ref.null nocont)
        )
        (ref.null nocont)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $return-sub (func (result (ref null $sub))))
  (type $return-sub (func (result (ref null $sub))))
  ;; CHECK:       (type $return-super (func (result (ref null $super))))
  (type $return-super (func (result (ref null $super))))

  ;; CHECK:       (type $return-sub-cont (cont $return-sub))
  (type $return-sub-cont (cont $return-sub))
  ;; CHECK:       (type $return-super-cont (cont $return-super))
  (type $return-super-cont (cont $return-super))

  ;; CHECK:       (type $6 (func))

  ;; CHECK:      (tag $e (type $6))
  (tag $e)

  ;; CHECK:      (func $resume-throw-cont-result (type $6)
  ;; CHECK-NEXT:  (local $cont (ref null $return-sub-cont))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block $l (result (ref null $return-super-cont))
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (resume_throw $return-sub-cont $e (on $e $l)
  ;; CHECK-NEXT:      (local.get $cont)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-throw-cont-result
    (local $cont (ref null $return-sub-cont))
    (drop
      (block $l (result (ref null $return-super-cont))
        (drop
          ;; The continuation we're resuming returns a $sub. In the next type we
          ;; give it, it returns a $super. This requires $sub <: $super.
          (resume_throw $return-sub-cont $e (on $e $l)
            (local.get $cont)
          )
        )
        (ref.null nocont)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $return-sub (func (result (ref null $sub))))
  (type $return-sub (func (result (ref null $sub))))
  ;; CHECK:       (type $return-super (func (result (ref null $super))))
  (type $return-super (func (result (ref null $super))))

  ;; CHECK:       (type $return-sub-cont (cont $return-sub))
  (type $return-sub-cont (cont $return-sub))
  ;; CHECK:       (type $return-super-cont (cont $return-super))
  (type $return-super-cont (cont $return-super))

  ;; CHECK:       (type $6 (func))

  ;; CHECK:      (tag $e (type $6))
  (tag $e)

  ;; CHECK:      (func $resume-throw-cont-result (type $6)
  ;; CHECK-NEXT:  (local $cont (ref null $return-sub-cont))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block $l (result (ref null $return-super-cont))
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (block ;; (replaces unreachable ResumeThrow we can't emit)
  ;; CHECK-NEXT:      (drop
  ;; CHECK-NEXT:       (ref.null nocont)
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:      (unreachable)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-throw-cont-result
    (local $cont (ref null $return-sub-cont))
    (drop
      (block $l (result (ref null $return-super-cont))
        (drop
          ;; Same as above, but now the continuation is null so we can optimize.
          (resume_throw $return-sub-cont $e (on $e $l)
            (ref.null nocont)
          )
        )
        (ref.null nocont)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $return-sub (func (result (ref null $sub))))
  (type $return-sub (func (result (ref null $sub))))
  ;; CHECK:       (type $return-super (func (result (ref null $super))))
  (type $return-super (func (result (ref null $super))))

  ;; CHECK:       (type $return-sub-cont (cont $return-sub))
  (type $return-sub-cont (cont $return-sub))
  ;; CHECK:       (type $return-super-cont (cont $return-super))
  (type $return-super-cont (cont $return-super))

  ;; CHECK:       (type $6 (func))

  ;; CHECK:      (tag $e (type $6))
  (tag $e)

  ;; CHECK:      (func $resume-throw-ref-cont-result (type $6)
  ;; CHECK-NEXT:  (local $cont (ref null $return-sub-cont))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block $l (result (ref null $return-super-cont))
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (resume_throw_ref $return-sub-cont (on $e $l)
  ;; CHECK-NEXT:      (ref.null noexn)
  ;; CHECK-NEXT:      (local.get $cont)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-throw-ref-cont-result
    (local $cont (ref null $return-sub-cont))
    (drop
      (block $l (result (ref null $return-super-cont))
        (drop
          ;; The continuation we're resuming returns a $sub. In the next type we
          ;; give it, it returns a $super. This requires $sub <: $super.
          (resume_throw_ref $return-sub-cont (on $e $l)
            (ref.null noexn)
            (local.get $cont)
          )
        )
        (ref.null nocont)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $return-sub (func (result (ref null $sub))))
  (type $return-sub (func (result (ref null $sub))))
  ;; CHECK:       (type $return-super (func (result (ref null $super))))
  (type $return-super (func (result (ref null $super))))

  ;; CHECK:       (type $return-sub-cont (cont $return-sub))
  (type $return-sub-cont (cont $return-sub))
  ;; CHECK:       (type $return-super-cont (cont $return-super))
  (type $return-super-cont (cont $return-super))

  ;; CHECK:       (type $6 (func))

  ;; CHECK:      (tag $e (type $6))
  (tag $e)

  ;; CHECK:      (func $resume-throw-ref-cont-result (type $6)
  ;; CHECK-NEXT:  (local $cont (ref null $return-sub-cont))
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (block $l (result (ref null $return-super-cont))
  ;; CHECK-NEXT:    (drop
  ;; CHECK-NEXT:     (block ;; (replaces unreachable ResumeThrow we can't emit)
  ;; CHECK-NEXT:      (drop
  ;; CHECK-NEXT:       (ref.null noexn)
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:      (drop
  ;; CHECK-NEXT:       (ref.null nocont)
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:      (unreachable)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-throw-ref-cont-result
    (local $cont (ref null $return-sub-cont))
    (drop
      (block $l (result (ref null $return-super-cont))
        (drop
          ;; Same as above, but now the continuation is null so we can optimize.
          (resume_throw_ref $return-sub-cont (on $e $l)
            (ref.null noexn)
            (ref.null nocont)
          )
        )
        (ref.null nocont)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  (rec
    ;; CHECK:       (type $f (func (param (ref null $super) (ref null $ret-cont))))
    (type $f (func (param (ref null $super) (ref null $ret-cont))))
    ;; CHECK:       (type $cont (cont $f))
    (type $cont (cont $f))

    ;; CHECK:       (type $ret-f (func))
    (type $ret-f (func))
    ;; CHECK:       (type $ret-cont (cont $ret-f))
    (type $ret-cont (cont $ret-f))
  )

  ;; CHECK:       (type $6 (func))

  ;; CHECK:      (tag $e (type $6))
  (tag $e)

  ;; CHECK:      (func $switch-param (type $6)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (switch $cont $e
  ;; CHECK-NEXT:   (struct.new_default $sub)
  ;; CHECK-NEXT:   (local.get $cont)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $switch-param
    (local $cont (ref null $cont))
    ;; The continuation expects a $super, but we send it a $sub. This requires
    ;; $sub <: $super.
    (switch $cont $e
      (struct.new $sub)
      (local.get $cont)
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  (rec
    ;; CHECK:       (type $f (func (param (ref null $super) (ref null $ret-cont))))
    (type $f (func (param (ref null $super) (ref null $ret-cont))))
    ;; CHECK:       (type $cont (cont $f))
    (type $cont (cont $f))

    ;; CHECK:       (type $ret-f (func))
    (type $ret-f (func))
    ;; CHECK:       (type $ret-cont (cont $ret-f))
    (type $ret-cont (cont $ret-f))
  )

  ;; CHECK:       (type $6 (func))

  ;; CHECK:      (tag $e (type $6))
  (tag $e)

  ;; CHECK:      (func $switch-param (type $6)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (block ;; (replaces unreachable StackSwitch we can't emit)
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (struct.new_default $sub)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $switch-param
    (local $cont (ref null $cont))
    ;; Same as above, but now the continuation is null so we can optimize.
    (switch $cont $e
      (struct.new $sub)
      (ref.null nocont)
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  (rec
    ;; CHECK:       (type $f (func (param (ref null $ret-cont)) (result (ref null $sub))))
    (type $f (func (param (ref null $ret-cont)) (result (ref null $sub))))
    ;; CHECK:       (type $cont (cont $f))
    (type $cont (cont $f))

    ;; CHECK:       (type $ret-f (func (result (ref null $super))))
    (type $ret-f (func (result (ref null $super))))
    ;; CHECK:       (type $ret-cont (cont $ret-f))
    (type $ret-cont (cont $ret-f))
  )

  ;; CHECK:       (type $6 (func (result (ref null $super))))

  ;; CHECK:       (type $7 (func))

  ;; CHECK:      (tag $e (type $6) (result (ref null $super)))
  (tag $e (result (ref null $super)))

  ;; CHECK:      (func $switch-target-result (type $7)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (switch $cont $e
  ;; CHECK-NEXT:   (local.get $cont)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $switch-target-result
    (local $cont (ref null $cont))
    ;; The current continuation returns a $super (as indicated in the tag) and
    ;; the target continuation will return a $sub. This requires $sub <: $super.
    (switch $cont $e
      (local.get $cont)
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  (rec
    ;; CHECK:       (type $f (func (param (ref null $ret-cont)) (result (ref null $sub))))
    (type $f (func (param (ref null $ret-cont)) (result (ref null $sub))))
    ;; CHECK:       (type $cont (cont $f))
    (type $cont (cont $f))

    ;; CHECK:       (type $ret-f (func (result (ref null $super))))
    (type $ret-f (func (result (ref null $super))))
    ;; CHECK:       (type $ret-cont (cont $ret-f))
    (type $ret-cont (cont $ret-f))
  )

  ;; CHECK:       (type $6 (func (result (ref null $super))))

  ;; CHECK:       (type $7 (func))

  ;; CHECK:      (tag $e (type $6) (result (ref null $super)))
  (tag $e (result (ref null $super)))

  ;; CHECK:      (func $switch-target-result (type $7)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (block ;; (replaces unreachable StackSwitch we can't emit)
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $switch-target-result
    (local $cont (ref null $cont))
    ;; Same as above, but now the continuation is null so we can optimize.
    (switch $cont $e
      (ref.null nocont)
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  (rec
    ;; CHECK:       (type $f (func (param (ref null $ret-cont)) (result (ref null $sub))))
    (type $f (func (param (ref null $ret-cont)) (result (ref null $sub))))
    ;; CHECK:       (type $cont (cont $f))
    (type $cont (cont $f))

    ;; CHECK:       (type $ret-f (func (result (ref null $super))))
    (type $ret-f (func (result (ref null $super))))
    ;; CHECK:       (type $ret-cont (cont $ret-f))
    (type $ret-cont (cont $ret-f))
  )

  ;; CHECK:       (type $6 (func (result (ref null $sub))))

  ;; CHECK:       (type $7 (func))

  ;; CHECK:      (tag $e (type $6) (result (ref null $sub)))
  (tag $e (result (ref null $sub)))

  ;; CHECK:      (func $switch-return-result (type $7)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (switch $cont $e
  ;; CHECK-NEXT:   (local.get $cont)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $switch-return-result
    (local $cont (ref null $cont))
    ;; The current continuation returns a $sub (as indicated in the tag) and
    ;; after the switch it will be given the return continuation type returning
    ;; $super. This requires $sub <: $super.
    (switch $cont $e
      (local.get $cont)
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub (struct)))
  (type $sub (sub $super (struct)))

  (rec
    ;; CHECK:       (type $f (func (param (ref null $ret-cont)) (result (ref null $sub))))
    (type $f (func (param (ref null $ret-cont)) (result (ref null $sub))))
    ;; CHECK:       (type $cont (cont $f))
    (type $cont (cont $f))

    ;; CHECK:       (type $ret-f (func (result (ref null $super))))
    (type $ret-f (func (result (ref null $super))))
    ;; CHECK:       (type $ret-cont (cont $ret-f))
    (type $ret-cont (cont $ret-f))
  )

  ;; CHECK:       (type $6 (func (result (ref null $sub))))

  ;; CHECK:       (type $7 (func))

  ;; CHECK:      (tag $e (type $6) (result (ref null $sub)))
  (tag $e (result (ref null $sub)))

  ;; CHECK:      (func $switch-return-result (type $7)
  ;; CHECK-NEXT:  (local $cont (ref null $cont))
  ;; CHECK-NEXT:  (block ;; (replaces unreachable StackSwitch we can't emit)
  ;; CHECK-NEXT:   (drop
  ;; CHECK-NEXT:    (ref.null nocont)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:   (unreachable)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $switch-return-result
    (local $cont (ref null $cont))
    ;; Same as above, but now the continuation is null so we can optimize.
    (switch $cont $e
      (ref.null nocont)
    )
  )
)

;; Test that processResumeHandlers correctly iterates handler tag parameters
;; using the inner loop variable. With two handlers where handler 1 has multiple
;; parameters, the subtyping constraint at param index 0 of handler 1 must be
;; noted (not the constraint at param index 1 repeated).
(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (struct)))
  (type $super (sub (struct)))
  ;; CHECK:       (type $sub (sub $super (struct)))
  (type $sub (sub $super (struct)))

  ;; CHECK:       (type $f (func))
  (type $f (func))
  ;; CHECK:       (type $cont (cont $f))
  (type $cont (cont $f))

  ;; First tag has 1 param; second tag has 2 params with $sub at index 0.
  ;; CHECK:       (type $4 (func (param i32)))

  ;; CHECK:       (type $5 (func (param (ref null $sub) i32)))

  ;; CHECK:       (type $6 (func (result (ref null $super) i32 (ref null $cont))))

  ;; CHECK:       (type $7 (func (result i32 (ref null $cont))))

  ;; CHECK:      (tag $e0 (type $4) (param i32))
  (tag $e0 (param i32))
  ;; CHECK:      (tag $e1 (type $5) (param (ref null $sub) i32))
  (tag $e1 (param (ref null $sub) i32))

  ;; CHECK:      (func $resume-handler-multi-param (type $f)
  ;; CHECK-NEXT:  (local $c (ref null $cont))
  ;; CHECK-NEXT:  (tuple.drop 2
  ;; CHECK-NEXT:   (block $l0 (type $7) (result i32 (ref null $cont))
  ;; CHECK-NEXT:    (tuple.drop 3
  ;; CHECK-NEXT:     (block $l1 (type $6) (result (ref null $super) i32 (ref null $cont))
  ;; CHECK-NEXT:      (resume $cont (on $e0 $l0) (on $e1 $l1)
  ;; CHECK-NEXT:       (local.get $c)
  ;; CHECK-NEXT:      )
  ;; CHECK-NEXT:      (unreachable)
  ;; CHECK-NEXT:     )
  ;; CHECK-NEXT:    )
  ;; CHECK-NEXT:    (unreachable)
  ;; CHECK-NEXT:   )
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $resume-handler-multi-param
    (local $c (ref null $cont))
    (tuple.drop 2
      (block $l0 (result i32 (ref null $cont))
        (tuple.drop 3
          (block $l1 (result (ref null $super) i32 (ref null $cont))
            ;; Handler 1 sends (ref null $sub, i32) to $l1 which expects
            ;; (ref null $super, i32, ref null $cont). This requires
            ;; $sub <: $super at param index 0 of handler 1.
            (resume $cont (on $e0 $l0) (on $e1 $l1)
              (local.get $c)
            )
            (unreachable)
          )
        )
        (unreachable)
      )
    )
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (func)))
  (type $super (sub (func)))
  ;; CHECK:       (type $sub (sub $super (func)))
  (type $sub (sub $super (func)))
  ;; CHECK:       (type $cont-super (sub (cont $super)))
  (type $cont-super (sub (cont $super)))
  ;; CHECK:       (type $cont-sub (sub $cont-super (cont $sub)))
  (type $cont-sub (sub $cont-super (cont $sub)))

  ;; CHECK:       (type $4 (func (param (ref $cont-sub)) (result (ref $cont-super))))

  ;; CHECK:      (func $cont-subtyping (type $4) (param $sub (ref $cont-sub)) (result (ref $cont-super))
  ;; CHECK-NEXT:  (local.get $sub)
  ;; CHECK-NEXT: )
  (func $cont-subtyping (param $sub (ref $cont-sub)) (result (ref $cont-super))
    ;; This requires $cont-sub <: $cont-super and $sub <: $super.
    (local.get $sub)
  )
)

(module
  ;; CHECK:      (rec
  ;; CHECK-NEXT:  (type $super (sub (func)))
  (type $super (sub (func)))
  ;; CHECK:       (type $sub (sub (func)))
  (type $sub (sub $super (func)))
  ;; CHECK:       (type $cont-super (sub (cont $super)))
  (type $cont-super (sub (cont $super)))
  ;; CHECK:       (type $cont-sub (sub (cont $sub)))
  (type $cont-sub (sub $cont-super (cont $sub)))

  ;; CHECK:       (type $4 (func (param (ref $cont-sub)) (result (ref $cont-sub))))

  ;; CHECK:      (func $cont-unsubtyping (type $4) (param $sub (ref $cont-sub)) (result (ref $cont-sub))
  ;; CHECK-NEXT:  (local $keepalive (ref $cont-super))
  ;; CHECK-NEXT:  (local.get $sub)
  ;; CHECK-NEXT: )
  (func $cont-unsubtyping (param $sub (ref $cont-sub)) (result (ref $cont-sub))
    (local $keepalive (ref $cont-super))
    ;; As above, but now we return the subtype, so there is no constraint. We
    ;; can unsubtype both the continuations and the funcs.
    (local.get $sub)
  )
)
