;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.
;; NOTE: This test was ported using port_passes_tests_to_lit.py and could be cleaned up.

;; RUN: foreach %s %t wasm-opt --vacuum --ignore-implicit-traps -S -o - | filecheck %s

(module
  (memory 1)
  ;; CHECK:      (type $0 (func (result i32)))

  ;; CHECK:      (type $1 (func))

  ;; CHECK:      (memory $0 1)

  ;; CHECK:      (func $load-would-normally-have-side-effects (result i32)
  ;; CHECK-NEXT:  (i64.ge_s
  ;; CHECK-NEXT:   (i64.const 2912825531628789796)
  ;; CHECK-NEXT:   (i64.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (func $load-would-normally-have-side-effects (result i32)
   (i64.ge_s
    (block (result i64)
     (drop
      (i64.eq
       (i64.load32_s
        (i32.const 678585719)
       )
       (i64.const 8097879367757079605)
      )
     )
     (i64.const 2912825531628789796)
    )
    (i64.const 0)
   )
  )
  ;; CHECK:      (func $unary-binary-may-trap
  ;; CHECK-NEXT:  (nop)
  ;; CHECK-NEXT: )
  (func $unary-binary-may-trap
   (drop
    (i64.div_s
     (i64.const -1)
     (i64.const 729618461987467893)
    )
   )
   (drop
    (i64.trunc_f32_u
     (f32.const 70847791997969805621592064)
    )
   )
  )
)

