import {
	BinaryenObj,
} from "../../-pre.ts";



/**
 * Operations
 * @see https://webassembly.github.io/spec/core/exec/numerics.html
 */
export enum Operation {
	// ### Control Operations ### //
	BrOnNull = BinaryenObj["_BinaryenBrOnNull"](),
	BrOnNonNull = BinaryenObj["_BinaryenBrOnNonNull"](),
	BrOnCast = BinaryenObj["_BinaryenBrOnCast"](),
	BrOnCastFail = BinaryenObj["_BinaryenBrOnCastFail"](),

	// ### Memory Operations ### //
	Load8x8SVec128 = BinaryenObj["_BinaryenLoad8x8SVec128"](),
	Load8x8UVec128 = BinaryenObj["_BinaryenLoad8x8UVec128"](),
	Load16x4SVec128 = BinaryenObj["_BinaryenLoad16x4SVec128"](),
	Load16x4UVec128 = BinaryenObj["_BinaryenLoad16x4UVec128"](),
	Load32x2SVec128 = BinaryenObj["_BinaryenLoad32x2SVec128"](),
	Load32x2UVec128 = BinaryenObj["_BinaryenLoad32x2UVec128"](),
	Load8SplatVec128 = BinaryenObj["_BinaryenLoad8SplatVec128"](),
	Load16SplatVec128 = BinaryenObj["_BinaryenLoad16SplatVec128"](),
	Load32SplatVec128 = BinaryenObj["_BinaryenLoad32SplatVec128"](),
	Load64SplatVec128 = BinaryenObj["_BinaryenLoad64SplatVec128"](),
	Load32ZeroVec128 = BinaryenObj["_BinaryenLoad32ZeroVec128"](),
	Load64ZeroVec128 = BinaryenObj["_BinaryenLoad64ZeroVec128"](),
	Load8LaneVec128 = BinaryenObj["_BinaryenLoad8LaneVec128"](),
	Load16LaneVec128 = BinaryenObj["_BinaryenLoad16LaneVec128"](),
	Load32LaneVec128 = BinaryenObj["_BinaryenLoad32LaneVec128"](),
	Load64LaneVec128 = BinaryenObj["_BinaryenLoad64LaneVec128"](),
	Store8LaneVec128 = BinaryenObj["_BinaryenStore8LaneVec128"](),
	Store16LaneVec128 = BinaryenObj["_BinaryenStore16LaneVec128"](),
	Store32LaneVec128 = BinaryenObj["_BinaryenStore32LaneVec128"](),
	Store64LaneVec128 = BinaryenObj["_BinaryenStore64LaneVec128"](),

	// ### Reference Operations ### //
	RefAsNonNull = BinaryenObj["_BinaryenRefAsNonNull"](),
	RefAsExternInternalize = BinaryenObj["_BinaryenRefAsExternInternalize"](),
	RefAsExternExternalize = BinaryenObj["_BinaryenRefAsExternExternalize"](),
	RefAsAnyConvertExtern = BinaryenObj["_BinaryenRefAsAnyConvertExtern"](),
	RefAsExternConvertAny = BinaryenObj["_BinaryenRefAsExternConvertAny"](),

	// ### Integer Operations ### //
	// #### unop #### //
	ClzInt32 = BinaryenObj["_BinaryenClzInt32"](),
	ClzInt64 = BinaryenObj["_BinaryenClzInt64"](),
	CtzInt32 = BinaryenObj["_BinaryenCtzInt32"](),
	CtzInt64 = BinaryenObj["_BinaryenCtzInt64"](),
	PopcntInt32 = BinaryenObj["_BinaryenPopcntInt32"](),
	PopcntInt64 = BinaryenObj["_BinaryenPopcntInt64"](),
	ExtendS8Int32 = BinaryenObj["_BinaryenExtendS8Int32"](),
	ExtendS8Int64 = BinaryenObj["_BinaryenExtendS8Int64"](),
	ExtendS16Int32 = BinaryenObj["_BinaryenExtendS16Int32"](),
	ExtendS16Int64 = BinaryenObj["_BinaryenExtendS16Int64"](),
	ExtendS32Int64 = BinaryenObj["_BinaryenExtendS32Int64"](),
	// #### binop #### //
	AddInt32 = BinaryenObj["_BinaryenAddInt32"](),
	AddInt64 = BinaryenObj["_BinaryenAddInt64"](),
	SubInt32 = BinaryenObj["_BinaryenSubInt32"](),
	SubInt64 = BinaryenObj["_BinaryenSubInt64"](),
	MulInt32 = BinaryenObj["_BinaryenMulInt32"](),
	MulInt64 = BinaryenObj["_BinaryenMulInt64"](),
	DivSInt32 = BinaryenObj["_BinaryenDivSInt32"](),
	DivSInt64 = BinaryenObj["_BinaryenDivSInt64"](),
	DivUInt32 = BinaryenObj["_BinaryenDivUInt32"](),
	DivUInt64 = BinaryenObj["_BinaryenDivUInt64"](),
	RemSInt32 = BinaryenObj["_BinaryenRemSInt32"](),
	RemSInt64 = BinaryenObj["_BinaryenRemSInt64"](),
	RemUInt32 = BinaryenObj["_BinaryenRemUInt32"](),
	RemUInt64 = BinaryenObj["_BinaryenRemUInt64"](),
	AndInt32 = BinaryenObj["_BinaryenAndInt32"](),
	AndInt64 = BinaryenObj["_BinaryenAndInt64"](),
	OrInt32 = BinaryenObj["_BinaryenOrInt32"](),
	OrInt64 = BinaryenObj["_BinaryenOrInt64"](),
	XorInt32 = BinaryenObj["_BinaryenXorInt32"](),
	XorInt64 = BinaryenObj["_BinaryenXorInt64"](),
	ShlInt32 = BinaryenObj["_BinaryenShlInt32"](),
	ShlInt64 = BinaryenObj["_BinaryenShlInt64"](),
	ShrSInt32 = BinaryenObj["_BinaryenShrSInt32"](),
	ShrSInt64 = BinaryenObj["_BinaryenShrSInt64"](),
	ShrUInt32 = BinaryenObj["_BinaryenShrUInt32"](),
	ShrUInt64 = BinaryenObj["_BinaryenShrUInt64"](),
	RotLInt32 = BinaryenObj["_BinaryenRotLInt32"](),
	RotLInt64 = BinaryenObj["_BinaryenRotLInt64"](),
	RotRInt32 = BinaryenObj["_BinaryenRotRInt32"](),
	RotRInt64 = BinaryenObj["_BinaryenRotRInt64"](),
	// #### testop #### //
	EqZInt32 = BinaryenObj["_BinaryenEqZInt32"](),
	EqZInt64 = BinaryenObj["_BinaryenEqZInt64"](),
	// #### relop #### //
	EqInt32 = BinaryenObj["_BinaryenEqInt32"](),
	EqInt64 = BinaryenObj["_BinaryenEqInt64"](),
	NeInt32 = BinaryenObj["_BinaryenNeInt32"](),
	NeInt64 = BinaryenObj["_BinaryenNeInt64"](),
	LtSInt32 = BinaryenObj["_BinaryenLtSInt32"](),
	LtSInt64 = BinaryenObj["_BinaryenLtSInt64"](),
	LtUInt32 = BinaryenObj["_BinaryenLtUInt32"](),
	LtUInt64 = BinaryenObj["_BinaryenLtUInt64"](),
	GtSInt32 = BinaryenObj["_BinaryenGtSInt32"](),
	GtSInt64 = BinaryenObj["_BinaryenGtSInt64"](),
	GtUInt32 = BinaryenObj["_BinaryenGtUInt32"](),
	GtUInt64 = BinaryenObj["_BinaryenGtUInt64"](),
	LeSInt32 = BinaryenObj["_BinaryenLeSInt32"](),
	LeSInt64 = BinaryenObj["_BinaryenLeSInt64"](),
	LeUInt32 = BinaryenObj["_BinaryenLeUInt32"](),
	LeUInt64 = BinaryenObj["_BinaryenLeUInt64"](),
	GeSInt32 = BinaryenObj["_BinaryenGeSInt32"](),
	GeSInt64 = BinaryenObj["_BinaryenGeSInt64"](),
	GeUInt32 = BinaryenObj["_BinaryenGeUInt32"](),
	GeUInt64 = BinaryenObj["_BinaryenGeUInt64"](),

	// ### Floating-Point Operations ### //
	// #### unop #### //
	AbsFloat32 = BinaryenObj["_BinaryenAbsFloat32"](),
	AbsFloat64 = BinaryenObj["_BinaryenAbsFloat64"](),
	NegFloat32 = BinaryenObj["_BinaryenNegFloat32"](),
	NegFloat64 = BinaryenObj["_BinaryenNegFloat64"](),
	SqrtFloat32 = BinaryenObj["_BinaryenSqrtFloat32"](),
	SqrtFloat64 = BinaryenObj["_BinaryenSqrtFloat64"](),
	CeilFloat32 = BinaryenObj["_BinaryenCeilFloat32"](),
	CeilFloat64 = BinaryenObj["_BinaryenCeilFloat64"](),
	FloorFloat32 = BinaryenObj["_BinaryenFloorFloat32"](),
	FloorFloat64 = BinaryenObj["_BinaryenFloorFloat64"](),
	TruncFloat32 = BinaryenObj["_BinaryenTruncFloat32"](),
	TruncFloat64 = BinaryenObj["_BinaryenTruncFloat64"](),
	NearestFloat32 = BinaryenObj["_BinaryenNearestFloat32"](),
	NearestFloat64 = BinaryenObj["_BinaryenNearestFloat64"](),
	// #### binop #### //
	AddFloat32 = BinaryenObj["_BinaryenAddFloat32"](),
	AddFloat64 = BinaryenObj["_BinaryenAddFloat64"](),
	SubFloat32 = BinaryenObj["_BinaryenSubFloat32"](),
	SubFloat64 = BinaryenObj["_BinaryenSubFloat64"](),
	MulFloat32 = BinaryenObj["_BinaryenMulFloat32"](),
	MulFloat64 = BinaryenObj["_BinaryenMulFloat64"](),
	DivFloat32 = BinaryenObj["_BinaryenDivFloat32"](),
	DivFloat64 = BinaryenObj["_BinaryenDivFloat64"](),
	MinFloat32 = BinaryenObj["_BinaryenMinFloat32"](),
	MinFloat64 = BinaryenObj["_BinaryenMinFloat64"](),
	MaxFloat32 = BinaryenObj["_BinaryenMaxFloat32"](),
	MaxFloat64 = BinaryenObj["_BinaryenMaxFloat64"](),
	CopySignFloat32 = BinaryenObj["_BinaryenCopySignFloat32"](),
	CopySignFloat64 = BinaryenObj["_BinaryenCopySignFloat64"](),
	// #### relop #### //
	EqFloat32 = BinaryenObj["_BinaryenEqFloat32"](),
	EqFloat64 = BinaryenObj["_BinaryenEqFloat64"](),
	NeFloat32 = BinaryenObj["_BinaryenNeFloat32"](),
	NeFloat64 = BinaryenObj["_BinaryenNeFloat64"](),
	LtFloat32 = BinaryenObj["_BinaryenLtFloat32"](),
	LtFloat64 = BinaryenObj["_BinaryenLtFloat64"](),
	GtFloat32 = BinaryenObj["_BinaryenGtFloat32"](),
	GtFloat64 = BinaryenObj["_BinaryenGtFloat64"](),
	LeFloat32 = BinaryenObj["_BinaryenLeFloat32"](),
	LeFloat64 = BinaryenObj["_BinaryenLeFloat64"](),
	GeFloat32 = BinaryenObj["_BinaryenGeFloat32"](),
	GeFloat64 = BinaryenObj["_BinaryenGeFloat64"](),

	// ### Conversions ### //
	ExtendSInt32 = BinaryenObj["_BinaryenExtendSInt32"](),
	ExtendUInt32 = BinaryenObj["_BinaryenExtendUInt32"](),
	WrapInt64 = BinaryenObj["_BinaryenWrapInt64"](),
	TruncSFloat32ToInt32 = BinaryenObj["_BinaryenTruncSFloat32ToInt32"](),
	TruncSFloat32ToInt64 = BinaryenObj["_BinaryenTruncSFloat32ToInt64"](),
	TruncSFloat64ToInt32 = BinaryenObj["_BinaryenTruncSFloat64ToInt32"](),
	TruncSFloat64ToInt64 = BinaryenObj["_BinaryenTruncSFloat64ToInt64"](),
	TruncUFloat32ToInt32 = BinaryenObj["_BinaryenTruncUFloat32ToInt32"](),
	TruncUFloat32ToInt64 = BinaryenObj["_BinaryenTruncUFloat32ToInt64"](),
	TruncUFloat64ToInt32 = BinaryenObj["_BinaryenTruncUFloat64ToInt32"](),
	TruncUFloat64ToInt64 = BinaryenObj["_BinaryenTruncUFloat64ToInt64"](),
	TruncSatSFloat32ToInt32 = BinaryenObj["_BinaryenTruncSatSFloat32ToInt32"](),
	TruncSatSFloat32ToInt64 = BinaryenObj["_BinaryenTruncSatSFloat32ToInt64"](),
	TruncSatSFloat64ToInt32 = BinaryenObj["_BinaryenTruncSatSFloat64ToInt32"](),
	TruncSatSFloat64ToInt64 = BinaryenObj["_BinaryenTruncSatSFloat64ToInt64"](),
	TruncSatUFloat32ToInt32 = BinaryenObj["_BinaryenTruncSatUFloat32ToInt32"](),
	TruncSatUFloat32ToInt64 = BinaryenObj["_BinaryenTruncSatUFloat32ToInt64"](),
	TruncSatUFloat64ToInt32 = BinaryenObj["_BinaryenTruncSatUFloat64ToInt32"](),
	TruncSatUFloat64ToInt64 = BinaryenObj["_BinaryenTruncSatUFloat64ToInt64"](),
	ConvertSInt32ToFloat32 = BinaryenObj["_BinaryenConvertSInt32ToFloat32"](),
	ConvertSInt32ToFloat64 = BinaryenObj["_BinaryenConvertSInt32ToFloat64"](),
	ConvertSInt64ToFloat32 = BinaryenObj["_BinaryenConvertSInt64ToFloat32"](),
	ConvertSInt64ToFloat64 = BinaryenObj["_BinaryenConvertSInt64ToFloat64"](),
	ConvertUInt32ToFloat32 = BinaryenObj["_BinaryenConvertUInt32ToFloat32"](),
	ConvertUInt32ToFloat64 = BinaryenObj["_BinaryenConvertUInt32ToFloat64"](),
	ConvertUInt64ToFloat32 = BinaryenObj["_BinaryenConvertUInt64ToFloat32"](),
	ConvertUInt64ToFloat64 = BinaryenObj["_BinaryenConvertUInt64ToFloat64"](),
	ReinterpretInt32 = BinaryenObj["_BinaryenReinterpretInt32"](),
	ReinterpretInt64 = BinaryenObj["_BinaryenReinterpretInt64"](),
	ReinterpretFloat32 = BinaryenObj["_BinaryenReinterpretFloat32"](),
	ReinterpretFloat64 = BinaryenObj["_BinaryenReinterpretFloat64"](),
	PromoteFloat32 = BinaryenObj["_BinaryenPromoteFloat32"](),
	DemoteFloat64 = BinaryenObj["_BinaryenDemoteFloat64"](),

	// ### Vector Operations ### //
	// #### vvunop #### //
	NotVec128 = BinaryenObj["_BinaryenNotVec128"](),
	// #### vvbinop #### //
	AndVec128 = BinaryenObj["_BinaryenAndVec128"](),
	AndNotVec128 = BinaryenObj["_BinaryenAndNotVec128"](),
	OrVec128 = BinaryenObj["_BinaryenOrVec128"](),
	XorVec128 = BinaryenObj["_BinaryenXorVec128"](),
	// #### vvternop #### //
	BitselectVec128 = BinaryenObj["_BinaryenBitselectVec128"](),
	// #### vvtestop #### //
	AnyTrueVec128 = BinaryenObj["_BinaryenAnyTrueVec128"](),
	// #### vunop_i #### //
	AbsVecI8x16 = BinaryenObj["_BinaryenAbsVecI8x16"](),
	AbsVecI16x8 = BinaryenObj["_BinaryenAbsVecI16x8"](),
	AbsVecI32x4 = BinaryenObj["_BinaryenAbsVecI32x4"](),
	AbsVecI64x2 = BinaryenObj["_BinaryenAbsVecI64x2"](),
	NegVecI8x16 = BinaryenObj["_BinaryenNegVecI8x16"](),
	NegVecI16x8 = BinaryenObj["_BinaryenNegVecI16x8"](),
	NegVecI32x4 = BinaryenObj["_BinaryenNegVecI32x4"](),
	NegVecI64x2 = BinaryenObj["_BinaryenNegVecI64x2"](),
	PopcntVecI8x16 = BinaryenObj["_BinaryenPopcntVecI8x16"](),
	// #### vunop_f #### //
	AbsVecF32x4 = BinaryenObj["_BinaryenAbsVecF32x4"](),
	AbsVecF64x2 = BinaryenObj["_BinaryenAbsVecF64x2"](),
	NegVecF32x4 = BinaryenObj["_BinaryenNegVecF32x4"](),
	NegVecF64x2 = BinaryenObj["_BinaryenNegVecF64x2"](),
	SqrtVecF32x4 = BinaryenObj["_BinaryenSqrtVecF32x4"](),
	SqrtVecF64x2 = BinaryenObj["_BinaryenSqrtVecF64x2"](),
	CeilVecF32x4 = BinaryenObj["_BinaryenCeilVecF32x4"](),
	CeilVecF64x2 = BinaryenObj["_BinaryenCeilVecF64x2"](),
	FloorVecF32x4 = BinaryenObj["_BinaryenFloorVecF32x4"](),
	FloorVecF64x2 = BinaryenObj["_BinaryenFloorVecF64x2"](),
	TruncVecF32x4 = BinaryenObj["_BinaryenTruncVecF32x4"](),
	TruncVecF64x2 = BinaryenObj["_BinaryenTruncVecF64x2"](),
	NearestVecF32x4 = BinaryenObj["_BinaryenNearestVecF32x4"](),
	NearestVecF64x2 = BinaryenObj["_BinaryenNearestVecF64x2"](),
	// #### vbinop_i #### //
	AddVecI8x16 = BinaryenObj["_BinaryenAddVecI8x16"](),
	AddVecI16x8 = BinaryenObj["_BinaryenAddVecI16x8"](),
	AddVecI32x4 = BinaryenObj["_BinaryenAddVecI32x4"](),
	AddVecI64x2 = BinaryenObj["_BinaryenAddVecI64x2"](),
	SubVecI8x16 = BinaryenObj["_BinaryenSubVecI8x16"](),
	SubVecI16x8 = BinaryenObj["_BinaryenSubVecI16x8"](),
	SubVecI32x4 = BinaryenObj["_BinaryenSubVecI32x4"](),
	SubVecI64x2 = BinaryenObj["_BinaryenSubVecI64x2"](),
	AddSatSVecI8x16 = BinaryenObj["_BinaryenAddSatSVecI8x16"](),
	AddSatSVecI16x8 = BinaryenObj["_BinaryenAddSatSVecI16x8"](),
	AddSatUVecI8x16 = BinaryenObj["_BinaryenAddSatUVecI8x16"](),
	AddSatUVecI16x8 = BinaryenObj["_BinaryenAddSatUVecI16x8"](),
	SubSatSVecI8x16 = BinaryenObj["_BinaryenSubSatSVecI8x16"](),
	SubSatSVecI16x8 = BinaryenObj["_BinaryenSubSatSVecI16x8"](),
	SubSatUVecI8x16 = BinaryenObj["_BinaryenSubSatUVecI8x16"](),
	SubSatUVecI16x8 = BinaryenObj["_BinaryenSubSatUVecI16x8"](),
	MulVecI16x8 = BinaryenObj["_BinaryenMulVecI16x8"](),
	MulVecI32x4 = BinaryenObj["_BinaryenMulVecI32x4"](),
	MulVecI64x2 = BinaryenObj["_BinaryenMulVecI64x2"](),
	AvgrUVecI8x16 = BinaryenObj["_BinaryenAvgrUVecI8x16"](),
	AvgrUVecI16x8 = BinaryenObj["_BinaryenAvgrUVecI16x8"](),
	Q15MulrSatSVecI16x8 = BinaryenObj["_BinaryenQ15MulrSatSVecI16x8"](),
	RelaxedQ15MulrSVecI16x8 = BinaryenObj["_BinaryenRelaxedQ15MulrSVecI16x8"](),
	MinSVecI8x16 = BinaryenObj["_BinaryenMinSVecI8x16"](),
	MinSVecI16x8 = BinaryenObj["_BinaryenMinSVecI16x8"](),
	MinSVecI32x4 = BinaryenObj["_BinaryenMinSVecI32x4"](),
	MinUVecI8x16 = BinaryenObj["_BinaryenMinUVecI8x16"](),
	MinUVecI16x8 = BinaryenObj["_BinaryenMinUVecI16x8"](),
	MinUVecI32x4 = BinaryenObj["_BinaryenMinUVecI32x4"](),
	MaxSVecI8x16 = BinaryenObj["_BinaryenMaxSVecI8x16"](),
	MaxSVecI16x8 = BinaryenObj["_BinaryenMaxSVecI16x8"](),
	MaxSVecI32x4 = BinaryenObj["_BinaryenMaxSVecI32x4"](),
	MaxUVecI8x16 = BinaryenObj["_BinaryenMaxUVecI8x16"](),
	MaxUVecI16x8 = BinaryenObj["_BinaryenMaxUVecI16x8"](),
	MaxUVecI32x4 = BinaryenObj["_BinaryenMaxUVecI32x4"](),
	// #### vbinop_f #### //
	AddVecF32x4 = BinaryenObj["_BinaryenAddVecF32x4"](),
	AddVecF64x2 = BinaryenObj["_BinaryenAddVecF64x2"](),
	SubVecF32x4 = BinaryenObj["_BinaryenSubVecF32x4"](),
	SubVecF64x2 = BinaryenObj["_BinaryenSubVecF64x2"](),
	MulVecF32x4 = BinaryenObj["_BinaryenMulVecF32x4"](),
	MulVecF64x2 = BinaryenObj["_BinaryenMulVecF64x2"](),
	DivVecF32x4 = BinaryenObj["_BinaryenDivVecF32x4"](),
	DivVecF64x2 = BinaryenObj["_BinaryenDivVecF64x2"](),
	MinVecF32x4 = BinaryenObj["_BinaryenMinVecF32x4"](),
	MinVecF64x2 = BinaryenObj["_BinaryenMinVecF64x2"](),
	MaxVecF32x4 = BinaryenObj["_BinaryenMaxVecF32x4"](),
	MaxVecF64x2 = BinaryenObj["_BinaryenMaxVecF64x2"](),
	PMinVecF32x4 = BinaryenObj["_BinaryenPMinVecF32x4"](),
	PMinVecF64x2 = BinaryenObj["_BinaryenPMinVecF64x2"](),
	PMaxVecF32x4 = BinaryenObj["_BinaryenPMaxVecF32x4"](),
	PMaxVecF64x2 = BinaryenObj["_BinaryenPMaxVecF64x2"](),
	RelaxedMinVecF32x4 = BinaryenObj["_BinaryenRelaxedMinVecF32x4"](),
	RelaxedMinVecF64x2 = BinaryenObj["_BinaryenRelaxedMinVecF64x2"](),
	RelaxedMaxVecF32x4 = BinaryenObj["_BinaryenRelaxedMaxVecF32x4"](),
	RelaxedMaxVecF64x2 = BinaryenObj["_BinaryenRelaxedMaxVecF64x2"](),
	// #### vternop_i #### //
	RelaxedLaneselectI8x16 = BinaryenObj["_BinaryenRelaxedLaneselectI8x16"](),
	RelaxedLaneselectI16x8 = BinaryenObj["_BinaryenRelaxedLaneselectI16x8"](),
	RelaxedLaneselectI32x4 = BinaryenObj["_BinaryenRelaxedLaneselectI32x4"](),
	RelaxedLaneselectI64x2 = BinaryenObj["_BinaryenRelaxedLaneselectI64x2"](),
	// #### vternop_f #### //
	RelaxedMaddVecF32x4 = BinaryenObj["_BinaryenRelaxedMaddVecF32x4"](),
	RelaxedMaddVecF64x2 = BinaryenObj["_BinaryenRelaxedMaddVecF64x2"](),
	RelaxedNmaddVecF32x4 = BinaryenObj["_BinaryenRelaxedNmaddVecF32x4"](),
	RelaxedNmaddVecF64x2 = BinaryenObj["_BinaryenRelaxedNmaddVecF64x2"](),
	// #### vtestop_i #### //
	AllTrueVecI8x16 = BinaryenObj["_BinaryenAllTrueVecI8x16"](),
	AllTrueVecI16x8 = BinaryenObj["_BinaryenAllTrueVecI16x8"](),
	AllTrueVecI32x4 = BinaryenObj["_BinaryenAllTrueVecI32x4"](),
	AllTrueVecI64x2 = BinaryenObj["_BinaryenAllTrueVecI64x2"](),
	// #### vrelop_i #### //
	EqVecI8x16 = BinaryenObj["_BinaryenEqVecI8x16"](),
	EqVecI16x8 = BinaryenObj["_BinaryenEqVecI16x8"](),
	EqVecI32x4 = BinaryenObj["_BinaryenEqVecI32x4"](),
	EqVecI64x2 = BinaryenObj["_BinaryenEqVecI64x2"](),
	NeVecI8x16 = BinaryenObj["_BinaryenNeVecI8x16"](),
	NeVecI16x8 = BinaryenObj["_BinaryenNeVecI16x8"](),
	NeVecI32x4 = BinaryenObj["_BinaryenNeVecI32x4"](),
	NeVecI64x2 = BinaryenObj["_BinaryenNeVecI64x2"](),
	LtSVecI8x16 = BinaryenObj["_BinaryenLtSVecI8x16"](),
	LtSVecI16x8 = BinaryenObj["_BinaryenLtSVecI16x8"](),
	LtSVecI32x4 = BinaryenObj["_BinaryenLtSVecI32x4"](),
	LtSVecI64x2 = BinaryenObj["_BinaryenLtSVecI64x2"](),
	LtUVecI8x16 = BinaryenObj["_BinaryenLtUVecI8x16"](),
	LtUVecI16x8 = BinaryenObj["_BinaryenLtUVecI16x8"](),
	LtUVecI32x4 = BinaryenObj["_BinaryenLtUVecI32x4"](),
	// LtUVecI64x2 // not supported; see #414
	GtSVecI8x16 = BinaryenObj["_BinaryenGtSVecI8x16"](),
	GtSVecI16x8 = BinaryenObj["_BinaryenGtSVecI16x8"](),
	GtSVecI32x4 = BinaryenObj["_BinaryenGtSVecI32x4"](),
	GtSVecI64x2 = BinaryenObj["_BinaryenGtSVecI64x2"](),
	GtUVecI8x16 = BinaryenObj["_BinaryenGtUVecI8x16"](),
	GtUVecI16x8 = BinaryenObj["_BinaryenGtUVecI16x8"](),
	GtUVecI32x4 = BinaryenObj["_BinaryenGtUVecI32x4"](),
	// GtUVecI64x2 // not supported; see #414
	LeSVecI8x16 = BinaryenObj["_BinaryenLeSVecI8x16"](),
	LeSVecI16x8 = BinaryenObj["_BinaryenLeSVecI16x8"](),
	LeSVecI32x4 = BinaryenObj["_BinaryenLeSVecI32x4"](),
	LeSVecI64x2 = BinaryenObj["_BinaryenLeSVecI64x2"](),
	LeUVecI8x16 = BinaryenObj["_BinaryenLeUVecI8x16"](),
	LeUVecI16x8 = BinaryenObj["_BinaryenLeUVecI16x8"](),
	LeUVecI32x4 = BinaryenObj["_BinaryenLeUVecI32x4"](),
	// LeUVecI64x2 // not supported; see #414
	GeSVecI8x16 = BinaryenObj["_BinaryenGeSVecI8x16"](),
	GeSVecI16x8 = BinaryenObj["_BinaryenGeSVecI16x8"](),
	GeSVecI32x4 = BinaryenObj["_BinaryenGeSVecI32x4"](),
	GeSVecI64x2 = BinaryenObj["_BinaryenGeSVecI64x2"](),
	GeUVecI8x16 = BinaryenObj["_BinaryenGeUVecI8x16"](),
	GeUVecI16x8 = BinaryenObj["_BinaryenGeUVecI16x8"](),
	GeUVecI32x4 = BinaryenObj["_BinaryenGeUVecI32x4"](),
	// GeUVecI64x2 // not supported; see #414
	// #### vrelop_f #### //
	EqVecF32x4 = BinaryenObj["_BinaryenEqVecF32x4"](),
	EqVecF64x2 = BinaryenObj["_BinaryenEqVecF64x2"](),
	NeVecF32x4 = BinaryenObj["_BinaryenNeVecF32x4"](),
	NeVecF64x2 = BinaryenObj["_BinaryenNeVecF64x2"](),
	LtVecF32x4 = BinaryenObj["_BinaryenLtVecF32x4"](),
	LtVecF64x2 = BinaryenObj["_BinaryenLtVecF64x2"](),
	GtVecF32x4 = BinaryenObj["_BinaryenGtVecF32x4"](),
	GtVecF64x2 = BinaryenObj["_BinaryenGtVecF64x2"](),
	LeVecF32x4 = BinaryenObj["_BinaryenLeVecF32x4"](),
	LeVecF64x2 = BinaryenObj["_BinaryenLeVecF64x2"](),
	GeVecF32x4 = BinaryenObj["_BinaryenGeVecF32x4"](),
	GeVecF64x2 = BinaryenObj["_BinaryenGeVecF64x2"](),
	// #### vshiftop #### //
	ShlVecI8x16 = BinaryenObj["_BinaryenShlVecI8x16"](),
	ShlVecI16x8 = BinaryenObj["_BinaryenShlVecI16x8"](),
	ShlVecI32x4 = BinaryenObj["_BinaryenShlVecI32x4"](),
	ShlVecI64x2 = BinaryenObj["_BinaryenShlVecI64x2"](),
	ShrSVecI8x16 = BinaryenObj["_BinaryenShrSVecI8x16"](),
	ShrSVecI16x8 = BinaryenObj["_BinaryenShrSVecI16x8"](),
	ShrSVecI32x4 = BinaryenObj["_BinaryenShrSVecI32x4"](),
	ShrSVecI64x2 = BinaryenObj["_BinaryenShrSVecI64x2"](),
	ShrUVecI8x16 = BinaryenObj["_BinaryenShrUVecI8x16"](),
	ShrUVecI16x8 = BinaryenObj["_BinaryenShrUVecI16x8"](),
	ShrUVecI32x4 = BinaryenObj["_BinaryenShrUVecI32x4"](),
	ShrUVecI64x2 = BinaryenObj["_BinaryenShrUVecI64x2"](),
	// #### bitmask #### //
	BitmaskVecI8x16 = BinaryenObj["_BinaryenBitmaskVecI8x16"](),
	BitmaskVecI16x8 = BinaryenObj["_BinaryenBitmaskVecI16x8"](),
	BitmaskVecI32x4 = BinaryenObj["_BinaryenBitmaskVecI32x4"](),
	BitmaskVecI64x2 = BinaryenObj["_BinaryenBitmaskVecI64x2"](),
	// #### vswizzleop #### //
	SwizzleVecI8x16 = BinaryenObj["_BinaryenSwizzleVecI8x16"](),
	RelaxedSwizzleVecI8x16 = BinaryenObj["_BinaryenRelaxedSwizzleVecI8x16"](),
	// #### vextunop #### //
	ExtAddPairwiseSVecI8x16ToI16x8 = BinaryenObj["_BinaryenExtAddPairwiseSVecI8x16ToI16x8"](),
	ExtAddPairwiseSVecI16x8ToI32x4 = BinaryenObj["_BinaryenExtAddPairwiseSVecI16x8ToI32x4"](),
	ExtAddPairwiseUVecI8x16ToI16x8 = BinaryenObj["_BinaryenExtAddPairwiseUVecI8x16ToI16x8"](),
	ExtAddPairwiseUVecI16x8ToI32x4 = BinaryenObj["_BinaryenExtAddPairwiseUVecI16x8ToI32x4"](),
	// #### vextbinop #### //
	ExtMulLowSVecI16x8 = BinaryenObj["_BinaryenExtMulLowSVecI16x8"](),
	ExtMulLowSVecI32x4 = BinaryenObj["_BinaryenExtMulLowSVecI32x4"](),
	ExtMulLowSVecI64x2 = BinaryenObj["_BinaryenExtMulLowSVecI64x2"](),
	ExtMulLowUVecI16x8 = BinaryenObj["_BinaryenExtMulLowUVecI16x8"](),
	ExtMulLowUVecI32x4 = BinaryenObj["_BinaryenExtMulLowUVecI32x4"](),
	ExtMulLowUVecI64x2 = BinaryenObj["_BinaryenExtMulLowUVecI64x2"](),
	ExtMulHighSVecI16x8 = BinaryenObj["_BinaryenExtMulHighSVecI16x8"](),
	ExtMulHighSVecI32x4 = BinaryenObj["_BinaryenExtMulHighSVecI32x4"](),
	ExtMulHighSVecI64x2 = BinaryenObj["_BinaryenExtMulHighSVecI64x2"](),
	ExtMulHighUVecI16x8 = BinaryenObj["_BinaryenExtMulHighUVecI16x8"](),
	ExtMulHighUVecI32x4 = BinaryenObj["_BinaryenExtMulHighUVecI32x4"](),
	ExtMulHighUVecI64x2 = BinaryenObj["_BinaryenExtMulHighUVecI64x2"](),
	DotSVecI16x8ToVecI32x4 = BinaryenObj["_BinaryenDotSVecI16x8ToVecI32x4"](),
	RelaxedDotI8x16I7x16SToVecI16x8 = BinaryenObj["_BinaryenRelaxedDotI8x16I7x16SToVecI16x8"](),
	RelaxedDotI8x16I7x16AddSToVecI32x4 = BinaryenObj["_BinaryenRelaxedDotI8x16I7x16AddSToVecI32x4"](),
	// #### narrow #### //
	NarrowSVecI16x8ToVecI8x16 = BinaryenObj["_BinaryenNarrowSVecI16x8ToVecI8x16"](),
	NarrowSVecI32x4ToVecI16x8 = BinaryenObj["_BinaryenNarrowSVecI32x4ToVecI16x8"](),
	NarrowUVecI16x8ToVecI8x16 = BinaryenObj["_BinaryenNarrowUVecI16x8ToVecI8x16"](),
	NarrowUVecI32x4ToVecI16x8 = BinaryenObj["_BinaryenNarrowUVecI32x4ToVecI16x8"](),
	// #### vcvtop #### //
	ExtendLowSVecI8x16ToVecI16x8 = BinaryenObj["_BinaryenExtendLowSVecI8x16ToVecI16x8"](),
	ExtendLowSVecI16x8ToVecI32x4 = BinaryenObj["_BinaryenExtendLowSVecI16x8ToVecI32x4"](),
	ExtendLowSVecI32x4ToVecI64x2 = BinaryenObj["_BinaryenExtendLowSVecI32x4ToVecI64x2"](),
	ExtendLowUVecI8x16ToVecI16x8 = BinaryenObj["_BinaryenExtendLowUVecI8x16ToVecI16x8"](),
	ExtendLowUVecI16x8ToVecI32x4 = BinaryenObj["_BinaryenExtendLowUVecI16x8ToVecI32x4"](),
	ExtendLowUVecI32x4ToVecI64x2 = BinaryenObj["_BinaryenExtendLowUVecI32x4ToVecI64x2"](),
	ExtendHighSVecI8x16ToVecI16x8 = BinaryenObj["_BinaryenExtendHighSVecI8x16ToVecI16x8"](),
	ExtendHighSVecI16x8ToVecI32x4 = BinaryenObj["_BinaryenExtendHighSVecI16x8ToVecI32x4"](),
	ExtendHighSVecI32x4ToVecI64x2 = BinaryenObj["_BinaryenExtendHighSVecI32x4ToVecI64x2"](),
	ExtendHighUVecI8x16ToVecI16x8 = BinaryenObj["_BinaryenExtendHighUVecI8x16ToVecI16x8"](),
	ExtendHighUVecI16x8ToVecI32x4 = BinaryenObj["_BinaryenExtendHighUVecI16x8ToVecI32x4"](),
	ExtendHighUVecI32x4ToVecI64x2 = BinaryenObj["_BinaryenExtendHighUVecI32x4ToVecI64x2"](),
	ConvertSVecI32x4ToVecF32x4 = BinaryenObj["_BinaryenConvertSVecI32x4ToVecF32x4"](),
	ConvertUVecI32x4ToVecF32x4 = BinaryenObj["_BinaryenConvertUVecI32x4ToVecF32x4"](),
	ConvertLowSVecI32x4ToVecF64x2 = BinaryenObj["_BinaryenConvertLowSVecI32x4ToVecF64x2"](),
	ConvertLowUVecI32x4ToVecF64x2 = BinaryenObj["_BinaryenConvertLowUVecI32x4ToVecF64x2"](),
	TruncSatSVecF32x4ToVecI32x4 = BinaryenObj["_BinaryenTruncSatSVecF32x4ToVecI32x4"](),
	TruncSatUVecF32x4ToVecI32x4 = BinaryenObj["_BinaryenTruncSatUVecF32x4ToVecI32x4"](),
	TruncSatZeroSVecF64x2ToVecI32x4 = BinaryenObj["_BinaryenTruncSatZeroSVecF64x2ToVecI32x4"](),
	TruncSatZeroUVecF64x2ToVecI32x4 = BinaryenObj["_BinaryenTruncSatZeroUVecF64x2ToVecI32x4"](),
	RelaxedTruncSVecF32x4ToVecI32x4 = BinaryenObj["_BinaryenRelaxedTruncSVecF32x4ToVecI32x4"](),
	RelaxedTruncUVecF32x4ToVecI32x4 = BinaryenObj["_BinaryenRelaxedTruncUVecF32x4ToVecI32x4"](),
	RelaxedTruncZeroSVecF64x2ToVecI32x4 = BinaryenObj["_BinaryenRelaxedTruncZeroSVecF64x2ToVecI32x4"](),
	RelaxedTruncZeroUVecF64x2ToVecI32x4 = BinaryenObj["_BinaryenRelaxedTruncZeroUVecF64x2ToVecI32x4"](),
	DemoteZeroVecF64x2ToVecF32x4 = BinaryenObj["_BinaryenDemoteZeroVecF64x2ToVecF32x4"](),
	PromoteLowVecF32x4ToVecF64x2 = BinaryenObj["_BinaryenPromoteLowVecF32x4ToVecF64x2"](),
	// #### splat #### //
	SplatVecI8x16 = BinaryenObj["_BinaryenSplatVecI8x16"](),
	SplatVecI16x8 = BinaryenObj["_BinaryenSplatVecI16x8"](),
	SplatVecI32x4 = BinaryenObj["_BinaryenSplatVecI32x4"](),
	SplatVecI64x2 = BinaryenObj["_BinaryenSplatVecI64x2"](),
	SplatVecF32x4 = BinaryenObj["_BinaryenSplatVecF32x4"](),
	SplatVecF64x2 = BinaryenObj["_BinaryenSplatVecF64x2"](),
	// #### extract_lane #### //
	ExtractLaneSVecI8x16 = BinaryenObj["_BinaryenExtractLaneSVecI8x16"](),
	ExtractLaneSVecI16x8 = BinaryenObj["_BinaryenExtractLaneSVecI16x8"](),
	ExtractLaneUVecI8x16 = BinaryenObj["_BinaryenExtractLaneUVecI8x16"](),
	ExtractLaneUVecI16x8 = BinaryenObj["_BinaryenExtractLaneUVecI16x8"](),
	ExtractLaneVecI32x4 = BinaryenObj["_BinaryenExtractLaneVecI32x4"](),
	ExtractLaneVecI64x2 = BinaryenObj["_BinaryenExtractLaneVecI64x2"](),
	ExtractLaneVecF32x4 = BinaryenObj["_BinaryenExtractLaneVecF32x4"](),
	ExtractLaneVecF64x2 = BinaryenObj["_BinaryenExtractLaneVecF64x2"](),
	// #### replace_lane #### //
	ReplaceLaneVecI8x16 = BinaryenObj["_BinaryenReplaceLaneVecI8x16"](),
	ReplaceLaneVecI16x8 = BinaryenObj["_BinaryenReplaceLaneVecI16x8"](),
	ReplaceLaneVecI32x4 = BinaryenObj["_BinaryenReplaceLaneVecI32x4"](),
	ReplaceLaneVecI64x2 = BinaryenObj["_BinaryenReplaceLaneVecI64x2"](),
	ReplaceLaneVecF32x4 = BinaryenObj["_BinaryenReplaceLaneVecF32x4"](),
	ReplaceLaneVecF64x2 = BinaryenObj["_BinaryenReplaceLaneVecF64x2"](),

	// ### Atomic Operations ### //
	AtomicRMWAdd = BinaryenObj["_BinaryenAtomicRMWAdd"](),
	AtomicRMWSub = BinaryenObj["_BinaryenAtomicRMWSub"](),
	AtomicRMWAnd = BinaryenObj["_BinaryenAtomicRMWAnd"](),
	AtomicRMWOr = BinaryenObj["_BinaryenAtomicRMWOr"](),
	AtomicRMWXor = BinaryenObj["_BinaryenAtomicRMWXor"](),
	AtomicRMWXchg = BinaryenObj["_BinaryenAtomicRMWXchg"](),

	// ### String Operations ### //
	StringNewLossyUTF8Array = BinaryenObj["_BinaryenStringNewLossyUTF8Array"](),
	StringNewWTF16Array = BinaryenObj["_BinaryenStringNewWTF16Array"](),
	StringNewFromCodePoint = BinaryenObj["_BinaryenStringNewFromCodePoint"](),
	StringMeasureUTF8 = BinaryenObj["_BinaryenStringMeasureUTF8"](),
	StringMeasureWTF16 = BinaryenObj["_BinaryenStringMeasureWTF16"](),
	StringEncodeLossyUTF8Array = BinaryenObj["_BinaryenStringEncodeLossyUTF8Array"](),
	StringEncodeWTF16Array = BinaryenObj["_BinaryenStringEncodeWTF16Array"](),
	StringEqEqual = BinaryenObj["_BinaryenStringEqEqual"](),
	StringEqCompare = BinaryenObj["_BinaryenStringEqCompare"](),

	// ### WideInt Operations ### //
	AddInt128 = BinaryenObj["_BinaryenAddInt128"](),
	SubInt128 = BinaryenObj["_BinaryenSubInt128"](),
	MulWideSInt64 = BinaryenObj["_BinaryenMulWideSInt64"](),
	MulWideUInt64 = BinaryenObj["_BinaryenMulWideUInt64"](),
}



export enum MemoryOrder {
	Unordered = BinaryenObj["_BinaryenMemoryOrderUnordered"](),
	SeqCst = BinaryenObj["_BinaryenMemoryOrderSeqCst"](),
	AcqRel = BinaryenObj["_BinaryenMemoryOrderAcqRel"](),
}
