(module
 (import "env" "memory" (memory $0 0))
 (data (global.get $gimport$3) "")
 (import "env" "__indirect_function_table" (table $timport$1 0 funcref))
 (import "env" "__stack_pointer" (global $gimport$2 (mut i32)))
 (import "env" "__memory_base" (global $gimport$3 i32))
 (import "env" "__table_base" (global $gimport$4 i32))
 (import "GOT.mem" "someglobal1" (global $gimport$6 (mut i32)))
 (import "GOT.mem" "someglobal2" (global $gimport$7 (mut i32)))
 (import "GOT.mem" "someglobal3" (global $gimport$8 (mut i32)))
 (global $global$1 i32 (i32.const 54))
 (global $global$2 i32 (i32.const 0))
 (export "someglobal2" (global $global$1))
 (export "main" (func $main))
 (export "__data_end" (global $global$2))
 (func $main (param $0 i32) (param $1 i32) (result i32)
  (i32.const 0)
 )
)

