(module
  (memory 1)
  (export "memory" memory)
  (type $FUNCSIG$i (func (result i32)))
  (type $FUNCSIG$jf (func (param f32) (result i64)))
  (type $FUNCSIG$vd (func (param f64)))
  (type $FUNCSIG$ffjjdi (func (param f32 i64 i64 f64 i32) (result f32)))
  (export "i" $i)
  (export "jf" $jf)
  (export "vd" $vd)
  (export "ffjjdi" $ffjjdi)
  (export "vd2" $vd2)
  (export "main" $main)
  (export "dynCall_i" $dynCall_i)
  (export "dynCall_jf" $dynCall_jf)
  (export "dynCall_vd" $dynCall_vd)
  (export "dynCall_ffjjdi" $dynCall_ffjjdi)
  (table $i $jf $vd $ffjjdi $vd2)
  (func $i (type $FUNCSIG$i) (result i32)
    (return
      (i32.const 0)
    )
  )
  (func $jf (type $FUNCSIG$jf) (param $$0 f32) (result i64)
    (return
      (i64.const 0)
    )
  )
  (func $vd (type $FUNCSIG$vd) (param $$0 f64)
    (return)
  )
  (func $ffjjdi (type $FUNCSIG$ffjjdi) (param $$0 f32) (param $$1 i64) (param $$2 i64) (param $$3 f64) (param $$4 i32) (result f32)
    (return
      (f32.const 0)
    )
  )
  (func $vd2 (type $FUNCSIG$vd) (param $$0 f64)
    (return)
  )
  (func $main (result i32)
    (i32.const 0)
    (i32.const 1)
    (i32.const 2)
    (i32.const 3)
    (i32.const 4)
    (return
      (i32.const 0)
    )
  )
  (func $dynCall_i (param $fptr i32) (result i32)
    (return
      (call_indirect $FUNCSIG$i
        (get_local $fptr)
      )
    )
  )
  (func $dynCall_jf (param $fptr i32) (param $$0 f32) (result i64)
    (return
      (call_indirect $FUNCSIG$jf
        (get_local $fptr)
        (get_local $$0)
      )
    )
  )
  (func $dynCall_vd (param $fptr i32) (param $$0 f64)
    (call_indirect $FUNCSIG$vd
      (get_local $fptr)
      (get_local $$0)
    )
  )
  (func $dynCall_ffjjdi (param $fptr i32) (param $$0 f32) (param $$1 i64) (param $$2 i64) (param $$3 f64) (param $$4 i32) (result f32)
    (return
      (call_indirect $FUNCSIG$ffjjdi
        (get_local $fptr)
        (get_local $$0)
        (get_local $$1)
        (get_local $$2)
        (get_local $$3)
        (get_local $$4)
      )
    )
  )
)
;; METADATA: { "asmConsts": {},"staticBump": 12, "initializers": [] }