(module
 (type $FUNCSIG$v (func))
 (type $FUNCSIG$vi (func (param i32)))
 (type $FUNCSIG$iii (func (param i32 i32) (result i32)))
 (type $FUNCSIG$fffi (func (param f32 f32 i32) (result f32)))
 (type $FUNCSIG$ddi (func (param f64 i32) (result f64)))
 (type $FUNCSIG$viii (func (param i32 i32 i32)))
 (type $FUNCSIG$ii (func (param i32) (result i32)))
 (type $FUNCSIG$didi (func (param i32 f64 i32) (result f64)))
 (type $FUNCSIG$fiffi (func (param i32 f32 f32 i32) (result f32)))
 (type $FUNCSIG$iiii (func (param i32 i32 i32) (result i32)))
 (type $FUNCSIG$vii (func (param i32 i32)))
 (type $FUNCSIG$viiii (func (param i32 i32 i32 i32)))
 (import "env" "atoi" (func $atoi (param i32) (result i32)))
 (import "env" "memory" (memory $0 1))
 (import "env" "jsCall_ddi" (func $jsCall_ddi (param i32 f64 i32) (result f64)))
 (import "env" "jsCall_fffi" (func $jsCall_fffi (param i32 f32 f32 i32) (result f32)))
 (import "env" "jsCall_iii" (func $jsCall_iii (param i32 i32 i32) (result i32)))
 (import "env" "jsCall_v" (func $jsCall_v (param i32)))
 (import "env" "jsCall_vi" (func $jsCall_vi (param i32 i32)))
 (import "env" "jsCall_viii" (func $jsCall_viii (param i32 i32 i32 i32)))
 (table 21 21 anyfunc)
 (elem (i32.const 0) $__wasm_nullptr $_Z18address_taken_funciii $_Z19address_taken_func2iii $jsCall_ddi_0 $jsCall_ddi_1 $jsCall_ddi_2 $jsCall_fffi_0 $jsCall_fffi_1 $jsCall_fffi_2 $jsCall_iii_0 $jsCall_iii_1 $jsCall_iii_2 $jsCall_v_0 $jsCall_v_1 $jsCall_v_2 $jsCall_vi_0 $jsCall_vi_1 $jsCall_vi_2 $jsCall_viii_0 $jsCall_viii_1 $jsCall_viii_2)
 (export "main" (func $main))
 (export "stackSave" (func $stackSave))
 (export "stackAlloc" (func $stackAlloc))
 (export "stackRestore" (func $stackRestore))
 (export "dynCall_viii" (func $dynCall_viii))
 (func $_Z18address_taken_funciii (; 7 ;) (type $FUNCSIG$viii) (param $0 i32) (param $1 i32) (param $2 i32)
 )
 (func $_Z19address_taken_func2iii (; 8 ;) (type $FUNCSIG$viii) (param $0 i32) (param $1 i32) (param $2 i32)
 )
 (func $main (; 9 ;) (param $0 i32) (param $1 i32) (result i32)
  (local $2 i32)
  (local $3 i32)
  (local $4 i32)
  (local $5 i32)
  (set_local $2
   (call $atoi
    (i32.load offset=4
     (get_local $1)
    )
   )
  )
  (set_local $3
   (call $atoi
    (i32.load offset=8
     (get_local $1)
    )
   )
  )
  (set_local $4
   (call $atoi
    (i32.load offset=12
     (get_local $1)
    )
   )
  )
  (set_local $5
   (call $atoi
    (i32.load offset=16
     (get_local $1)
    )
   )
  )
  (set_local $1
   (call $atoi
    (i32.load offset=20
     (get_local $1)
    )
   )
  )
  (call_indirect (type $FUNCSIG$v)
   (get_local $2)
  )
  (call_indirect (type $FUNCSIG$vi)
   (i32.const 3)
   (get_local $3)
  )
  (drop
   (call_indirect (type $FUNCSIG$iii)
    (i32.const 4)
    (i32.const 5)
    (get_local $4)
   )
  )
  (drop
   (call_indirect (type $FUNCSIG$fffi)
    (f32.const 3.0999999046325684)
    (f32.const 4.199999809265137)
    (i32.const 5)
    (get_local $5)
   )
  )
  (drop
   (call_indirect (type $FUNCSIG$ddi)
    (f64.const 4.2)
    (i32.const 5)
    (get_local $1)
   )
  )
  (call_indirect (type $FUNCSIG$viii)
   (i32.const 1)
   (i32.const 2)
   (i32.const 3)
   (select
    (i32.const 1)
    (i32.const 2)
    (i32.gt_s
     (get_local $0)
     (i32.const 3)
    )
   )
  )
  (i32.const 0)
 )
 (func $__wasm_nullptr (; 10 ;) (type $FUNCSIG$v)
  (unreachable)
 )
 (func $stackSave (; 11 ;) (result i32)
  (i32.load offset=4
   (i32.const 0)
  )
 )
 (func $stackAlloc (; 12 ;) (param $0 i32) (result i32)
  (local $1 i32)
  (i32.store offset=4
   (i32.const 0)
   (tee_local $1
    (i32.and
     (i32.sub
      (i32.load offset=4
       (i32.const 0)
      )
      (get_local $0)
     )
     (i32.const -16)
    )
   )
  )
  (get_local $1)
 )
 (func $stackRestore (; 13 ;) (param $0 i32)
  (i32.store offset=4
   (i32.const 0)
   (get_local $0)
  )
 )
 (func $dynCall_viii (; 14 ;) (param $fptr i32) (param $0 i32) (param $1 i32) (param $2 i32)
  (call_indirect (type $FUNCSIG$viii)
   (get_local $0)
   (get_local $1)
   (get_local $2)
   (get_local $fptr)
  )
 )
 (func $jsCall_ddi_0 (; 15 ;) (param $0 f64) (param $1 i32) (result f64)
  (call $jsCall_ddi
   (i32.const 0)
   (get_local $0)
   (get_local $1)
  )
 )
 (func $jsCall_ddi_1 (; 16 ;) (param $0 f64) (param $1 i32) (result f64)
  (call $jsCall_ddi
   (i32.const 1)
   (get_local $0)
   (get_local $1)
  )
 )
 (func $jsCall_ddi_2 (; 17 ;) (param $0 f64) (param $1 i32) (result f64)
  (call $jsCall_ddi
   (i32.const 2)
   (get_local $0)
   (get_local $1)
  )
 )
 (func $jsCall_fffi_0 (; 18 ;) (param $0 f32) (param $1 f32) (param $2 i32) (result f32)
  (call $jsCall_fffi
   (i32.const 0)
   (get_local $0)
   (get_local $1)
   (get_local $2)
  )
 )
 (func $jsCall_fffi_1 (; 19 ;) (param $0 f32) (param $1 f32) (param $2 i32) (result f32)
  (call $jsCall_fffi
   (i32.const 1)
   (get_local $0)
   (get_local $1)
   (get_local $2)
  )
 )
 (func $jsCall_fffi_2 (; 20 ;) (param $0 f32) (param $1 f32) (param $2 i32) (result f32)
  (call $jsCall_fffi
   (i32.const 2)
   (get_local $0)
   (get_local $1)
   (get_local $2)
  )
 )
 (func $jsCall_iii_0 (; 21 ;) (param $0 i32) (param $1 i32) (result i32)
  (call $jsCall_iii
   (i32.const 0)
   (get_local $0)
   (get_local $1)
  )
 )
 (func $jsCall_iii_1 (; 22 ;) (param $0 i32) (param $1 i32) (result i32)
  (call $jsCall_iii
   (i32.const 1)
   (get_local $0)
   (get_local $1)
  )
 )
 (func $jsCall_iii_2 (; 23 ;) (param $0 i32) (param $1 i32) (result i32)
  (call $jsCall_iii
   (i32.const 2)
   (get_local $0)
   (get_local $1)
  )
 )
 (func $jsCall_v_0 (; 24 ;)
  (call $jsCall_v
   (i32.const 0)
  )
 )
 (func $jsCall_v_1 (; 25 ;)
  (call $jsCall_v
   (i32.const 1)
  )
 )
 (func $jsCall_v_2 (; 26 ;)
  (call $jsCall_v
   (i32.const 2)
  )
 )
 (func $jsCall_vi_0 (; 27 ;) (param $0 i32)
  (call $jsCall_vi
   (i32.const 0)
   (get_local $0)
  )
 )
 (func $jsCall_vi_1 (; 28 ;) (param $0 i32)
  (call $jsCall_vi
   (i32.const 1)
   (get_local $0)
  )
 )
 (func $jsCall_vi_2 (; 29 ;) (param $0 i32)
  (call $jsCall_vi
   (i32.const 2)
   (get_local $0)
  )
 )
 (func $jsCall_viii_0 (; 30 ;) (param $0 i32) (param $1 i32) (param $2 i32)
  (call $jsCall_viii
   (i32.const 0)
   (get_local $0)
   (get_local $1)
   (get_local $2)
  )
 )
 (func $jsCall_viii_1 (; 31 ;) (param $0 i32) (param $1 i32) (param $2 i32)
  (call $jsCall_viii
   (i32.const 1)
   (get_local $0)
   (get_local $1)
   (get_local $2)
  )
 )
 (func $jsCall_viii_2 (; 32 ;) (param $0 i32) (param $1 i32) (param $2 i32)
  (call $jsCall_viii
   (i32.const 2)
   (get_local $0)
   (get_local $1)
   (get_local $2)
  )
 )
)
;; METADATA: { "asmConsts": {},"staticBump": 12, "initializers": [], "jsCallStartIndex": 3, "jsCallFuncType": ["ddi","fffi","iii","v","vi","viii"], "declares": ["atoi"], "externs": [], "implementedFunctions": ["_main","_stackSave","_stackAlloc","_stackRestore","_dynCall_viii"], "exports": ["main","stackSave","stackAlloc","stackRestore","dynCall_viii"], "invokeFuncs": [] }
