(module
  (memory 1)
  (data (i32.const 4) "\10\04\00\00")
  (export "memory" memory)
  (export "test_udiv_2" $test_udiv_2)
  (export "test_udiv_5" $test_udiv_5)
  (export "test_sdiv_2" $test_sdiv_2)
  (export "test_sdiv_5" $test_sdiv_5)
  (export "test_urem_2" $test_urem_2)
  (export "test_urem_5" $test_urem_5)
  (export "test_srem_2" $test_srem_2)
  (export "test_srem_5" $test_srem_5)
  (func $test_udiv_2 (param $0 i32) (result i32)
    (i32.shr_u
      (get_local $0)
      (i32.const 1)
    )
  )
  (func $test_udiv_5 (param $0 i32) (result i32)
    (i32.div_u
      (get_local $0)
      (i32.const 5)
    )
  )
  (func $test_sdiv_2 (param $0 i32) (result i32)
    (i32.div_s
      (get_local $0)
      (i32.const 2)
    )
  )
  (func $test_sdiv_5 (param $0 i32) (result i32)
    (i32.div_s
      (get_local $0)
      (i32.const 5)
    )
  )
  (func $test_urem_2 (param $0 i32) (result i32)
    (i32.and
      (get_local $0)
      (i32.const 1)
    )
  )
  (func $test_urem_5 (param $0 i32) (result i32)
    (i32.rem_u
      (get_local $0)
      (i32.const 5)
    )
  )
  (func $test_srem_2 (param $0 i32) (result i32)
    (i32.rem_s
      (get_local $0)
      (i32.const 2)
    )
  )
  (func $test_srem_5 (param $0 i32) (result i32)
    (i32.rem_s
      (get_local $0)
      (i32.const 5)
    )
  )
)
;; METADATA: { "asmConsts": {},"staticBump": 1040, "initializers": [] }
