(module
 (import "env" "memory" (memory $0 1))
 (table 0 funcref)
 (data (i32.const 4) "\10\04\00\00")
 (export "test_udiv_2" (func $test_udiv_2))
 (export "test_udiv_5" (func $test_udiv_5))
 (export "test_sdiv_2" (func $test_sdiv_2))
 (export "test_sdiv_5" (func $test_sdiv_5))
 (export "test_urem_2" (func $test_urem_2))
 (export "test_urem_5" (func $test_urem_5))
 (export "test_srem_2" (func $test_srem_2))
 (export "test_srem_5" (func $test_srem_5))
 (export "stackSave" (func $stackSave))
 (export "stackAlloc" (func $stackAlloc))
 (export "stackRestore" (func $stackRestore))
 (func $test_udiv_2 (; 0 ;) (param $0 i32) (result i32)
  (i32.shr_u
   (local.get $0)
   (i32.const 1)
  )
 )
 (func $test_udiv_5 (; 1 ;) (param $0 i32) (result i32)
  (i32.div_u
   (local.get $0)
   (i32.const 5)
  )
 )
 (func $test_sdiv_2 (; 2 ;) (param $0 i32) (result i32)
  (i32.div_s
   (local.get $0)
   (i32.const 2)
  )
 )
 (func $test_sdiv_5 (; 3 ;) (param $0 i32) (result i32)
  (i32.div_s
   (local.get $0)
   (i32.const 5)
  )
 )
 (func $test_urem_2 (; 4 ;) (param $0 i32) (result i32)
  (i32.and
   (local.get $0)
   (i32.const 1)
  )
 )
 (func $test_urem_5 (; 5 ;) (param $0 i32) (result i32)
  (i32.rem_u
   (local.get $0)
   (i32.const 5)
  )
 )
 (func $test_srem_2 (; 6 ;) (param $0 i32) (result i32)
  (i32.rem_s
   (local.get $0)
   (i32.const 2)
  )
 )
 (func $test_srem_5 (; 7 ;) (param $0 i32) (result i32)
  (i32.rem_s
   (local.get $0)
   (i32.const 5)
  )
 )
 (func $stackSave (; 8 ;) (result i32)
  (i32.load offset=4
   (i32.const 0)
  )
 )
 (func $stackAlloc (; 9 ;) (param $0 i32) (result i32)
  (local $1 i32)
  (i32.store offset=4
   (i32.const 0)
   (local.tee $1
    (i32.and
     (i32.sub
      (i32.load offset=4
       (i32.const 0)
      )
      (local.get $0)
     )
     (i32.const -16)
    )
   )
  )
  (local.get $1)
 )
 (func $stackRestore (; 10 ;) (param $0 i32)
  (i32.store offset=4
   (i32.const 0)
   (local.get $0)
  )
 )
)
;; METADATA: { "asmConsts": {},"staticBump": 1040, "initializers": [], "declares": [], "externs": [], "implementedFunctions": ["_test_udiv_2","_test_udiv_5","_test_sdiv_2","_test_sdiv_5","_test_urem_2","_test_urem_5","_test_srem_2","_test_srem_5","_stackSave","_stackAlloc","_stackRestore"], "exports": ["test_udiv_2","test_udiv_5","test_sdiv_2","test_sdiv_5","test_urem_2","test_urem_5","test_srem_2","test_srem_5","stackSave","stackAlloc","stackRestore"], "invokeFuncs": [] }
