(module
 (type $FUNCSIG$v (func))
 (import "env" "abort" (func $abort))
 (import "env" "memory" (memory $0 1))
 (table 0 anyfunc)
 (data (i32.const 4) "\10\04\00\00")
 (export "f1" (func $f1))
 (export "f2" (func $f2))
 (export "f3" (func $f3))
 (export "stackSave" (func $stackSave))
 (export "stackAlloc" (func $stackAlloc))
 (export "stackRestore" (func $stackRestore))
 (func $f1 (; 1 ;) (result i32)
  (call $abort)
  (unreachable)
 )
 (func $f2 (; 2 ;)
  (unreachable)
 )
 (func $f3 (; 3 ;)
  (unreachable)
 )
 (func $stackSave (; 4 ;) (result i32)
  (i32.load offset=4
   (i32.const 0)
  )
 )
 (func $stackAlloc (; 5 ;) (param $0 i32) (result i32)
  (local $1 i32)
  (i32.store offset=4
   (i32.const 0)
   (tee_local $1
    (i32.and
     (i32.sub
      (i32.load offset=4
       (i32.const 0)
      )
      (get_local $0)
     )
     (i32.const -16)
    )
   )
  )
  (get_local $1)
 )
 (func $stackRestore (; 6 ;) (param $0 i32)
  (i32.store offset=4
   (i32.const 0)
   (get_local $0)
  )
 )
)
;; METADATA: { "asmConsts": {},"staticBump": 1040, "initializers": [], "declares": ["abort"], "externs": [], "implementedFunctions": ["_f1","_f2","_f3","_stackSave","_stackAlloc","_stackRestore"], "exports": ["f1","f2","f3","stackSave","stackAlloc","stackRestore"], "invokeFuncs": [] }
