(module
  (func $f1 (export "anyref") (param $x anyref) (result i32)
    (ref.is_null (local.get $x))
  )
  (func $f2 (export "eqref") (param $x eqref) (result i32)
    (ref.is_null (local.get $x))
  )
  (func $f3 (export "externref") (param $x externref) (result i32)
    (ref.is_null (local.get $x))
  )
  (func $f4 (export "funcref") (param $x funcref) (result i32)
    (ref.is_null (local.get $x))
  )
)

(assert_return (invoke "anyref" (ref.null any)) (i32.const 1))
(assert_return (invoke "eqref" (ref.null eq)) (i32.const 1))
(assert_return (invoke "externref" (ref.null extern)) (i32.const 1))
(assert_return (invoke "funcref" (ref.null func)) (i32.const 1))
