(module
  (func (export "fac-expr") (param $n i64) (result i64)
    (local $i i64)
    (local $res i64)
    (push (local.get $n))
    (local.set $i (pop))
    (push (i64.const 1))
    (local.set $res (pop))
    (block $done
      (loop $loop
        (push (local.get $i))
        (push (i64.const 0))
        (push (i64.eq (pop) (pop)))
        (if (pop)
          (then (br $done))
          (else
            (push (local.get $i))
            (push (local.get $res))
            (push (i64.mul (pop) (pop)))
            (local.set $res (pop))
            (push (local.get $i))
            (push (i64.const 1))
            (push (i64.sub (pop) (pop)))
            (local.set $i (pop))
          )
        )
        (br $loop)
      )
    )
    (local.get $res)
  )
)

(assert_return (invoke "fac-expr" (i64.const 25)) (i64.const 7034535277573963776))
