;; Use lots of functions so we end up importing at least some.
(module
  (func $a (param i32)
  )
  (func $a1 (param i32)
  )
  (func $a2 (param i32)
  )
  (func $a3 (param i32)
  )
  (func $a4 (param i32)
  )

  (func $b (result i32)
   (i32.const 0)
  )
  (func $b1 (result i32)
   (i32.const 1)
  )
  (func $b2 (result i32)
   (i32.const 2)
  )
  (func $b3 (result i32)
   (i32.const 3)
  )
  (func $b4 (result i32)
   (i32.const 4)
  )
)

