;; NOTE: Assertions have been generated by update_lit_checks.py --all-items and should not be edited.

;; Test that new-style nominal types are correctly parsed and round-tripped
;; TODO: Remove --nominal below

;; RUN: wasm-opt %s --nominal -all -S -o - | filecheck %s
;; RUN: wasm-opt %s --nominal -all --roundtrip -S -o - | filecheck %s

(module
  ;; CHECK:      (type $use-all (func (result (ref $sub-void-func) (ref $sub-i32-func))))
  (type $use-all (func (result (ref $sub-void-func) (ref $sub-i32-func))))

  ;; CHECK:      (type $sub-void-func (func_subtype $super-void-func))
  (type $sub-void-func (func_subtype $super-void-func))

  ;; CHECK:      (type $sub-i32-func (func_subtype (param i32) (result i32) $super-i32-func))
  (type $sub-i32-func (func_subtype (param i32) (result i32) $super-i32-func))

  ;; CHECK:      (type $super-void-func (func))
  (type $super-void-func (func_subtype func))

  ;; CHECK:      (type $super-i32-func (func (param i32) (result i32)))
  (type $super-i32-func (func_subtype (param i32) (result i32) func))

  ;; CHECK:      (global $g (ref null $use-all) (ref.null $use-all))
  (global $g (ref null $use-all) (ref.null $use-all))
)
