;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt -all             %s -S -o - | filecheck %s
;; RUN: wasm-opt -all --roundtrip %s -S -o - | filecheck %s

(module
  ;; CHECK:      (@binaryen.removable.if.unused)
  ;; CHECK-NEXT: (func $func-annotation (type $0)
  ;; CHECK-NEXT:  (drop
  ;; CHECK-NEXT:   (i32.const 0)
  ;; CHECK-NEXT:  )
  ;; CHECK-NEXT: )
  (@binaryen.removable.if.unused)
  (func $func-annotation
    ;; The annotation here is on the function.
    (drop
      (i32.const 0)
    )
  )
)


