(module
 (type $0 (func (param i32) (result i32)))
 (import "env" "table" (table $timport$9 7 funcref))
 (elem (i32.const 1) $foo $bar $tabled)
 (export "main" (func $main))
 (func $main
  (drop
   (call_indirect (type $0)
    (i32.const 1)
    (call $foo (i32.const 2))
   )
  )
  (drop
   (call_indirect (type $0)
    (call $foo (i32.const 3))
    (i32.const 4)
   )
  )
  (drop
   (call_indirect (type $0)
    (call $foo (i32.const 5))
    (call $bar (i32.const 6))
   )
  )
  (drop
   (call_indirect (type $0)
    (i32.const 7)
    (i32.const 8)
   )
  )
 )
 (func $foo (param i32) (result i32)
  (i32.const 1)
 )
 (func $bar (param i32) (result i32)
  (i32.const 2)
 )
 (func $tabled (param i32) (result i32)
  (i32.const 3)
 )
)

