/*
 * Copyright 2026 WebAssembly Community Group participants
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// WebAssembly-to-C code translator. Converts wasm functions into
// valid standards-compliant C.
//

#ifndef wasm_wasm2c_h
#define wasm_wasm2c_h

#include <algorithm>
#include <cmath>
#include <iomanip>
#include <iostream>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <unordered_set>
#include <vector>

#include "ir/module-utils.h"
#include "parser/wat-parser.h"
#include "parsing.h"
#include "pass.h"
#include "picosha2.h"
#include "wasm-io.h"
#include "wasm-validator.h"
#include "wasm.h"

// code to be inserted into the generated output
extern const char* s_header_top;
extern const char* s_header_bottom;
extern const char* s_source_includes;
extern const char* s_source_declarations;
extern const char* s_spec_top;

namespace wasm {

class CPrinter;
typedef CPrinter& (*CPrinterManipulator)(CPrinter&);

class CPrinter {
public:
  std::ostream& out;
  int indent_level = 0;
  bool start_of_line = true;

  CPrinter(std::ostream& out) : out(out) {}

  void indent() { indent_level++; }
  void outdent() { indent_level--; }

  CPrinter& operator<<(CPrinter& (*pf)(CPrinter&)) { return pf(*this); }

  template<typename T> CPrinter& operator<<(const T& val) {
    if (start_of_line) {
      for (int i = 0; i < indent_level * 2; i++) {
        out << ' ';
      }
      start_of_line = false;
    }
    out << val;
    return *this;
  }
};

inline CPrinter& endl(CPrinter& p) {
  p.out << '\n';
  p.start_of_line = true;
  return p;
}

class Wasm2CBuilder {
public:
  struct Flags {
    bool debug = false;
    std::string moduleName = "";
    std::string headerName = "";
  };

  Wasm2CBuilder(Flags f) : flags(f) {}

  static std::string mangleName(const std::string& name) {
    if (name.empty())
      return "";
    std::string result;
    bool is_first = true;
    for (char c : name) {
      if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
          (c >= '0' && c <= '9')) {
        result += c;
        is_first = false;
      } else if (c == '_') {
        if (is_first) {
          result += "0x5F";
          is_first = false;
        } else {
          result += '_';
        }
      } else {
        char buf[8];
        snprintf(buf, sizeof(buf), "0x%02X", (unsigned char)c);
        result += buf;
        is_first = false;
      }
    }
    return result;
  }

  std::string getCType(Type type) {
    if (type == Type::i32)
      return "u32";
    if (type == Type::i64)
      return "u64";
    if (type == Type::f32)
      return "f32";
    if (type == Type::f64)
      return "f64";
    if (type == Type::none)
      return "void";
    Fatal() << "Unsupported type: " << type;
    return "";
  }

  std::vector<Type> getBasicTypes(Type type) {
    std::vector<Type> result;
    if (type.isTuple()) {
      for (auto t : type) {
        result.push_back(t);
      }
    } else if (type != Type::none) {
      result.push_back(type);
    }
    return result;
  }

  void processWasm(Module* wasm, std::ostream& c_out, std::ostream& h_out) {
    this->module = wasm;
    std::string module_name =
      flags.moduleName.empty() ? "test" : mangleName(flags.moduleName);
    std::string guard_name = "WASM_H_GENERATED_" + module_name;
    std::transform(
      guard_name.begin(), guard_name.end(), guard_name.begin(), ::toupper);

    CPrinter h(h_out);
    CPrinter c(c_out);

    // Header File
    h << "/* Automatically generated by wasm2c */" << endl;
    h << "#ifndef " << guard_name << endl;
    h << "#define " << guard_name << endl << endl;
    h << "#include \"wasm-rt.h\"" << endl << endl;
    h << s_header_top << endl;

    // Structure context definition
    h << "typedef struct w2c_" << module_name << " {" << endl;
    h.indent();
    h << "char dummy_member;" << endl;
    h.outdent();
    h << "} w2c_" << module_name << ";" << endl << endl;
    //
    // Lifecycle signatures in header
    h << "void wasm2c_" << module_name << "_instantiate(w2c_" << module_name
      << "*";
    h << ");" << endl;

    h << "void wasm2c_" << module_name << "_free(w2c_" << module_name << "*);"
      << endl;
    h << "wasm_rt_func_type_t wasm2c_" << module_name
      << "_get_func_type(uint32_t param_count, uint32_t result_count, ...);"
      << endl
      << endl;

    h << s_header_bottom << endl;
    h << "#endif  /* " << guard_name << " */" << endl;

    // Source File
    c << "/* Automatically generated by wasm2c */" << endl;
    c << s_source_includes << endl;

    if (!flags.headerName.empty()) {
      c << "#include \"" << flags.headerName << "\"" << endl;
    } else {
      c << "#include \"wasm.h\"" << endl;
    }

    c << s_source_declarations << endl;

    // Instantiate hooks
    c << "void wasm2c_" << module_name << "_instantiate(w2c_" << module_name
      << "* instance";
    c << ") {" << endl;
    c.indent();
    c << "assert(wasm_rt_is_initialized());" << endl;
    c.outdent();
    c << "}" << endl << endl;

    // Free hooks
    c << "void wasm2c_" << module_name << "_free(w2c_" << module_name
      << "* instance) {" << endl;
    c << "}" << endl << endl;

    // Signature match ladders
    c << "wasm_rt_func_type_t wasm2c_" << module_name
      << "_get_func_type(uint32_t param_count, uint32_t result_count, ...) {"
      << endl;
    c.indent();
    c << "va_list args;" << endl << endl;

    c << "return NULL;" << endl;
    c.outdent();
    c << "}" << endl << endl;
  }

private:
  Flags flags;
  Module* module = nullptr;

  void processFunction(Function* func, CPrinter& c) {
    processStatement(func->body, func, c);
  }

  void processStatement(Expression* expr, Function* func, CPrinter& c) {
    if (!expr)
      return;

    if (expr->is<Nop>()) {
      return;
    }

    Fatal() << "Unsupported statement type";
    std::string val = processExpression(expr, func, c);
    c << val << ";" << endl;
  }

  std::string processExpression(Expression* curr, Function* func, CPrinter& c) {
    if (!curr)
      return "";

    if (curr->is<Unreachable>()) {
      return "TRAP(UNREACHABLE)";
    }

    Fatal() << "Unsupported expression node type.";
    return "";
  }
};

static void optimizeWasm(Module& wasm, PassOptions options) {
  // Run flattening and simplification passes before codegen
  PassRunner runner(&wasm, options);
  runner.add("flatten");
  runner.add("simplify-locals-notee-nostructure");
  runner.add("reorder-locals");
  runner.add("vacuum");
  runner.run();
}

class AssertionEmitter {
public:
  AssertionEmitter(WATParser::WASTScript& script,
                   Wasm2CBuilder::Flags flags,
                   const PassOptions& options)
    : script(script), flags(flags), options(options) {}

  void emit(std::ostream& c_out, std::ostream& h_out) {
    CPrinter h(h_out);
    CPrinter c(c_out);

    // Print static prefix templates to C source stream
    if (!flags.headerName.empty()) {
      c << "#include \"" << flags.headerName << "\"" << endl;
    } else {
      c << "#include \"wasm.h\"" << endl;
    }
    c << s_spec_top;

    std::stringstream h_stream;
    std::stringstream c_stream;
    std::vector<std::string> checks;
    std::vector<std::string> prefixes;

    // Loop sequentially through WASTScript AST commands
    for (size_t i = 0; i < script.size(); i++) {
      auto& entry = script[i];
      auto& cmd = entry.cmd;

      if (auto* mod = std::get_if<WATParser::WASTModule>(&cmd)) {
        if (mod->isDefinition) {
          Fatal() << "Module definition is not supported";
        }
        auto* w = std::get_if<std::shared_ptr<Module>>(&mod->module);
        if (!w) {
          Fatal() << "Expected parsed Module pointer inside WASTModule";
        }
        auto wasm = *w;
        std::string prefix = "spec_" + std::to_string(module_counter++);

        name_to_prefix[prefix] = prefix;
        if (wasm->name.is()) {
          name_to_prefix[Wasm2CBuilder::mangleName(wasm->name.toString())] =
            prefix;
        }

        Wasm2CBuilder::Flags mod_flags = flags;
        mod_flags.moduleName = prefix;

        // Run standard validation and flattening simplification passes
        optimizeWasm(*wasm.get(), options);
        Wasm2CBuilder builder(mod_flags);
        builder.processWasm(wasm.get(), c_stream, h_stream);

        // Cache exported function return types and parameter types
        for (auto& exp : wasm->exports) {
          if (exp->kind == ExternalKind::Function) {
            Function* func = wasm->getFunction(*exp->getInternalName());
            std::string c_func_name =
              "w2c_" + prefix + "_" +
              Wasm2CBuilder::mangleName(exp->name.toString());
            func_returns[c_func_name] = builder.getCType(func->getResults());
            func_params[c_func_name] = builder.getBasicTypes(func->getParams());
          }
        }

        last_module_prefix = prefix;
        prefixes.push_back(prefix);
        wasm_modules_cache[prefix] = wasm;

      } else if (auto* reg = std::get_if<WATParser::Register>(&cmd)) {
        std::string mangled_instance_name =
          reg->instanceName.has_value()
            ? Wasm2CBuilder::mangleName(reg->instanceName->toString())
            : "";

        std::string target_prefix;
        if (reg->instanceName.has_value()) {
          if (!name_to_prefix.count(mangled_instance_name)) {
            Fatal() << "Unregistered instance name mapping for alias register: "
                    << mangled_instance_name;
          }
          target_prefix = name_to_prefix[mangled_instance_name];
        } else {
          target_prefix = last_module_prefix;
        }

        std::string alias = Wasm2CBuilder::mangleName(reg->name.toString());
        name_to_prefix[alias] = target_prefix;

        // Output preprocessor define redirects
        h_stream << "#define w2c_" << alias << " w2c_" << target_prefix << "\n";
        h_stream << "#define wasm2c_" << alias << "_instantiate wasm2c_"
                 << target_prefix << "_instantiate\n";
        h_stream << "#define wasm2c_" << alias << "_free wasm2c_"
                 << target_prefix << "_free\n";

        // Redirect all exported symbols from the alias to the target provider
        // prefix
        if (wasm_modules_cache.count(target_prefix)) {
          auto wasm = wasm_modules_cache[target_prefix];
          for (auto& exp : wasm->exports) {
            std::string exp_name =
              Wasm2CBuilder::mangleName(exp->name.toString());
            h_stream << "#define w2c_" << alias << "_" << exp_name << " w2c_"
                     << target_prefix << "_" << exp_name << "\n";
          }
        }
        h_stream << "\n";

      } else if (auto* assn = std::get_if<WATParser::Assertion>(&cmd)) {
        if (auto* ret = std::get_if<WATParser::AssertReturn>(assn)) {
          if (auto* inv = std::get_if<WATParser::InvokeAction>(&ret->action)) {
            std::string expr_call = translateInvoke(*inv);
            std::string field_name =
              "w2c_" + getInvokePrefix(*inv) + "_" +
              Wasm2CBuilder::mangleName(inv->name.toString());

            std::string assert_macro;
            auto& exp = ret->expected[0][0]; // Get first alternative
            if (auto* lit = std::get_if<Literal>(&exp)) {
              std::string ret_type = func_returns[field_name];
              switch (ret_type) {
                case "i32":
                  assert_macro = "ASSERT_RETURN_I32";
                  break;
                case "i64":
                  assert_macro = "ASSERT_RETURN_I64";
                  break;
                case "f32":
                  assert_macro = "ASSERT_RETURN_F32";
                  break;
                case "f64":
                  assert_macro = "ASSERT_RETURN_F64";
                  break;
                default:
                  Fatal() << "Unsupported return type: " << ret_type;
                  break;
              }
              checks.push_back(assert_macro + "(" + expr_call + ", " +
                               translateLiteral(*lit) + ");");
            }
          } else if (auto* nan_val = std::get_if<WATParser::NaNResult>(&exp)) {
            if (nan_val->type == Type::f32) {
              switch (nan_val->kind) {
                case WATParser::NaNKind::Canonical:
                  assert_macro = "ASSERT_RETURN_CANONICAL_NAN_F32";
                  break;
                case WATParser::NaNKind::Arithmetic:
                  assert_macro = "ASSERT_RETURN_ARITHMETIC_NAN_F32";
                  break;
                default:
                  Fatal() << "Unsupported NaN kind: " << nan_val->kind;
              }
            } else if (nan_val->type == Type::f64) {
              switch (nan_val->kind) {
                case WATParser::NaNKind::Canonical:
                  assert_macro = "ASSERT_RETURN_CANONICAL_NAN_F64";
                  break;
                case WATParser::NaNKind::Arithmetic:
                  assert_macro = "ASSERT_RETURN_ARITHMETIC_NAN_F64";
                  break;
                default:
                  Fatal() << "Unsupported NaN kind: " << nan_val->kind;
              }
            }
            checks.push_back(assert_macro + "(" + expr_call + ");");
          }
        } else if (auto* act = std::get_if<WATParser::AssertAction>(assn)) {
          if (act->type == WATParser::ActionAssertionType::Trap) {
            if (auto* inv =
                  std::get_if<WATParser::InvokeAction>(&act->action)) {
              std::string expr_call = translateInvoke(*inv);
              checks.push_back("ASSERT_TRAP(" + expr_call + ");");
            }
          }
        }
      }
    }

    // Write C headers and definitions
    h << endl
      << "/* === MODULE HEADERS === */" << endl
      << h_stream.str() << endl;
    c << endl
      << "/* === MODULE SOURCES === */" << endl
      << c_stream.str() << endl;

    // Write main execution entry point
    c << "void run_spec_tests() {" << endl;
    c.indent();

    // Declare all module instances
    for (auto& prefix : prefixes) {
      c << "w2c_" << prefix << " inst_" << prefix << ";" << endl;
    }
    c << endl;

    // Instantiate all module instances matching their imports metadata
    for (auto& prefix : prefixes) {
      c << "wasm2c_" << prefix << "_instantiate(&inst_" << prefix;

      // Gather all unique imported modules namespaces
      std::set<std::string> imported_namespaces;
      for (auto& mem : wasm_modules_cache[prefix]->memories) {
        if (mem->imported())
          imported_namespaces.insert(
            Wasm2CBuilder::mangleName(mem->module.toString()));
      }
      for (auto& table : wasm_modules_cache[prefix]->tables) {
        if (table->imported())
          imported_namespaces.insert(
            Wasm2CBuilder::mangleName(table->module.toString()));
      }
      for (auto& global : wasm_modules_cache[prefix]->globals) {
        if (global->imported())
          imported_namespaces.insert(
            Wasm2CBuilder::mangleName(global->module.toString()));
      }
      ModuleUtils::iterImportedFunctions(
        *wasm_modules_cache[prefix], [&](Function* func) {
          imported_namespaces.insert(
            Wasm2CBuilder::mangleName(func->module.toString()));
        });

      for (auto& ns : imported_namespaces) {
        if (ns == "spectest") {
          c << ", w2c_spectest_instance";
        } else {
          std::string prov_prefix = name_to_prefix[ns];
          c << ", (struct w2c_" << ns << "*)&inst_" << prov_prefix;
        }
      }
      c << ");" << endl;
    }
    c << endl;

    // Run all checks
    for (auto& chk : checks) {
      c << chk << endl;
    }
    c << endl;

    // Free contexts in REVERSE order of instantiation
    for (auto it = prefixes.rbegin(); it != prefixes.rend(); ++it) {
      c << "wasm2c_" << *it << "_free(&inst_" << *it << ");" << endl;
    }

    c.outdent();
    c << "}" << endl;
  }

private:
  WATParser::WASTScript& script;
  Wasm2CBuilder::Flags flags;
  PassOptions options;

  std::map<std::string, std::string> name_to_prefix;
  std::map<std::string, std::vector<Type>> func_params;
  std::map<std::string, std::string> func_returns;
  std::map<std::string, std::shared_ptr<Module>> wasm_modules_cache;
  std::string last_module_prefix = "";
  size_t module_counter = 0;

  std::string getInvokePrefix(const WATParser::InvokeAction& invoke) {
    if (invoke.base.has_value()) {
      std::string base_mangled =
        Wasm2CBuilder::mangleName(invoke.base->toString());
      if (name_to_prefix.count(base_mangled)) {
        return name_to_prefix[base_mangled];
      }
    }
    return last_module_prefix;
  }

  std::string translateInvoke(const WATParser::InvokeAction& invoke) {
    std::string prefix = getInvokePrefix(invoke);
    std::string mangled_name =
      Wasm2CBuilder::mangleName(invoke.name.toString());
    std::string field_name = "w2c_" + prefix + "_" + mangled_name;

    std::string expr = field_name + "(&inst_" + prefix;
    for (auto& arg : invoke.args) {
      expr += ", " + translateLiteral(arg);
    }
    expr += ")";
    return expr;
  }

  std::string translateLiteral(const Literal& lit) {
    std::stringstream os;
    switch (lit.type.getBasic()) {
      case Type::i32:
        os << lit.geti32() << "u";
        break;
      case Type::i64:
        os << lit.geti64() << "ULL";
        break;
      case Type::f32:
        os << "float_from_u32(0x" << std::hex << lit.reinterpreti32() << "u)"
           << std::dec;
        break;
      case Type::f64:
        os << "double_from_u64(0x" << std::hex << lit.reinterpreti64() << "ULL)"
           << std::dec;
        break;
      default:
        Fatal() << "Unsupported literal type: " << lit.type;
    }
    return os.str();
  }

  std::string getTrapEnum(const std::string& msg) {
    if (msg.find("out of bounds") != std::string::npos ||
        msg.find("bounds") != std::string::npos)
      return "WASM_RT_TRAP_OOB";
    if (msg.find("overflow") != std::string::npos)
      return "WASM_RT_TRAP_INT_OVERFLOW";
    if (msg.find("divide") != std::string::npos ||
        msg.find("zero") != std::string::npos)
      return "WASM_RT_TRAP_DIV_BY_ZERO";
    if (msg.find("invalid conversion") != std::string::npos)
      return "WASM_RT_TRAP_INVALID_CONVERSION";
    if (msg.find("unreachable") != std::string::npos)
      return "WASM_RT_TRAP_UNREACHABLE";
    if (msg.find("indirect call") != std::string::npos ||
        msg.find("undefined") != std::string::npos ||
        msg.find("uninitialized") != std::string::npos ||
        msg.find("signature mismatch") != std::string::npos) {
      return "WASM_RT_TRAP_CALL_INDIRECT";
    }
    if (msg.find("exhaustion") != std::string::npos ||
        msg.find("exhausted") != std::string::npos)
      return "WASM_RT_TRAP_EXHAUSTION";
    return "WASM_RT_TRAP_NONE";
  }
};

} // namespace wasm

#endif // wasm_wasm2c_h
