(module
  (memory 1 2)
  (import "env" "import" (func $import))
  (func $liveness1 (param $live0 i32) (param $dead0 i32)
    (local $live1 i32)
    (local $dead1 i32)
    (drop (local.get $dead0))
    (drop (local.get $dead1))
    (call $import)
    (drop (local.get $live0))
    (drop (local.get $live1))
  )
  (func $liveness2 (param $live0 i32) (param $dead0 i32)
    (local $live1 i32)
    (local $dead1 i32)
    (drop (local.get $dead0))
    (drop (local.get $dead1))
    (call $import)
    (drop (local.get $live0))
    (drop (local.get $live1))
  )
  (func $liveness3 (param $live0 i32) (param $dead0 i32)
    (local $live1 i32)
    (local $dead1 i32)
    (call $import)
    (drop (local.get $live0))
    (call $import)
    (drop (local.get $live1))
  )
  (func $liveness4 (param $live0 i32) (param $dead0 i32)
    (if (i32.const 0)
      (call $import)
    )
    (drop (local.get $live0))
  )
)

