(module
  (memory 10)
  (type $ii (func (param i32) (param i32)))
  (table $call-me)
  (func $call-me (param i32) (param i32)
  )
  (func $code-to-kill
    (local $x i32)
    (block $out
      (br $out) ;; kill everything after this
      (i32.const 0)
      (if (i32.const 1)
        (i32.const 2)
      )
      (br_table $out $out $out $out (i32.const 3))
      (call $code-to-kill)
    )
    (if (i32.const 0)
      (block $out
        (unreachable)
        (i32.const 0)
      )
    )
    (if (i32.const 0)
      (block $out
        (return)
        (i32.const 0)
      )
    )
    (block $out
      (br_table $out $out $out $out (i32.const 4))
      (i32.const 0)
    )
    (block $out
      (br_if $out (i32.const 3)) ;; but not after this
      (i32.const 0)
    )
    (if (i32.const 0)
      (block
        (if (i32.const 0) ;; if that is unreachable both ways
          (block $out
            (unreachable)
            (i32.const 0)
          )
          (block $out
            (unreachable)
            (i32.const 0)
          )
        )
        (i32.const 0)
      )
    )
    (if (i32.const 0)
      (block $out
        (br $out (unreachable))
        (i32.const 0)
      )
    )
    (if (i32.const 0)
      (block $out
        (br_if $out (unreachable) (i32.const 0))
        (i32.const 0)
      )
    )
    (if (i32.const 0)
      (block $out
        (br_if $out (unreachable) (unreachable))
        (i32.const 0)
      )
    )
    (block $out
      (block $in
        (br_if $out (i32.const 1))
      )
      (unreachable)
    )
    (if (i32.const 0)
      (block
        (block $out
          (block $in
            (br_if $in (i32.const 1))
          )
          (unreachable)
        )
        (i32.const 10)
      )
    )
    (block $out
      (block $in
        (br_table $out $in (i32.const 1))
      )
      (unreachable)
    )
    (block $out
      (block $in
        (br_table $in $out (i32.const 1))
      )
      (unreachable)
    )
    (if (i32.const 0)
      (block
        (block $out
          (block $in
            (br_table $in $in (i32.const 1))
          )
          (unreachable)
        )
        (i32.const 10)
      )
    )
    (if (i32.const 0)
      (block
        (i32.const 10)
        (i32.const 42)
        (unreachable)
        (return (unreachable))
        (unreachable)
        (return)
      )
    )
    (if (i32.const 0)
      (loop (unreachable))
    )
    (loop $out $in
      (br_if $out (i32.const 1))
      (unreachable)
    )
    (if (i32.const 0)
      (block
        (loop $out $in
          (br_if $in (i32.const 1))
          (unreachable)
        )
        (i32.const 10)
      )
    )
    (if (i32.const 1)
      (call $call-me (i32.const 123) (unreachable))
    )
    (if (i32.const 2)
      (call $call-me (unreachable) (i32.const 0))
    )
    (if (i32.const 3)
      (call $call-me (unreachable) (unreachable))
    )
    (if (i32.const -1)
      (call_indirect $ii (i32.const 123) (i32.const 456) (unreachable))
    )
    (if (i32.const -2)
      (call_indirect $ii (i32.const 139) (unreachable) (i32.const 0))
    )
    (if (i32.const -3)
      (call_indirect $ii (i32.const 246) (unreachable) (unreachable))
    )
    (if (i32.const -4)
      (call_indirect $ii (unreachable) (unreachable) (unreachable))
    )
    (if (i32.const 11)
      (set_local $x (unreachable))
    )
    (if (i32.const 22)
      (i32.load (unreachable))
    )
    (if (i32.const 33)
      (i32.store (i32.const 0) (unreachable))
    )
    (if (i32.const 44)
      (i32.store (unreachable) (i32.const 0))
    )
    (if (i32.const 55)
      (i32.store (unreachable) (unreachable))
    )
    (if (i32.const 66)
      (i32.eqz (unreachable))
    )
    (if (i32.const 77)
      (i32.add (unreachable) (i32.const 0))
    )
    (if (i32.const 88)
      (i32.add (i32.const 0) (unreachable))
    )
    (if (i32.const 99)
      (i32.add (unreachable) (unreachable))
    )
    (if (i32.const 100)
      (select (i32.const 123) (i32.const 456) (unreachable))
    )
    (if (i32.const 101)
      (select (i32.const 123) (unreachable) (i32.const 456))
    )
    (if (i32.const 102)
      (select (unreachable) (i32.const 123) (i32.const 456))
    )
    (i32.const 1337)
  )
)

