(module
  (import "env" "malloc" (func $malloc (param i32) (result i32)))
  (import "env" "realloc" (func $realloc (param i32 i32) (result i32)))
  (import "env" "calloc" (func $calloc (param i32 i32) (result i32)))
  (import "env" "free" (func $free (param i32)))
  (func $test_malloc (result i32)
    (call $malloc (i32.const 2))
  )
  (func $test_realloc (param i32 i32) (result i32)
    (call $realloc (i32.const 4) (i32.const 8))
  )
  (func $test_calloc (param i32 i32) (result i32)
    (call $calloc (i32.const 16) (i32.const 32))
  )
  (func $test_free (param i32)
    (call $free (i32.const 64))
  )
)