(module
  (func $yes-big-const-42 (result i32)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (i32.const 42)
  )
  (func $yes-big-const-42-1 (result i32)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (i32.const 42)
  )
  (func $yes-big-const-43 (result i32)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (i32.const 43)
  )


  (func $no-small-const-44 (result i32)
    (i32.const 44)
  )

  (func $no-small-const-45 (result i32)
    (i32.const 45)
  )


  (func $yes-reuse-param-0
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (drop (i32.const 42))
    (drop (i32.const 42))
  )
  (func $yes-reuse-param-1
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (drop (i32.const 43))
    (drop (i32.const 43))
  )


  (func $yes-offset-local-indices-1 (param $a i32) (param $b i32)
    (local $x i32)
    (local $y i32)
    (drop (local.get $a))
    (drop (local.get $b))
    (drop (local.get $x))
    (drop (local.get $y))
    (drop (local.tee $x (local.get $x)))
    (drop (local.tee $y (local.get $y)))
    (drop (local.tee $a (local.get $a)))
    (drop (local.tee $b (local.get $b)))
    (drop (i32.const 1))
  )
  (func $yes-offset-local-indices-2 (param $a i32) (param $b i32)
    (local $x i32)
    (local $y i32)
    (drop (local.get $a))
    (drop (local.get $b))
    (drop (local.get $x))
    (drop (local.get $y))
    (drop (local.tee $x (local.get $x)))
    (drop (local.tee $y (local.get $y)))
    (drop (local.tee $a (local.get $a)))
    (drop (local.tee $b (local.get $b)))
    (drop (i32.const 2))
  )
)
