(module
  (type $[i8] (array i8))
  (func $callee-0 (result i32) (i32.const 0))
  (func $callee-1 (result i32) (i32.const 1))
  (func $callee-2 (result i32) (i32.const 2))

  (func $callee-take-arg-0 (param i32) (result i32) (i32.const 0))
  (func $callee-take-arg-1 (param i32) (result i32) (i32.const 1))
  (func $callee-take-arg-2 (param i32) (result i32) (i32.const 2))

  (func $yes-call-callee-0 (result i32)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (call $callee-0)
  )
  (func $yes-call-callee-1 (result i32)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (call $callee-1)
  )
  (func $yes-call-callee-2 (result i32)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (call $callee-2)
  )


  (func $yes-call-callee-take-arg-0 (result i32)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (call $callee-take-arg-0 (i32.const 0))
  )
  (func $yes-call-callee-take-arg-1 (result i32)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (call $callee-take-arg-1 (i32.const 1))
  )


  (func $no-call-callee-take-arg-0 (result i32)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (call $callee-take-arg-0
      (block (result i32)
        (drop (i32.const 0))
        (i32.const 0)
      )
    )
  )
  (func $no-call-callee-take-arg-1 (result i32)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (call $callee-take-arg-1
      (block (result i32)
        (drop (i32.const 0))
        (drop (i32.const 0))
        (i32.const 0)
      )
    )
  )


  (func $take-ref-null-data (param (ref null data))
    (unreachable)
  )
  (func $take-ref-eq (param (ref eq))
    (unreachable)
  )
  (func $no-call-subtyping-same-operand-0
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (call $take-ref-null-data
      (array.init_static $[i8])
    )
  )
  (func $no-call-subtyping-same-operand-1
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (nop) (nop) (nop) (nop) (nop) (nop)
    (call $take-ref-eq
      (array.init_static $[i8])
    )
  )

)
