(module
  (memory 1024 1024)
  (type $FUNCSIG$v (func))
  (type $FUNCSIG$i (func (result i32)))
  (type $FUNCSIG$d (func (result f64)))
  (import $waka "somewhere" "waka")
  (import $waka-ret "somewhere" "waka-ret" (result i32))
  (import $waka-ret-d "somewhere" "waka-ret-d" (result f64))
  (import $waka-sneaky "somewhere" "waka-sneaky")
  (import "env" "memBase" (global i32))
  (import "env" "table" (table $table 1 1 funcref))
  (elem (i32.const 0) $waka-sneaky)
  (func $nada (type $FUNCSIG$v)
    (call $waka)
    (drop
      (call $waka-ret)
    )
    (drop
      (call $waka-ret-d)
    )
    (call_indirect (i32.const 0))
  )
)
