(module
 (type $0 (func))
 (type $FUNCSIG$j (func (result i32)))
 (type $FUNCSIG$i (func (result i32)))
 (type $legaltype$wasm2js_scratch_load_i64 (func (result i32)))
 (type $FUNCSIG$vj (func (param i32 i32)))
 (type $legaltype$wasm2js_scratch_store_i64 (func (param i32 i32)))
 (import "env" "wasm2js_scratch_load_i32" (func $wasm2js_scratch_load_i32 (param i32) (result i32)))
 (import "env" "wasm2js_scratch_store_i32" (func $wasm2js_scratch_store_i32 (param i32 i32)))
 (import "env" "wasm2js_scratch_load_f32" (func $wasm2js_scratch_load_f32 (result f32)))
 (import "env" "wasm2js_scratch_store_f32" (func $wasm2js_scratch_store_f32 (param f32)))
 (import "env" "wasm2js_scratch_load_f64" (func $wasm2js_scratch_load_f64 (result f64)))
 (import "env" "wasm2js_scratch_store_f64" (func $wasm2js_scratch_store_f64 (param f64)))
 (import "env" "getTempRet0" (func $getTempRet0 (result i32)))
 (import "env" "wasm2js_scratch_load_i64" (func $legalimport$wasm2js_scratch_load_i64 (result i32)))
 (import "env" "wasm2js_scratch_store_i64" (func $legalimport$wasm2js_scratch_store_i64 (param i32 i32)))
 (import "env" "wasm2js_scratch_load_i64" (func $wasm2js_scratch_load_i64 (result i64)))
 (import "env" "wasm2js_scratch_store_i64" (func $wasm2js_scratch_store_i64 (param i64)))
 (memory $0 1 1)
 (global $i64toi32_i32$HIGH_BITS (mut i32) (i32.const 0))
 (func $0 (; 11 ;) (type $0)
  (local $0 f64)
  (local $1 i32)
  (block $label$1
   (block
    (nop)
    (drop
     (if (result f64)
      (i32.const 1)
      (block (result f64)
       (nop)
       (f64.load
        (i32.const 19)
       )
      )
      (block
       (drop
        (f64.const 1)
       )
       (br $label$1)
       (nop)
      )
     )
    )
   )
   (nop)
  )
 )
 (func $legalfunc$wasm2js_scratch_load_i64 (; 12 ;) (result i32)
  (local $0 i32)
  (local $1 i32)
  (local.set $1
   (i32.or
    (call $legalimport$wasm2js_scratch_load_i64)
    (block (result i32)
     (nop)
     (block (result i32)
      (nop)
      (i32.const 0)
     )
    )
   )
  )
  (global.set $i64toi32_i32$HIGH_BITS
   (call $getTempRet0)
  )
  (local.get $1)
 )
 (func $legalfunc$wasm2js_scratch_store_i64 (; 13 ;) (param $0 i32) (param $1 i32)
  (call $legalimport$wasm2js_scratch_store_i64
   (block (result i32)
    (nop)
    (local.get $0)
   )
   (block (result i32)
    (nop)
    (local.get $1)
   )
  )
 )
)
