(module
  (type $FUNCSIG$v (func))
  (type $FUNCSIG$i (func (result i32)))
  (type $FUNCSIG$d (func (result f64)))
  (import "somewhere" "waka" (func $waka))
  (import "somewhere" "waka-ret" (func $waka-ret (result i32)))
  (import "somewhere" "waka-ret-d" (func $waka-ret-d (result f64)))
  (import "somewhere" "waka-sneaky" (func $waka-sneaky))
  (import "env" "memBase" (global i32))
  (import "env" "table" (table $table 1 1 funcref))
  (memory 1024 1024)
  (elem (i32.const 0) $waka-sneaky)
  (func $nada (type $FUNCSIG$v)
    (call $waka)
    (drop
      (call $waka-ret)
    )
    (drop
      (call $waka-ret-d)
    )
    (call_indirect (i32.const 0))
  )
)
